import type { MeadowState } from './meadows/state';
import type { Vec3 } from '../world/types';
import type { EnvironmentState } from '../environment/time';
export interface ResourceNode extends Vec3 { gearItems?:import('./equipment/items').GearContainer; id: number; kind: string; amount: number; ready: number; drop?:boolean; velocity?:Vec3; removed?:string[]; growth?:{kind:string;remaining:number}; swimming?:{homeX:number;homeZ:number;heading:number}; health?: number; spawnTimer?:number; harvested?: boolean; log?: import('./meadows/forestry').LogState }
export interface EnemyState extends Vec3 { homeY?:number; id: number; definition: string; tier: number; health: number; cooldown: number; windup: number; slow: number; boss: boolean; homeX: number; homeZ: number; respawnAt?: number; stars?: number; tame?: number; fed?: number; baby?: number; heading?: number; breeding?: number; attackKind?: string; attackReady?: Record<string,number>; attackYaw?: number; attackFlash?: number; alerted?: number; stagger?:number; burn?: number }
export interface BuildingState extends Vec3 { gearItems?:import('./equipment/items').GearContainer; site?:number; creator?: string; shared?: boolean; id: number; definition: string; rotation: number; support: number; contents: Record<string, number>; removed?:string[]; salvage?:Record<string,number>; health?: number; fuel?: number; open?: boolean; progress?: number; cooking?: {id:string;time:number}[]; label?: string }
export interface Projectile extends Vec3 { gearFlight?:number; id: number; vx: number; vy: number; vz: number; life: number; damage: number; element: string; radius: number; owner?: string; recover?: string; burn?: number; kind?:'arrow'|'spear'; gravity?:number }
export interface AdventureSave { gearItems?:import('./equipment/items').GearContainer; graveGear?:import('./equipment/items').GearContainer; gearFlights?:{id:number;point:Vec3;gearItems:import('./equipment/items').GearContainer}[]; race?:import('./trail-race').TrailRaceSave; exploration?:import('./adventure-exploration').ExplorationState; siteWorld?:import('./site-state').SiteWorld; siteJournal?:number[]; trialWorld?: import('../content/adventure-trials').TrialWorld; trialJournal?: number[]; downed?: number; seconds: number; health: number; stamina: number; mana: number; inventory: Record<string, number>; equipment: string; unlocked: number; defeated: string[]; resources: ResourceNode[]; enemies: EnemyState[]; buildings: BuildingState[]; death: Vec3 | null; food: number; rested: number; spawn: Vec3 | null; poison?: number; chill?: number; grave?: Record<string, number>; waterSeeds?: string[]; meadows?: MeadowState }
export interface AdventureSnapshot extends AdventureSave { raceTarget?:Vec3; explorationStatus?:import('./adventure-exploration').ExplorationStatus; sharedPins?:import('./shared-pins').SharedPin[]; expeditions?:import('./sites').ExpeditionsSnapshot; companions?:import('./companions').CompanionSnapshot; dialogue?: import('../content/adventure-trials').DialogueSnapshot; journey?: import('../content/adventure-trials').JourneySnapshot; coop?: import('./coop-revive').CoopSnapshot; traversal?: import('./traversal').TraversalSnapshot; environment: EnvironmentState; generator: 1 | 2 | 3 | 4; skybound?: import('./skybound/types').SkyboundSnapshot; biome: string; objective: string; projectiles: Projectile[]; guarding: boolean; dodging: boolean; attack: number; attackMotion?: import('./combat/attack').AttackMotion; wet: boolean }
export type GameAction = 'race' | 'map-pin-share' | 'map-pin-remove' | import('./sites').SiteAction | import('./companions').CompanionAction | 'building-share' | 'terrain-undo' | 'talk' | 'dialogue' | 'trial' | 'trial-reset' | 'revive' | 'return' | 'glide' | 'climb' | import('./skybound/types').SkyAction | 'gather' | 'attack' | 'heavy' | 'guard' | 'dodge' | 'craft' | 'build' | 'remove' | 'spell' | 'summon' | 'eat' | 'equip' | 'travel' | 'rest' | 'chest' | 'portal' | 'repair' | 'upgrade' | 'cook' | 'fuel' | 'interact' | 'feed' | 'power' | 'offer' | 'drop' | 'plant' | 'sneak' | 'sprint' | 'fish' | 'trade' | 'repairBuilding' | 'split' | 'move' | 'pin' | 'unpin' | 'label' | 'store' | 'take' | 'landscape' | 'sell';

