import type { MeadowState } from './meadows/state';
import type { Vec3 } from '../world/types';
import type { EnvironmentState } from '../environment/time';
export interface ResourceNode extends Vec3 { id: number; kind: string; amount: number; ready: number; drop?:boolean; velocity?:Vec3; removed?:string[]; growth?:{kind:string;remaining:number}; swimming?:{homeX:number;homeZ:number;heading:number}; health?: number; spawnTimer?:number; harvested?: boolean; log?: import('./meadows/forestry').LogState }
export interface EnemyState extends Vec3 { id: number; definition: string; tier: number; health: number; cooldown: number; windup: number; slow: number; boss: boolean; homeX: number; homeZ: number; respawnAt?: number; stars?: number; tame?: number; fed?: number; baby?: number; heading?: number; breeding?: number; attackKind?: string; attackReady?: Record<string,number>; attackYaw?: number; attackFlash?: number; alerted?: number; stagger?:number; burn?: number }
export interface BuildingState extends Vec3 { id: number; definition: string; rotation: number; support: number; contents: Record<string, number>; removed?:string[]; salvage?:Record<string,number>; health?: number; fuel?: number; open?: boolean; progress?: number; cooking?: {id:string;time:number}[]; label?: string }
export interface Projectile extends Vec3 { id: number; vx: number; vy: number; vz: number; life: number; damage: number; element: string; radius: number; owner?: string; recover?: string; burn?: number; kind?:'arrow'|'spear'; gravity?:number }
export interface AdventureSave { seconds: number; health: number; stamina: number; mana: number; inventory: Record<string, number>; equipment: string; unlocked: number; defeated: string[]; resources: ResourceNode[]; enemies: EnemyState[]; buildings: BuildingState[]; death: Vec3 | null; food: number; rested: number; spawn: Vec3 | null; poison?: number; chill?: number; grave?: Record<string, number>; waterSeeds?: string[]; meadows?: MeadowState }
export interface AdventureSnapshot extends AdventureSave { environment: EnvironmentState; generator: 1 | 2 | 3; biome: string; objective: string; projectiles: Projectile[]; guarding: boolean; dodging: boolean; attack: number; wet: boolean }
export type GameAction = 'gather' | 'attack' | 'heavy' | 'guard' | 'dodge' | 'craft' | 'build' | 'remove' | 'spell' | 'summon' | 'eat' | 'equip' | 'travel' | 'rest' | 'chest' | 'portal' | 'repair' | 'upgrade' | 'cook' | 'fuel' | 'interact' | 'feed' | 'power' | 'offer' | 'drop' | 'plant' | 'sneak' | 'sprint' | 'fish' | 'trade' | 'repairBuilding' | 'split' | 'move' | 'pin' | 'unpin' | 'label' | 'store' | 'take' | 'landscape' | 'sell';

