/** Original presentation; gameplay reference data is tracked in the milestone document. */
export const MEADOW_ITEMS: Record<string,string> = {
 stump:'切り株',fallenLog:'倒木',sapling:'若木',dolmen:'巨石墓',stoneCircle:'環状列石',graveyard:'舟形墓地',merchant:'旅商人',branch:'落ち枝',beech:'ブナ',birch:'白樺',oak:'オーク',finewood:'上質な木',beechSeed:'ブナの種',birchSeed:'白樺の種',acorn:'ドングリ',flint:'火打石',mushroom:'赤キノコ',dandelion:'タンポポ',leatherScraps:'皮の切れ端',deerHide:'鹿皮',feathers:'羽',boarMeat:'猪の生肉',deerMeat:'鹿の生肉',neckTail:'ネックの尾',cookedBoar:'猪の焼肉',cookedDeer:'鹿の焼肉',cookedNeck:'焼いた尾',honey:'蜂蜜',queenBee:'女王蜂',beeNest:'野生の蜂の巣',coal:'炭',deerTrophy:'鹿のトロフィー',boarTrophy:'猪のトロフィー',neckTrophy:'ネックのトロフィー',hardAntler:'硬い角',stormTrophy:'雷鹿のトロフィー',amber:'琥珀',amberPearl:'琥珀珠',coins:'硬貨',ruby:'ルビー',silverNecklace:'銀の首飾り',perch:'パーチ',pike:'パイク',rawFish:'生魚',cookedFish:'焼き魚',club:'木の棍棒',torch:'松明',hammer:'ハンマー',hoe:'鍬',flintAxe:'火打石の斧',flintKnife:'火打石のナイフ',flintSpear:'火打石の槍',crudeBow:'粗末な弓',woodArrow:'木の矢',fireArrow:'火の矢',flintArrow:'火打石の矢',towerShield:'木の大盾',ragTunic:'ぼろの上着',ragPants:'ぼろのズボン',leatherHelmet:'革の兜',leatherTunic:'革の上着',leatherPants:'革のズボン',deerCape:'鹿皮のマント',antlerPickaxe:'角のつるはし',lootChest:'遺された箱',buriedChest:'埋蔵された箱',runestone:'旅の石碑',sacrifice:'供物石',altar:'雷鹿の祭壇',entrails:'内臓',draugrTrophy:'亡者のトロフィー',greyEye:'森人の目',fishingRod:'釣り竿',bait:'釣り餌',linenHat:'旅人の帽子'
};
export interface FoodDefinition { health:number; stamina:number; seconds:number; healing:number }
export const FOODS:Record<string,FoodDefinition>={
 berry:{health:7,stamina:20,seconds:600,healing:1},mushroom:{health:15,stamina:15,seconds:900,healing:1},honey:{health:8,stamina:35,seconds:900,healing:1},cookedBoar:{health:30,stamina:10,seconds:1200,healing:2},cookedDeer:{health:35,stamina:12,seconds:1200,healing:2},cookedNeck:{health:25,stamina:8,seconds:1200,healing:2},cookedFish:{health:45,stamina:15,seconds:1200,healing:2},stew:{health:30,stamina:25,seconds:1200,healing:2}
};
export const COOKING:Record<string,{output:string;seconds:number}>={boarMeat:{output:'cookedBoar',seconds:25},deerMeat:{output:'cookedDeer',seconds:25},neckTail:{output:'cookedNeck',seconds:20},rawFish:{output:'cookedFish',seconds:30}};
export const ARMOR:Record<string,{slot:string;armor:number;durability:number}>={ragTunic:{slot:'chest',armor:1,durability:100},ragPants:{slot:'legs',armor:1,durability:100},leatherHelmet:{slot:'head',armor:2,durability:400},leatherTunic:{slot:'chest',armor:2,durability:400},leatherPants:{slot:'legs',armor:2,durability:400},deerCape:{slot:'cape',armor:1,durability:400}};
export const TOOL_DURABILITY:Record<string,number>={axe:100,flintAxe:150,flintKnife:100,flintSpear:100,club:100,torch:100,crudeBow:50,hammer:100,hoe:200,antlerPickaxe:100,shield:200,towerShield:200};
export const ITEM_WEIGHT:Record<string,number>={wood:2,stone:2,flint:2,finewood:2,leatherScraps:.5,deerHide:1,resin:.3,feathers:.1,coins:0,woodArrow:.1,fireArrow:.1,flintArrow:.1};
export const ARMOR_RECIPES=[['ragTunic',{leatherScraps:5}],['ragPants',{leatherScraps:5}],['leatherHelmet',{deerHide:6}],['leatherTunic',{deerHide:6}],['leatherPants',{deerHide:6}],['deerCape',{deerHide:4,bone:5}]] as const;
export const MEADOW_RECIPE_COSTS:Record<string,Record<string,number>>={
 club:{wood:6},torch:{wood:1,resin:1},hammer:{wood:3,stone:2},hoe:{wood:5,stone:2},flintAxe:{wood:4,flint:6},flintKnife:{wood:2,flint:4,leatherScraps:2},flintSpear:{wood:5,flint:10,leatherScraps:2},crudeBow:{wood:10,leatherScraps:8},woodArrow:{wood:8},fireArrow:{wood:8,resin:8,feathers:2},flintArrow:{wood:8,flint:2,feathers:2},towerShield:{wood:10,leatherScraps:6},ragTunic:{leatherScraps:5},ragPants:{leatherScraps:5},leatherHelmet:{deerHide:6},leatherTunic:{deerHide:6},leatherPants:{deerHide:6},deerCape:{deerHide:4,bone:5},antlerPickaxe:{wood:10,hardAntler:1}
};
export const MEADOW_CRAFT_IDS=new Set(['axe','shield',...Object.keys(MEADOW_RECIPE_COSTS)]);
export const MEADOW_BUILD_IDS=new Set(['floor','wall','roof','pillar','bench','fire','bed','chest','roof45','ridge','ridge45','roofCorner','roofInner','roofCorner45','roofInner45','halfWall','slantWall','smallFloor','shortPole','beam','shortBeam','beam26','beam45','stairs','ladder','door','gate','fence','stakeWall','spikes','cook','choppingBlock','tanningRack','beehive','sign','standingTorch','raft','spring','drain']);
export const MEADOW_FAUNA=['boar','deer','neck','greyling','gull'];
export const LOOT:Record<string,Record<string,number>>={boar:{boarMeat:1,leatherScraps:1},deer:{deerMeat:2,deerHide:2},neck:{neckTail:1},greyling:{resin:1},gull:{feathers:3},greydwarf:{wood:1,stone:1,resin:1,greyEye:1},draugr:{entrails:2}};
export const TREE_KINDS=new Set(['beech','birch','oak']);
