import type { Vec3, WorldBounds } from '../../world/types';
export type SkyMaterial = 'wood' | 'stone' | 'metal';
export type SkyPartKind = 'beam' | 'slab' | 'block' | 'wheel' | 'thruster' | 'sail' | 'battery' | 'switch' | 'lamp' | 'emitter' | 'seat' | 'storage' | 'bed';
export interface SkyPart { cargoMass?: number; wrecked?: boolean; loan?:{site:number;role:'cargo'|'device'}; q?: import('./orientation').Quaternion; angularVelocity?: Vec3; sleeping?: boolean; id: number; kind: SkyPartKind; material: SkyMaterial; position: Vec3; velocity: Vec3; rotation: number; mass: number; links: number[]; epoch: number; energy?: number; enabled?: boolean; integrity?: number; burning?: number; wet?: number; frozen?: number; element?: SkyElement; creator?: string; shared?: boolean; trial?: number; anchored?: boolean; carried?: number; recalled?: number; heated?: boolean }
export interface SkyBlueprint { id: number; owner: string; name: string; parts: {kind: SkyPartKind; material: SkyMaterial; offset: Vec3; q?: import('./orientation').Quaternion; rotation: number; links: number[]}[] }
export interface SkyFusion { equipment: string; material: string; damage: number; durability: number; effect: 'impact' | 'fire' | 'frost' }
export interface SkyboundSave { storageGear?:Record<string,import('../equipment/items').GearContainer>; storage?: Record<string, Record<string, number>>; camps?: Record<string, number>; nextId?:number; version: 1 | 2; parts: SkyPart[]; blueprints: SkyBlueprint[]; fusions: Record<string, SkyFusion[]> }
export interface SkyLease { owner: string; expiresTick: number }
export interface AscendPreview { from: Vec3; exit: Vec3; expiresTick: number }
export interface SkyContactEvent {id:string;tick:number;part:number;position:Vec3;material:SkyMaterial;strength:number;kind:'collision'|'explosion'}
export interface SkyboundSnapshot {contactEvents?:SkyContactEvent[]; storage?: {part: number; items: Record<string, number>;gearItems?:import('../equipment/items').GearContainer}[]; camp?: {bed: number}; physics?: {activeAssemblies:number;sleepingParts:number;contacts:number;dynamicContacts?:number;historyFrames:number}; parts: (SkyPart & {lease?: SkyLease; recalling: boolean; powered: boolean; lightRadius: number})[]; riding?: {seat: number; driver: boolean}; blueprints: SkyBlueprint[]; fusions: SkyFusion[]; ascendPreview?: AscendPreview }
export interface SkyContext {prepareDrops?(drops:readonly {id:string;count:number;point:Vec3}[]):()=>void; prepareEquipmentTransfer?(direction:'store'|'take',items:Record<string,number>,gearItems:import('../equipment/items').GearContainer|undefined,selection:string):import('../equipment/items').GearStoragePlan; canReceiveItem?(id: string, count: number): boolean; unsafeCamp?(point: Vec3): boolean; canRest?: boolean; energyCapacity?:number; tick: number; bounds: WorldBounds; player: Vec3; inventory: Record<string, number>; actors: {id: string; position: Vec3}[]; material?(point:Vec3):SkyMaterial|undefined; solid(point: Vec3): boolean; occupied?(point: Vec3): boolean; protected?(point: Vec3): boolean; immersion?(point: Vec3): number; waterFraction?(point:Vec3,height:number):number; hullWaterFraction?(parts:readonly SkyPart[],point:Vec3,height:number):number; temperature?(point: Vec3): number; terrainEdits?: readonly {position:Vec3;radius:number}[]; current?(point:Vec3):Vec3; wind?(point:Vec3):Vec3 }
export type SkyAction = 'sky-throw' | 'sky-plan-rename' | 'sky-plan-delete' | 'sky-store' | 'sky-take' | 'sky-camp' | 'sky-camp-clear' | 'sky-upright' | 'sky-share' | 'sky-element' | 'sky-toggle' | 'sky-charge' | 'sky-ride' | 'sky-salvage' | 'sky-part' | 'sky-grab' | 'sky-move' | 'sky-release' | 'sky-glue' | 'sky-unglue' | 'sky-recall' | 'sky-ascend-preview' | 'sky-ascend' | 'sky-blueprint' | 'sky-rebuild' | 'sky-fuse' | 'sky-unfuse';
export const SKY_ACTIONS: readonly SkyAction[] = ['sky-throw','sky-plan-rename','sky-plan-delete','sky-store','sky-take','sky-camp','sky-camp-clear','sky-upright','sky-share','sky-element','sky-toggle','sky-charge','sky-ride','sky-salvage','sky-part','sky-grab','sky-move','sky-release','sky-glue','sky-unglue','sky-recall','sky-ascend-preview','sky-ascend','sky-blueprint','sky-rebuild','sky-fuse','sky-unfuse'];
export const SKY_LIMITS = { parts: 64, assembly: 16, blueprints: 16, historyTicks: 120, leaseTicks: 150, previewTicks: 90 } as const;
export const PART_HALF: Record<SkyPartKind, Vec3> = {beam: {x: 1, y: .125, z: .125}, slab: {x: 1, y: .125, z: 1}, block: {x: .5, y: .5, z: .5}, wheel: {x: .2, y: .5, z: .5}, thruster: {x: .3, y: .3, z: .5}, sail: {x: 1, y: 1.5, z: .125}, battery: {x: .3, y: .3, z: .3}, switch: {x: .2, y: .125, z: .2}, lamp: {x: .2, y: .3, z: .2}, emitter: {x: .3, y: .3, z: .4}, seat: {x: .4, y: .25, z: .4}, storage: {x: .5, y: .4, z: .4}, bed: {x: .45, y: .2, z: .9}};
export const MATERIAL_ITEM: Record<SkyMaterial, string> = {wood: 'wood', stone: 'stone', metal: 'iron'};
export const MATERIAL_MASS: Record<SkyMaterial, number> = {wood: 2, stone: 6, metal: 10};
export const PART_COST: Record<SkyPartKind, number> = {beam: 2, slab: 4, block: 3, wheel: 2, thruster: 6, sail: 4, battery: 4, switch: 1, lamp: 2, emitter: 4, seat: 2, storage: 4, bed: 3};

export type SkyElement = 'fire' | 'frost' | 'shock';
export interface SkyEffect { id: string; tick: number; sourcePart: number; owner: string; element: SkyElement; origin: Vec3; direction: Vec3; range: number; radius: number; damage: number; targets: 'enemies' }
export const ENVIRONMENT_LIMITS = {effectsPerTick: 32, chainParts: 8, spreadPerTick: 16} as const;

export interface SkyTrialTemplate { kind: SkyPartKind; material: SkyMaterial; position: Vec3; rotation?: number; links: number[]; energy?: number; frozen?: number; anchored?: boolean }
