import {test,expect,type Locator,type Page} from '@playwright/test';
import {PlayerControls,read,choosePerformance,type CampaignProbe} from './helpers/campaign-controls';
import type {InventoryState} from '../../src/prototype/core/inventory';
const activate=(locator:Locator,mobile:boolean)=>mobile?locator.tap():locator.click();
const probe=async(page:Page)=>await read(page) as CampaignProbe&{campaign:CampaignProbe['campaign']&{inventory:InventoryState};home:{storage:{materials:Record<number,number>;items:Record<string,number>}}};

test('campaign-inventory-stacks empty layouts and storage expose bounded, accessible count controls',async({page,isMobile})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('/?test=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=inventory]'),isMobile);
 const workbench=page.getByRole('region',{name:'所持品の枠操作'});await expect(workbench).toContainText('持物の枠 0/96');await expect(workbench.locator('[data-inventory-action=sort]')).toBeDisabled();
 await activate(page.locator('[data-tab=homestead]'),isMobile);const wood=page.locator('[data-item="deposit:4"]'),quantity=wood.getByRole('spinbutton');await expect(quantity).toHaveValue('1');await expect(wood.locator('[data-command=homestead]')).toBeDisabled();for(const invalid of ['0','1.5','999999999','']){await quantity.fill(invalid);await expect(quantity).toHaveAttribute('aria-invalid','true');await expect(wood.locator('[data-command=homestead]')).toBeDisabled();}
 for(const element of [quantity,wood.locator('[data-command=homestead]')]){const box=await element.boundingBox();expect(box?.width).toBeGreaterThanOrEqual(48);expect(box?.height).toBeGreaterThanOrEqual(48);}expect((await read(page)).inventory[4]).toBe(0);expect(errors).toEqual([]);
});

test('campaign-inventory-stacks earned supplies support split combine move storage cancel physical pickup and saved reload',async({page,isMobile},testInfo)=>{
 test.setTimeout(900000);testInfo.annotations.push({type:'input-mode',description:isMobile?'Production Android touch controls':'Production keyboard look and menu controls'});const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('/?test=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await choosePerformance(page,isMobile);await activate(page.locator('#start'),isMobile);const controls=new PlayerControls(page,isMobile);await controls.initialize();
 try{
  await controls.walkTo(-.55,6.15);await controls.action('#tool-switch','Digit2');await controls.gather(4,18,[{x:-1.7,y:.58,z:6.25},{x:-1.7,y:.58,z:6.95},{x:-2.2,y:.58,z:6.25}],'sample-wood');await controls.walkTo(-.55,5.25);await controls.walkTo(-3.45,5.25);await controls.walkTo(-3.45,6.35);await controls.gather(3,15,[{x:-4.2,y:.55,z:6.8},{x:-4.5,y:.55,z:6.8},{x:-4.5,y:.65,z:6.5}],'sample-stone');await controls.walkTo(-3.45,6.65);await controls.gather(7,8,[{x:-3.45,y:.5,z:7.9},{x:-3.1,y:.5,z:7.9},{x:-3.8,y:.5,z:7.9}],'sample-grass');await controls.walkTo(-3.45,5.3);await controls.interact('hearth',{x:-3,y:.9,z:4});await expect.poll(async()=>(await read(page)).campaign.flameTier).toBe(1);await controls.walkTo(-.75,5.3);await controls.aim({x:-.75,y:.4,z:4.3});
  await controls.menu('crafting');for(const id of ['arrows','berry-meal']){await page.locator(`[data-item="${id}"]`).getByRole('spinbutton').fill('2');await controls.row(id,'craft');}await controls.row('dagger','craft');await expect.poll(async()=>(await read(page)).campaign.items.arrows).toBe(16);await expect.poll(async()=>(await read(page)).campaign.items['berry-meal']).toBe(2);
  await activate(page.locator('[data-tab=inventory]'),isMobile);const workbench=page.getByRole('region',{name:'所持品の枠操作'}),wood=workbench.locator('[data-inventory-key="material:4"]');await activate(wood,isMobile);const woodSlot=Number(await wood.getAttribute('data-inventory-slot')),quantity=workbench.getByRole('spinbutton',{name:'操作する数',exact:true}),target=workbench.getByRole('combobox',{name:'移動・結合先の枠'}),woodBefore=(await read(page)).inventory[4];
  for(const value of ['0','1.5','999999999','']){await quantity.fill(value);await expect(workbench.locator('[data-inventory-action=split]')).toBeDisabled();await expect(workbench.locator('[data-inventory-action=drop]')).toBeDisabled();}await quantity.fill('3');await target.selectOption('95');await activate(workbench.locator('[data-inventory-action=split]'),isMobile);await expect(workbench.locator('[data-inventory-slot="95"]')).toContainText('×3');expect((await read(page)).inventory[4]).toBe(woodBefore);
  await activate(workbench.locator('[data-inventory-slot="95"]'),isMobile);await quantity.fill('1');await target.selectOption(String(woodSlot));await activate(workbench.locator('[data-inventory-action=combine]'),isMobile);await expect(workbench.locator('[data-inventory-slot="95"]')).toContainText('×2');await quantity.fill('2');await target.selectOption('94');await activate(workbench.locator('[data-inventory-action=move]'),isMobile);await expect(workbench.locator('[data-inventory-slot="95"]')).toHaveCount(0);await expect(workbench.locator('[data-inventory-slot="94"]')).toContainText('×2');await activate(workbench.locator('[data-inventory-action=sort]'),isMobile);await expect(workbench.locator('[data-inventory-key="material:4"]')).toHaveCount(1);expect((await read(page)).inventory[4]).toBe(woodBefore);
  await activate(workbench.locator('[data-inventory-key="item:dagger"]'),isMobile);await expect(workbench.locator('.inventory-selection')).toContainText('通常攻撃 32→20');await expect(workbench.locator('[data-inventory-action=drop]')).toBeDisabled();await controls.row('dagger','equip');await expect.poll(async()=>(await read(page)).campaign.equipment.weapon).toBe('dagger');
  await activate(workbench.locator('[data-inventory-key="item:arrows"]'),isMobile);await quantity.fill('2');await activate(workbench.locator('[data-inventory-action=drop]'),isMobile);await expect(page.getByRole('group',{name:'落とす数の確認'})).toBeVisible();await activate(page.getByRole('group',{name:'落とす数の確認'}).getByRole('button',{name:'やめる',exact:true}),isMobile);expect((await probe(page)).campaign.inventory.drops).toHaveLength(0);await activate(workbench.locator('[data-inventory-action=drop]'),isMobile);await activate(page.locator('[data-tab=homestead]'),isMobile);await activate(page.locator('[data-tab=inventory]'),isMobile);await expect(page.getByRole('group',{name:'落とす数の確認'})).toHaveCount(0);expect((await read(page)).campaign.items.arrows).toBe(16);
  await activate(page.locator('[data-tab=homestead]'),isMobile);const transfer=async(id:string,count:number)=>{const row=page.locator(`[data-item="${id}"]`);await row.getByRole('spinbutton').fill(String(count));await activate(row.locator('[data-command=homestead]'),isMobile);};await transfer('deposit:4',2);await transfer('deposit:item:arrows',5);await transfer('deposit:item:berry-meal',1);await transfer('withdraw:item:arrows',3);expect((await probe(page)).home.storage.items.arrows).toBe(2);expect((await read(page)).campaign.items.arrows).toBe(14);expect((await probe(page)).home.storage.items['berry-meal']).toBe(1);
  await activate(page.locator('[data-tab=inventory]'),isMobile);await activate(workbench.locator('[data-inventory-key="item:arrows"]'),isMobile);await quantity.fill('2');await activate(workbench.locator('[data-inventory-action=drop]'),isMobile);await activate(page.getByRole('button',{name:'地面に落とす（確定）',exact:true}),isMobile);await expect.poll(async()=>(await probe(page)).campaign.inventory.drops.length).toBe(1);expect((await read(page)).campaign.items.arrows).toBe(12);await controls.resume();const start=(await read(page)).seconds;await expect.poll(async()=>(await read(page)).seconds).toBeGreaterThan(start+1);const drop=(await probe(page)).campaign.inventory.drops[0];await controls.aim(drop.position);await expect(page.locator('#game')).toHaveAttribute('data-target','inventory-drop:'+drop.id);await page.screenshot({path:testInfo.outputPath('physical-inventory-bundle.png')});await controls.action('[data-action="interact"]','KeyE');await expect.poll(async()=>(await read(page)).campaign.items.arrows).toBe(14);await expect.poll(async()=>(await probe(page)).campaign.inventory.drops.length).toBe(0);
  await controls.menu('inventory');await activate(workbench.locator('[data-inventory-key="item:berry-meal"]'),isMobile);await quantity.fill('1');await activate(workbench.locator('[data-inventory-action=drop]'),isMobile);await activate(page.getByRole('button',{name:'地面に落とす（確定）',exact:true}),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);await activate(page.getByRole('button',{name:'今すぐ保存',exact:true}),isMobile);const saved=await probe(page);expect(saved.campaign.inventory.drops).toHaveLength(1);await controls.dispose();await page.reload();await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});const restored=await probe(page);expect(restored.campaign.inventory.drops).toEqual(saved.campaign.inventory.drops);expect(restored.home.storage).toEqual(saved.home.storage);expect(restored.campaign.items.arrows).toBe(14);
  await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=inventory]'),isMobile);const bundle=page.locator('.inventory-drop');await expect(bundle).toContainText('野草の煮込み');await activate(bundle.getByRole('button',{name:'指定数を回収',exact:true}),isMobile);await expect.poll(async()=>(await read(page)).campaign.items['berry-meal']).toBe(1);expect((await probe(page)).campaign.inventory.drops).toHaveLength(0);await page.screenshot({path:testInfo.outputPath('saved-inventory-and-storage.png')});
 }finally{await controls.dispose();}expect(errors).toEqual([]);
});
