import {test,expect,type Locator} from '@playwright/test';
const activate=(locator:Locator,mobile:boolean)=>mobile?locator.tap():locator.click();
test('western expedition is added through a confirmed saved-world menu, preserving its source',async({page,isMobile})=>{
 test.setTimeout(300000);const errors:string[]=[];page.on('pageerror',error=>errors.push(String(error)));
 const read=()=>page.evaluate(()=>Reflect.get(window,'__coreProbe') as {worldReady:boolean;westernContent:boolean;saveStatus:string;restoreFailure:string|null;campaign:{flameTier:number};inventory:Record<string,number>});
 await page.goto('/?test=1&streaming=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await expect.poll(async()=>(await read()).worldReady,{timeout:120000}).toBe(true);await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);
 const expand=page.getByRole('button',{name:'西方遠征を追加する',exact:true});await expect(expand).toBeEnabled();await activate(expand,isMobile);const confirmation=page.getByRole('group',{name:'西方遠征追加の確認'});await expect(confirmation).toContainText('逆移行できません');await activate(confirmation.getByRole('button',{name:'やめる',exact:true}),isMobile);expect((await read()).westernContent).toBe(false);expect(await page.evaluate(()=>localStorage.getItem('ash-campaign-v4'))).toBeNull();
 const before=await read();await activate(expand,isMobile);await Promise.all([page.waitForEvent('domcontentloaded'),activate(page.getByRole('button',{name:'保存して西方遠征を追加',exact:true}),isMobile)]);await expect.poll(async()=>(await read())?.worldReady,{timeout:120000}).toBe(true);expect((await read()).westernContent).toBe(true);expect((await read()).restoreFailure).toBeNull();expect((await read()).inventory).toEqual(before.inventory);expect((await read()).campaign.flameTier).toBe(before.campaign.flameTier);
 expect(await page.evaluate(()=>localStorage.getItem('ash-campaign-active-format'))).toBe('campaign-v4');const source=await page.evaluate(()=>localStorage.getItem('ash-campaign-v3'));expect(source).not.toBeNull();const original=await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.includes('migration')||key.includes('western')).map(key=>localStorage.getItem(key)));expect(original).toContain(source);
 await page.goto('/?test=1');await expect.poll(async()=>(await read())?.worldReady,{timeout:120000}).toBe(true);expect((await read()).westernContent).toBe(true);await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);await expect(page.getByRole('button',{name:'西方遠征を追加する',exact:true})).toHaveCount(0);expect(errors).toEqual([]);
});
