import {test,expect,type Locator} from '@playwright/test';
const activate=(locator:Locator,mobile:boolean)=>mobile?locator.tap():locator.click();
test('optional exploration camera is reachable, saved and keeps first-person default',async({page,isMobile},info)=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',error=>errors.push(String(error)));
 const read=()=>page.evaluate(()=>Reflect.get(window,'__coreProbe') as {worldReady:boolean;settings:{cameraMode:string;cameraDistance:number;reducedMotion:boolean;textScale:number};stats:{cameraMode:string;cameraDistance:number;reducedMotion:boolean};yaw:number;pitch:number});
 await page.goto('/?test=1&streaming=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await expect.poll(async()=>(await read()).worldReady,{timeout:120000}).toBe(true);expect((await read()).settings.cameraMode).toBe('first');
 await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);const before=await read();await page.getByRole('combobox',{name:'視点',exact:true}).selectOption('third');
 await expect.poll(async()=>(await read()).stats.cameraMode).toBe('third');await page.getByRole('combobox',{name:'説明文の大きさ',exact:true}).selectOption('1.25');await page.getByRole('combobox',{name:'画面の揺れ・被弾の明滅',exact:true}).selectOption('1');await expect(page.locator('body')).toHaveClass(/reduced-motion/);await expect.poll(async()=>(await read()).stats.reducedMotion).toBe(true);expect((await read()).yaw).toBe(before.yaw);expect((await read()).pitch).toBe(before.pitch);
 await activate(page.getByRole('button',{name:'今すぐ保存',exact:true}),isMobile);await page.reload();await expect.poll(async()=>(await read())?.worldReady,{timeout:120000}).toBe(true);expect((await read()).settings.cameraMode).toBe('third');expect((await read()).settings.reducedMotion).toBe(true);expect((await read()).settings.textScale).toBe(1.25);
 await activate(page.locator('#start'),isMobile);await expect(page.locator('#game')).toHaveAttribute('data-running','true');await expect.poll(async()=>(await read()).stats.cameraDistance).toBeGreaterThan(.7);await page.screenshot({path:info.outputPath('third-person-exploration.png')});
 if(isMobile)await page.locator('#campaign-toggle').tap();else await page.keyboard.press('KeyI');await activate(page.locator('[data-tab=settings]'),isMobile);await page.getByRole('combobox',{name:'視点',exact:true}).selectOption('first');await expect.poll(async()=>(await read()).stats.cameraMode).toBe('first');expect(errors).toEqual([]);
});
