import {test,expect} from '@playwright/test';
const probe=(page:import('@playwright/test').Page)=>page.evaluate(()=>Reflect.get(window,'__coreProbe'));
test('campaign menus and exact save continuation are reachable',async({page,isMobile})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('/?test=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await page.locator('#start').click();await expect(page.locator('#game')).toHaveAttribute('data-running','true');
 if(isMobile)await page.locator('#campaign-toggle').tap();else await page.keyboard.press('KeyI');await expect(page.locator('#campaign-panel')).toBeVisible();await expect(page.locator('#game')).toHaveAttribute('data-running','false');await page.locator('[data-tab=crafting]').click();await expect(page.locator('[data-item=grapple]')).toContainText('鍛冶師');await page.locator('[data-tab=journal]').click();await expect(page.locator('[data-item=gather]')).toContainText('木材8');await page.locator('[data-tab=map]').click();await expect(page.locator('.campaign-map-marker.player')).toBeVisible();await page.locator('[data-tab=settings]').click();await page.getByRole('button',{name:'今すぐ保存',exact:true}).click();await expect(page.locator('#campaign-body')).toContainText('保存済み');const before=await probe(page);await page.reload();await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});expect((await probe(page)).inventory).toEqual(before.inventory);expect((await probe(page)).campaign.completed).toEqual(before.campaign.completed);await page.locator('#start').click();if(isMobile)await page.locator('#campaign-toggle').tap();else await page.keyboard.press('KeyM');await page.locator('[data-tab=settings]').click();await page.getByRole('button',{name:'新しく始める',exact:true}).click();await page.getByRole('button',{name:'やめる',exact:true}).click();expect((await probe(page)).campaign).toEqual(before.campaign);await page.getByRole('button',{name:'探索に戻る',exact:true}).click();await expect(page.locator('#campaign-panel')).toBeHidden();await expect(page.locator('#game')).toHaveAttribute('data-running','true');expect(errors).toEqual([]);await page.screenshot({path:`test-results/${isMobile?'mobile':'desktop'}-campaign-start.png`});
});
test('campaign new-world confirmation protects the previous checkpoint',async({page})=>{
 test.setTimeout(180000);await page.goto('/?test=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await page.locator('#campaign-toggle').click();await page.locator('[data-tab=settings]').click();const volume=page.getByRole('slider',{name:'音量'});await volume.focus();await page.keyboard.press('Home');for(let i=0;i<4;i++)await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'今すぐ保存',exact:true}).click();await page.getByRole('button',{name:'新しく始める',exact:true}).click();await page.getByRole('button',{name:'バックアップして新しい旅へ',exact:true}).click();await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});expect(await page.evaluate(()=>!!localStorage.getItem('ash-campaign-v1:backup'))).toBe(true);expect((await probe(page)).campaign.level).toBe(1);expect((await probe(page)).campaign.flameTier).toBe(0);expect((await probe(page)).settings.volume).toBe(.8);
});
