import {test,expect,type Locator} from '@playwright/test';
const activate=(locator:Locator,mobile:boolean)=>mobile?locator.tap():locator.click();
test('a downloaded save imports only after validation and confirmation while retaining both journeys',async({page,isMobile})=>{
 test.setTimeout(360000);const errors:string[]=[];page.on('pageerror',error=>errors.push(String(error)));
 const read=()=>page.evaluate(()=>Reflect.get(window,'__coreProbe') as {worldReady:boolean;settings:{volume:number};saveStatus:string;restoreFailure:string|null});
 const bytes=()=>page.evaluate(()=>localStorage.getItem('ash-campaign-v3'));
 const ready=async()=>{await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await expect.poll(async()=>(await read()).worldReady,{timeout:120000}).toBe(true);expect((await read()).restoreFailure).toBeNull();};
 const settings=async()=>{await activate(page.locator('#restart'),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);};
 await page.goto('/?test=1&streaming=1');await ready();await settings();const volume=page.getByRole('slider',{name:'音量',exact:true});await volume.scrollIntoViewIfNeeded();if(isMobile){const box=(await volume.boundingBox())!;await volume.tap({position:{x:box.width*.2,y:box.height/2}});}else{await volume.focus();await page.keyboard.press('Home');for(let i=0;i<4;i++)await page.keyboard.press('ArrowRight');}
 await expect.poll(async()=>(await read()).settings.volume).toBeLessThan(.5);await activate(page.getByRole('button',{name:'今すぐ保存',exact:true}),isMobile);await expect.poll(async()=>(await read()).saveStatus).toContain('保存済み');const original=await bytes(),originalVolume=(await read()).settings.volume;
 const [download]=await Promise.all([page.waitForEvent('download'),activate(page.getByRole('button',{name:'最後の保存を端末へ書き出す',exact:true}),isMobile)]);expect(download.suggestedFilename()).toMatch(/^seven-lights-[a-z0-9]+-[0-9a-f]{8}\.json$/);const stream=await download.createReadStream();expect(stream).not.toBeNull();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));const fileBytes=Buffer.concat(chunks);expect(fileBytes.toString('utf8')).toBe(original);
 await activate(page.getByRole('button',{name:'新しく始める',exact:true}),isMobile);await Promise.all([page.waitForEvent('domcontentloaded'),activate(page.getByRole('button',{name:'バックアップして新しい旅へ',exact:true}),isMobile)]);await ready();expect((await read()).settings.volume).toBe(.8);await settings();const fresh=await bytes();
 const chooser=page.getByLabel('取り込む保存ファイル',{exact:true});await chooser.setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await expect(page.locator('.campaign-feedback')).toContainText(/検証|読み取れません|不正/);expect(await bytes()).toBe(fresh);await expect(page.getByRole('group',{name:'保存ファイル取込の確認'})).toHaveCount(0);
 await chooser.setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:fileBytes});const confirmation=page.getByRole('group',{name:'保存ファイル取込の確認'});await expect(confirmation).toBeVisible({timeout:30000});expect(await bytes()).toBe(fresh);await activate(confirmation.getByRole('button',{name:'やめる',exact:true}),isMobile);expect(await bytes()).toBe(fresh);
 await chooser.setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:fileBytes});await expect(confirmation).toBeVisible({timeout:30000});await Promise.all([page.waitForEvent('domcontentloaded'),activate(page.getByRole('button',{name:'現在の保存を保管して取り込む',exact:true}),isMobile)]);await ready();expect((await read()).settings.volume).toBe(originalVolume);expect(await bytes()).toBe(original);expect(await page.evaluate(raw=>Object.keys(localStorage).some(key=>key.startsWith('ash-campaign-v3:archive:')&&localStorage.getItem(key)===raw),fresh)).toBe(true);expect(errors).toEqual([]);
});
