import {test,expect,type Locator,type Page} from '@playwright/test';
const KEY='ash-campaign-v3';
const activate=(locator:Locator,mobile:boolean)=>mobile?locator.tap():locator.click();
const probe=(page:Page)=>page.evaluate(()=>Reflect.get(window,'__coreProbe') as {worldReady:boolean;saveStatus:string;restoreFailure:string|null});
const slots=(page:Page)=>page.evaluate(key=>({primary:localStorage.getItem(key),backup:localStorage.getItem(key+':backup'),index:localStorage.getItem(key+':archives'),journal:localStorage.getItem(key+':archive-cleanup')}),KEY);
const archives=(page:Page)=>page.evaluate(key=>{const raw=localStorage.getItem(key+':archives');return raw===null?[]:(JSON.parse(JSON.parse(raw).payload) as {id:string}[]).map(entry=>({...entry,raw:localStorage.getItem(key+':archive:'+entry.id)}));},KEY);
async function ready(page:Page){await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await expect.poll(async()=>(await probe(page)).worldReady,{timeout:120000}).toBe(true);expect((await probe(page)).restoreFailure).toBeNull();}
async function settings(page:Page,mobile:boolean){await activate(page.locator('#restart'),mobile);await activate(page.locator('[data-tab=settings]'),mobile);}
async function save(page:Page,mobile:boolean){await activate(page.getByRole('button',{name:'今すぐ保存',exact:true}),mobile);await expect.poll(async()=>(await probe(page)).saveStatus).toContain('保存済み');}

test('history cleanup exports the exact selected journey and requires a fresh irreversible confirmation',async({page,isMobile},testInfo)=>{
 test.setTimeout(480000);testInfo.annotations.push({type:'save-history-cleanup',description:'Production menus create two archives; storage is observed only. Cancel, tab switch, close/reopen and exact export are exercised before deletion.'});
 const errors:string[]=[];page.on('pageerror',error=>errors.push(String(error)));await page.goto('/?test=1&streaming=1');await ready(page);
 for(let i=0;i<2;i++){await settings(page,isMobile);await save(page,isMobile);await activate(page.getByRole('button',{name:'新しく始める',exact:true}),isMobile);await Promise.all([page.waitForEvent('domcontentloaded'),activate(page.getByRole('button',{name:'バックアップして新しい旅へ',exact:true}),isMobile)]);await ready(page);}
 await settings(page,isMobile);await save(page,isMobile);await save(page,isMobile);const before=await slots(page),history=await archives(page);expect(history).toHaveLength(2);const target=history[0],retained=history[1],row=page.locator(`[data-archive-id="${target.id}"]`),choose=row.getByRole('button',{name:'書き出して履歴整理を確認',exact:true});
 await expect(page.locator(`[data-archive-id="${retained.id}"]`).getByRole('button',{name:'書き出して履歴整理を確認',exact:true})).toBeDisabled();await expect(page.locator('.campaign-archive-usage')).toContainText('2 / 32件');
 const warning=page.getByRole('group',{name:'履歴の完全削除の確認'}),confirm=warning.getByRole('button',{name:'選んだ履歴を完全に削除',exact:true}),ack=warning.getByRole('checkbox',{name:'書き出したJSONファイルを端末で確認しました',exact:true});
 async function chooseAndExport(){const [download]=await Promise.all([page.waitForEvent('download'),activate(choose,isMobile)]);await expect(warning).toBeVisible();const stream=await download.createReadStream();expect(stream).not.toBeNull();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString('utf8')).toBe(target.raw);await expect(warning).toContainText(target.id);await expect(warning).toContainText(download.suggestedFilename());await expect(confirm).toBeDisabled();await expect(ack).not.toBeChecked();expect(await slots(page)).toEqual(before);}
 await chooseAndExport();await activate(warning.getByRole('button',{name:'やめる',exact:true}),isMobile);await expect(warning).toHaveCount(0);expect(await archives(page)).toEqual(history);
 await chooseAndExport();await activate(page.locator('[data-tab=inventory]'),isMobile);await activate(page.locator('[data-tab=settings]'),isMobile);await expect(warning).toHaveCount(0);
 await chooseAndExport();await activate(page.getByRole('button',{name:'旅の記録を閉じる',exact:true}),isMobile);await settings(page,isMobile);await expect(warning).toHaveCount(0);expect(await archives(page)).toEqual(history);
 // Fault injection is confined to this fresh Playwright context. It simulates a
 // quota rejection without changing a stored value or using a gameplay shortcut.
 await chooseAndExport();await activate(ack,isMobile);await page.evaluate(key=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(name:string,value:string){if(name===key+':archive-cleanup'){Storage.prototype.setItem=original;throw new DOMException('Test quota rejection','QuotaExceededError');}original.call(this,name,value);};},KEY);await activate(confirm,isMobile);await expect(warning).toHaveCount(0);await expect(page.locator('.campaign-feedback')).toContainText('完了確認できません');expect(await slots(page)).toEqual(before);expect(await archives(page)).toEqual(history);
 await chooseAndExport();await activate(ack,isMobile);await expect(confirm).toBeEnabled();for(const button of [choose,confirm,warning.getByRole('button',{name:'やめる',exact:true})]){await button.scrollIntoViewIfNeeded();expect((await button.boundingBox())?.height).toBeGreaterThanOrEqual(48);}
 await activate(confirm,isMobile);await expect(row).toHaveCount(0);await expect(page.locator('.campaign-feedback')).toContainText('選んだ履歴を完全に削除しました');await expect(page.locator('.campaign-archive-usage')).toContainText('1 / 32件');expect(await archives(page)).toEqual([retained]);expect(await slots(page)).toMatchObject({primary:before.primary,backup:before.backup,journal:null});expect(await page.evaluate(({key,id})=>localStorage.getItem(key+':archive:'+id),{key:KEY,id:target.id})).toBeNull();
 await page.screenshot({path:testInfo.outputPath('history-cleanup-confirmed.png')});await page.reload();await ready(page);await settings(page,isMobile);await expect(warning).toHaveCount(0);expect(await archives(page)).toEqual([retained]);expect(errors).toEqual([]);
});
