import {observeNotice} from './helpers/transient-observation';
import {CAMPAIGN_PROTOCOL} from '../../src/prototype/network/protocol';
import {test,expect,type Page} from '@playwright/test';
// These two manually managed contexts have one explicit trace owner.
test.use({trace:'off'});
const readInput=(page:Page)=>page.evaluate(()=>Reflect.get(window,'__inputProbe'));
const read=(page:Page)=>page.evaluate(()=>Reflect.get(window,'__coreProbe'));
async function openJourney(page:Page,url:string){await page.goto(url);await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:120000});await expect.poll(async()=>(await read(page)).worldReady,{timeout:180000}).toBe(true);await expect(page.locator('#start')).toBeEnabled();for(let i=0;i<3&&(await read(page)).settings.graphics!=='performance';i++)await page.locator('#quality-toggle').click();expect((await read(page)).settings.graphics).toBe('performance');await page.locator('#start').click();if((await read(page)).guestPreview){await expect(page.locator('#campaign-panel')).toBeVisible();await expect(page.locator('#game')).toHaveAttribute('data-running','false');}else{await expect(page.locator('#game')).toHaveAttribute('data-running','true');await page.keyboard.press('KeyI');}await page.locator('[data-tab=cooperation]').click();}
test('cooperation integration: two real browsers share movement, permissions, chat and reconnect',async({browser,request},testInfo)=>{
 test.skip(process.env.E2E_COOP!=='1','Requires the exact deployed PR4 relay, not the static preview server');test.setTimeout(600000);
 const origin=process.env.E2E_BASE_URL!;const manifest=await (await request.get(origin+'/deployment.json')).json();expect(manifest.commit).toBe(process.env.EXPECTED_COMMIT);expect(manifest.campaignCoop).toBe(true);expect(manifest.campaignProtocol).toBe(CAMPAIGN_PROTOCOL);expect(await (await request.get(origin+'/campaign-room/health')).json()).toMatchObject({enabled:true,maxPlayers:2,protocol:CAMPAIGN_PROTOCOL});
 const hostContext=await browser.newContext({viewport:{width:960,height:540},deviceScaleFactor:1}),guestContext=await browser.newContext({viewport:{width:960,height:540},deviceScaleFactor:1});hostContext.setDefaultTimeout(30000);guestContext.setDefaultTimeout(30000);await hostContext.tracing.start({screenshots:false,snapshots:true,sources:true});await guestContext.tracing.start({screenshots:false,snapshots:true,sources:true});const host=await hostContext.newPage(),guest=await guestContext.newPage(),errors:string[]=[],phases:string[]=[];const mark=async(label:string)=>{phases.push(label);await testInfo.attach('phase-'+phases.length,{body:JSON.stringify({phase:label,at:new Date().toISOString()}),contentType:'application/json'});};for(const page of [host,guest])page.on('pageerror',error=>errors.push(String(error)));
 try{
  await mark('host: load and open cooperation menu');await openJourney(host,origin+'/?test=1');await mark('host: create room');await expect(host.locator('[data-coop=create]')).toBeEnabled();await host.locator('[data-coop=create]').click();await expect.poll(async()=>(await read(host)).cooperation.online).toBe(true);const invite=await host.locator('#cooperation-invite').inputValue(),guestURL=new URL(invite);guestURL.searchParams.set('test','1');
  await mark('guest: load invite without autojoining');await openJourney(guest,guestURL.href);await mark('guest: explicitly join');expect((await read(guest)).cooperation.role).toBeNull();const soloSave=await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'));await guest.locator('[data-coop=join]').click();await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:180000}).toBe(true);await expect.poll(async()=>(await read(host)).cooperation.players).toBe(2);expect((await read(guest)).cooperation.guestBuild).toBe(false);
  await mark('both: shared chat');await guest.locator('#cooperation-chat').fill('灯台で合流しよう <b>text</b>');const chatButton=await guest.locator('[data-coop=chat]').elementHandle();expect(chatButton).not.toBeNull();const chatTime=(await read(guest)).seconds;await expect.poll(async()=>(await read(guest)).seconds).toBeGreaterThan(chatTime+.5);expect(await chatButton!.evaluate(node=>node.isConnected),'Live world snapshots must not detach the chat action').toBe(true);await expect(guest.locator('#cooperation-chat')).toHaveValue('灯台で合流しよう <b>text</b>');await guest.locator('[data-coop=chat]').click();await expect(host.getByRole('log')).toContainText('灯台で合流しよう <b>text</b>');expect(await host.getByRole('log').locator('b').count()).toBe(0);
  const pausedHost=await read(host);await mark('guest: move through authoritative world');await guest.getByRole('button',{name:'探索に戻る',exact:true}).click();await expect(guest.locator('#game')).toHaveAttribute('data-running','true');const start=await readInput(guest);await guest.keyboard.down('KeyD');try{await expect.poll(async()=>(await readInput(guest)).position.x,{timeout:60000}).toBeGreaterThan(start.position.x+.65);}finally{await guest.keyboard.up('KeyD');}await expect.poll(async()=>Math.abs((await read(host)).cooperation.companion.position.x-(await read(guest)).position.x),{timeout:30000}).toBeLessThan(.4);
  await expect(host.locator('#error')).toBeHidden();await expect(guest.locator('#error')).toBeHidden();const movedHost=await read(host);expect(movedHost.seconds).toBeGreaterThan(pausedHost.seconds);expect(movedHost.stats.renderedFrames).toBe(pausedHost.stats.renderedFrames);await mark('permissions: denied then host grants');const deniedNotice=await observeNotice(guest,'#message','許可');try{await guest.keyboard.press('KeyB');await expect.poll(()=>deniedNotice.read()).not.toBeNull();}finally{await deniedNotice.dispose();}await expect(guest.locator('#cast')).toContainText('放つ');expect((await read(host)).cooperation.guestBuild).toBe(false);
  await host.locator('[data-coop=allow-build]').click();await expect.poll(async()=>(await read(guest)).cooperation.guestBuild).toBe(true);await guest.keyboard.press('KeyB');await expect(guest.locator('#cast')).toContainText('建築終了');await guest.keyboard.press('KeyG');
  expect(await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe(soloSave);await host.screenshot({path:testInfo.outputPath('host-party.png')});await guest.screenshot({path:testInfo.outputPath('guest-party.png')});
  await mark('host: reload, guest pauses without queuing movement');const beforeReload=(await read(guest)).position;await host.reload();await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:30000}).toBe(false);const frozen=(await read(guest)).position;await guest.keyboard.down('KeyD');await guest.waitForTimeout(500);await guest.keyboard.up('KeyD');expect((await read(guest)).position).toEqual(frozen);
  await mark('host: explicitly resume saved room identity');await expect(host.locator('#game')).toHaveAttribute('data-ready','true',{timeout:120000});await expect.poll(async()=>(await read(host)).worldReady,{timeout:180000}).toBe(true);await expect(host.locator('#start')).toBeEnabled();await host.locator('#start').click();await host.keyboard.press('KeyI');await host.locator('[data-tab=cooperation]').click();await host.locator('[data-coop=join]').click();await expect.poll(async()=>(await read(host)).cooperation.role).toBe('host');await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:180000}).toBe(true);expect(Math.hypot((await read(guest)).position.x-beforeReload.x,(await read(guest)).position.z-beforeReload.z)).toBeLessThan(.6);expect(await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe(soloSave);expect(errors).toEqual([]);await mark('complete: movement, permissions, chat, save isolation, reconnect');
 }finally{
  await testInfo.attach('completed-phases',{body:JSON.stringify(phases,null,2),contentType:'application/json'});
  const bounded=async(task:Promise<unknown>)=>Promise.race([task.catch(()=>{}),new Promise(resolve=>setTimeout(resolve,5000))]);
  await bounded(hostContext.tracing.stop({path:testInfo.outputPath('host-trace.zip')}));await bounded(guestContext.tracing.stop({path:testInfo.outputPath('guest-trace.zip')}));
  await bounded(guestContext.close());await bounded(hostContext.close());
 }
});
