import {test,expect,type Page} from '@playwright/test';
const read=(page:Page)=>page.evaluate(()=>Reflect.get(window,'__coreProbe'));
async function openJourney(page:Page,url:string){await page.goto(url);await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:120000});await expect.poll(async()=>(await read(page)).worldReady,{timeout:180000}).toBe(true);await expect(page.locator('#start')).toBeEnabled();await page.locator('#start').click();await expect(page.locator('#game')).toHaveAttribute('data-running','true');await page.keyboard.press('KeyI');await page.locator('[data-tab=cooperation]').click();}
test('cooperation integration: two real browsers share movement, permissions, chat and reconnect',async({browser,request},testInfo)=>{
 test.skip(process.env.E2E_COOP!=='1','Requires the exact deployed PR4 relay, not the static preview server');test.setTimeout(900000);
 const origin=process.env.E2E_BASE_URL!;const manifest=await (await request.get(origin+'/deployment.json')).json();expect(manifest.commit).toBe(process.env.EXPECTED_COMMIT);expect(manifest.campaignCoop).toBe(true);expect(await (await request.get(origin+'/campaign-room/health')).json()).toMatchObject({enabled:true,maxPlayers:2,protocol:1});
 const hostContext=await browser.newContext({viewport:{width:960,height:540},deviceScaleFactor:1}),guestContext=await browser.newContext({viewport:{width:960,height:540},deviceScaleFactor:1});const host=await hostContext.newPage(),guest=await guestContext.newPage(),errors:string[]=[];for(const page of [host,guest])page.on('pageerror',error=>errors.push(String(error)));
 try{
  await openJourney(host,origin+'/?test=1');await expect(host.locator('[data-coop=create]')).toBeEnabled();await host.locator('[data-coop=create]').click();await expect.poll(async()=>(await read(host)).cooperation.online).toBe(true);const invite=await host.locator('#cooperation-invite').inputValue(),guestURL=new URL(invite);guestURL.searchParams.set('test','1');
  await openJourney(guest,guestURL.href);expect((await read(guest)).cooperation.role).toBeNull();const soloSave=await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'));await guest.locator('[data-coop=join]').click();await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:180000}).toBe(true);await expect.poll(async()=>(await read(host)).cooperation.players).toBe(2);expect((await read(guest)).cooperation.guestBuild).toBe(false);
  await guest.locator('#cooperation-chat').fill('灯台で合流しよう <b>text</b>');await guest.locator('[data-coop=chat]').click();await expect(host.getByRole('log')).toContainText('灯台で合流しよう <b>text</b>');expect(await host.getByRole('log').locator('b').count()).toBe(0);
  await guest.getByRole('button',{name:'探索に戻る',exact:true}).click();const start=await read(guest);await guest.keyboard.down('KeyD');try{await expect.poll(async()=>(await read(guest)).position.x,{timeout:60000}).toBeGreaterThan(start.position.x+.65);}finally{await guest.keyboard.up('KeyD');}await expect.poll(async()=>Math.abs((await read(host)).cooperation.companion.position.x-(await read(guest)).position.x),{timeout:30000}).toBeLessThan(.4);
  await guest.keyboard.press('KeyB');await expect(guest.locator('#message')).toContainText('許可');expect((await read(host)).cooperation.guestBuild).toBe(false);
  await host.locator('[data-coop=allow-build]').click();await expect.poll(async()=>(await read(guest)).cooperation.guestBuild).toBe(true);await guest.keyboard.press('KeyB');await expect(guest.locator('#cast')).toContainText('建築終了');await guest.keyboard.press('KeyG');
  expect(await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe(soloSave);await host.screenshot({path:testInfo.outputPath('host-party.png')});await guest.screenshot({path:testInfo.outputPath('guest-party.png')});
  const beforeReload=(await read(guest)).position;await host.reload();await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:30000}).toBe(false);const frozen=(await read(guest)).position;await guest.keyboard.down('KeyD');await guest.waitForTimeout(500);await guest.keyboard.up('KeyD');expect((await read(guest)).position).toEqual(frozen);
  await expect(host.locator('#game')).toHaveAttribute('data-ready','true',{timeout:120000});await expect.poll(async()=>(await read(host)).worldReady,{timeout:180000}).toBe(true);await expect(host.locator('#start')).toBeEnabled();await host.locator('#start').click();await host.keyboard.press('KeyI');await host.locator('[data-tab=cooperation]').click();await host.locator('[data-coop=join]').click();await expect.poll(async()=>(await read(host)).cooperation.role).toBe('host');await expect.poll(async()=>(await read(guest)).cooperation.online,{timeout:180000}).toBe(true);expect(Math.hypot((await read(guest)).position.x-beforeReload.x,(await read(guest)).position.z-beforeReload.z)).toBeLessThan(.6);expect(await guest.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe(soloSave);expect(errors).toEqual([]);
 }finally{await guestContext.close();await hostContext.close();}
});
