import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {GameSimulation} from '../../src/simulation/game-simulation';
test.use({deviceScaleFactor:.5,viewport:{width:844,height:390}});
interface FlightEvidence{tick:number;x:number;y:number;z:number;health:number;stamina:number;active:boolean;staminaDrops:number}
async function evidence(page:Page){return page.evaluate(()=>(window as typeof window&{flightEvidence:FlightEvidence}).flightEvidence);}
async function ticks(page:Page,count:number){const start=(await evidence(page)).tick;await expect.poll(async()=>(await evidence(page)).tick).toBeGreaterThan(start+count);}
test('voxel adventure debug flight supports free steering, held ascent/descent, safe save/exit and menu cancellation',async({page},info)=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 // Observe production worker snapshots only; movement and toggle actions still
 // travel through actual keyboard/touch controls and authority validation.
 await page.addInitScript(()=>{const observed={tick:0,x:0,y:0,z:0,health:0,stamina:0,active:false,staminaDrops:0};(window as typeof window&{flightEvidence:typeof observed}).flightEvidence=observed;window.Worker=new Proxy(window.Worker,{construct(Target,args,newTarget){const worker=Reflect.construct(Target,args,newTarget) as Worker;worker.addEventListener('message',(event:MessageEvent)=>{const message=event.data as {type?:string;state?:{tick:number;player:{x:number;y:number;z:number};adventure:{health:number;stamina:number;traversal?:{debugFlying?:boolean}}}};if(message.type!=='snapshot'||!message.state)return;const s=message.state,active=!!s.adventure.traversal?.debugFlying;if(active&&observed.active&&s.adventure.stamina<observed.stamina-.01)observed.staminaDrops++;Object.assign(observed,{tick:s.tick,...s.player,health:s.adventure.health,stamina:s.adventure.stamina,active});});return worker;}});});
 await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('#app')).toHaveAttribute('data-state','running',{timeout:60000});
 const sim=new GameSimulation();sim.adventure.state.enemies=[];sim.fluid.restore([]);sim.adventure.state.stamina=0;const epoch=await page.locator('#app').getAttribute('data-world-epoch');await page.locator('#import-file').setInputFiles({name:'debug-flight-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(sim.save()))});await expect.poll(()=>page.locator('#app').getAttribute('data-world-epoch')).not.toBe(epoch);await expect(page.locator('#app')).toHaveAttribute('data-state','running');
 const touch=info.project.name==='android-chromium'?await page.context().newCDPSession(page):undefined;
 await page.locator('#system-menu').click();const toggle=page.locator('#debug-flight-toggle');await expect(toggle).toBeEnabled();
 if(touch){const box=await toggle.boundingBox();if(!box)throw Error('Debug setting missing');const x=box.x+box.width/2,y=box.y+box.height/2;await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:5}]});for(let i=1;i<=5;i++)await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-i*20,id:5}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>page.locator('#system-panel').evaluate(el=>el.scrollTop)).toBeGreaterThan(10);await expect(toggle).toHaveAttribute('aria-pressed','false');}
 await toggle.click();await expect(toggle).toHaveAttribute('aria-pressed','true');await page.locator('#system-close').click();await expect(page.locator('#debug-flight-stop')).toBeVisible();const start=await evidence(page);
 const point=async(selector:string,id:number)=>{const box=await page.locator(selector).boundingBox();if(!box)throw Error('Flight control missing: '+selector);expect(box.width).toBeGreaterThanOrEqual(48);expect(box.height).toBeGreaterThanOrEqual(48);return {x:box.x+box.width/2,y:box.y+box.height/2,id};};
 if(touch){const stick=await point('#stick',11),up=await point('#debug-flight-up',12);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[stick,up]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...stick,x:stick.x+32},up]});}else{await page.keyboard.down('KeyD');await page.keyboard.down('Space');}
 await expect.poll(async()=>(await evidence(page)).y).toBeGreaterThan(start.y+5);await expect.poll(async()=>Math.hypot((await evidence(page)).x-start.x,(await evidence(page)).z-start.z)).toBeGreaterThan(2);
 if(touch)await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});else{await page.keyboard.up('Space');await page.keyboard.up('KeyD');}await ticks(page,4);const hover=(await evidence(page)).y;await ticks(page,15);expect((await evidence(page)).y).toBeCloseTo(hover,1);expect((await evidence(page)).staminaDrops).toBe(0);
 // Both mouse/keyboard and mobile can cancel a vertical hold by opening a menu.
 if(touch){const down=await point('#debug-flight-down',13);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[down]});}else await page.keyboard.down('KeyV');await expect.poll(async()=>(await evidence(page)).y).toBeLessThan(hover-1);await page.locator('#system-menu').click();if(touch)await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await page.keyboard.up('KeyV');await ticks(page,4);const paused=(await evidence(page)).y;await ticks(page,12);expect((await evidence(page)).y).toBeCloseTo(paused,1);
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise,path=await download.path();if(!path)throw Error('Export download missing');const saved=JSON.parse(await readFile(path,'utf8')) as {player:{y:number};adventure:Record<string,unknown>};expect(saved.player.y).toBeLessThan(start.y+1);expect(saved.adventure.traversal).toBeUndefined();await expect(toggle).toHaveAttribute('aria-pressed','true');await page.locator('#system-close').click();await ticks(page,8);expect((await evidence(page)).y).toBeCloseTo(paused,1);
 const health=(await evidence(page)).health;await page.locator('#debug-flight-stop').click();await expect.poll(async()=>(await evidence(page)).active).toBe(false);await ticks(page,20);expect((await evidence(page)).health).toBeGreaterThanOrEqual(health);await expect(page.locator('#debug-flight-controls')).toBeHidden();await expect(page.locator('#traverse-glide')).toBeVisible();
 // Flight preference is deliberately temporary, including a reload of a midair save.
 await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#app')).toHaveAttribute('data-state','running',{timeout:60000});await expect.poll(async()=>(await evidence(page)).active).toBe(false);await page.locator('#system-menu').click();await expect(page.locator('#debug-flight-toggle')).toHaveAttribute('aria-pressed','false');expect(errors).toEqual([]);
});
