import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import type {Snapshot} from '../../src/dungeon/types';
const read=(page:Page)=>page.evaluate(()=>window.__dungeonProbe?.()??null) as Promise<Snapshot|null>;
const own=(s:Snapshot)=>s.actors.find(a=>a.id===s.you)!;
async function tap(page:Page,selector:string,mobile:boolean){const target=page.locator(selector);if(mobile)await target.tap();else await target.click();}
async function walk(page:Page,mobile:boolean,x:number,z:number){const session=mobile?await page.context().newCDPSession(page):null;try{for(let step=0;step<45;step++){const s=await read(page);if(!s)throw new Error('No authoritative snapshot');const a=own(s);expect(a.status).toBe('alive');const dx=x-a.position.x,dz=z-a.position.z;if(Math.hypot(dx,dz)<.35)return;const horizontal=Math.abs(dx)>Math.abs(dz),positive=horizontal?dx>0:dz<0,ms=Math.max(70,Math.min(250,(horizontal?Math.abs(dx):Math.abs(dz))/3*850));if(session){const bounds=await page.locator('[data-dungeon-pad=move]').boundingBox();if(!bounds)throw new Error('Move pad missing');const cx=bounds.x+bounds.width/2,cy=bounds.y+bounds.height/2;await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:cx,y:cy,radiusX:4,radiusY:4,force:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:cx+(horizontal?(positive?42:-42):0),y:cy+(!horizontal?(positive?-42:42):0),radiusX:4,radiusY:4,force:1}]});await page.waitForTimeout(ms);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{const key=horizontal?(positive?'KeyD':'KeyA'):(positive?'KeyW':'KeyS');await page.keyboard.down(key);await page.waitForTimeout(ms);await page.keyboard.up(key);}await page.waitForTimeout(130);}throw new Error('Ordinary input did not reach the requested point');}finally{await session?.detach();}}

test('dungeon legacy launch and save isolation smoke',async({page,isMobile})=>{test.setTimeout(180000);await page.goto('/?trial=1&test=1');await expect(page.locator('#game')).toHaveAttribute('data-ready','true',{timeout:90000});await page.evaluate(()=>localStorage.setItem('ash-campaign-v1','preserved-campaign-sentinel'));await page.goto('/?mode=dungeon&test=1');await expect(page.getByTestId('dungeon-create')).toBeVisible();await expect(page.locator('.dungeon-canvas')).toHaveAttribute('data-ready','true');expect(await page.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe('preserved-campaign-sentinel');await page.screenshot({path:test.info().outputPath('dungeon-lobby.png')});});

test('dungeon two-client server movement loot extraction and persistent reconnect',async({page,browser,isMobile},testInfo)=>{test.skip(process.env.E2E_DUNGEON!=='1','Requires the deployed same-origin dungeon server');test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',error=>errors.push(String(error)));let rivalContext:BrowserContext|undefined;
 try{const deployment=await (await page.request.get('/deployment.json')).json();expect(deployment.commit).toBe(process.env.EXPECTED_COMMIT);const health=await (await page.request.get('/dungeon-room/health')).json();expect(health).toMatchObject({enabled:true,authority:'server',protocol:1,stashScope:'room-player'});await page.goto('/?mode=dungeon&test=1');await page.evaluate(()=>localStorage.setItem('ash-campaign-v1','untouched-legacy'));await page.getByTestId('dungeon-name').fill('探索A');await tap(page,'[data-testid=dungeon-create]',isMobile);await expect.poll(async()=>(await read(page))?.actors.length).toBe(1);const invite=await page.getByTestId('dungeon-invite').inputValue();expect(invite).not.toContain('identity');rivalContext=await browser.newContext({viewport:{width:960,height:540}});const rival=await rivalContext.newPage();rival.on('pageerror',error=>errors.push(String(error)));const url=new URL(invite);url.searchParams.set('test','1');await rival.goto(url.href);expect(await read(rival)).toBeNull();await rival.getByTestId('dungeon-name').fill('探索B');await rival.getByTestId('dungeon-join').click();await expect.poll(async()=>(await read(page))?.actors.length).toBe(2);await tap(page,'[data-testid=dungeon-ready]',isMobile);await rival.getByTestId('dungeon-ready').click();await tap(page,'[data-testid=dungeon-start]',isMobile);await expect.poll(async()=>(await read(page))?.phase).toBe('raid');await expect(page.locator('.dungeon-canvas')).toHaveAttribute('data-ready','true');const me=own((await read(page))!).id;
 await walk(page,isMobile,-11,8.6);await expect.poll(async()=>(await read(rival))?.actors.find(a=>a.id===me)?.position.z).toBeLessThan(9.2);await tap(page,'[data-target=chest0]',isMobile);await expect.poll(async()=>(await read(page))?.containers.find(c=>c.id==='chest0')?.opened).toBe(true);await tap(page,'[data-target=chest0]',isMobile);const loot=page.locator('[data-loot-target=chest0]').first();await expect(loot).toBeVisible();const item=await loot.getAttribute('data-loot-item');if(isMobile)await loot.tap();else await loot.click();await expect.poll(async()=>own((await read(page))!).bag.some(i=>i.id===item)).toBe(true);if(isMobile)await page.getByRole('button',{name:'閉じる · I / Esc',exact:true}).tap();else await page.getByRole('button',{name:'閉じる · I / Esc',exact:true}).click();await walk(page,isMobile,-12,11.8);await expect.poll(async()=>(await read(page))?.elapsed,{timeout:60000}).toBeGreaterThan(45);await tap(page,'[data-target=exit-west]',isMobile);await expect.poll(async()=>own((await read(page))!).status,{timeout:15000}).toBe('extracted');expect((await read(page))!.stash.filter(i=>i.id===item)).toHaveLength(1);await page.screenshot({path:testInfo.outputPath('extracted-stash.png')});const before=(await read(page))!.stash.map(i=>i.id);await page.reload();await tap(page,'[data-testid=dungeon-join]',isMobile);await expect.poll(async()=>(await read(page))?.stash.map(i=>i.id)).toEqual(before);expect(own((await read(page))!).id).toBe(me);expect(await page.evaluate(()=>localStorage.getItem('ash-campaign-v1'))).toBe('untouched-legacy');expect(errors).toEqual([]);
 }finally{await rivalContext?.close();}
});
