import { GameSimulation } from '../../src/simulation/game-simulation';
import { test,expect,type Page } from '@playwright/test';
test.use({deviceScaleFactor:.5});
async function ready(page:Page){await page.goto('/');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await expect(page.locator('#error')).toBeHidden();}
async function ticks(page:Page,n=10){const tick=Number(await page.locator('#app').getAttribute('data-tick'));await expect.poll(async()=>Number(await page.locator('#app').getAttribute('data-tick'))).toBeGreaterThan(tick+n);}
async function fixture(page:Page,sim:GameSimulation){await page.locator('#import-file').setInputFiles({name:'core-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(sim.save()))});await expect(page.locator('#app')).toHaveAttribute('data-state','running');await ticks(page,4);}
function sparse(){const sim=new GameSimulation();sim.adventure.state.resources=[];sim.adventure.state.enemies=[];sim.adventure.state.buildings=[];sim.fluid.cells.clear();return sim;}

test('core landscape starts, moves with keyboard, keeps the landscape canvas across rotation',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('#adventure-hud')).toContainText('HP');await expect(page.locator('#hotbar button')).toHaveCount(8);
 const v=page.viewportSize()!;expect(await page.locator('canvas').evaluate(c=>c.clientWidth)).toBe(Math.max(v.width,v.height));
 const x=Number(await page.locator('#position').getAttribute('data-x'));await page.keyboard.down('KeyD');await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(x+.4);await page.keyboard.up('KeyD');await page.keyboard.press('Space');await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/ジャンプ ([\d.]+)m/)?.[1]??0)).toBeGreaterThan(.4);
 await page.setViewportSize({width:844,height:390});await expect(page.locator('canvas')).toHaveJSProperty('clientWidth',844);await expect(page.locator('#app')).toHaveAttribute('data-rotated','false');await page.screenshot({scale:'css',path:info.outputPath('core-landscape.png')});await page.setViewportSize({width:390,height:844});await expect(page.locator('canvas')).toHaveJSProperty('clientWidth',844);await expect(page.locator('#app')).toHaveAttribute('data-rotated','true');expect(errors).toEqual([]);
});
test('two fingers move and jump together on a rotated phone, and water is always available',async({page},info)=>{
 test.skip(info.project.name==='desktop-chromium','Phone touch coordinates');await ready(page);const sim=sparse();await fixture(page,sim);await expect(page.locator('#position')).toHaveAttribute('data-grounded','true');const stick=await page.locator('#stick').boundingBox(),jump=await page.locator('#jump').boundingBox();if(!stick||!jump)throw Error('Touch controls missing');const session=await page.context().newCDPSession(page),left={x:stick.x+stick.width/2,y:stick.y+stick.height*.8,id:1},right={x:jump.x+jump.width/2,y:jump.y+jump.height/2,id:2};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[left]});await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(.2);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[left,right]});await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/ジャンプ ([\d.]+)m/)?.[1]??0)).toBeGreaterThan(.4);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#water-cast').click();await expect(page.locator('#notice')).toContainText('水を流しました');await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/水 (\d+)セル/)?.[1]??0)).toBeGreaterThan(8);await page.keyboard.press('KeyF');await expect(page.locator('#error')).toBeHidden();
});
test('survival adventure uses aim interaction, inventory slots, quick equipment and saved ground drops',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);const sim=sparse(),p=sim.player;sim.adventure.state.inventory={ragTunic:1,club:1,wood:3};sim.adventure.state.resources=[{id:900,kind:'branch',x:p.x,y:sim.groundAt(p.x,p.z-1.8),z:p.z-1.8,amount:2,ready:0},{id:901,kind:'stone',x:p.x+1.5,y:p.y,z:p.z-1,amount:1,ready:0}];await fixture(page,sim);await expect(page.locator('#app')).toHaveAttribute('data-interaction','r:900');await page.keyboard.press('KeyE');await expect(page.locator('#notice')).toContainText('木材');await page.keyboard.press('Tab');await expect(page.locator('.slot-grid button')).toHaveCount(32);await page.locator('[data-slot="2"]').click();await expect(page.locator('#adventure-content')).toContainText('木材 ×5');await page.locator('[data-quantity-action="drop"]').click();await expect(page.locator('#notice')).toContainText('地面に置きました');await page.locator('#adventure-close').click();await page.keyboard.press('Digit2');await expect(page.locator('#adventure-hud')).toContainText('棍棒');await page.keyboard.press('Tab');await page.locator('[data-tab="craft"]').click();await expect(page.locator('#adventure-content')).toContainText('粗末な弓');await page.screenshot({scale:'css',path:info.outputPath('inventory-crafting.png')});await page.locator('#adventure-close').click();await page.locator('#system-menu').click();await page.locator('#save').click();await page.locator('#system-close').click();await page.reload();await expect(page.locator('#app')).toHaveAttribute('data-state','running');await expect(page.locator('#adventure-hud')).toContainText('棍棒');expect(errors).toEqual([]);
});
test('survival adventure previews, rotates and places the matching voxel building',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);const sim=sparse();sim.adventure.state.inventory={wood:40,stone:40,hammer:1};sim.adventure.state.equipment='hammer';await fixture(page,sim);await page.keyboard.press('KeyB');await page.locator('[data-game-action="place"][data-id="bench"]').click();await expect(page.locator('#build-controls')).toBeVisible();await page.locator('#build-rotate').click();await expect(page.locator('#use-tool')).toBeEnabled();await page.screenshot({scale:'css',path:info.outputPath('voxel-building-preview.png')});await page.locator('#use-tool').click();await expect(page.locator('#notice')).toContainText('作業台を設置');await page.locator('#build-cancel').click();await expect(page.locator('#build-controls')).toBeHidden();expect(errors).toEqual([]);
});
test('desktop mouse locks the camera, rotates freely, attacks and holds guard',async({page},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Desktop mouse controls');await ready(page);const sim=sparse();sim.adventure.state.inventory={club:1,shield:1};sim.adventure.state.equipment='club';sim.adventure.state.meadows!.gear.offhand='shield';await fixture(page,sim);await page.mouse.click(550,300);await expect.poll(()=>page.evaluate(()=>document.pointerLockElement?.id)).toBe('game');const before=Number(await page.locator('#app').getAttribute('data-camera-yaw'));await page.mouse.move(620,320);await expect.poll(async()=>Number(await page.locator('#app').getAttribute('data-camera-yaw'))).not.toBe(before);await page.mouse.down({button:'right'});await expect(page.locator('#adventure-hud')).toContainText('ガード');await page.mouse.up({button:'right'});await expect(page.locator('#guard')).toHaveAttribute('aria-pressed','false');await page.mouse.click(620,320);await expect(page.locator('#notice')).toContainText('攻撃');await page.keyboard.press('Tab');await expect(page.locator('#adventure-panel')).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.pointerLockElement?.id??'')).toBe('');
});
test('renders equipped voxel characters and physical HDR graphics without shader errors',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader/i.test(m.text()))errors.push(m.text());});await page.goto('/?graphicsProbe=1');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await ticks(page,10);const graphics=async()=>JSON.parse((await page.locator('#app').getAttribute('data-graphics'))!);await expect.poll(async()=>(await graphics()).samples).toBeGreaterThan(0);const g=await graphics();expect(g.invalidPixels).toBe(0);expect(g.beautyEnergy).toBeGreaterThan(0);expect(g.features).toEqual(['pbr','physical-sky','ibl','sh','volumetric','exposure','bloom','shadow','ssr']);await page.setViewportSize({width:844,height:390});await page.screenshot({scale:'css',path:info.outputPath('voxel-hdr.png')});expect(errors).toEqual([]);
});
test('shows WebGL context loss clearly and rejects corrupt saves',async({page})=>{await ready(page);await page.locator('#import-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await expect(page.locator('#notice')).toContainText('対応しないセーブ');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await page.locator('canvas').dispatchEvent('webglcontextlost');await expect(page.locator('#error')).toContainText('WebGL');});
