import { GameSimulation } from '../../src/simulation/game-simulation';
import { test,expect,type Page } from '@playwright/test';
test.use({deviceScaleFactor:.5});
async function streamReport(page:Page){console.log('STREAMING',await page.locator('#app').getAttribute('data-streaming'));}
async function ready(page:Page){await page.goto('/');try{await expect(page.locator('#app')).toHaveAttribute('data-state','running');await expect(page.locator('#error')).toBeHidden();}finally{await streamReport(page);}}
async function ticks(page:Page,n=10){const tick=Number(await page.locator('#app').getAttribute('data-tick'));await expect.poll(async()=>Number(await page.locator('#app').getAttribute('data-tick'))).toBeGreaterThan(tick+n);}
async function fixture(page:Page,sim:GameSimulation){const epoch=await page.locator('#app').getAttribute('data-world-epoch');await page.locator('#import-file').setInputFiles({name:'core-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(sim.save()))});await expect.poll(()=>page.locator('#app').getAttribute('data-world-epoch')).not.toBe(epoch);try{await expect(page.locator('#app')).toHaveAttribute('data-state','running');await ticks(page,4);}finally{await streamReport(page);}}
function sparse(){const sim=new GameSimulation();sim.adventure.state.resources=[];sim.adventure.state.enemies=[];sim.adventure.state.buildings=[];sim.fluid.cells.clear();return sim;}

test('core landscape starts, moves with keyboard, keeps the landscape canvas across rotation',async({page},info)=>{
 // Software WebGL on CI can spend over 60 seconds booting and resizing this fine-voxel world.
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('#adventure-hud')).toContainText('HP');await expect(page.locator('#hotbar button')).toHaveCount(8);
 const v=page.viewportSize()!;expect(await page.locator('canvas').evaluate(c=>c.clientWidth)).toBe(Math.max(v.width,v.height));
 const x=Number(await page.locator('#position').getAttribute('data-x'));await page.keyboard.down('KeyD');await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(x+.4);await page.keyboard.up('KeyD');await page.keyboard.press('Space');await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/ジャンプ ([\d.]+)m/)?.[1]??0)).toBeGreaterThan(.4);
 await page.setViewportSize({width:844,height:390});await expect(page.locator('canvas')).toHaveJSProperty('clientWidth',844);await expect(page.locator('#app')).toHaveAttribute('data-rotated','false');await page.screenshot({scale:'css',path:info.outputPath('core-landscape.png')});await page.setViewportSize({width:390,height:844});await expect(page.locator('canvas')).toHaveJSProperty('clientWidth',844);await expect(page.locator('#app')).toHaveAttribute('data-rotated','true');expect(errors).toEqual([]);
});
test('two fingers move, sprint, crouch and jump together on a rotated phone, and water is always available',async({page},info)=>{
 test.skip(info.project.name==='desktop-chromium','Phone touch coordinates');await ready(page);const sim=sparse();await fixture(page,sim);await expect(page.locator('#position')).toHaveAttribute('data-grounded','true');
 const stick=await page.locator('#stick').boundingBox();if(!stick)throw Error('Touch controls missing');const session=await page.context().newCDPSession(page),left={x:stick.x+stick.width/2,y:stick.y+stick.height*.8,id:1};
 const second=async(id:string)=>{const box=await page.locator('#'+id).boundingBox();if(!box)throw Error(id+' missing');await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[left,{x:box.x+box.width/2,y:box.y+box.height/2,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[left]});};
 await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[left]});await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(.2);
 await second('sprint');await expect(page.locator('#sprint')).toHaveAttribute('aria-pressed','true');await second('sneak');await expect(page.locator('#sneak')).toHaveAttribute('aria-pressed','true');const before=Number(await page.locator('#position').getAttribute('data-x'));await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(before+.2);await second('sneak');
 await second('jump');await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/ジャンプ ([\d.]+)m/)?.[1]??0)).toBeGreaterThan(.4);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.locator('#water-cast').tap();await expect(page.locator('#notice')).toContainText('水を流しました');await expect.poll(async()=>Number((await page.locator('#metrics').textContent())?.match(/水 (\d+)セル/)?.[1]??0)).toBeGreaterThan(8);await page.screenshot({path:info.outputPath('right-movement-controls.png'),scale:'css'});await expect(page.locator('#error')).toBeHidden();
});
test('survival adventure uses aim interaction, inventory slots, quick equipment and saved ground drops',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);const sim=sparse(),p=sim.player;sim.adventure.state.inventory={ragTunic:1,club:1,wood:3};sim.adventure.state.resources=[{id:900,kind:'branch',x:p.x,y:sim.groundAt(p.x,p.z-3.2),z:p.z-3.2,amount:2,ready:0},{id:901,kind:'stone',x:p.x+1.5,y:p.y,z:p.z-1,amount:1,ready:0}];await fixture(page,sim);await expect(page.locator('#app')).toHaveAttribute('data-interaction','r:900');await page.keyboard.press('KeyE');await expect(page.locator('#notice')).toContainText('木材');await page.keyboard.press('Tab');await expect(page.locator('.slot-grid button')).toHaveCount(32);await page.locator('[data-slot="2"]').click();await expect(page.locator('#adventure-content')).toContainText('木材 ×5');await page.locator('[data-quantity-action="drop"]').click();await expect(page.locator('#notice')).toContainText('地面に置きました');await page.locator('#adventure-close').click();await page.keyboard.press('Digit2');await expect(page.locator('#adventure-hud')).toContainText('棍棒');await page.keyboard.press('Tab');await page.locator('[data-tab="craft"]').click();await expect(page.locator('#adventure-content')).toContainText('粗末な弓');await page.screenshot({scale:'css',path:info.outputPath('inventory-crafting.png')});await page.locator('#adventure-close').click();await page.locator('#system-menu').click();await page.locator('#save').click();await page.locator('#system-close').click();await page.reload();await expect(page.locator('#app')).toHaveAttribute('data-state','running');await expect(page.locator('#adventure-hud')).toContainText('棍棒');expect(errors).toEqual([]);
});
test('survival adventure previews, rotates and places the matching voxel building',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);const sim=sparse();sim.adventure.state.inventory={wood:40,stone:40,hammer:1};sim.adventure.state.equipment='hammer';await fixture(page,sim);await page.keyboard.press('KeyB');await page.locator('[data-game-action="place"][data-id="bench"]').click();await expect(page.locator('#build-controls')).toBeVisible();await page.locator('#build-rotate').click();await expect(page.locator('#use-tool')).toBeEnabled();await page.screenshot({scale:'css',path:info.outputPath('voxel-building-preview.png')});await page.locator('#use-tool').click();await expect(page.locator('#notice')).toContainText('作業台を設置');await page.locator('#build-cancel').click();await expect(page.locator('#build-controls')).toBeHidden();expect(errors).toEqual([]);
});
test('desktop mouse locks the camera, rotates freely, attacks and holds guard',async({page},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Desktop mouse controls');await ready(page);const sim=sparse();sim.adventure.state.inventory={club:1,shield:1};sim.adventure.state.equipment='club';sim.adventure.state.meadows!.gear.offhand='shield';await fixture(page,sim);await page.mouse.click(550,300);await expect.poll(()=>page.evaluate(()=>document.pointerLockElement?.id)).toBe('game');const before=Number(await page.locator('#app').getAttribute('data-camera-yaw'));await page.mouse.move(620,320);await expect.poll(async()=>Number(await page.locator('#app').getAttribute('data-camera-yaw'))).not.toBe(before);await page.mouse.down({button:'right'});await expect(page.locator('#adventure-hud')).toContainText('ガード');await page.mouse.up({button:'right'});await expect(page.locator('#guard')).toHaveAttribute('aria-pressed','false');await page.mouse.click(620,320);await expect(page.locator('#notice')).toContainText('攻撃');await page.keyboard.press('Tab');await expect(page.locator('#adventure-panel')).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.pointerLockElement?.id??'')).toBe('');
});
test('renders equipped voxel characters and physical HDR graphics without shader errors',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader/i.test(m.text()))errors.push(m.text());});await page.goto('/?terrain=mesh&graphicsProbe=1');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await ticks(page,10);const graphics=async()=>JSON.parse((await page.locator('#app').getAttribute('data-graphics'))!);await expect.poll(async()=>(await graphics()).stageSamples).toBeGreaterThan(0);const g=await graphics();expect(g.invalidPixels).toBe(0);expect(g.beautyEnergy).toBeGreaterThan(0);expect(g.features).toEqual(['pbr','physical-sky','ibl','sh','volumetric','exposure','bloom','shadow','ssr']);await page.setViewportSize({width:844,height:390});await page.screenshot({scale:'css',path:info.outputPath('voxel-hdr.png')});expect(errors).toEqual([]);
});
test('shows WebGL context loss clearly and rejects corrupt saves',async({page})=>{await ready(page);await page.locator('#import-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await expect(page.locator('#notice')).toContainText('対応しないセーブ');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await page.locator('canvas').dispatchEvent('webglcontextlost');await expect(page.locator('#error')).toContainText('WebGL');});

test('desktop mouse releases held combat and movement across menus and landscape changes',async({page},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Desktop interruption regression');
 await ready(page);const sim=sparse();sim.adventure.state.inventory={shield:1};sim.adventure.state.meadows!.gear.offhand='shield';await fixture(page,sim);
 await page.mouse.click(550,300);await page.mouse.down({button:'right'});await expect(page.locator('#guard')).toHaveAttribute('aria-pressed','true');
 await page.keyboard.press('Tab');await expect(page.locator('#adventure-panel')).toBeVisible();await expect(page.locator('#guard')).toHaveAttribute('aria-pressed','false');await page.mouse.up({button:'right'});await page.keyboard.press('Tab');
 await page.keyboard.down('KeyW');await ticks(page,3);await page.setViewportSize({width:900,height:500});await ticks(page,3);const before=Number(await page.locator('#position').getAttribute('data-z'));await ticks(page,5);const after=Number(await page.locator('#position').getAttribute('data-z'));await page.keyboard.up('KeyW');expect(Math.abs(after-before)).toBeLessThan(.08);await expect(page.locator('#error')).toBeHidden();
});

test('desktop mouse keeps movement responsive across a terrain boundary',async({page},info)=>{
 test.skip(info.project.name!=='desktop-chromium','Movement streaming regression');
 await ready(page);const sim=sparse();sim.bodies.length=0;Object.assign(sim.player,{x:15.5,z:8,y:sim.groundAt(15.5,8),vy:0,grounded:true});await fixture(page,sim);
 const frameRun=page.evaluate(()=>new Promise<{samples:number;maxGap:number;p95Gap:number}>(resolve=>{const gaps:number[]=[];let last=performance.now();const start=last;const step=(now:number)=>{gaps.push(now-last);last=now;if(now-start<4000)requestAnimationFrame(step);else{gaps.sort((a,b)=>a-b);resolve({samples:gaps.length,maxGap:gaps.at(-1)??0,p95Gap:gaps[Math.floor((gaps.length-1)*.95)]??0});}};requestAnimationFrame(step);}));
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(18);}finally{await page.keyboard.up('KeyD');}
 const frames=await frameRun,phases=JSON.parse((await page.locator('#app').getAttribute('data-performance'))??'{}');await info.attach('movement-profile.json',{body:JSON.stringify({frames,phases,note:'CI software GPU; seconds-long-stall regression, not phone FPS'},null,2),contentType:'application/json'});
 console.log('MOVEMENT_PROFILE',JSON.stringify({frames,phases}));expect(frames.samples).toBeGreaterThan(5);expect(frames.maxGap,'No multi-second main-frame freeze while crossing x=16').toBeLessThan(2000);await expect(page.locator('#error')).toBeHidden();
});

test('direct field terrain renders, moves, mines and preserves saves with comparable frame samples',async({page},info)=>{
 test.setTimeout(150000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const profiles:Record<string,unknown>={};
 const sim=sparse();sim.bodies.length=0;for(let x=14;x<18;x+=.5)for(let z=6;z<10;z+=.5)sim.fluid.add({x,y:sim.groundAt(x,z)+.5,z},.1);sim.adventure.state.inventory={antlerPickaxe:1,wood:37};sim.adventure.state.equipment='antlerPickaxe';Object.assign(sim.player,{x:15.5,z:8,y:sim.groundAt(15.5,8),vy:0,grounded:true});
 for(const mode of ['mesh','direct']){
  await page.goto(mode==='direct'?'/?terrain=direct&waterProbe=1':'/?terrain=mesh');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await fixture(page,sim);if(mode==='direct')await expect.poll(()=>page.locator('#app').getAttribute('data-water-probe')).toBeTruthy();
  await expect(page.locator('#app')).toHaveAttribute('data-terrain-mode',mode==='direct'?'direct-field':'surface-mesh');
  const frames=page.evaluate(()=>new Promise(resolve=>{const gaps:number[]=[];let previous=performance.now();const start=previous;const step=(now:number)=>{gaps.push(now-previous);previous=now;if(now-start<4000)requestAnimationFrame(step);else{gaps.sort((a,b)=>a-b);resolve({samples:gaps.length,maxGap:gaps.at(-1),p95Gap:gaps[Math.floor((gaps.length-1)*.95)]});}};requestAnimationFrame(step);}));
  await page.keyboard.down('KeyD');try{await expect.poll(async()=>Number(await page.locator('#position').getAttribute('data-x'))).toBeGreaterThan(18);}finally{await page.keyboard.up('KeyD');}
  profiles[mode]={frames:await frames,diagnostics:JSON.parse((await page.locator('#app').getAttribute('data-diagnostics'))??'{}')};console.log('DIRECT_FIELD_SAMPLE',mode,JSON.stringify(profiles[mode]));
  if(mode==='direct'){
   await expect.poll(()=>page.locator('#app').getAttribute('data-water-probe')).toBeTruthy();const water=JSON.parse((await page.locator('#app').getAttribute('data-water-probe'))!);console.log('DIRECT_WATER_LIGHTING',JSON.stringify(water));expect(water.error).toBeUndefined();expect(water.waterPixels).toBeGreaterThan(0);expect(water.invalidPixels).toBe(0);expect(water.litEnergy).toBeGreaterThan(.01);expect(water.environmentGain).toBeGreaterThan(0);
   if(info.project.name==='android-chromium'){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:210,y:420,id:3}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:70,y:420,id:3}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.mouse.move(500,150);await page.mouse.down({button:'middle'});await page.mouse.move(500,290);await page.mouse.up({button:'middle'});}
   await expect.poll(async()=>Number(await page.locator('#app').getAttribute('data-camera-pitch'))).toBeGreaterThan(.9);await expect.poll(async()=>{const a=JSON.parse((await page.locator('#app').getAttribute('data-aim'))??'{}');return a.target?Math.hypot(a.target.x-a.player.x,a.target.y-a.player.y-.85,a.target.z-a.player.z):99;}).toBeLessThan(2.2);
   const before=Number(await page.locator('#edit-count').getAttribute('data-count'));if(info.project.name==='desktop-chromium'){await page.mouse.click(550,300);await page.mouse.click(550,300);}else await page.locator('#attack').click();await expect.poll(async()=>Number(await page.locator('#edit-count').getAttribute('data-count'))).toBeGreaterThan(before);
   await page.screenshot({path:info.outputPath('direct-field-mining.png'),scale:'css'});await page.locator('#system-menu').click();await page.locator('#save').click();await expect.poll(async()=>Number(await page.locator('#save-status').getAttribute('data-edits'))).toBeGreaterThan(before);await page.locator('#system-close').click();await page.goto('/?terrain=mesh');await expect(page.locator('#app')).toHaveAttribute('data-state','running');await expect.poll(async()=>Number(await page.locator('#edit-count').getAttribute('data-count'))).toBeGreaterThan(before);
  }
  await expect(page.locator('#error')).toBeHidden();
 }
 console.log('DIRECT_FIELD_COMPARISON',JSON.stringify(profiles));await info.attach('direct-field-comparison.json',{body:JSON.stringify(profiles,null,2),contentType:'application/json'});expect(errors).toEqual([]);
});

test.describe('third-person combat capture',()=>{
 test.use({video:{mode:'on',size:{width:844,height:390}}});
 test('survival adventure shoulder aim, weapon contact and right-side combat controls',async({page},info)=>{
  test.skip(info.project.name!=='android-chromium','Phone combat acceptance');test.setTimeout(90000);await page.setViewportSize({width:844,height:390});await ready(page);await expect(page.locator('#app')).toHaveAttribute('data-terrain-mode','direct-field');
  const sim=sparse(),p=sim.player;sim.bodies.length=0;sim.adventure.state.inventory={club:1,shield:1};sim.adventure.state.equipment='club';sim.adventure.state.meadows!.gear.offhand='shield';
  sim.adventure.state.enemies=[{id:901,definition:'boar',tier:1,x:p.x+.6,y:sim.groundAt(p.x+.6,p.z-1.8),z:p.z-1.8,homeX:p.x+.6,homeZ:p.z-1.8,health:200,cooldown:60,windup:0,slow:0,boss:false,stagger:30}];await fixture(page,sim);
  const touch=await page.context().newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:430,y:150,id:3}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:430,y:187,id:3}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await expect.poll(async()=>JSON.parse((await page.locator('#app').getAttribute('data-camera-probe'))??'{}').head?.x??1).toBeLessThan(-.05);await expect(page.locator('.reticle')).toBeVisible();
  const hp=async()=>Number((await page.locator('#enemy-focus').textContent())?.match(/([\d.]+) HP/)?.[1]??0),before=await hp();expect(before).toBeGreaterThan(0);await page.locator('#attack').tap();await expect.poll(hp).toBeLessThan(before);await page.screenshot({path:info.outputPath('shoulder-melee-contact.png'),scale:'css'});
  await expect.poll(async()=>JSON.parse((await page.locator('#app').getAttribute('data-combat'))??'{}').attackMotion??null).toBeNull();const guard=await page.locator('#guard').boundingBox();if(!guard)throw Error('Guard missing');await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:guard.x+guard.width/2,y:guard.y+guard.height/2,id:4}]});await expect(page.locator('#guard')).toHaveAttribute('aria-pressed','true');await page.screenshot({path:info.outputPath('shoulder-guard.png'),scale:'css'});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#dodge').tap();await expect(page.locator('#notice')).toContainText('回避');
  const probe=await page.locator('#app').getAttribute('data-camera-probe');console.log('SHOULDER_COMBAT_PROBE',probe);await info.attach('shoulder-combat-probe.json',{body:probe??'{}',contentType:'application/json'});await expect(page.locator('#error')).toBeHidden();
 });
});
