import * as THREE from 'three';
import {pbrMaterial} from '../materials/pbr';
import type {Snapshot} from '../../simulation/protocol';
/** Original six-legged lantern-backed animal. Five instanced draws cover all eight animals. */
export function createCompanions(scene:THREE.Scene){
 const box=new THREE.BoxGeometry(1,1,1),materials=[pbrMaterial('#789da4','cloth'),pbrMaterial('#354d58','leather'),pbrMaterial('#bc9660','leather'),new THREE.MeshStandardMaterial({color:'#d7ecc0',emissive:'#a5d5ac',emissiveIntensity:.5,roughness:.65}),new THREE.MeshBasicMaterial({color:'#18272c'})],ropeMaterial=new THREE.LineBasicMaterial({color:'#d7bd7f'});
 const meshes=materials.map((material,i)=>{const mesh=new THREE.InstancedMesh(box,material,i===1?64:32);mesh.count=0;mesh.frustumCulled=false;mesh.castShadow=true;scene.add(mesh);return mesh;});
 const views=new Map<number,{position:THREE.Vector3;target:THREE.Vector3;heading:number;yaw:number;rope:THREE.Line;moving:number}>();let time=0;
 const root=new THREE.Matrix4(),local=new THREE.Matrix4(),world=new THREE.Matrix4(),position=new THREE.Vector3(),scale=new THREE.Vector3(),quaternion=new THREE.Quaternion(),up=new THREE.Vector3(0,1,0),xAxis=new THREE.Vector3(1,0,0),offset=new THREE.Vector3();
 const add=(index:number,x:number,y:number,z:number,sx:number,sy:number,sz:number,angle=0)=>{quaternion.setFromAxisAngle(xAxis,angle);local.compose(position.set(x,y,z),quaternion,scale.set(sx,sy,sz));world.multiplyMatrices(root,local);const mesh=meshes[index];mesh.setMatrixAt(mesh.count++,world);};
 return {update(state:Snapshot){time=state.adventure.seconds;const seen=new Set<number>();for(const c of state.adventure.companions?.creatures??[]){seen.add(c.id);let view=views.get(c.id);if(!view){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3));const rope=new THREE.Line(geometry,ropeMaterial);rope.frustumCulled=false;scene.add(rope);view={position:new THREE.Vector3(c.position.x,c.position.y,c.position.z),target:new THREE.Vector3(),heading:c.heading,yaw:c.heading,rope,moving:0};views.set(c.id,view);}view.target.set(c.position.x,c.position.y,c.position.z);view.moving=Math.min(1,view.position.distanceTo(view.target)*3);if(view.position.distanceTo(view.target)>8)view.position.copy(view.target);view.heading=c.heading;const target=state.adventure.skybound?.parts.find(p=>p.id===c.tetherPart);view.rope.visible=!!target;if(target){const positions=view.rope.geometry.getAttribute('position');positions.setXYZ(0,c.position.x,c.position.y+.65,c.position.z);positions.setXYZ(1,target.position.x,target.position.y,target.position.z);positions.needsUpdate=true;}}
  for(const[id,v]of views)if(!seen.has(id)){scene.remove(v.rope);v.rope.geometry.dispose();views.delete(id);}},animate(dt:number){for(const mesh of meshes)mesh.count=0;for(const v of views.values()){v.position.lerp(v.target,1-Math.exp(-15*dt));v.yaw+=Math.atan2(Math.sin(v.heading-v.yaw),Math.cos(v.heading-v.yaw))*(1-Math.exp(-15*dt));root.compose(v.position,quaternion.setFromAxisAngle(up,v.yaw),scale.set(1,1,1));add(0,0,.73,0,1,.6,1.2);add(0,0,1,.66,.52,.46,.55);add(1,0,.96,.98,.36,.16,.13);add(2,0,1.025,-.08,.52,.07,.58);let leg=0;for(const side of[-1,1]){add(4,side*.17,1.09,.946,.07,.06,.03);add(3,side*.36,1,.15,.2,.22,.32);for(const z of[-.4,0,.4]){const angle=Math.sin(time*7+leg++*Math.PI)*.38*v.moving;offset.set(0,-.24,0).applyAxisAngle(xAxis,angle);add(1,side*.37,.55+offset.y,z+offset.z,.17,.48,.19,angle);}}}for(const mesh of meshes)mesh.instanceMatrix.needsUpdate=true;},dispose(){for(const v of views.values()){scene.remove(v.rope);v.rope.geometry.dispose();}views.clear();for(const mesh of meshes){scene.remove(mesh);mesh.dispose();}box.dispose();for(const m of[...materials,ropeMaterial])m.dispose();}};
}
