import * as THREE from 'three';
import {pbrMaterial} from '../materials/pbr';
import type {Snapshot} from '../../simulation/protocol';
/** Small original guide lanterns and a distinct blue-clothed evacuee. */
export function createExpeditions(scene:THREE.Scene){
 const box=new THREE.BoxGeometry(1,1,1),cloth=pbrMaterial('#719dad','cloth'),skin=pbrMaterial('#dab986','skin'),boots=pbrMaterial('#3b4c53','leather'),glow=pbrMaterial('#bfdaa0','crystal'),dim=pbrMaterial('#688c92','stone'),rescue=new THREE.Group();scene.add(rescue);const markers=new Map<number,THREE.Mesh>();
 const part=(mat:THREE.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number)=>{const m=new THREE.Mesh(box,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);rescue.add(m);return m;};part(cloth,0,.8,0,.43,.58,.28);part(skin,0,1.26,0,.32,.35,.3);const legs=[part(boots,-.12,.26,0,.16,.52,.19),part(boots,.12,.26,0,.16,.52,.19)];part(cloth,-.3,.83,0,.14,.53,.17);part(cloth,.3,.83,0,.14,.53,.17);const target=new THREE.Vector3();let moving=false,time=0,initialized=false;
 return{update(state:Snapshot){time=state.adventure.seconds;const sites=state.adventure.expeditions?.sites??[],seen=new Set<number>();for(const site of sites){seen.add(site.id);let m=markers.get(site.id);if(!m){m=new THREE.Mesh(box,dim);m.scale.set(.35,.55,.35);scene.add(m);markers.set(site.id,m);}m.position.set(site.x,site.y+2.6,site.z+5.5);m.rotation.y=time*.4;m.material=site.completed?glow:dim;}for(const[id,m]of markers)if(!seen.has(id)){scene.remove(m);markers.delete(id);}const npc=state.adventure.expeditions?.rescue;rescue.visible=!!npc;if(npc){target.set(npc.position.x,npc.position.y,npc.position.z);if(!initialized||rescue.position.distanceTo(target)>10){rescue.position.copy(target);initialized=true;}moving=rescue.position.distanceTo(target)>.03;const delta=target.clone().sub(rescue.position);if(delta.lengthSq()>.001)rescue.rotation.y=Math.atan2(delta.x,delta.z);}},animate(dt:number){if(rescue.visible){rescue.position.lerp(target,1-Math.exp(-15*dt));legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(time*7+i*Math.PI)*.25:0);}},dispose(){scene.remove(rescue);for(const m of markers.values())scene.remove(m);box.dispose();for(const m of[cloth,skin,boots,glow,dim])m.dispose();}};
}
