import type {ResolutionMode} from '../rendering/resolution';
import type { CameraView } from '../input/touch/look';
export const BINDING_LABELS:Record<string,string>={KeyW:'前へ',KeyS:'後ろへ',KeyA:'左へ',KeyD:'右へ',Space:'ジャンプ',KeyE:'使う',KeyQ:'能力',KeyG:'翼',KeyV:'急降下',KeyP:'写真',KeyT:'登る',KeyB:'建築',KeyF:'放水',KeyR:'強攻撃',KeyJ:'攻撃',KeyK:'盾を構える',KeyH:'仲間を助ける',KeyC:'回避',KeyX:'解体',ShiftLeft:'走る',...Object.fromEntries(Array.from({length:8},(_,i)=>['Digit'+(i+1),'クイックスロット'+(i+1)]))};
export interface GamePreferences{version:1;fov:number;resolution:ResolutionMode;holdAssist:boolean;aimAssist:boolean;musicVolume:number;environmentVolume:number;effectsVolume:number;textScale:number;reducedMotion:boolean;invertY:boolean;volume:number;distance:number;sensitivity:number;bindings:Record<string,string>}
export function normalizePreferences(raw:unknown):GamePreferences{
 const s=raw&&typeof raw==='object'?raw as Partial<GamePreferences>:{},number=(v:unknown,min:number,max:number,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback;
 const bindings:Record<string,string>={},used=new Set<string>();
 for(const code of Object.keys(BINDING_LABELS)){const requested=s.bindings?.[code],value=typeof requested==='string'&&/^(Key[A-Z]|Digit[0-9]|Space|Shift(Left|Right)|Control(Left|Right)|Arrow(Up|Down|Left|Right))$/.test(requested)&&!used.has(requested)?requested:code;bindings[code]=value;used.add(value);}
 if(new Set(Object.values(bindings)).size!==Object.keys(BINDING_LABELS).length)for(const code of Object.keys(BINDING_LABELS))bindings[code]=code;
 return {version:1,fov:number(s.fov,45,85,55),aimAssist:s.aimAssist!==false,holdAssist:s.holdAssist===true,musicVolume:number(s.musicVolume,0,1,.6),environmentVolume:number(s.environmentVolume,0,1,.8),effectsVolume:number(s.effectsVolume,0,1,1),resolution:['auto','high','medium','low'].includes(s.resolution??'')?s.resolution!:'auto',textScale:number(s.textScale,1,1.4,1),reducedMotion:s.reducedMotion===true,invertY:s.invertY===true,volume:number(s.volume,0,1,.65),distance:number(s.distance,2.5,8,5),sensitivity:number(s.sensitivity,.4,1.6,1),bindings};
}
export function accessibilityUI(signal:AbortSignal){
 const key='voxel-coop-preferences-v1';let preferences:GamePreferences;try{preferences=normalizePreferences(JSON.parse(localStorage.getItem(key)??'null'));}catch{preferences=normalizePreferences(null);}
 const panel=document.querySelector('#system-panel')!,section=document.createElement('section');section.id='accessibility-settings';
 section.innerHTML='<h3>見やすさ・操作</h3><label>視野角（45〜85度）<input id="camera-fov" type="range" min="45" max="85" step="1"></label><label><input id="aim-assist" type="checkbox">弓の照準補助（見える敵・5度以内）</label><label><input id="hold-assist" type="checkbox">救助は押すたびに開始 / 停止</label><label>音楽<input id="music-volume" type="range" min="0" max="1" step=".05"></label><label>環境音<input id="environment-volume" type="range" min="0" max="1" step=".05"></label><label>効果音<input id="effects-volume" type="range" min="0" max="1" step=".05"></label><label>描画解像度<select id="render-resolution"><option value="auto">自動調整</option><option value="high">高</option><option value="medium">中</option><option value="low">低・省電力</option></select></label><p>地形・衝突・共有状態は同じです。低い設定は遠景が粗くなります。</p><label>文字の大きさ<input id="text-scale" type="range" min="1" max="1.4" step=".1"></label><label><input id="reduced-motion" type="checkbox">画面の点滅・揺れを抑える</label><label><input id="invert-camera" type="checkbox">カメラ上下を反転</label><details><summary>キーボード割り当て</summary><p>欄を選び、使いたいキーを押してください。マウス左=攻撃、右=盾。J/Kでも操作できます。TabとEscはメニュー操作のため固定です。</p><div class="binding-grid">'+Object.entries(BINDING_LABELS).map(([code,label])=>`<label>${label}<input data-binding="${code}" readonly aria-label="${label}のキー"></label>`).join('')+'</div><button type="button" id="binding-reset">標準キーへ戻す</button></details><p id="settings-message" role="status"></p>';
 panel.append(section);let view:CameraView|undefined;
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(preferences));}catch{section.querySelector('#settings-message')!.textContent='設定を保存できませんでした';}};
 const apply=()=>{document.documentElement.style.setProperty('--text-scale',String(preferences.textScale));document.querySelector<HTMLElement>('#app')!.dataset.motion=preferences.reducedMotion?'reduced':'normal';if(view){view.invertY=preferences.invertY;view.distance=preferences.distance;view.sensitivity=preferences.sensitivity;}};
 const ranges=[['camera-fov','fov'],['music-volume','musicVolume'],['environment-volume','environmentVolume'],['effects-volume','effectsVolume'],['text-scale','textScale'],['sound-volume','volume'],['camera-distance','distance'],['camera-sensitivity','sensitivity']] as const;
 for(const[id,field]of ranges){const input=document.querySelector<HTMLInputElement>('#'+id)!;input.value=String(preferences[field]);input.addEventListener('input',()=>{preferences=normalizePreferences({...preferences,[field]:Number(input.value)});apply();save();},{signal});}
 for(const[id,field]of [['aim-assist','aimAssist'],['hold-assist','holdAssist'],['reduced-motion','reducedMotion'],['invert-camera','invertY']] as const){const input=section.querySelector<HTMLInputElement>('#'+id)!;input.checked=preferences[field];input.addEventListener('change',()=>{preferences[field]=input.checked;apply();save();},{signal});}
 const refresh=()=>{for(const input of section.querySelectorAll<HTMLInputElement>('[data-binding]'))input.value=preferences.bindings[input.dataset.binding!];};
 section.addEventListener('keydown',event=>{const input=(event.target as HTMLElement).closest<HTMLInputElement>('[data-binding]');if(!input)return;if(event.key==='Tab'||event.key==='Escape')return;event.preventDefault();event.stopPropagation();if(!/^(Key[A-Z]|Digit[0-9]|Space|Shift(Left|Right)|Control(Left|Right)|Arrow(Up|Down|Left|Right))$/.test(event.code))return;
  const logical=input.dataset.binding!,conflict=Object.entries(preferences.bindings).find(([code,value])=>code!==logical&&value===event.code);if(conflict){section.querySelector('#settings-message')!.textContent=`このキーは「${BINDING_LABELS[conflict[0]]}」で使用中です`;return;}preferences.bindings[logical]=event.code;refresh();save();section.querySelector('#settings-message')!.textContent='キーを保存しました';},{signal});
 section.querySelector('#binding-reset')!.addEventListener('click',()=>{preferences.bindings=normalizePreferences(null).bindings;refresh();save();},{signal});
 const resolution=section.querySelector<HTMLSelectElement>('#render-resolution')!;resolution.value=preferences.resolution;resolution.addEventListener('change',()=>{preferences=normalizePreferences({...preferences,resolution:resolution.value});save();},{signal});
 refresh();apply();signal.addEventListener('abort',()=>section.remove(),{once:true});
 return {boundCode:(physical:string)=>Object.keys(preferences.bindings).find(key=>preferences.bindings[key]===physical)??(Object.hasOwn(preferences.bindings,physical)?'':physical),bindView(next:CameraView){view=next;apply();},get fov(){return preferences.fov;},get aimAssist(){return preferences.aimAssist;},get holdAssist(){return preferences.holdAssist;},get audioMix(){return {music:preferences.musicVolume,environment:preferences.environmentVolume,effects:preferences.effectsVolume};},get resolution(){return preferences.resolution;},get reducedMotion(){return preferences.reducedMotion;}};
}
