import type {Snapshot} from '../simulation/protocol';
import type {CompanionAction} from '../game/companions';
export function companionsUI(signal:AbortSignal,action:(kind:CompanionAction,id:string)=>void,selectedPart:()=>number){
 const section=document.createElement('section');section.id='companion-controls';section.innerHTML='<hr><h3>灯背獣ルメル</h3><p>出発点の東にいる、灯を背負った六脚の生物です。木の実を3回あげると仲間になります。騎乗は移動入力、手綱は8部品・質量60までの自分/共有構造物を引けます。</p><label>近くの灯背獣<select id="companion-choice"></select></label><p id="companion-status" role="status"></p><div class="power-controls"><button data-companion="feed">木の実を1個あげる</button><button data-companion="call">呼ぶ / 待つ</button><button data-companion="ride">乗る / 降りる</button><button data-companion="lead">選択部品へ手綱を結ぶ</button><button data-companion="untether">手綱を外す</button></div>';
 document.querySelector('#powers-panel')!.append(section);const choices=section.querySelector<HTMLSelectElement>('#companion-choice')!;let selected=0,state:Snapshot|null=null;
 choices.addEventListener('change',()=>selected=Number(choices.value),{signal});section.addEventListener('click',event=>{const kind=(event.target as HTMLElement).closest<HTMLElement>('[data-companion]')?.dataset.companion;if(!kind||!selected)return;const suffix=kind==='lead'?':'+selectedPart():kind==='untether'?':off':'';action(('companion-'+(kind==='untether'?'lead':kind))as CompanionAction,String(selected)+suffix);if(kind==='ride')document.querySelector<HTMLElement>('#powers-panel')!.hidden=true;},{signal});
 const dismount=document.createElement('button');dismount.id='companion-dismount';dismount.textContent='ルメルから降りる';dismount.hidden=true;document.querySelector('#app')!.append(dismount);dismount.addEventListener('click',()=>{const id=state?.adventure.companions?.riding;if(id)action('companion-ride',String(id));},{signal});
 signal.addEventListener('abort',()=>{section.remove();dismount.remove();},{once:true});
 return {update(next:Snapshot){state=next;const herd=next.adventure.companions;section.hidden=next.adventure.generator!==4;dismount.hidden=!herd?.riding;if(!herd)return;const owner=document.querySelector<HTMLElement>('#session-status')?.dataset.player??'host',near=herd.creatures.filter(c=>c.owner===owner||Math.hypot(c.position.x-next.player.x,c.position.y-next.player.y,c.position.z-next.player.z)<20);if(!near.some(c=>c.id===selected))selected=near[0]?.id??0;const markup=near.map(c=>`<option value="${c.id}">ルメル #${c.id} · 絆 ${c.bond}/3</option>`).join('');if(choices.innerHTML!==markup){choices.innerHTML=markup;choices.value=String(selected);}const c=near.find(c=>c.id===selected);section.querySelector('#companion-status')!.textContent=c?`持久 ${Math.round(c.stamina)} · ${c.owner?c.owner===owner?'自分の仲間':'仲間の灯背獣':'まだ野生'}${c.following?' · 追従中':''}${c.rider?' · 騎乗中':''}${c.tetherPart?' · 牽引 #'+c.tetherPart:''}`:'出発点から東へ進み、近づいてください';}};
}
