import type {AdventureSnapshot} from '../game/types';
import type {Vec3} from '../world/types';
import {SITES,SITE_ROOMS,ANNEX_ROOMS} from '../content/adventure-sites';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function expeditionPanel(state:AdventureSnapshot,player:Vec3):string{
 const expeditions=state.expeditions;if(!expeditions?.sites.length)return '';const button=(label:string,action:string,id:number,disabled=false)=>`<button data-game-action="${action}" data-id="${id}" ${disabled?'disabled':''}>${label}</button>`;
 return '<h3>途切れた三層の連絡網</h3><p>輸送・救助・設備復旧に加え、各拠点の別棟に3つの記録があります。正面の道だけでなく、側道・屋根・掘った道も使えます。貸出品の復旧は自作物や掘削を戻しません。</p><div class=region-cards>'+expeditions.sites.map(site=>{const def=SITES.find(s=>s.id===site.id)!,near=Math.hypot(player.x-site.x,player.y-site.y-.4,player.z-site.z-5.5);return `<article class=recipe-card><strong>${site.completed?'◆':'◇'} ${site.name}</strong><p>${def.task} / ${def.guide}</p><small>X ${site.x}, Y ${site.y.toFixed(1)}, Z ${site.z}</small><p>見つけた部屋: ${site.rooms.length}/6 ${site.rooms.map(id=>[...SITE_ROOMS,...ANNEX_ROOMS].find(r=>r.id===id)?.name??'').join('・')}</p><p>${escape(site.reason)}</p><p>番人: ${site.boss.name}${site.boss.defeated?' · 鎮めた':''}</p><div class=panel-actions>${button('案内人と話す','site-talk',site.id,near>4)}${button(site.accepted?'依頼を確認':'依頼を聞く','site-accept',site.id,near>4)}${button('結果を報告','site-report',site.id,near>4)}${button('貸出品を復旧','site-reset',site.id,near>9)}</div>${site.skipped?'<small>既存物を守るため一部の遺構配置を省略しています。</small>':''}</article>`;}).join('')+'</div><p>全員の成長: HP +'+expeditions.growth.health+' / 持久 +'+expeditions.growth.stamina+'</p>';
}
export function rescueUI(signal:AbortSignal,action:()=>void){const button=document.createElement('button');button.id='site-rescue';button.hidden=true;button.textContent='測り手に声をかける';document.querySelector('#app')!.append(button);button.addEventListener('click',action,{signal});signal.addEventListener('abort',()=>button.remove(),{once:true});return{update(state:AdventureSnapshot,player:Vec3){const rescue=state.expeditions?.rescue;button.hidden=!rescue||rescue.arrived||Math.hypot(rescue.position.x-player.x,rescue.position.y-player.y,rescue.position.z-player.z)>3.5;button.textContent=rescue?.following?'測り手に待ってもらう':'測り手を入口へ案内';}};}
