import {CLASSES} from './catalog';
import {BASTION_SKILLS,bastionTrainingStats,validBastionTraining,validBastionSkillState} from './training';
import {RAVAGER_SKILLS,validRavagerTraining,validRavagerSkillState} from './ravager-training';
import {isQuestId,validQuestJournal} from './quests';
import {validSupplyStock} from './economy';
import type {Action,ClientPacket,Input,RaidState,Actor} from './types';
import {validInventory,STASH_HEIGHT} from './inventory';
const record=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const finite=(x:unknown,min=-1e6,max=1e6):x is number=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;
const integer=(x:unknown,min=0,max=1e9)=>finite(x,min,max)&&Number.isInteger(x);
const text=(x:unknown,max=96):x is string=>typeof x==='string'&&x.length<=max;
const keys=(x:Record<string,unknown>,expected:string[])=>Object.keys(x).every(k=>expected.includes(k))&&expected.every(k=>Object.hasOwn(x,k));
export const privateKey=(x:unknown):x is string=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
export function validInput(x:unknown):x is Input{return record(x)&&keys(x,['x','z','yaw','pitch','block','crouch'])&&finite(x.x,-1,1)&&finite(x.z,-1,1)&&finite(x.yaw,-Math.PI*2,Math.PI*2)&&finite(x.pitch,-1.45,1.45)&&typeof x.block==='boolean'&&typeof x.crouch==='boolean';}
export function validAction(x:unknown):x is Action{if(!record(x))return false;switch(x.kind){case'configure-ravager-training':return keys(x,['kind','skill','perk'])&&validRavagerTraining({skill:x.skill,perk:x.perk});case'configure-training':return keys(x,['kind','skill','perk'])&&validBastionTraining({skill:x.skill,perk:x.perk});case'skill':return keys(x,['kind']);case'accept-quest':case'claim-quest':return keys(x,['kind','quest'])&&isQuestId(x.quest);case'deliver-quest':return keys(x,['kind','quest','item'])&&isQuestId(x.quest)&&text(x.item);case'buy-supply':return keys(x,['kind','supply'])&&(x.supply==='potion'||x.supply==='bandage');case'sell-treasure':return keys(x,['kind','item'])&&text(x.item);case'ready':case'start':case'return':case'cast':case'shoot':case'heal':return keys(x,['kind']);case'class':return keys(x,['kind','classId'])&&text(x.classId)&&Object.hasOwn(CLASSES,x.classId);case'attack':return Object.keys(x).every(k=>['kind','heavy'].includes(k))&&(x.heavy===undefined||typeof x.heavy==='boolean');case'interact':return keys(x,['kind','target'])&&text(x.target);case'loot':return keys(x,['kind','target','item'])&&text(x.target)&&text(x.item);case'claim-return':case'transfer':return keys(x,['kind','item','to'])&&text(x.item)&&(x.to==='bag'||x.to==='stash');case'move-item':return keys(x,['kind','item','x','y','rotate'])&&text(x.item)&&integer(x.x,0,9)&&integer(x.y,0,4)&&typeof x.rotate==='boolean';default:return false;}}
export function parsePacket(raw:string):ClientPacket|null{if(raw.length>4096)return null;let x:unknown;try{x=JSON.parse(raw);}catch{return null;}if(!record(x))return null;if(x.type==='hello'&&keys(x,['type','protocol','key','name'])&&integer(x.protocol,0,100)&&privateKey(x.key)&&text(x.name,24)&&x.name.trim().length>0&&!/[\u0000-\u001f<>]/.test(x.name))return x as unknown as ClientPacket;if(x.type==='input'&&keys(x,['type','sequence','input'])&&integer(x.sequence,1)&&validInput(x.input))return x as unknown as ClientPacket;if(x.type==='action'&&keys(x,['type','sequence','action'])&&integer(x.sequence,1)&&validAction(x.action))return x as unknown as ClientPacket;return null;}
const velocity=(x:unknown)=>record(x)&&finite(x.x,-100,100)&&finite(x.y,-100,100)&&finite(x.z,-100,100);
const vector=(x:unknown)=>record(x)&&finite(x.x,-100,100)&&finite(x.y,-10,100)&&finite(x.z,-100,100);
function actor(x:unknown):x is Actor{return record(x)&&(!Object.hasOwn(x,'ravagerTraining')||validRavagerTraining(x.ravagerTraining))&&(!Object.hasOwn(x,'ravagerSkillState')||validRavagerSkillState(x.ravagerSkillState)&&x.classId==='ravager'&&validRavagerTraining(x.ravagerTraining)&&x.ravagerTraining.skill===x.ravagerSkillState.skill)&&(!Object.hasOwn(x,'training')||validBastionTraining(x.training))&&(!Object.hasOwn(x,'skillState')||validBastionSkillState(x.skillState)&&x.classId==='bastion'&&validBastionTraining(x.training)&&x.training.skill===x.skillState.skill)&&text(x.id)&&text(x.name,24)&&text(x.classId)&&Object.hasOwn(CLASSES,x.classId)&&vector(x.position)&&finite(x.yaw,-7,7)&&finite(x.pitch,-1.45,1.45)&&finite(x.hp,0,1000)&&finite(x.maxHp,1,1000)&&finite(x.recoverable,0,1000)&&x.hp<=x.maxHp&&finite(x.time,0,1e6)&&finite(x.guard,0,1)&&finite(x.cast,-2,2)&&finite(x.extract,0,10)&&finite(x.inputAt,-100,1e6)&&integer(x.seq)&&integer(x.arrows,0,1000)&&integer(x.spells,0,1000)&&integer(x.kills)&&integer(x.xp)&&finite(x.damageTaken,0,1e6)&&finite(x.team,-1,6)&&validInput(x.input)&&validInventory(x.bag)&&['idle','windup','strike','recover','dodge','stagger','dead','heal'].includes(String(x.phase))&&['slash','return','overhead'].includes(String(x.kind))&&['lobby','alive','dead','extracted'].includes(String(x.status))&&['sword','greatsword','dagger','bow','staff'].includes(String(x.weapon))&&(x.interaction===null||text(x.interaction))&&Array.isArray(x.hit)&&x.hit.length<=10&&x.hit.every(v=>text(v))&&typeof x.ready==='boolean'&&typeof x.connected==='boolean';}
/** Fail closed on corrupt/unknown durable state; never silently reset a stash. */
export function validRaidState(x:unknown):x is RaidState{if(!record(x)||x.version!==1||!integer(x.raid)||!integer(x.seed,0,65536)||!integer(x.tick)||!integer(x.serial)||!finite(x.elapsed,0,1e6)||!['lobby','raid','finished'].includes(String(x.phase))||!Array.isArray(x.profiles)||x.profiles.length>6||!Array.isArray(x.enemies)||x.enemies.length>16||!Array.isArray(x.containers)||x.containers.length>64||!Array.isArray(x.doors)||x.doors.length>16||!Array.isArray(x.exits)||x.exits.length>16||!Array.isArray(x.shots)||x.shots.length>64||!Array.isArray(x.events)||x.events.length>12||!x.events.every(e=>text(e,128)))return false;
 if(x.shop!==undefined&&!validSupplyStock(x.shop))return false;
 const trainingClock=(a:Actor)=>(!a.skillState||a.skillState.readyAt-BASTION_SKILLS[a.skillState.skill].cooldown<=Number(x.elapsed)+1e-7)&&(!a.ravagerSkillState||a.ravagerSkillState.readyAt-RAVAGER_SKILLS[a.ravagerSkillState.skill].cooldown<=Number(x.elapsed)+1e-7);
 const ids=new Set<string>(),itemIds=new Set<string>(),secrets=new Set<string>();
 const uniqueItems=(items:{id:string}[])=>items.every(i=>{
  // Generated IDs must belong to the already-issued range, including offline owners.
  const generated=/^r(\d+)-i(\d+)$/.exec(i.id);
  if(itemIds.has(i.id)||generated&&(Number(generated[1])>Number(x.raid)||Number(generated[2])>Number(x.serial)))return false;
  itemIds.add(i.id);return true;
 });
 for(const p of x.profiles){if(!record(p)||!privateKey(p.key)||secrets.has(p.key)||!actor(p.actor)||!trainingClock(p.actor)||ids.has(p.actor.id)||!validInventory(p.stash,STASH_HEIGHT)||!integer(p.gold)||!integer(p.raid)||!integer(p.lastAction)||!text(p.result,200)||!Array.isArray(p.receipt)||p.receipt.length>128||!p.receipt.every(r=>text(r))||!uniqueItems(p.stash)||!uniqueItems(p.actor.bag))return false;
  if((p.actor.training||p.actor.ravagerTraining)&&p.actor.maxHp!==(p.actor.classId==='bastion'?bastionTrainingStats(p.actor.training??{skill:null,perk:null}).maxHp:CLASSES[p.actor.classId].hp))return false;
  if(Object.hasOwn(p,'quests')&&!validQuestJournal(p.quests))return false;
  if(p.pendingReturn!==undefined&&(!validInventory(p.pendingReturn)||!p.pendingReturn.every(item=>item.found)||!uniqueItems(p.pendingReturn)))return false;
  if(Array.isArray(p.pendingReturn)&&p.pendingReturn.length&&(p.actor.status==='alive'||p.actor.ready))return false;
  ids.add(p.actor.id);secrets.add(p.key);}
 for(const e of x.enemies){if(!actor(e)||!trainingClock(e)||ids.has(e.id)||!record(e)||!vector(e.home)||!finite(e.alert,0,100)||typeof e.lootClaimed!=='boolean'||!uniqueItems(e.bag))return false;ids.add(e.id);}
 for(const c of x.containers){if(!record(c)||!text(c.id)||!text(c.name,64)||!vector(c.position)||!validInventory(c.items)||!uniqueItems(c.items)||typeof c.opened!=='boolean'||typeof c.locked!=='boolean'||!['chest','corpse'].includes(String(c.kind)))return false;}
 for(const d of x.doors)if(!record(d)||!text(d.id)||!vector(d.position)||typeof d.open!=='boolean')return false;
 for(const e of x.exits)if(!record(e)||!text(e.id)||!vector(e.position)||!finite(e.opensAt,0,480)||!integer(e.remaining,0,6))return false;
 for(const s of x.shots)if(!record(s)||!text(s.id)||!text(s.owner)||!vector(s.position)||!velocity(s.velocity)||!finite(s.life,0,4)||!finite(s.damage,0,1000)||typeof s.magic!=='boolean')return false;
 return true;
}
