import { CoreSimulation } from './core/simulation';
import { createView } from './rendering/scene';
import { createInput } from './input';
import { createAudio } from './audio';
import { materialDefinition } from './core/materials';
import { key } from './core/voxel';
import { materialColors } from './rendering/element-effects';
import {createCampaignUI,type CampaignCommand,type CampaignTab} from './campaign-ui';
import {captureCampaign,createCampaignStore,defaultSettings,restoreCampaignInto,getCampaignRestoreFailure,type CampaignSettings} from './campaign-session';
import {bootstrapCampaignWorld} from './core/world-bootstrap';
import {CampaignRoomSession} from './network/game-session';
import {createCoopAvatar} from './rendering/coop-avatar';
import {executeGameCommand,isGameCommand} from './campaign-commands';
import {campaignSnapshot} from './campaign-presenter';
import './style.css';
export function startPrototype(){
 const canvas=document.querySelector<HTMLCanvasElement>('#game')!,audio=createAudio(),$=(id:string)=>document.getElementById(id)!;
 const trial=new URLSearchParams(location.search).has('trial'),store=createCampaignStore(),loaded=store.read();
 const pendingSave=!trial&&(loaded.status==='loaded'||loaded.status==='recovered')?loaded.data:null;
 const sim=new CoreSimulation(!trial,!trial),settings:CampaignSettings=pendingSave?JSON.parse(JSON.stringify(pendingSave.settings)):defaultSettings();let loadFailed=false,savingAllowed=!trial&&loaded.status==='empty',hasSave=!!pendingSave,saveStatus=trial?'試練モード（保存なし）':pendingSave?'保存した世界を展開中…':'周辺地域を準備中。拠点から遊び始められます',saveTimer=0;
 for(const [action,key] of Object.entries(settings.bindings))if(key==='KeyZ')delete settings.bindings[action];
 let room:CampaignRoomSession|null=null,guestSessionUsed=false,awaitingGuestRespawn=false;
  function save(){if(guestSessionUsed||room?.role==='guest'){saveStatus='同行中は自分の単独プレイ保存を変更しません';return false;}if(!sim.worldReady){saveStatus='周辺地域を準備中。完了後に変更を保存します';return false;}if(!savingAllowed){saveStatus='元の保存を保護しています。保存の再開か新規開始を選んでください';return false;}const result=store.write(captureCampaign(sim,settings));saveStatus=result.ok?'保存済み '+new Date().toLocaleTimeString():result.error;hasSave ||=result.ok;return result.ok;}

 let needsRender=true,active=false,paused=true,disposed=false,last=performance.now(),accumulator=0,raf=0,uiTimer=0,messageUntil=0,hitUntil=0,hurtUntil=0,debug=false,timeScale=1;
 const elementNames={fire:'火',water:'水',earth:'土',wind:'風',lightning:'雷'},elementColors={fire:'#ffac6c',water:'#8bd4ff',earth:'#dfbd85',wind:'#b7edc5',lightning:'#d6b7ff'};
 const materialNames:Record<number,string>={1:'地面',2:'土',3:'石',4:'木材',5:'木材',6:'金属',7:'草',8:'碑石',9:'灯火',10:'布'};
 const inventoryNodes=[4,3,2,6,7,10].map(id=>{const node=document.createElement('span');node.style.color=materialColors[id];$('inventory').append(node);return {id,node};});
 const dropCountNode=document.createElement('span');dropCountNode.id='drop-count';$('inventory').append(dropCountNode);
 const view=createView(canvas,sim);const qualityLabels={balanced:'標準',performance:'省電力',high:'高品質'};const applyGraphics=(quality:CampaignSettings['graphics'])=>{settings.graphics=quality;view.setGraphics(quality);$('quality-toggle').textContent='画質：'+qualityLabels[quality];$('quality-toggle').title=quality==='performance'?'低解像度・動的影なし・簡略化した空。地形・戦闘・ゲーム速度は同じ。'+(view.stats().softwareRendering?' ソフトウェアGPUを検出。':''):'描画品質を切り替えます';};applyGraphics(settings.graphics);audio.setVolume(settings.volume);const portrait=()=>innerHeight>innerWidth;
 function pause(){if(paused)return;save();paused=true;input.setEnabled(false);$('menu').hidden=false;$('menu-title').textContent='一息つく';$('start').textContent='再開';updateUI(performance.now());if(document.pointerLockElement)document.exitPointerLock();}
 const performAction=(a:import('./core/simulation').Action)=>{if(!room?.action(a))sim.action(a,input.controls());};
 const input=createInput(canvas,performAction,(x,y)=>sim.look(x,y),pause);document.body.classList.toggle('touch',input.mobile);input.setSensitivity(settings.sensitivity);for(const [action,key] of Object.entries(settings.bindings))input.bind(action,key);
 const campaignUI=createCampaignUI(command);if(trial){$('campaign-toggle').hidden=true;$('campaign-status').hidden=true;}
 const coopAvatar=createCoopAvatar(view.scene);if(!trial){room=new CampaignRoomSession(sim,{settings:()=>settings,save,mode:role=>{if(role==='guest')guestSessionUsed=true;input.reset();},notice:message=>{campaignUI.notify(message);$('message').textContent=message;messageUntil=performance.now()+3500;}});void room.probe();}
 function command(cmd:CampaignCommand){let result:{ok:boolean;message:string;heal?:number;position?:{x:number;y:number;z:number}}|undefined;
 if(cmd.type==='open'){pause();return;}if(cmd.type==='close'){if(!paused)pause();return;}if(cmd.type==='resume'){campaignUI.close();void begin();return;}
 if(cmd.type==='coop'){void room?.command(cmd.id,cmd.text);updateUI(performance.now());return;}
 if(isGameCommand(cmd)){if(room?.gameCommand(cmd)){updateUI(performance.now());return;}result=executeGameCommand(sim,cmd);}
 if(cmd.type==='save')result={ok:save(),message:saveStatus};if(cmd.type==='continue'){if(loaded.status==='recovered'){const recovery=store.recoverBackup();if(!recovery.ok){campaignUI.notify(recovery.error);return;}}savingAllowed=false;location.reload();return;}
 if(cmd.type==='new-game'){const reset=store.reset();if(!reset.ok){campaignUI.notify(reset.error);return;}savingAllowed=false;location.reload();return;}
 if(cmd.type==='setting'){if(cmd.key==='volume'&&typeof cmd.value==='number'){settings.volume=cmd.value;audio.setVolume(cmd.value);}if(cmd.key==='sensitivity'&&typeof cmd.value==='number'){settings.sensitivity=cmd.value;input.setSensitivity(cmd.value);}if(cmd.key==='graphics'&&(cmd.value==='balanced'||cmd.value==='performance'||cmd.value==='high')){applyGraphics(cmd.value);}}
 if(cmd.type==='binding'){const ok=input.bind(cmd.action,cmd.key);if(ok)settings.bindings[cmd.action]=cmd.key;result={ok,message:ok?'割り当てを変更':'移動・メニュー用キーまたは重複キーは使えません'};}if(cmd.type==='reset-bindings'){input.resetBindings();settings.bindings={};}
 if(cmd.type==='pin'){if(settings.pins.length>=12)settings.pins.shift();settings.pins.push({id:'pin:'+Date.now(),x:cmd.x,z:cmd.z});result={ok:true,message:'地図にピンを置いた'};}if(cmd.type==='remove-pin')settings.pins=settings.pins.filter(p=>p.id!==cmd.id);
 if(result){campaignUI.notify(result.message);audio.play(result.ok?'interact':'parry');if(result.ok)save();}updateUI(performance.now());
 }
 function resize(){input.reset();$('rotate').hidden=!portrait();if(portrait())pause();view.resize();needsRender=true;updateUI(performance.now());}
 async function begin(){if(portrait()||loadFailed||pendingSave&&!sim.worldReady||room?.role==='guest'&&!room.online)return;active=true;paused=false;input.setEnabled(true);$('menu').hidden=true;audio.start();updateUI(performance.now());
  if(input.mobile){try{await document.documentElement.requestFullscreen();const orientation=screen.orientation as ScreenOrientation&{lock?:(value:string)=>Promise<void>};await orientation.lock?.('landscape');}catch{}}
  else await input.lock();
 }
 $('quality-toggle').addEventListener('click',()=>{const order:CampaignSettings['graphics'][]=['balanced','performance','high'];applyGraphics(order[(order.indexOf(settings.graphics)+1)%order.length]);if(!trial)save();updateUI(performance.now());});
 $('start').addEventListener('click',()=>void begin());$('menu-toggle').addEventListener('click',pause);$('restart').addEventListener('click',()=>campaignUI.open('settings'));$('retry').addEventListener('click',()=>{if(room?.respawn()){awaitingGuestRespawn=true;($('retry') as HTMLButtonElement).disabled=true;return;}sim.respawn();save();$('death').hidden=true;void begin();});$('day-toggle').addEventListener('click',()=>{view.toggleDay();needsRender=true;});
 const toggleMotion=()=>{timeScale=timeScale===1?.25:1;$('motion-toggle').textContent='動作：'+(timeScale===1?'通常':'1/4');};$('motion-toggle').addEventListener('click',toggleMotion);
 $('tool-switch').addEventListener('click',()=>{if(!paused)performAction('tool');});$('heal').addEventListener('click',()=>{if(!paused)performAction('heal');});
 document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;const tab:CampaignTab|undefined=({KeyI:'inventory',KeyJ:'journal',KeyM:'map',Tab:'inventory'} as Record<string,CampaignTab>)[e.code];if(tab&&!campaignUI.isOpen){e.preventDefault();campaignUI.open(tab);return;}if(e.code==='F4'){e.preventDefault();toggleMotion();}if(e.code==='F3'){e.preventDefault();debug=!debug;$('diagnostics').hidden=!debug;}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',resize);resize();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('error').hidden=false;$('error').textContent='描画が停止しました。再読み込みしてください。';});
 function updateUI(now:number){
  ($('start') as HTMLButtonElement).disabled=loadFailed||!!pendingSave&&!sim.worldReady;const p=sim.player,target=sim.target(sim.campaign.canGrapple?7:2.75);const ui=campaignSnapshot(sim,settings,{available:hasSave,label:guestSessionUsed?'同行中は自分の単独プレイ保存を保護しています':'このブラウザの単独プレイ。新規開始は元の保存をバックアップします。',status:saveStatus},input.bindings());if(room)ui.cooperation=room.snapshot();campaignUI.update(ui);
  for(const {id,node} of inventoryNodes)node.textContent=materialNames[id]+' '+(sim.survival.inventory[id]??0);
  dropCountNode.textContent='未回収 '+[...sim.survival.drops,...sim.survival.pendingDrops].reduce((sum,d)=>sum+d.count,0);
  const element=sim.selectedElement,recipe=sim.survival.recipe,prefix=input.mobile?'':'F ';
  $('element-switch').textContent=sim.buildMode?(input.mobile?'回転':'F 回転')+' '+sim.survival.rotation*90+'°':prefix+elementNames[element]+' ▸';$('element-switch').style.setProperty('--element-color',elementColors[element]);
  $('cast').textContent=(input.mobile?'':'G ')+(sim.buildMode?'建築終了':'放つ');$('dismantle').hidden=!sim.buildMode;$('special').textContent=(input.mobile?'':'X ')+(sim.buildMode?'戻す':'集中 '+Math.floor(sim.focus.value));($('special') as HTMLButtonElement).disabled=paused||p.phase!=='idle'||!sim.buildMode&&sim.focus.value<100;$('recipe-switch').textContent=(input.mobile?'':'V ')+recipe.label+' ▸';$('build').textContent=(input.mobile?'':'B ')+(sim.buildMode?'置く':'建築');
  $('recipe-cost').textContent='木材 '+recipe.cost+' / '+(sim.survival.inventory[4]??0)+(recipe.id==='workbench'?' · 地面を狙って設置':' · 作業台の3m以内')+' · 素材は近づいて回収';
  for(const id of ['element-switch','cast','recipe-switch','build','dismantle'])($(id) as HTMLButtonElement).disabled=paused||p.hp<=0||(id==='cast'||id==='build'||id==='dismantle')&&p.phase!=='idle';
  const cell=target?.hit.cell??null,reactions=target?.enemy?sim.enemyElements[target.enemy.id].reactions:sim.elements,state=cell?reactions.states.get(key(cell.x,cell.y,cell.z)):undefined;
  $('material-status').textContent=cell?(materialNames[cell.material]??materialDefinition(cell.material).name)+' · 耐久 '+Math.ceil(reactions.durability(cell))+'/'+materialDefinition(cell.material).durability+(state?.fire?' · 燃焼':'')+(state?.wet?' · 濡れ':'')+(state?.charge?' · 帯電':'')+(cell.object&&sim.elements.protectedObjects.has(cell.object)?' · 重要対象を保護':''):'';
$('hp-fill').style.width=p.hp/sim.campaign.maxHp*100+'%';$('stamina-fill').style.width=p.stamina/sim.campaign.maxStamina*100+'%';$('hp-value').textContent=String(Math.ceil(p.hp));$('stamina-value').textContent=String(Math.ceil(p.stamina));$('target').textContent=target?.label??'';$('prompt').textContent=target?.action??'';
  const interact=document.querySelector<HTMLButtonElement>('[data-action="interact"]')!;interact.hidden=!target?.action.startsWith('E /');interact.disabled=p.phase!=='idle';interact.textContent=target?.action.replace('E / 操作 · ','')??'操作';if(target?.action.startsWith('E /'))$('prompt').textContent=p.phase!=='idle'?'硬直中':input.mobile?target.action.replace('E / 操作 · ',''):target.action;$('enemy-health').hidden=!target?.enemy;if(target?.enemy)$('enemy-fill').style.width=target.enemy.hp/(target.enemy.maxHp??100)*100+'%';
  $('tool-switch').textContent=p.tool?'2 鑿':'1 剣';$('heal').textContent=p.phase==='heal'?'服薬中…':'Q 回復 ×'+p.flasks;($('heal') as HTMLButtonElement).disabled=p.phase!=='idle'||!p.flasks||p.hp>=100;$('objective').textContent=sim.campaign.objective().label+' · '+sim.campaign.objective().detail;$('reticle').classList.toggle('hit',now<hitUntil);$('hurt').style.opacity=now<hurtUntil?'1':'0';if(now>messageUntil)$('message').textContent='';
  if(awaitingGuestRespawn&&(p.hp>0||!room?.online)){awaitingGuestRespawn=false;($('retry') as HTMLButtonElement).disabled=false;if(p.hp>0){$('death').hidden=true;void begin();}}
  if(p.hp<=0){if(room?.role!=='guest'&&!sim.campaign.state.deathPending){sim.campaign.die(sim.safePosition(p.position));save();}$('death').hidden=false;$('death').querySelector('p')!.textContent=room?.role==='guest'?'同行者が倒れた。共有拠点で復活できます':(sim.deathCause||'戦闘で倒れた')+' · 素材25%を残し、装備と重要品は保持。安全な拠点で復活します。';input.setEnabled(false);paused=true;}
  if(debug)$('diagnostics').textContent=JSON.stringify({waterCell:.125,waterM3:sim.water.total().toFixed(3),solidVoxels:sim.arena.field.cells.size,...view.stats()},null,2);
  canvas.dataset.ready='true';canvas.dataset.running=String(active&&!paused&&!portrait());canvas.dataset.target=target?.hit.cell.object??'';
 }
 if(new URLSearchParams(location.search).has('test'))Object.defineProperty(window,'__coreProbe',{configurable:true,get:()=>({position:{...sim.player.position},hp:sim.player.hp,stamina:sim.player.stamina,phase:sim.player.phase,phaseTime:sim.player.time,attack:sim.player.attack,weapon:sim.pose(),timeScale,enemies:sim.enemies.map(e=>({position:{...e.position},phase:e.phase,time:e.time,hp:e.hp,burning:sim.enemyElements[e.id].burning,wet:sim.enemyElements[e.id].wet,shock:sim.enemyElements[e.id].shock,voxelRevision:sim.enemyElements[e.id].field.revision,scars:sim.enemyElements[e.id].scars.length})),seconds:sim.seconds,yaw:sim.player.yaw,pitch:sim.player.pitch,door:sim.arena.objects.get('door')?.open,tool:sim.player.tool,selectedElement:sim.selectedElement,selectedRecipe:sim.selectedRecipe,inventory:{...sim.survival.inventory},drops:sim.survival.drops.map(d=>({...d,position:{...d.position}})),elementStates:sim.elements.states.size,burning:[...sim.elements.states.values()].filter(s=>s.fire>0).length,wet:[...sim.elements.states.values()].filter(s=>s.wet>0).length,charged:[...sim.elements.states.values()].filter(s=>s.charge>0).length,elementEffects:sim.elements.effects.length,water:sim.water.total(),target:sim.target()?.hit.cell.object,campaign:sim.campaign.snapshot(),home:sim.home.snapshot(),saveStatus,settings:{...settings},focus:sim.focus.value,oxygen:sim.oxygen,cold:sim.cold,worldHour:sim.worldHour,projectiles:sim.enemyShots.length,tells:sim.tells.length,gliding:sim.gliding,grapple:sim.grapple,worldReady:sim.worldReady,restoreFailure:getCampaignRestoreFailure(sim),cooperation:room?{online:room.online,...room.snapshot(),companion:sim.companion?{position:{...sim.companion.position},hp:sim.companion.hp,phase:sim.companion.phase}:null}:null,stats:view.stats()})});
 function frame(now:number){if(disposed)return;const dt=Math.min(.1,(now-last)/1000);last=now;input.tick(dt);
  if(room?.role!=='guest'&&(active||room?.hostRunning)&&(!paused||room?.hostRunning)&&!portrait()&&!document.hidden){accumulator+=dt*timeScale;let steps=0;while(accumulator>=1/60&&steps++<6){sim.tick(1/60,paused?{x:0,z:0,sprint:false,block:false,water:false}:input.controls());accumulator-=1/60;}}else accumulator=0;room?.tick(dt,input.controls(),active&&!paused&&!portrait()&&!document.hidden);coopAvatar.set(room?.remoteActor??null);coopAvatar.update(dt);
  for(const e of sim.events.splice(0)){audio.play(e.kind);if(e.text){$('message').textContent=e.text;messageUntil=now+1800;}if(e.kind==='hit'||e.kind==='parry')hitUntil=now+180;if(e.kind==='hurt')hurtUntil=now+350;}
  if(room?.role!=='guest'&&(active&&!paused||room?.hostRunning)){saveTimer+=dt;if(saveTimer>=30){saveTimer=0;save();}}uiTimer+=dt;if(uiTimer>=.08){updateUI(now);uiTimer=0;}if(!document.hidden&&(needsRender||active&&!paused&&!portrait())){view.render(dt,input.controls().block);needsRender=false;}raf=requestAnimationFrame(frame);
 }
 $('start').textContent=hasSave?'保存した旅を続ける':'新しい旅を始める';$('restart').textContent='保存・新規開始';
 if(!trial){const controller=new AbortController();void bootstrapCampaignWorld(sim.arena,{budgetMs:3,signal:controller.signal,onProgress:stage=>{saveStatus=stage==='merging'?'周辺地域を接続中。拠点での変更を保持しています':'周辺地域を背景で展開中…';}}).then(()=>{if(disposed)return;sim.worldReady=true;sim.protectQuestObjects();sim.water.refreshSolids();if(pendingSave){const restored=restoreCampaignInto(sim,pendingSave);if(!restored){loadFailed=true;saveStatus='保存内容を検証できません（'+(getCampaignRestoreFailure(sim)??'unknown')+'）。原本を保護しました。設定から新規開始を選べます';$('menu-title').textContent='保存データの確認が必要';return;}/* Preserve explicit settings changes made while loading; settings already came from this validated save. */input.setSensitivity(settings.sensitivity);audio.setVolume(settings.volume);applyGraphics(settings.graphics);for(const [action,key] of Object.entries(settings.bindings))input.bind(action,key as string);savingAllowed=loaded.status==='loaded';saveStatus=loaded.status==='recovered'?'バックアップから読み込みました。設定の「保存から続ける」で復元を確定':'保存した旅を読み込みました';}else if(savingAllowed)save();updateUI(performance.now());}).catch(error=>{if(disposed)return;loadFailed=true;pause();saveStatus='世界の準備に失敗しました。保存は変更していません。再読み込みしてください';$('menu-title').textContent=saveStatus;console.error('Campaign world bootstrap failed',error);});window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
 raf=requestAnimationFrame(frame);const dispose=()=>{if(disposed)return;disposed=true;cancelAnimationFrame(raf);window.removeEventListener('resize',resize);save();room?.dispose();coopAvatar.dispose();campaignUI.dispose();input.dispose();view.dispose();audio.dispose();};window.addEventListener('pagehide',e=>{if(!e.persisted)dispose();else pause();});return {dispose};
}
