import {ParticipantJournal} from './participant-journal';
import {playerRestRows} from './player-rest-presenter';
import {moveMapPin,campaignMapWorldBounds} from './campaign-map';
import {combatReadout} from './core/combat-resources';
import type {PreparedArchiveCleanup} from '../save/checkpoint';
import type {ArchiveCleanupInfo} from './archive-cleanup-view';
import {gamepadButtonLabel} from './gamepad-settings';
import {startGameLoop,gameLoopPolicy} from './game-loop';
import {defaultGamepadSettings} from './gamepad-settings';
import {inputObservation} from './input-observation';

import {CAMPAIGN_ITEMS} from './core/campaign';
import {exportCampaignFile,readCampaignImportFile,commitPreparedCampaignImport,type PreparedCampaignImport} from '../save/campaign-file-transfer';
import {regionAt} from './core/regions';
import { CoreSimulation } from './core/simulation';
import { createView } from './rendering/scene';
import { createInput } from './input';
import { createAudio,DEFAULT_AUDIO_MIX } from './audio';
import { materialDefinition } from './core/materials';
import { key } from './core/voxel';
import { materialColors } from './rendering/element-effects';
import {createCampaignUI,type CampaignCommand,type CampaignTab} from './campaign-ui';
import {captureCampaign,defaultSettings,restoreCampaignInto,getCampaignRestoreFailure,browserCampaignStorage,type CampaignSettings} from './campaign-session';
import {planCampaignStartup,readHostResumeIdentity,selectCampaignStartupStore} from '../save/campaign-startup';
import {bootstrapCampaignWorld} from './core/world-bootstrap';
import {CampaignRoomSession} from './network/game-session';
import {createCoopAvatar} from './rendering/coop-avatar';
import {executeGameCommand,isGameCommand} from './campaign-commands';
import {campaignSnapshot} from './campaign-presenter';
import './style.css';
export function startPrototype(){
 const canvas=document.querySelector<HTMLCanvasElement>('#game')!,audio=createAudio(),$=(id:string)=>document.getElementById(id)!;
 const startup=planCampaignStartup(location.search,location.hash,new URLSearchParams(location.search).has('trial')?null:readHostResumeIdentity(location.hash,()=>sessionStorage)),trial=startup.trial,guestPreview=startup.guestPreview;
 const selection=selectCampaignStartupStore(startup,browserCampaignStorage);
 const {store,loaded}=selection,streamed=!trial&&selection.streamed,western=!trial&&selection.western;
 const pendingSave=!trial&&!selection.blocked&&(loaded.status==='loaded'||loaded.status==='recovered')?loaded.data:null;
 const sim=new CoreSimulation(!trial,!trial&&!streamed,streamed,western),settings:CampaignSettings=pendingSave?JSON.parse(JSON.stringify(pendingSave.settings)):defaultSettings();let loadFailed=selection.blocked||!trial&&!guestPreview&&['invalid','unsupported','unavailable'].includes(loaded.status),savingAllowed=!trial&&!guestPreview&&!selection.blocked&&loaded.status==='empty',hasSave=!!pendingSave,saveStatus=trial?'試練モード（保存なし）':guestPreview?'招待を確認中。自分の保存は読み書きしません':selection.error??(pendingSave?'保存した世界を展開中…':streamed?'オンデマンド地形の旅を準備しました':'周辺地域を準備中。拠点から遊び始められます'),saveTimer=0;
 if(!pendingSave&&matchMedia('(prefers-reduced-motion: reduce)').matches)settings.reducedMotion=true;
 for(const [action,key] of Object.entries(settings.bindings))if(key==='KeyZ')delete settings.bindings[action];
 let room:CampaignRoomSession|null=null,guestSessionUsed=guestPreview,awaitingGuestRespawn=false;let roomProbeRaf=0,roomProbeTimer:ReturnType<typeof setTimeout>|undefined;
 let archiveCache:ReturnType<typeof store.listArchives>|null=null,archiveViewOpen=false,archiveDirty=true,pinSequence=0;let importCandidate:{prepared:PreparedCampaignImport;name:string;savedAt:number;sizeBytes:number}|null=null,fileBusy=false,fileGeneration=0;const downloadURLs=new Set<string>();let cleanupCandidate:{prepared:PreparedArchiveCleanup;info:ArchiveCleanupInfo}|null=null,cleanupRequest=0;
 function refreshArchives(){archiveCache=trial||guestSessionUsed||room?.role==='guest'?null:store.listArchives();archiveDirty=false;}
 function cancelFileImport(){cancelCleanup();fileGeneration++;importCandidate=null;fileBusy=false;}
 function cancelCleanup(){if(cleanupCandidate)store.cancelArchiveCleanup(cleanupCandidate.prepared);cleanupCandidate=null;}
 function canCleanup(){return !trial&&!guestSessionUsed&&!room?.role&&!selection.blocked&&!loadFailed&&sim.worldReady;}
 function canImportFile(){return !trial&&!guestSessionUsed&&!room?.role&&!selection.blocked&&!loadFailed&&sim.worldReady;}
 async function prepareFileImport(file:File){if(!canImportFile()){campaignUI.notify('単独プレイの有効な世界で保存ファイルを選んでください');return;}cancelCleanup();const generation=++fileGeneration;importCandidate=null;fileBusy=true;campaignUI.notify('保存ファイルの地形・所持品・進行を検証中…');updateUI(performance.now());await new Promise(resolve=>setTimeout(resolve,0));const checked=await readCampaignImportFile(store,file);if(disposed||generation!==fileGeneration)return;fileBusy=false;if(checked.ok)importCandidate={prepared:checked.prepared,name:file.name.slice(0,120),savedAt:checked.savedAt,sizeBytes:checked.sizeBytes};updateUI(performance.now());campaignUI.notify(checked.ok?'検証しました。まだ保存は変更していません。内容を確認して取り込んでください':checked.error);}
 async function exportFile(id?:string,cleanup=false){
  if(fileBusy)return;if(trial||guestSessionUsed||room?.role==='guest'||cleanup&&!canCleanup()){campaignUI.notify('自分の単独プレイの旅へ戻ってから操作してください');return;}
  cancelFileImport();const generation=++fileGeneration;fileBusy=true;campaignUI.notify('保存ファイルを検証して準備中…');updateUI(performance.now());await new Promise(resolve=>setTimeout(resolve,0));
  const result=exportCampaignFile(store,id);if(disposed||generation!==fileGeneration)return;fileBusy=false;
  if(!result.ok){updateUI(performance.now());campaignUI.notify(result.error);return;}
  const preparation=cleanup&&id!==undefined?store.prepareArchiveCleanup(id):null;
  if(preparation&&(!preparation.ok||preparation.raw!==result.raw)){updateUI(performance.now());campaignUI.notify(preparation.ok?'確認中に履歴が更新されました。選び直してください':preparation.error);return;}
  try{const url=URL.createObjectURL(new Blob([result.raw],{type:'application/json'})),link=document.createElement('a');downloadURLs.add(url);link.href=url;link.download=result.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>{URL.revokeObjectURL(url);downloadURLs.delete(url);},30000);
   if(preparation?.ok)cleanupCandidate={prepared:preparation.prepared,info:{request:++cleanupRequest,entry:preparation.entry,filename:result.filename}};
   updateUI(performance.now());campaignUI.notify('ダウンロードを開始しました。端末の保存先とファイルを確認してください');
  }catch{if(preparation?.ok)store.cancelArchiveCleanup(preparation.prepared);updateUI(performance.now());campaignUI.notify('ダウンロードを開始できませんでした。履歴は変更していません');}
 }
  function save(){if(guestSessionUsed||room?.role==='guest'){saveStatus='同行中は自分の単独プレイ保存を変更しません';return false;}if(!sim.worldReady){saveStatus='周辺地域を準備中。完了後に変更を保存します';return false;}if(!savingAllowed){saveStatus='元の保存を保護しています。保存の再開か新規開始を選んでください';return false;}const result=store.write(captureCampaign(sim,settings));saveStatus=result.ok?'保存済み '+new Date().toLocaleTimeString():result.error;hasSave ||=result.ok;archiveDirty ||=result.ok;return result.ok;}

 let needsRender=true,active=false,paused=true,disposed=false,accumulator=0,uiTimer=0,messageUntil=0,hitUntil=0,hurtUntil=0,debug=false,timeScale=1,restRenderTimer=0;
 const elementNames={fire:'火',water:'水',earth:'土',wind:'風',lightning:'雷'},elementColors={fire:'#ffac6c',water:'#8bd4ff',earth:'#dfbd85',wind:'#b7edc5',lightning:'#d6b7ff'};
 const materialNames:Record<number,string>={1:'地面',2:'土',3:'石',4:'木材',5:'木材',6:'金属',7:'草',8:'碑石',9:'灯火',10:'布'};
 const inventoryNodes=[4,3,2,6,7,10].map(id=>{const node=document.createElement('span');node.style.color=materialColors[id];$('inventory').append(node);return {id,node};});
 const dropCountNode=document.createElement('span');dropCountNode.id='drop-count';$('inventory').append(dropCountNode);
 const view=createView(canvas,sim);const qualityLabels={balanced:'標準',performance:'省電力',high:'高品質'};const applyGraphics=(quality:CampaignSettings['graphics'])=>{settings.graphics=quality;view.setGraphics(quality);needsRender=true;$('quality-toggle').textContent='画質：'+qualityLabels[quality];$('quality-toggle').title=quality==='performance'?'低解像度・動的影なし・簡略化した空。地形・戦闘・ゲーム速度は同じ。'+(view.stats().softwareRendering?' ソフトウェアGPUを検出。':''):'描画品質を切り替えます';};applyGraphics(settings.graphics);audio.setVolume(settings.volume);audio.setMix(settings.audioMix??DEFAULT_AUDIO_MIX);const applyCamera=()=>{view.setCamera(settings.cameraMode??'first',settings.cameraDistance??3);needsRender=true;};const applyAccessibility=()=>{view.setReducedMotion(!!settings.reducedMotion);document.body.classList.toggle('reduced-motion',!!settings.reducedMotion);document.documentElement.style.setProperty('--read-scale',String(settings.textScale??1));needsRender=true;};applyCamera();applyAccessibility();const portrait=()=>innerHeight>innerWidth;
 function pause(){if(sim.bedWait.active){sim.bedWait.cancel();save();}if(paused)return;save();paused=true;input.setEnabled(false);$('menu').hidden=false;$('menu-title').textContent='一息つく';$('start').textContent='再開';updateUI(performance.now());if(document.pointerLockElement)document.exitPointerLock();}
 const performAction=(a:import('./core/simulation').Action)=>{if(!room?.action(a))sim.action(a,input.controls());};
 const input=createInput(canvas,performAction,(x,y)=>sim.look(x,y),pause);document.body.classList.toggle('touch',input.mobile);input.setSensitivity(settings.sensitivity);input.setGamepadSettings(settings.gamepad??defaultGamepadSettings());for(const [action,key] of Object.entries(settings.bindings))input.bind(action,key);
 const campaignUI=createCampaignUI(command);if(trial){$('campaign-toggle').hidden=true;$('campaign-status').hidden=true;}
 const coopAvatar=createCoopAvatar(view.scene,()=>sim.campaign.armorMaterial,()=>sim.campaign.state.equipment);if(!trial){room=new CampaignRoomSession(sim,{guestPreview,settings:()=>settings,save,mode:role=>{if(role==='guest')guestSessionUsed=true;input.reset();},notice:message=>{campaignUI.notify(message);$('message').textContent=message;messageUntil=performance.now()+3500;}});}
 const participantJournal=new ParticipantJournal(()=>localStorage);
 function command(cmd:CampaignCommand){
 if(cmd.type==='homestead'&&cmd.id.startsWith('player-rest:')){const target=cmd.id.slice(12);const r=target==='cancel'?sim.bedWait.cancel():target==='dawn'||target==='dusk'?sim.startPlayerRest(target,!!room?.role||guestPreview):{ok:false,message:'休息時刻が不正です。'};if(r.ok){input.reset();save();}campaignUI.notify(r.message);needsRender=true;updateUI(performance.now());return;}
 if(sim.bedWait.active){sim.bedWait.cancel();save();}
 let result:{ok:boolean;message:string;heal?:number;position?:{x:number;y:number;z:number}}|undefined;
 if(cmd.type==='story-read'){const detail=participantJournal.read(cmd.id);if(detail)campaignUI.notify(detail);updateUI(performance.now());return;}
 if(cmd.type==='open'){pause();return;}if(cmd.type==='close'){cancelFileImport();if(!paused)pause();return;}if(cmd.type==='resume'){cancelFileImport();campaignUI.close();void begin();return;}
 if(cmd.type==='cancel-cleanup'){cancelFileImport();updateUI(performance.now());return;}
 if(cmd.type==='prepare-cleanup'){void exportFile(cmd.id,true);return;}
 if(cmd.type==='confirm-cleanup'){if(!canCleanup()||!cleanupCandidate||fileBusy){cancelFileImport();campaignUI.notify('単独プレイで履歴整理を選び直してください');return;}const prepared=cleanupCandidate.prepared;cleanupCandidate=null;const cleaned=store.commitArchiveCleanup(prepared);archiveDirty=true;updateUI(performance.now());campaignUI.notify(cleaned.ok?'選んだ履歴を完全に削除しました。書き出したJSONを保管してください':cleaned.error);return;}
 if(cmd.type==='recover-cleanup'){if(!canCleanup()||fileBusy)return;cancelFileImport();const recovered=store.recoverArchiveCleanup();archiveDirty=true;updateUI(performance.now());campaignUI.notify(recovered.ok?'整理状態を確認しました。未削除の履歴は一覧に戻し、削除済みの履歴は端末のJSONから取り込めます':recovered.error);return;}
 if(cmd.type==='cancel-import'){cancelFileImport();updateUI(performance.now());return;}
 if(cmd.type==='prepare-import'){void prepareFileImport(cmd.file);return;}
 if(cmd.type==='export-file'){void exportFile(cmd.id);return;}
 if(cmd.type==='confirm-import'){if(!canImportFile()||!importCandidate||fileBusy){campaignUI.notify('単独プレイで取り込み候補を選び直してください');return;}const prepared=importCandidate.prepared;cancelFileImport();fileBusy=true;const result=commitPreparedCampaignImport(store,prepared);fileBusy=false;archiveDirty=true;if(!result.ok){updateUI(performance.now());campaignUI.notify(result.error);return;}savingAllowed=false;location.reload();return;}
 if(cmd.type==='coop'){cancelFileImport();void room?.command(cmd.id,cmd.text);updateUI(performance.now());return;}
 if((guestSessionUsed||room?.role==='guest')&&['save','continue','new-game','restore-archive','expand-world','cancel-expansion'].includes(cmd.type)){campaignUI.notify('保存管理は退出して自分の旅へ戻ってから行ってください');return;}
 if(['new-game','restore-archive','continue','expand-world'].includes(cmd.type))cancelFileImport();
 if(guestPreview&&!room?.online&&isGameCommand(cmd)){campaignUI.notify('招待先へ参加してから操作してください');return;}
 if(cmd.type==='expand-world'){if(western||room?.role||!savingAllowed||!sim.worldReady){campaignUI.notify('単独プレイで有効な保存を準備してから追加してください');return;}if(!save()){campaignUI.notify(saveStatus);return;}savingAllowed=false;const url=new URL(location.href);url.hash='';url.searchParams.set('expedition','west');url.searchParams.set('streaming','1');location.assign(url.href);return;}
 if(cmd.type==='cancel-expansion'){if(!startup.western||!selection.blocked||room?.role)return;savingAllowed=false;const url=new URL(location.href);url.searchParams.delete('expedition');url.searchParams.delete('streaming');location.assign(url.href);return;}
 if(room?.role&&['new-game','restore-archive'].includes(cmd.type)){campaignUI.notify('共有中の世界を切り替える前に協力プレイから退出してください');return;}
 if(cmd.type==='restore-archive'){if(selection.blocked||loaded.status==='unsupported'){campaignUI.notify('この保存形式では履歴を復元できません。原本を保護しています');return;}const restored=store.restore(cmd.id);archiveDirty=true;if(!restored.ok){campaignUI.notify(restored.error);return;}savingAllowed=false;location.reload();return;}
 if(isGameCommand(cmd)){if(room?.gameCommand(cmd)){updateUI(performance.now());return;}result=executeGameCommand(sim,cmd);}
 if(cmd.type==='save')result={ok:save(),message:saveStatus};if(cmd.type==='continue'){if(selection.blocked){campaignUI.notify(selection.error??'保存形式を確認できません。原本を保護しています');return;}if(loaded.status==='recovered'){const recovery=store.recoverBackup();if(!recovery.ok){campaignUI.notify(recovery.error);return;}}savingAllowed=false;location.reload();return;}
 if(cmd.type==='new-game'){if(selection.blocked||loaded.status==='unsupported'){campaignUI.notify(selection.error??'保存形式を確認できないため、新規開始を中止しました');return;}const reset=store.reset();archiveDirty=true;if(!reset.ok){campaignUI.notify(reset.error);return;}savingAllowed=false;location.reload();return;}
 if(cmd.type==='setting'){if(cmd.key==='reducedMotion'&&(cmd.value===0||cmd.value===1)){settings.reducedMotion=cmd.value===1;applyAccessibility();}if(cmd.key==='textScale'&&typeof cmd.value==='number'&&Number.isFinite(cmd.value)){settings.textScale=Math.max(1,Math.min(1.25,cmd.value));applyAccessibility();}if(cmd.key==='cameraMode'&&(cmd.value==='first'||cmd.value==='third')){settings.cameraMode=cmd.value;applyCamera();}if(cmd.key==='cameraDistance'&&typeof cmd.value==='number'&&Number.isFinite(cmd.value)){settings.cameraDistance=Math.max(1.4,Math.min(4,cmd.value));applyCamera();}if(['music','effects','ambience'].includes(cmd.key)&&typeof cmd.value==='number'&&Number.isFinite(cmd.value)){settings.audioMix??={...DEFAULT_AUDIO_MIX};settings.audioMix[cmd.key as 'music'|'effects'|'ambience']=Math.max(0,Math.min(1,cmd.value));audio.setMix(settings.audioMix);}if(cmd.key==='volume'&&typeof cmd.value==='number'){settings.volume=cmd.value;audio.setVolume(cmd.value);}if(cmd.key==='sensitivity'&&typeof cmd.value==='number'){settings.sensitivity=cmd.value;input.setSensitivity(cmd.value);}if(cmd.key==='graphics'&&(cmd.value==='balanced'||cmd.value==='performance'||cmd.value==='high')){applyGraphics(cmd.value);}}
 if(cmd.type==='gamepad-setting'){const ok=input.setGamepadSettings(cmd.value);if(ok)settings.gamepad=input.gamepadSettings();result={ok,message:ok?'コントローラー設定を変更。ボタンとスティックを一度離してください':'コントローラー設定が不正です'};}
 if(cmd.type==='binding'){const ok=input.bind(cmd.action,cmd.key);if(ok)settings.bindings[cmd.action]=cmd.key;result={ok,message:ok?'割り当てを変更':'移動・メニュー用キーまたは重複キーは使えません'};}if(cmd.type==='reset-bindings'){input.resetBindings();settings.bindings={};}
 if(cmd.type==='move-pin')result=moveMapPin(settings.pins,cmd.id,{x:cmd.x,z:cmd.z},campaignMapWorldBounds(western))?{ok:true,message:'同じピンを選んだ位置へ移動した'}:{ok:false,message:'既存のピンと地図の範囲を確認してください'};
 if(cmd.type==='pin'){if(!Number.isFinite(cmd.x)||!Number.isFinite(cmd.z)||cmd.x<(western?-128:-80)||cmd.x>(western?128:80)||cmd.z<(western?-160:-100)||cmd.z>(western?100:30)){campaignUI.notify('地図の範囲内を選んでください');return;}if(settings.pins.length>=12)settings.pins.shift();settings.pins.push({id:'pin:'+Date.now()+':'+(++pinSequence),x:cmd.x,z:cmd.z});result={ok:true,message:'地図にピンを置いた'};}if(cmd.type==='remove-pin')settings.pins=settings.pins.filter(p=>p.id!==cmd.id);
 if(result){campaignUI.notify(result.message);audio.play(result.ok?'interact':'parry');if(result.ok)save();}updateUI(performance.now());
 }
 function resize(){input.reset();$('rotate').hidden=!portrait();if(portrait())pause();view.resize();needsRender=true;updateUI(performance.now());}
 async function begin(){if(guestPreview&&!room?.role){campaignUI.open('cooperation');return;}if(portrait()||loadFailed||pendingSave&&!sim.worldReady||room?.role==='guest'&&!room.online)return;active=true;paused=false;input.setEnabled(true);$('menu').hidden=true;audio.start();updateUI(performance.now());
  if(input.mobile){try{await document.documentElement.requestFullscreen();const orientation=screen.orientation as ScreenOrientation&{lock?:(value:string)=>Promise<void>};await orientation.lock?.('landscape');}catch{}}
  else await input.lock();
 }
 $('quality-toggle').addEventListener('click',()=>{const order:CampaignSettings['graphics'][]=['balanced','performance','high'];applyGraphics(order[(order.indexOf(settings.graphics)+1)%order.length]);if(!trial)save();updateUI(performance.now());});
 $('start').addEventListener('click',()=>void begin());$('menu-toggle').addEventListener('click',pause);$('restart').addEventListener('click',()=>campaignUI.open('settings'));$('retry').addEventListener('click',()=>{if(room?.respawn()){awaitingGuestRespawn=true;($('retry') as HTMLButtonElement).disabled=true;return;}sim.respawn();save();$('death').hidden=true;void begin();});$('day-toggle').textContent=trial?'昼 / 夜':'寝台で休息';$('day-toggle').addEventListener('click',()=>{if(trial)view.toggleDay();else campaignUI.open('homestead');needsRender=true;});
 const toggleMotion=()=>{timeScale=timeScale===1?.25:1;$('motion-toggle').textContent='動作：'+(timeScale===1?'通常':'1/4');};$('motion-toggle').addEventListener('click',toggleMotion);
 $('tool-switch').addEventListener('click',()=>{if(!paused)performAction('tool');});$('heal').addEventListener('click',()=>{if(!paused)performAction('heal');});
 document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;const tab:CampaignTab|undefined=({KeyI:'inventory',KeyJ:'journal',KeyM:'map',Tab:'inventory'} as Record<string,CampaignTab>)[e.code];if(tab&&!campaignUI.isOpen){e.preventDefault();campaignUI.open(tab);return;}if(e.code==='F4'){e.preventDefault();toggleMotion();}if(e.code==='F3'){e.preventDefault();debug=!debug;$('diagnostics').hidden=!debug;}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',resize);resize();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('error').hidden=false;$('error').textContent='描画が停止しました。再読み込みしてください。';});
 function updateUI(now:number){
  document.body.classList.toggle('campaign-mode',!trial);document.body.classList.toggle('building-mode',!trial&&(sim.buildMode||sim.soilFilling));document.body.classList.toggle('soil-fill-mode',sim.soilFilling);document.body.classList.toggle('focus-ready',!trial&&sim.focus.value>=100);
  const settingsOpen=campaignUI.isOpen&&campaignUI.currentTab==='settings';if(settingsOpen&&(!archiveViewOpen||archiveDirty))refreshArchives();archiveViewOpen=settingsOpen;
  ($('start') as HTMLButtonElement).disabled=loadFailed||!!pendingSave&&!sim.worldReady||room?.role==='guest'&&!room.online;if(guestPreview)$('start').textContent=!room?.role?'招待先を確認':room.online?'共有の旅へ':'同期準備中';const p=sim.player,target=sim.target(sim.campaign.canGrapple?7:2.75);const ui=campaignSnapshot(sim,settings,{archiveProtection:archiveCache?.ok?archiveCache.cleanupProtection:undefined,canCleanup:canCleanup()&&archiveCache?.ok===true,cleanupInfo:cleanupCandidate?.info,cleanupPending:archiveCache?.ok?archiveCache.cleanupPending:undefined,canImport:canImportFile(),canExport:!trial&&!guestSessionUsed&&room?.role!=='guest'&&hasSave,fileBusy,importInfo:importCandidate?{name:importCandidate.name,savedAt:importCandidate.savedAt,sizeBytes:importCandidate.sizeBytes}:undefined,canExpand:!western&&!room?.role&&!guestSessionUsed&&savingAllowed&&sim.worldReady,expanded:western&&!selection.blocked,expansionBlocked:startup.western&&selection.blocked&&!guestSessionUsed,available:hasSave,switchBlocked:!!room?.role,disabledForGuest:guestSessionUsed||room?.role==='guest',archives:archiveCache?.ok?archiveCache.entries:[],archiveError:archiveCache&&!archiveCache.ok?archiveCache.error:undefined,archiveScope:western?'西方遠征':streamed?'オンデマンド地形の旅':'基本の旅',label:guestSessionUsed?'同行中は自分の単独プレイ保存を保護しています':'このブラウザの単独プレイ。新規開始は元の保存をバックアップします。',status:saveStatus},input.bindings(),campaignUI.isOpen&&campaignUI.currentTab==='crafting');if(room){ui.cooperation=room.snapshot();if(room.journalScope&&room.online){participantJournal.update(room.journalScope,ui.quests,{position:sim.player.position,alive:sim.player.hp>0,hearth:sim.campaign.state.flameTier>0,artisan:sim.campaign.state.artisanRescued?sim.npc.position:null});ui.personalQuests=participantJournal.rows();}}if(!trial)ui.homestead=[...playerRestRows(sim,!!room?.role||guestPreview),...(ui.homestead??[])];campaignUI.update(ui);
  for(const {id,node} of inventoryNodes)node.textContent=materialNames[id]+' '+(sim.survival.inventory[id]??0);
  dropCountNode.textContent='未回収 '+[...sim.survival.drops,...sim.survival.pendingDrops].reduce((sum,d)=>sum+d.count,0);
  const element=sim.selectedElement,recipe=sim.survival.recipe,prefix=input.mobile?'':'F ';
  $('element-switch').textContent=sim.buildMode?(input.mobile?'回転':'F 回転')+' '+sim.survival.rotation*90+'°':prefix+elementNames[element]+' ▸';$('element-switch').style.setProperty('--element-color',elementColors[element]);
  $('cast').textContent=(input.mobile?'':'G ')+(sim.buildMode?'建築終了':sim.combat.pending?'詠唱中':'放つ');$('dismantle').hidden=!sim.buildMode;$('special').textContent=(input.mobile?'':'X ')+(sim.buildMode?'戻す':'集中 '+Math.floor(sim.focus.value));($('special') as HTMLButtonElement).disabled=paused||p.phase!=='idle'||!sim.buildMode&&sim.focus.value<100;$('recipe-switch').textContent=(input.mobile?'':'V ')+recipe.label+' ▸';$('build').textContent=(input.mobile?'':'B ')+(sim.buildMode?'置く':'建築');
  $('build-snap').hidden=!sim.buildMode;$('build-snap').textContent=(input.mobile?'':'N ')+(sim.buildSnap?'吸着 1.5m':'自由配置');$('build-snap').setAttribute('aria-pressed',String(sim.buildSnap));
  $('recipe-cost').textContent='木材 '+recipe.cost+' / '+(sim.survival.inventory[4]??0)+(recipe.id==='workbench'?' · 地面を狙って設置':' · 作業台の3m以内')+' · 素材は近づいて回収';
  if(sim.rakeSelected&&!sim.buildMode){$('element-switch').textContent=prefix+(sim.soilFilling?'盛土 ▸':'削る ▸');$('element-switch').setAttribute('aria-label','熊手の削る・盛土を切替（'+gamepadButtonLabel(input.gamepadSettings().buttons['element-next'])+'）');}else $('element-switch').removeAttribute('aria-label');
  if(sim.soilFilling){$('cast').textContent=(input.mobile?'':'G ')+'盛土終了';$('dismantle').hidden=false;$('dismantle').textContent='盛土撤去';$('special').textContent=(input.mobile?'':'X ')+'戻す';($('special') as HTMLButtonElement).disabled=paused||p.phase!=='idle';$('build').textContent=(input.mobile?'':'B ')+'盛土';$('recipe-cost').textContent='盛土 · 土9 / 所持'+sim.survival.inventory[2]+' · 無傷の撤去のみ返却';}else $('dismantle').textContent='解体';
  for(const id of ['element-switch','cast','recipe-switch','build','dismantle','build-snap'])($(id) as HTMLButtonElement).disabled=paused||p.hp<=0||(id==='cast'||id==='build'||id==='dismantle')&&p.phase!=='idle';
  const cell=target?.animal||target?.npc||target?.inventoryDrop?null:target?.hit.cell??null,reactions=target?.enemy?sim.enemyElements[target.enemy.id].reactions:sim.elements,state=cell?reactions.states.get(key(cell.x,cell.y,cell.z)):undefined;
  $('material-status').textContent=cell?(materialNames[cell.material]??materialDefinition(cell.material).name)+' · 耐久 '+Math.ceil(reactions.durability(cell))+'/'+materialDefinition(cell.material).durability+(state?.fire?' · 燃焼':'')+(state?.wet?' · 濡れ':'')+(state?.charge?' · 帯電':'')+(cell.object&&sim.elements.protectedObjects.has(cell.object)?' · 重要対象を保護':''):'';
$('combat-status').textContent=combatReadout(sim.combat,sim.focusUnlocked&&sim.focusWeaponSupported);$('combat-status').setAttribute('aria-label',$('combat-status').textContent!);
$('hp-fill').style.width=p.hp/sim.campaign.maxHp*100+'%';$('stamina-fill').style.width=p.stamina/sim.campaign.maxStamina*100+'%';$('hp-value').textContent=String(Math.ceil(p.hp));$('stamina-value').textContent=String(Math.ceil(p.stamina));$('target').textContent=target?.label??'';$('prompt').textContent=target?.action??'';
  const interact=document.querySelector<HTMLButtonElement>('[data-action="interact"]')!;interact.hidden=!target?.action.startsWith('E /');interact.disabled=p.phase!=='idle';interact.textContent=target?.action.replace('E / 操作 · ','')??'操作';if(target?.action.startsWith('E /'))$('prompt').textContent=p.phase!=='idle'?'硬直中':input.mobile?target.action.replace('E / 操作 · ',''):target.action;$('enemy-health').hidden=!target?.enemy;if(target?.enemy)$('enemy-fill').style.width=target.enemy.hp/(target.enemy.maxHp??100)*100+'%';
  if(sim.soilFilling){const preview=sim.soilPreview();$('target').textContent='熊手 · 盛土（土9）';$('prompt').textContent=preview?.message??'3m以内の地面を狙う';$('prompt').setAttribute('aria-live','polite');}else $('prompt').removeAttribute('aria-live');
  if(sim.ladders.active(p)){$('target').textContent='木の梯子';$('prompt').textContent='前後で昇降 · 左右/E/跳躍で離す';interact.hidden=false;interact.disabled=false;interact.textContent='梯子から離す';$('enemy-health').hidden=true;}
  if(sim.campaignMode&&sim.fishing.selected){const status=sim.fishing.status,guest=room?.role==='guest';$('target').textContent='葦糸の釣竿';$('prompt').textContent=guest?'釣りはホストが操作中':status.message+' · E / 操作';interact.hidden=false;interact.disabled=guest||p.phase!=='idle';interact.textContent=status.phase==='idle'?'浮きを投げる':status.phase==='bite'?'巻き上げる':'巻き上げて中断';$('enemy-health').hidden=true;}
  $('tool-switch').textContent=p.tool?'2 '+(sim.activeTool?CAMPAIGN_ITEMS[sim.activeTool].label:'鑿'):'1 '+(sim.campaign.equippedWeapon?CAMPAIGN_ITEMS[sim.campaign.equippedWeapon].label:'剣');$('tool-switch').setAttribute('aria-label','武器と道具の切替');const hammer=p.tool&&sim.activeTool==='build-hammer';document.querySelector<HTMLButtonElement>('[data-action=attack]')!.textContent=sim.soilFilling?'盛土':hammer?'設置':sim.rakeSelected?'削る':'斬撃';document.querySelector<HTMLButtonElement>('[data-action=heavy]')!.textContent=sim.soilFilling?'盛土撤去':hammer?'解体':'溜め強撃';document.querySelector<HTMLButtonElement>('[data-action=block]')!.disabled=!sim.campaign.canGuard||p.tool;$('heal').textContent=p.phase==='heal'?'服薬中…':'Q 回復 ×'+p.flasks;($('heal') as HTMLButtonElement).disabled=p.phase!=='idle'||!p.flasks||p.hp>=sim.campaign.maxHp;$('objective').textContent=sim.campaign.objective().label+' · '+sim.campaign.objective().detail;$('reticle').classList.toggle('hit',now<hitUntil);$('hurt').style.opacity=now<hurtUntil&&!settings.reducedMotion?'1':'0';if(now>messageUntil)$('message').textContent='';
  if(awaitingGuestRespawn&&(p.hp>0||!room?.online)){awaitingGuestRespawn=false;($('retry') as HTMLButtonElement).disabled=false;if(p.hp>0){$('death').hidden=true;void begin();}}
  if(p.hp<=0){if(room?.role!=='guest'&&!sim.campaign.state.deathPending){sim.campaign.die(sim.safePosition(p.position));save();}$('death').hidden=false;$('death').querySelector('p')!.textContent=room?.role==='guest'?'同行者が倒れた。共有拠点で復活できます':(sim.deathCause||'戦闘で倒れた')+' · 素材25%を残し、装備と重要品は保持。安全な拠点で復活します。';input.setEnabled(false);paused=true;}
  if(debug)$('diagnostics').textContent=JSON.stringify({waterCell:.125,waterM3:sim.water.total().toFixed(3),solidVoxels:sim.arena.field.cells.size,...view.stats()},null,2);
  canvas.dataset.ready='true';canvas.dataset.running=String(active&&!paused&&!portrait());canvas.dataset.target=target?.hit.cell.object??'';
 }
 // High-frequency input observations must not raycast terrain or clone saves.
 if(new URLSearchParams(location.search).has('test'))Object.defineProperty(window,'__inputProbe',{configurable:true,get:()=>({...inputObservation(sim),controls:input.controls(),running:active&&!paused&&!portrait()&&!document.hidden,paused,documentHidden:document.hidden,hasFocus:document.hasFocus(),loop:loop?.stats,cooperation:room?.diagnostics()??null})});
 if(new URLSearchParams(location.search).has('test'))Object.defineProperty(window,'__coreProbe',{configurable:true,get:()=>({position:{...sim.player.position},hp:sim.player.hp,stamina:sim.player.stamina,combat:structuredClone(sim.combat),phase:sim.player.phase,phaseTime:sim.player.time,attack:sim.player.attack,weapon:sim.pose(),timeScale,enemies:sim.enemies.map(e=>({position:{...e.position},phase:e.phase,time:e.time,hp:e.hp,awareness:sim.enemyAwareness(e),burning:sim.enemyElements[e.id].burning,wet:sim.enemyElements[e.id].wet,shock:sim.enemyElements[e.id].shock,voxelRevision:sim.enemyElements[e.id].field.revision,scars:sim.enemyElements[e.id].scars.length})),seconds:sim.seconds,watermill:{...sim.watermill.snapshot(),flow:sim.watermill.flow,blockedReason:sim.watermill.blockedReason},waterOn:sim.waterOn,yaw:sim.player.yaw,pitch:sim.player.pitch,door:sim.arena.objects.get('door')?.open,tool:sim.player.tool,selectedElement:sim.selectedElement,selectedRecipe:sim.selectedRecipe,soilFill:sim.soilFilling,soil:sim.survival.soil.snapshot(),inventory:{...sim.survival.inventory},drops:sim.survival.drops.map(d=>({...d,position:{...d.position}})),elementStates:sim.elements.states.size,burning:[...sim.elements.states.values()].filter(s=>s.fire>0).length,wet:[...sim.elements.states.values()].filter(s=>s.wet>0).length,charged:[...sim.elements.states.values()].filter(s=>s.charge>0).length,elementEffects:sim.elements.effects.length,water:sim.water.total(),target:sim.target()?.hit.cell.object,campaign:sim.campaign.snapshot(),home:sim.home.snapshot(),display:sim.display.snapshot(),saveStatus,guestPreview,settings:{...settings},focus:sim.focus.value,oxygen:sim.oxygen,cold:sim.cold,worldHour:sim.worldHour,bedWait:sim.bedWait.snapshot(),weather:sim.weather,weatherRoofRays:sim.weatherReactions.lastRayCount,projectiles:sim.enemyShots.length,tells:sim.tells.length,climbing:sim.ladders.active(sim.player),gliding:sim.gliding,grapple:sim.grapple,worldReady:sim.worldReady,streamedWorld:sim.streamedWorld,westernContent:sim.westernContent,western:sim.western?.snapshot()??null,dungeon:sim.dungeon.snapshot(),dungeonCrustMined:sim.dungeon.crustMined(),dungeonTrapPhase:sim.dungeon.trapPhase(sim.seconds),fishing:sim.fishing.snapshot(),animal:structuredClone(sim.animal.state),npcLife:sim.npc.snapshot(),westernNpcLife:sim.western?sim.westNpcs.snapshot():null,environment:{...sim.environment},worldSamples:[{x:-1.7,y:.58,z:6.25},{x:-1.7,y:.58,z:6.95},{x:-4.2,y:.55,z:6.8}].map(point=>sim.arena.field.distance(point)),worldRevision:sim.arena.field.revision,restoreFailure:getCampaignRestoreFailure(sim),cooperation:room?{online:room.online,...room.snapshot(),companion:sim.companion?{position:{...sim.companion.position},hp:sim.companion.hp,phase:sim.companion.phase}:null}:null,stats:{...view.stats(),loop:loop?.stats}})});
 function loopPolicy(){return gameLoopPolicy({active,paused,portrait:portrait(),hidden:document.hidden,guest:room?.role==='guest',hostRunning:!!room?.hostRunning,needsRender});}
 function update(dt:number,now:number){if(disposed)return;const policy=loopPolicy();
  if(sim.bedWait.active){accumulator=0;if(document.hidden||portrait()){sim.bedWait.cancel();save();}else{const deadline=performance.now()+6,result=sim.advancePlayerRest(!!room?.role||guestPreview,()=>performance.now()>=deadline);restRenderTimer+=dt;if(restRenderTimer>=.5){needsRender=true;restRenderTimer=0;}if(result.ended){needsRender=true;save();campaignUI.notify(result.message??'休息を終えました。');updateUI(now);}}}
  else if(policy.simulate){accumulator+=dt*timeScale;let steps=0;while(accumulator>=1/60&&steps++<6){sim.tick(1/60,paused?{x:0,z:0,sprint:false,block:false,water:false}:input.controls());accumulator-=1/60;}}else accumulator=0;room?.tick(dt,input.controls(),policy.inputActive);coopAvatar.set(room?.remoteActor??null);coopAvatar.update(dt);
  audio.update({seconds:sim.seconds,weather:sim.weather,sheltered:view.sheltered,region:regionAt(sim.player.position)?.id??null,active:active&&!paused&&!portrait()&&!document.hidden,danger:sim.enemies.some(e=>e.hp>0&&sim.enemyActive(e)&&['chase','alert'].includes(sim.enemyAwareness(e))&&Math.hypot(e.position.x-sim.player.position.x,e.position.z-sim.player.position.z)<7)});
  for(const e of sim.events.splice(0)){audio.play(e.kind,e.position?Math.hypot(e.position.x-sim.player.position.x,e.position.y-sim.player.position.y,e.position.z-sim.player.position.z):0);if(e.text){$('message').textContent=e.text;messageUntil=now+1800;}if(e.kind==='hit'||e.kind==='parry')hitUntil=now+180;if(e.kind==='hurt')hurtUntil=now+350;}
  if(room?.role!=='guest'&&(active&&!paused||room?.hostRunning)){saveTimer+=dt;if(saveTimer>=30){saveTimer=0;save();}}uiTimer+=dt;if(uiTimer>=.08){updateUI(now);uiTimer=0;}
 }
 $('start').textContent=guestPreview?'招待先を確認':hasSave?'保存した旅を続ける':'新しい旅を始める';$('restart').textContent='保存・新規開始';
 // Begin health timing after startup/restore and the first expensive WebGL frame.
 function scheduleRoomProbe(){if(!room||disposed)return;cancelAnimationFrame(roomProbeRaf);if(roomProbeTimer!==undefined)clearTimeout(roomProbeTimer);roomProbeRaf=requestAnimationFrame(()=>{roomProbeRaf=0;roomProbeTimer=setTimeout(()=>{roomProbeTimer=undefined;if(!disposed)void room?.probe();},0);});}
 function finishWorldLoad(){if(disposed)return;sim.worldReady=true;sim.protectQuestObjects();sim.water.refreshSolids();if(pendingSave){const restored=restoreCampaignInto(sim,pendingSave);if(!restored){loadFailed=true;saveStatus='保存内容を検証できません（'+(getCampaignRestoreFailure(sim)??'unknown')+'）。原本を保護しました。設定から新規開始を選べます';$('menu-title').textContent='保存データの確認が必要';needsRender=true;updateUI(performance.now());return;}/* Preserve explicit settings changes made while loading. */input.setSensitivity(settings.sensitivity);input.setGamepadSettings(settings.gamepad??defaultGamepadSettings());audio.setVolume(settings.volume);audio.setMix(settings.audioMix??DEFAULT_AUDIO_MIX);applyGraphics(settings.graphics);applyCamera();applyAccessibility();for(const [action,key] of Object.entries(settings.bindings))input.bind(action,key as string);savingAllowed=loaded.status==='loaded';saveStatus=selection.migrated?'旧形式を別途保護し、新形式へ移行しました':loaded.status==='recovered'?'バックアップから読み込みました。設定の「保存から続ける」で復元を確定':'保存した旅を読み込みました';}else if(savingAllowed)save();needsRender=true;updateUI(performance.now());scheduleRoomProbe();}
 function failWorldLoad(error:unknown){if(disposed)return;loadFailed=true;pause();saveStatus='世界の準備に失敗しました。保存は変更していません。再読み込みしてください';$('menu-title').textContent=saveStatus;console.error('Campaign world startup failed',error);needsRender=true;updateUI(performance.now());}
 if(loadFailed&&!pendingSave){$('menu-title').textContent='保存形式の確認が必要';saveStatus=selection.error??('error' in loaded?loaded.error:'保存を確認できません。原本を保護しています');updateUI(performance.now());}
 else if(!trial&&streamed){try{finishWorldLoad();}catch(error){failWorldLoad(error);}}
 else if(!trial){const controller=new AbortController();void bootstrapCampaignWorld(sim.arena,{budgetMs:3,signal:controller.signal,onProgress:stage=>{if(guestPreview)return;saveStatus=stage==='merging'?'周辺地域を接続中。拠点での変更を保持しています':'周辺地域を背景で展開中…';}}).then(finishWorldLoad).catch(failWorldLoad);window.addEventListener('pagehide',()=>controller.abort(),{once:true});}

 const loop=startGameLoop(update,dt=>{if(loopPolicy().render){needsRender=view.render(dt,input.controls().block,room?.role!=='guest')===false;}},()=>(!!room?.role||sim.bedWait.active)&&!document.hidden,undefined,{poll:dt=>input.tick(dt),enabled:()=>!document.hidden});const dispose=()=>{if(disposed)return;sim.bedWait.cancel();disposed=true;cancelAnimationFrame(roomProbeRaf);if(roomProbeTimer!==undefined)clearTimeout(roomProbeTimer);cancelFileImport();for(const url of downloadURLs)URL.revokeObjectURL(url);downloadURLs.clear();loop.stop();window.removeEventListener('resize',resize);save();room?.dispose();coopAvatar.dispose();campaignUI.dispose();input.dispose();view.dispose();audio.dispose();};window.addEventListener('pagehide',e=>{if(!e.persisted)dispose();else{cancelFileImport();pause();}});return {dispose};
}
