import {homesteadRows} from './homestead-presenter';
import type {CoreSimulation} from './core/simulation';
import {CAMPAIGN_ITEMS,CAMPAIGN_RECIPES,CAMPAIGN_SKILLS,CAMPAIGN_POINTS,CAMPAIGN_MATERIALS,isShrouded} from './core/campaign';
import type {CampaignUISnapshot,CampaignRow} from './campaign-ui';
import {REGIONAL_POINTS,REGIONS} from './core/regions';
import type {CampaignSettings} from './campaign-session';
export function campaignSnapshot(sim:CoreSimulation,settings:CampaignSettings,save:CampaignUISnapshot['save'],bindings:CampaignUISnapshot['bindings']):CampaignUISnapshot{
 const c=sim.campaign,s=c.state;
 return {homestead:homesteadRows(sim.home,sim.homeContext),materials:Object.values(CAMPAIGN_MATERIALS).map(m=>({id:String(m.id),label:m.icon+' '+m.label,count:c.materials[m.id]??0,detail:m.description+' / '+m.source})),
 items:Object.entries(s.items).filter(([,n])=>n>0).map(([id,count])=>{const item=CAMPAIGN_ITEMS[id];return {id,label:item.icon+' '+item.label,count,detail:item.description+' / '+item.source,action:item.slot?'equip':item.category==='food'||item.category==='medicine'?'consume':undefined} as CampaignRow;}),
 recipes:CAMPAIGN_RECIPES.map(r=>{const status=c.recipeStatus(r.id,sim.player.position);return {id:r.id,label:r.label,detail:r.description+' · '+Object.entries(r.cost).map(([id,n])=>`${CAMPAIGN_MATERIALS[Number(id)]?.label??id} ${c.materials[Number(id)]??0}/${n}`).join(' / '),reason:status.message,available:status.ok,action:'craft'};}),
 quests:[...c.questRows(),...c.regionQuestRows().map(q=>({...q,side:false}))].map(q=>({id:q.id,label:(q.side?'副依頼 · ':'主目的 · ')+q.label,detail:q.detail,completed:q.status==='complete',reason:q.status==='locked'?'前の主目的から進める':q.status==='active'?'進行中':'完了'})),
 points:[{id:'rescue',label:'安全帰還（素材25%を残す）',detail:'地形に閉じ込められた場合の救済。装備と重要品は保持',action:'gear'},{id:'player',label:'現在地',position:sim.player.position},...CAMPAIGN_POINTS.filter(p=>s.discovered.includes(p.id)).map(p=>({id:p.id,label:p.label,detail:p.description,position:p.position,action:p.kind==='base'?'travel' as const:undefined,available:c.canTravel(p.id).ok,reason:p.kind==='base'?c.canTravel(p.id).message:undefined})),...REGIONAL_POINTS.filter(p=>s.discoveredRegions.includes(p.region)).map(p=>({id:p.id,label:p.name,detail:p.lore??'地域の探索地点',position:p.position,action:p.kind==='hearth'?'travel' as const:undefined,available:c.canTravel(p.id).ok})),...settings.pins.map(p=>({id:p.id,label:'手動ピン',position:p,action:'remove-pin' as const}))],
 skills:CAMPAIGN_SKILLS.map(skill=>({id:skill.id,label:skill.label,detail:skill.description+' · '+skill.cost+'ポイント',completed:s.skills.includes(skill.id),available:!s.skills.includes(skill.id)&&s.skillPoints>=skill.cost&&(!skill.requires||s.skills.includes(skill.requires)),action:'learn'})),
 equipment:[...Object.entries(s.equipment).map(([slot,id])=>({id:'unequip:'+slot,label:({weapon:'武器',armor:'防具',grapple:'鉤縄',glider:'滑空具',charm:'護符'} as Record<string,string>)[slot],detail:id?CAMPAIGN_ITEMS[id].label:'未装備',action:id?'gear' as const:undefined})),...Object.entries(s.items).filter(([id,count])=>count>0&&['weapon','armor'].includes(CAMPAIGN_ITEMS[id].category)).flatMap(([id])=>{const gear=c.gearInfo(id),repair=c.repairStatus(id,sim.player.position),upgrade=c.upgradeStatus(id,sim.player.position),salvage=c.salvagePreview(id);return [{id:'repair:'+id,label:CAMPAIGN_ITEMS[id].label+' · 耐久 '+gear.durability+'/'+gear.maxDurability,detail:repair.message,available:repair.ok,action:'gear' as const},{id:'upgrade:'+id,label:'強化 +'+gear.upgrade+' → '+(gear.upgrade+1),detail:upgrade.message,available:upgrade.ok,action:'gear' as const},{id:(gear.socket?'unsocket:':'socket:')+id,label:gear.socket?'ジェムを外す':'灯火の石を装着',available:!!gear.socket||c.has('ember-gem'),action:'gear' as const},{id:'salvage:'+id,label:CAMPAIGN_ITEMS[id].label+'を解体',detail:salvage.message+' '+Object.entries(salvage.materials??{}).map(([key,n])=>CAMPAIGN_MATERIALS[Number(key)].label+' '+n).join(' / '),available:salvage.ok,action:'gear' as const}];}),{id:'reset-skills',label:'技能を再配分',detail:'習得した技能のポイントをすべて戻す',action:'gear'}],
 stats:{level:s.level,xp:s.xp,skillPoints:s.skillPoints,region:REGIONS.find(r=>s.discoveredRegions.includes(r.id)&&sim.player.position.x>=r.bounds.minX&&sim.player.position.x<=r.bounds.maxX&&sim.player.position.z>=r.bounds.minZ&&sim.player.position.z<=r.bounds.maxZ)?.name??(sim.player.position.z<-20?'銅風の尾根':isShrouded(sim.player.position)?'霞の高台':'火守りの谷'),objective:c.objective().label,shroud:isShrouded(sim.player.position)?s.shroudSeconds:undefined,food:s.foodSeconds,rest:s.restSeconds,oxygen:sim.swimming?sim.oxygen:undefined,cold:sim.cold>0?sim.cold:undefined,focus:sim.focus.value},settings,save,bindings};
}
