import './gamepad-settings.css';
import {defaultGamepadSettings,copyGamepadSettings,remapGamepadButton,GAMEPAD_ACTIONS,GAMEPAD_BUTTONS,GAMEPAD_LABELS,gamepadButtonLabel,type GamepadSettings} from './gamepad-settings';
function node<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string){const element=document.createElement(tag);if(text!==undefined)element.textContent=text;return element;}
export function createGamepadSettingsView(value:GamepadSettings|undefined,onChange:(value:GamepadSettings)=>void,signal:AbortSignal){
 let settings=copyGamepadSettings(value??defaultGamepadSettings());const refresh:(()=>void)[]=[];const commit=(next:GamepadSettings)=>{settings=copyGamepadSettings(next);for(const update of refresh)update();onChange(copyGamepadSettings(settings));};
 const section=node('section'),heading=node('h3','コントローラー設定'),help=node('p','標準 Gamepad 配列に対応。ボタンを変更すると、使用中の操作と入れ替えます。Start/Options の一時停止と、メニューの A 決定・B 戻る・十字移動は固定です。');section.className='campaign-gamepad-settings';help.className='campaign-help';section.append(heading,help);
 const grid=node('div');grid.className='campaign-binding-grid';
 for(const action of GAMEPAD_ACTIONS){const label=node('label',GAMEPAD_LABELS[action]),select=node('select');select.setAttribute('aria-label',GAMEPAD_LABELS[action]+'のコントローラーボタン');select.dataset.gamepadAction=action;for(const button of GAMEPAD_BUTTONS){const option=node('option',gamepadButtonLabel(button));option.value=String(button);select.append(option);}refresh.push(()=>{select.value=String(settings.buttons[action]);});select.value=String(settings.buttons[action]);select.addEventListener('change',()=>{const next=remapGamepadButton(settings,action,Number(select.value));if(next)commit(next);},{signal});label.append(select);grid.append(label);}
 section.append(grid);
 const deadzoneLabel=node('label','スティックの遊び'),deadzone=node('select');deadzone.setAttribute('aria-label','スティックの遊び');for(const n of [...new Set([.05,.1,.15,.18,.2,.25,.3,.4,settings.deadzone])].sort((a,b)=>a-b)){const option=node('option',Math.round(n*100)+'%');option.value=String(n);deadzone.append(option);}refresh.push(()=>{deadzone.value=String(settings.deadzone);});deadzone.value=String(settings.deadzone);deadzone.addEventListener('change',()=>commit({...copyGamepadSettings(settings),deadzone:Number(deadzone.value)}),{signal});deadzoneLabel.append(deadzone);section.append(deadzoneLabel);
 for(const [key,text] of [['invertY','上下の視点を反転'],['swapSticks','左右のスティックを交換']] as const){const label=node('label',text),select=node('select');select.setAttribute('aria-label',text);for(const [value,text] of [['0','しない'],['1','する']]){const option=node('option',text);option.value=value;select.append(option);}refresh.push(()=>{select.value=settings[key]?'1':'0';});select.value=settings[key]?'1':'0';select.addEventListener('change',()=>commit({...copyGamepadSettings(settings),[key]:select.value==='1'}),{signal});label.append(select);section.append(label);}
 const reset=node('button','コントローラー設定を初期化');reset.type='button';reset.addEventListener('click',()=>commit(defaultGamepadSettings()),{signal});section.append(reset);return section;
}
