import {spawn,type ChildProcess} from 'node:child_process';
import {appendFileSync,mkdirSync,readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs';
import {mkdtemp,readFile} from 'node:fs/promises';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {WebSocket} from 'ws';
import {COOP_PROTOCOL,type CoopAction,type CoopServerPacket,type CoopWireServerPacket} from '../src/networking/coop-protocol';
import {CoopFrameDecoder} from '../src/networking/coop-frame-decoder';
import type {RoomAccessView} from '../src/networking/room-access';
import type {Snapshot} from '../src/simulation/protocol';
import {SdfWorld} from '../src/world/density';
import type {Vec3} from '../src/world/types';
import {validateCheckpoint} from '../src/save/checkpoint';
import {fluidDigest,inventoryDigest,distribution,snapshotDigest} from './soak-coop-common';
const DURATION=15*60*1000,ROOM='e'.repeat(48),startedAt=Date.now(),root=process.cwd();
const output=process.argv[2]?resolve(process.argv[2]):await mkdtemp(join(tmpdir(),'voxel-coop-soak-'));mkdirSync(output,{recursive:true});const saves=join(output,'saves');mkdirSync(saves,{recursive:true});
const eventFile=join(output,'events.jsonl'),summaryFile=join(output,'summary.json');
const record=(event:Record<string,unknown>)=>appendFileSync(eventFile,JSON.stringify({at:Date.now(),...event})+'\n');
function sourceHash():string{const hash=createHash('sha256');for(const base of ['src','apps/coop','scripts']){const walk=(path:string)=>{for(const name of readdirSync(path).sort()){const file=join(path,name);if(statSync(file).isDirectory())walk(file);else if(/\.(ts|json)$/.test(name)){hash.update(file.slice(root.length));hash.update(readFileSync(file));}}};walk(join(root,base));}hash.update(readFileSync(join(root,'package.json')));hash.update(readFileSync(join(root,'package-lock.json')));return hash.digest('hex');}
const revision=sourceHash(),failures:string[]=[],notices:string[]=[],serverFinal:Record<string,unknown>[]=[],serverMetrics:Record<string,unknown>[]=[],latencies:number[]=[];
let running=true,paused=true,globalError:Error|undefined,server:ChildProcess|undefined,port=0,start=0,serverGeneration=0,bytesReceived=0,bytesSent=0,frames=0,saveChecks=0,fluidChecks=0,snapshotChecks=0,gaps=0,resyncs=0,plannedDisconnects=0,restarts=0,accepted=0,rejected=0,replays=0;
const expectedSnapshots=new Map<string,string>(),actualSnapshots=new Map<string,string>();
const expectedFluids=new Map<string,string>(),actualFluids=new Map<string,string>();
function fail(message:string):void{if(!failures.includes(message))failures.push(message);record({source:'driver',kind:'failure',message});globalError??=new Error(message);}
function pair(key:string){const expectedState=expectedSnapshots.get(key),actualState=actualSnapshots.get(key);if(expectedState&&actualState){if(expectedState!==actualState)fail('Full snapshot mismatch '+key);else snapshotChecks++;expectedSnapshots.delete(key);actualSnapshots.delete(key);}const expected=expectedFluids.get(key),actual=actualFluids.get(key);if(expected&&actual){if(expected!==actual)fail('Fluid dictionary mismatch '+key);else fluidChecks++;expectedFluids.delete(key);actualFluids.delete(key);}}
async function until(test:()=>boolean,label:string,timeout=15000,allowFailure=false){const end=performance.now()+timeout;while(!test()){if(globalError&&!allowFailure)throw globalError;if(performance.now()>end)throw Error('Timeout: '+label);await new Promise(r=>setTimeout(r,25));}}
async function startServer(){if(sourceHash()!==revision)throw Error('Source changed during soak');serverGeneration++;let ready=false,buffer='';const child=server=spawn(process.execPath,['--import','tsx','scripts/soak-coop-server.ts',saves],{cwd:root,stdio:['ignore','pipe','pipe']});
 child.stdout!.on('data',(data:Buffer)=>{buffer+=data.toString();let at:number;while((at=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,at);buffer=buffer.slice(at+1);if(!line.trim())continue;try{const event=JSON.parse(line) as Record<string,unknown>;record({...event,serverGeneration});if(event.kind==='ready'){port=Number(event.port);if(event.protocol!==COOP_PROTOCOL)fail('Server protocol mismatch');ready=true;}if(event.kind==='metrics'){serverMetrics.push(event);if((event.exceptions as number)>0)fail('Server exception counter increased');if((event.rooms as {readOnly:boolean}[]).some(r=>r.readOnly))fail('Room entered read-only mode');}if(event.kind==='final')serverFinal.push(event);if(event.kind==='fluid-sample'){const key=event.epoch+':'+event.playerId+':'+event.tick+':'+event.packetKind+':'+event.waterRevision;expectedFluids.set(key,String(event.digest));expectedSnapshots.set(key,String(event.snapshotDigest));pair(key);}if(event.kind==='save-validation'){if(event.valid===false)fail('Saved checkpoint failed validation');else saveChecks++;}if(event.kind==='exception'||event.kind==='shutdown-error')fail('Server '+event.kind+': '+event.message);if(event.kind==='notice'&&/失敗|停止|読み直|結果を確認/.test(String(event.message)))fail('Server notice: '+event.message);}catch(error){if(error instanceof SyntaxError)record({source:'server',kind:'stdout',line});else fail(String(error));}}});
 child.stderr!.on('data',(data:Buffer)=>record({source:'server',kind:'stderr',text:data.toString()}));child.on('error',error=>fail('Server process: '+error.message));child.on('exit',(code,signal)=>{record({source:'driver',kind:'server-exit',serverGeneration,code,signal});if(running&&!paused)fail('Unexpected server exit');});await until(()=>ready,'server startup',30000);
}
async function stopServer(){const child=server;if(!child||child.exitCode!==null)return;child.kill('SIGTERM');await until(()=>child.exitCode!==null||child.signalCode!==null,'graceful server shutdown',30000,true);if(child.exitCode!==0)throw Error('Server shutdown failed: '+child.exitCode);}
type Ack=Extract<CoopServerPacket,{type:'ack'}>;
class Client{
 readonly key=randomBytes(32).toString('hex');readonly publicId=createHash('sha256').update(this.key).digest('hex');
 socket:WebSocket|undefined;state:Snapshot|undefined;access:RoomAccessView|undefined;epoch='';sequence=0;online=false;plannedClose=false;awaitingBaseline=false;dropNext=false;expectGap=false;welcomes=0;nextAction=0;lastGuard:{commandId:string;action:CoopAction}|undefined;lastWelcomeInventory='';mirror:SdfWorld|undefined;
 private decoder=new CoopFrameDecoder(token=>this.send({type:'delivery',token}));private pending=new Map<string,{started:number;resolve:(ack:Ack)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>;name:string}>();
 constructor(readonly name:string){}
 async connect(){this.plannedClose=false;this.online=false;this.awaitingBaseline=true;const socket=this.socket=new WebSocket(`ws://127.0.0.1:${port}/coop/${ROOM}`);socket.on('message',raw=>{bytesReceived+=Buffer.byteLength(raw as Buffer);try{this.receive(JSON.parse(String(raw)) as CoopWireServerPacket);}catch(error){fail(this.name+' decode: '+String(error));}});socket.on('error',error=>fail(this.name+' socket: '+error.message));socket.on('close',code=>{this.online=false;record({source:'client',kind:'close',client:this.name,code,planned:this.plannedClose});for(const request of this.pending.values()){clearTimeout(request.timer);request.reject(Error('Socket closed'));}this.pending.clear();if(!this.plannedClose&&running)fail(this.name+' unexpected socket close '+code);});await new Promise<void>((yes,no)=>{socket.once('open',yes);socket.once('error',no);});this.send({type:'hello',protocol:COOP_PROTOCOL,resumeKey:this.key});await until(()=>this.online,this.name+' welcome');}
 send(packet:unknown){if(this.socket?.readyState!==WebSocket.OPEN)return;const text=JSON.stringify(packet);bytesSent+=Buffer.byteLength(text);this.socket.send(text);}
 private receive(raw:CoopWireServerPacket){
  const waterRevision=raw.type==='delta'?raw.water.revision:0;
  if(raw.type==='delta'){frames++;if(this.dropNext){this.dropNext=false;this.expectGap=true;record({source:'client',kind:'dropped-frame',client:this.name,tick:raw.tick});return;}if(this.awaitingBaseline||raw.epoch!==this.epoch)return;}
  let packet:CoopServerPacket;try{packet=this.decoder.accept(raw);}catch(error){if(this.expectGap){this.expectGap=false;gaps++;resyncs++;this.awaitingBaseline=true;record({source:'client',kind:'expected-gap-resync',client:this.name,message:String(error)});this.send({type:'resync'});return;}throw error;}
  if(packet.type==='welcome'){if(packet.protocol!==COOP_PROTOCOL||packet.playerId!==this.publicId)throw Error('Welcome identity/protocol changed');this.mirror=new SdfWorld(undefined,packet.save.generator);for(const edit of packet.save.edits)this.mirror.apply(edit);this.epoch=packet.epoch;this.state=packet.state;this.sequence=packet.state.ack??0;this.online=true;this.awaitingBaseline=false;this.welcomes++;this.lastWelcomeInventory=inventoryDigest(packet.save.adventure!.inventory);record({source:'client',kind:'welcome',client:this.name,epoch:this.epoch,tick:packet.state.tick,fluids:packet.state.fluids.length,edits:packet.state.edits,inventory:this.lastWelcomeInventory});this.sample('welcome',0);return;}
  if(packet.type==='frame'){if(packet.editBase!==this.mirror!.edits.length)throw Error('Terrain delta gap');for(const edit of packet.edits)this.mirror!.apply(edit);if(this.state&&packet.state.tick<this.state.tick)throw Error('Tick regressed without new epoch');this.state=packet.state;if(this.state.tick%300===0)this.sample('frame',waterRevision);return;}
  if(packet.type==='room-access'){this.access=packet.access;if(packet.access.readOnly)fail(this.name+' received read-only access state');return;}
  if(packet.type==='ack'){const waiting=this.pending.get(packet.commandId);if(waiting){clearTimeout(waiting.timer);this.pending.delete(packet.commandId);latencies.push(performance.now()-waiting.started);if(packet.accepted)accepted++;else rejected++;record({source:'client',kind:'ack',client:this.name,name:waiting.name,commandId:packet.commandId,accepted:packet.accepted,message:packet.message,latencyMs:performance.now()-waiting.started});waiting.resolve(packet);}return;}
  if(packet.type==='notice'){notices.push(packet.message);record({source:'client',kind:'notice',client:this.name,message:packet.message});if(/失敗|停止|読み直|結果を確認/.test(packet.message))fail(this.name+' notice '+packet.message);}
 }
 private sample(kind:'welcome'|'frame',waterRevision:number){const state=this.state!;const key=this.epoch+':'+this.publicId+':'+state.tick+':'+kind+':'+waterRevision;actualFluids.set(key,fluidDigest(state.fluids));actualSnapshots.set(key,snapshotDigest(state));pair(key);}
 input(x:number,z:number,jump=false){if(this.online&&!this.awaitingBaseline&&!this.access?.pending&&!this.access?.readOnly)this.send({type:'input',sequence:++this.sequence,input:{x,z,jump}});}
 async act(action:CoopAction,name:string,commandId:string=randomUUID()):Promise<Ack>{if(!this.online)throw Error('Actor offline');if(this.access?.pending)await until(()=>!this.access?.pending,this.name+' management save');const promise=new Promise<Ack>((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(commandId);reject(Error('ACK timeout '+name));},10000);this.pending.set(commandId,{started:performance.now(),resolve,reject,timer,name});});this.nextAction=performance.now()+650;this.send({type:'action',commandId,message:action});const ack=await promise;if(/データが不正|フィールド|Invalid action|版がありません/.test(ack.message))fail('Protocol rejection: '+ack.message);return ack;}
 async guardReceipt(){const commandId=randomUUID(),action:CoopAction={type:'game-action',action:'guard',id:'off',aim:{x:0,y:0,z:1}};const ack=await this.act(action,'guard-receipt',commandId);if(!ack.accepted)throw Error('Guard receipt rejected');this.lastGuard={commandId,action};return this.lastGuard;}
 async replayGuard(){if(!this.lastGuard)return;const ack=await this.act(this.lastGuard.action,'replay-guard',this.lastGuard.commandId);replays++;if(!ack.accepted)throw Error('Persisted receipt was not recognized');}
 async drain(){await until(()=>this.pending.size===0,this.name+' pending ACKs');}
 async close(){this.plannedClose=true;this.online=false;const socket=this.socket;if(!socket||socket.readyState===WebSocket.CLOSED)return;const closed=new Promise<void>(r=>socket.once('close',()=>r()));socket.close();await closed;}
 ground(point:Vec3){const world=this.mirror!;let previous=Math.min(46,point.y+1.2);if(world.density({...point,y:previous})<=0)return point.y;for(let y=previous-.25;y>-15;y-=.25){if(world.density({...point,y})<=0){let low=y,high=previous;for(let i=0;i<8;i++){const mid=(low+high)/2;if(world.density({...point,y:mid})<=0)low=mid;else high=mid;}return high;}previous=y;}return point.y;}
}
const a=new Client('A'),b=new Client('B'),clients=[a,b];let inputTimer:ReturnType<typeof setInterval>|undefined,metricTimer:ReturnType<typeof setInterval>|undefined;
async function checkpoint(){const text=await readFile(join(saves,ROOM+'.json'),'utf8');const checked=validateCheckpoint(JSON.parse(text));saveChecks++;return checked;}
async function sharedPickup(){const node=a.state!.adventure.resources.find(n=>n.drop&&n.kind==='wood'&&n.amount===12);if(!node)throw Error('Original shared wood cache missing');const commands=clients.map(()=>randomUUID()),action:CoopAction={type:'game-action',action:'gather',id:String(node.id),aim:{x:0,y:0,z:1}};const responses=await Promise.all(clients.map((c,i)=>c.act(action,'shared-pickup-race',commands[i])));if(responses.filter(p=>p.accepted).length!==1)throw Error('Pickup race did not have exactly one winner');await until(()=>clients.reduce((n,c)=>n+(c.state?.adventure.inventory.wood??0),0)===12,'shared pickup inventory');const replay=await Promise.all(clients.map((c,i)=>c.act(action,'shared-pickup-replay',commands[i])));replays+=2;if(replay.filter(p=>p.accepted).length!==1)throw Error('Pickup receipt replay diverged');await new Promise(r=>setTimeout(r,250));if(clients.reduce((n,c)=>n+(c.state?.adventure.inventory.wood??0),0)!==12)throw Error('Pickup duplicated');record({source:'driver',kind:'pickup-check',count:12,winners:1});return responses[0].accepted?a:b;}
let owner:Client,partId:number|undefined,nextWater=20,nextDig=45,nextRock=90,nextPart=60,nextFood=40,nextReturn=120,helperUntil=0;
async function controls(elapsed:number){for(const c of clients){if(!c.online||c.awaitingBaseline||performance.now()<c.nextAction||c.access?.pending)continue;const state=c.state!,s=state.adventure,p=state.player,other=c===a?b:a;if(s.coop?.downedSeconds||s.health<=0)continue;
 if(other.state?.adventure.coop?.downedSeconds&&Math.hypot(other.state.player.x-p.x,other.state.player.y-p.y,other.state.player.z-p.z)<2.8&&elapsed>helperUntil){const ack=await c.act({type:'game-action',action:'revive',id:other.publicId,aim:{x:0,y:0,z:1}},'revive');if(ack.accepted){helperUntil=elapsed+4;c.nextAction=performance.now()+4000;}continue;}
 if(elapsed<helperUntil)continue;const enemy=s.enemies.filter(e=>e.health>0).sort((x,y)=>Math.hypot(x.x-p.x,x.y-p.y,x.z-p.z)-Math.hypot(y.x-p.x,y.y-p.y,y.z-p.z))[0];if(enemy&&Math.hypot(enemy.x-p.x,enemy.y-p.y,enemy.z-p.z)<2.8){const dx=enemy.x-p.x,dy=enemy.y+.6-p.y-.85,dz=enemy.z-p.z,d=Math.max(.01,Math.hypot(dx,dy,dz));await c.act({type:'game-action',action:'attack',aim:{x:dx/d,y:dy/d,z:dz/d}},'combat');continue;}
 }
 if(!owner.online||performance.now()<owner.nextAction||elapsed<helperUntil||owner.state!.adventure.health<=0)return;const state=owner.state!,p=state.player;
 if(elapsed>=nextWater){nextWater+=30;await owner.act({type:'action',tool:'water',target:{x:p.x+2,y:p.y+.3,z:p.z}},'water');return;}
 if(elapsed>=nextDig){nextDig+=60;const point={x:p.x+3.5,y:p.y,z:p.z+1.5};point.y=owner.ground(point)-.2;await owner.act({type:'action',tool:'dig',expectedRevision:state.edits,target:point},'dig');return;}
 if(elapsed>=nextRock){nextRock+=180;await owner.act({type:'action',tool:'rock',target:{x:p.x+3.5,y:p.y,z:p.z-1.5}},'rock');return;}
 if(elapsed>=nextFood){nextFood+=45;for(const c of clients)if(c.online&&c.state!.adventure.inventory.berry>0&&!c.state!.adventure.meadows?.foods.some(f=>f.id==='berry'&&f.remaining>300))await c.act({type:'game-action',action:'eat',id:'berry',aim:{x:0,y:0,z:1}},'food');return;}
 if(elapsed>=nextPart){nextPart+=120;const part=state.adventure.skybound?.parts.find(p=>p.id===partId);if(part&&Math.hypot(part.position.x-p.x,part.position.y-p.y,part.position.z-p.z)<6){const grabbed=await owner.act({type:'game-action',action:'sky-grab',id:String(part.id),expectedEpoch:part.epoch,aim:{x:1,y:0,z:0}},'grab');if(grabbed.accepted){await new Promise(r=>setTimeout(r,250));const current=owner.state!.adventure.skybound!.parts.find(p=>p.id===partId)!;await owner.act({type:'game-action',action:'sky-move',id:String(part.id),expectedEpoch:current.epoch,target:{...current.position,y:current.position.y+.35},aim:{x:1,y:0,z:0}},'move-part');await owner.act({type:'game-action',action:'sky-release',id:String(part.id),aim:{x:1,y:0,z:0}},'release-part');}}else record({source:'driver',kind:'part-operation-skipped',reason:'Natural part moved out of reach'});return;}
 if(elapsed>=nextReturn){nextReturn+=90;for(const c of clients)if(c.online&&c.state!.adventure.health>0&&(Math.hypot(c.state!.player.x,c.state!.player.z-8)>12||c.state!.player.y<-5))await c.act({type:'game-action',action:'return',aim:{x:0,y:0,z:1}},'return-via-gameplay');}
}
try{
 if(COOP_PROTOCOL!==7)throw Error('This soak requires the fixed protocol-7 checkout');record({source:'driver',kind:'start',protocol:COOP_PROTOCOL,sourceHash:revision,durationMs:DURATION,root,output,note:'Real initial world; no simulation fixture replacement; not a browser/UI/device test'});await startServer();await a.connect();await b.connect();owner=await sharedPickup();
 for(const c of clients){await new Promise(r=>setTimeout(r,300));await c.act({type:'game-action',action:'equip',id:'club',aim:{x:0,y:0,z:1}},'equip');await new Promise(r=>setTimeout(r,300));await c.act({type:'game-action',action:'eat',id:'berry',aim:{x:0,y:0,z:1}},'initial-food');}
 await until(()=>performance.now()>=owner.nextAction,'initial part action interval');const at=owner.state!.player,partTarget={x:at.x+4,y:at.y,z:at.z};partTarget.y=owner.ground(partTarget)+1.1;const made=await owner.act({type:'game-action',action:'sky-part',id:'block:wood',target:partTarget,aim:{x:1,y:0,z:0}},'initial-part');if(!made.accepted)throw Error('Initial part creation rejected: '+made.message);if(made.accepted){await until(()=>!!owner.state!.adventure.skybound?.parts.some(p=>p.creator===owner.publicId),'authored part snapshot');partId=owner.state!.adventure.skybound!.parts.find(p=>p.creator===owner.publicId)!.id;}
 start=performance.now();paused=false;inputTimer=setInterval(()=>{if(paused)return;const t=(performance.now()-start)/1000,phase=Math.floor(t/3)%4;const helping=t<helperUntil;for(const [i,c]of clients.entries()){if(helping)c.input(0,0);else c.input(i===0?(phase===0?.25:phase===2?-.25:0):0,i===1?(phase===1?.25:phase===3?-.25:0):0);if(Math.floor(t)%3===0)c.send({type:'ping'});}},50);
 metricTimer=setInterval(()=>record({source:'driver',kind:'metrics',elapsedMs:performance.now()-start,memory:process.memoryUsage(),bytesReceived,bytesSent,frames,accepted,rejected,fluidChecks,snapshotChecks,saveChecks,clients:clients.map(c=>({name:c.name,online:c.online,tick:c.state?.tick,health:c.state?.adventure.health,downed:c.state?.adventure.coop?.downedSeconds,position:c.state?.player,fluids:c.state?.fluids.length,edits:c.state?.edits}))}),1000);
 let gapDone=false,disconnectDone=false,restartDone=false;
 while(performance.now()-start<DURATION){if(globalError)throw globalError;const elapsed=(performance.now()-start)/1000;
  if(!gapDone&&elapsed>=180){gapDone=true;a.dropNext=true;record({source:'driver',kind:'inject-one-water-gap'});}
  if(!disconnectDone&&elapsed>=300){disconnectDone=true;paused=true;await a.drain();await b.drain();await b.guardReceipt();await b.close();plannedDisconnects++;await new Promise(r=>setTimeout(r,1000));const stored=await checkpoint(),expected=inventoryDigest(stored.world.members!.find(m=>m.id===b.publicId)!.adventure.inventory);await b.connect();if(b.lastWelcomeInventory!==expected)throw Error('Reconnect inventory changed');await b.replayGuard();paused=false;record({source:'driver',kind:'reconnect-check',inventoryMatched:true});}
  if(!restartDone&&elapsed>=600){restartDone=true;paused=true;await a.drain();await b.drain();await a.guardReceipt();await b.guardReceipt();for(const c of clients)c.plannedClose=true;await stopServer();const stored=await checkpoint(),expected=new Map(clients.map(c=>[c.publicId,inventoryDigest(stored.world.members!.find(m=>m.id===c.publicId)!.adventure.inventory)]));await startServer();for(const c of clients){await c.connect();if(c.lastWelcomeInventory!==expected.get(c.publicId))throw Error('Restart inventory changed '+c.name);await c.replayGuard();}restarts++;paused=false;record({source:'driver',kind:'restart-check',sameSource:true,inventoryMatched:true});}
  await controls(elapsed);await new Promise(r=>setTimeout(r,200));
 }
 paused=true;for(const c of clients){await c.drain();await c.guardReceipt();}await until(()=>gaps===1&&resyncs===1&&a.welcomes>=3,'gap resynchronization evidence');if(plannedDisconnects!==1||restarts!==1)throw Error('Planned lifecycle phases did not complete');if(snapshotChecks<20)throw Error('Not enough exact full snapshot comparisons');if(fluidChecks<20)throw Error('Not enough exact water comparisons');const final=await checkpoint();if(final.world.edits.length<2)throw Error('Real terrain operations did not persist');if(accepted<20)throw Error('Too few accepted operations');record({source:'driver',kind:'functional-checks-complete',durationMs:performance.now()-start,fluidChecks,edits:final.world.edits.length,accepted});
}catch(error){fail(error instanceof Error?error.stack??error.message:String(error));}
finally{
 paused=true;if(inputTimer)clearInterval(inputTimer);if(metricTimer)clearInterval(metricTimer);for(const c of clients)try{await c.close();}catch(error){fail('Client cleanup: '+String(error));}try{await stopServer();}catch(error){fail('Server cleanup: '+String(error));server?.kill('SIGKILL');}running=false;
 const durationMs=start?performance.now()-start:0,serverRss=serverMetrics.map(e=>(e.memory as {rss:number}).rss),serverHeap=serverMetrics.map(e=>(e.memory as {heapUsed:number}).heapUsed);const summary={status:failures.length?'failed':'completed',protocol:COOP_PROTOCOL,startedAt:new Date(startedAt).toISOString(),sourceHash:revision,root,output,durationMs,requiredDurationMs:DURATION,notBrowserOrDeviceTest:true,fixturesReplaced:false,plannedDisconnects,restarts,gaps,resyncs,fluidChecks,snapshotChecks,saveChecks,accepted,rejected,replays,frames,bytesReceived,bytesSent,ackLatencyMs:distribution(latencies),serverRss:distribution(serverRss),serverHeap:distribution(serverHeap),serverEpochs:serverFinal,failures,notices};writeFileSync(summaryFile,JSON.stringify(summary,null,2));console.log(JSON.stringify({status:summary.status,summary:summaryFile,durationMs,failures},null,2));if(failures.length)process.exitCode=1;
}
