import {seedInventory} from '../helpers/equipment';
import {it,expect} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {foodEffect} from '../../src/content/adventure-food';
import {validateSave} from '../../src/save/format';
const aim={x:0,y:0,z:-1};
function game(){const sim=new GameSimulation();sim.fluid.restore([]);sim.adventure.state.enemies=[];sim.adventure.state.inventory={berry:20,mushroom:20,honey:5,crystal:3};sim.adventure.state.buildings=[{id:90001,definition:'fire',x:sim.player.x+2,y:sim.player.y,z:sim.player.z,rotation:0,support:1,contents:{},fuel:120,open:false}];return sim;}
it('cooks original recipes atomically, applies bounded food effects and restores their remaining time',()=>{const sim=game();sim.adventure.action('craft','sunSoup',undefined,aim);expect(sim.adventure.state.inventory.berry).toBe(18);expect(sim.adventure.state.inventory.sunSoup).toBe(1);sim.adventure.action('eat','sunSoup',undefined,aim);expect(foodEffect(sim.adventure.state,'warmth')).toBe(true);expect(()=>sim.adventure.action('eat','sunSoup',undefined,aim)).toThrow();const restored=new GameSimulation(validateSave(sim.save()));expect(foodEffect(restored.adventure.state,'warmth')).toBe(true);expect(restored.adventure.state.meadows!.foods[0].remaining).toBe(300);});
it('preserves ingredients when the fire is wet, out of reach or ingredients are missing',()=>{const sim=game(),before={...sim.adventure.state.inventory};sim.adventure.state.buildings[0].open=true;expect(()=>sim.adventure.action('craft','sunSoup',undefined,aim)).toThrow('焚き火');expect(sim.adventure.state.inventory).toEqual(before);sim.adventure.state.buildings[0].open=false;sim.adventure.state.inventory.mushroom=0;const depleted={...sim.adventure.state.inventory};expect(()=>sim.adventure.action('craft','sunSoup',undefined,aim)).toThrow('素材');expect(sim.adventure.state.inventory).toEqual(depleted);});
it('reduces gliding stamina with endurance food and shields cold/hot exposure through personal effects',()=>{const sim=game();sim.adventure.action('craft','trailTea',undefined,aim);sim.adventure.action('eat','trailTea',undefined,aim);sim.adventure.action('craft','coolInfusion',undefined,aim);sim.adventure.action('eat','coolInfusion',undefined,aim);Object.assign(sim.player,{x:60,y:-10.5,z:8});const health=sim.adventure.state.health;for(let i=0;i<60;i++)sim.step({x:0,z:0,jump:false});expect(sim.adventure.state.health).toBeGreaterThanOrEqual(health);Object.assign(sim.player,{x:0,y:15,z:8,grounded:false});seedInventory(sim.adventure,{...sim.adventure.state.inventory,glider:1});sim.adventure.action('glide','on',undefined,aim);const before=sim.adventure.state.stamina;sim.adventure.traversal.beforeMove({x:0,z:0,jump:false},1);expect(before-sim.adventure.state.stamina).toBeCloseTo(3.5);});
