import {expect,it} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {SessionAuthority} from '../../src/simulation/session';
import {AdventureSites,ensureAdventureSites} from '../../src/game/sites';
import {SITES,SITE_ROUTES,SITE_ROOMS,sitePieces,siteAnnexPieces} from '../../src/content/adventure-sites';
import {siteClear,siteSupport} from '../../src/game/site-walking';
import {skyContext} from '../../src/game/skybound/context';
import {strikeVoxels} from '../../src/game/voxel/destruction';
import {validateSave} from '../../src/save/format';
import {validateSiteWorld} from '../../src/game/site-state';
import {participantSave} from '../../src/save/participant';
const idle={x:0,z:0,jump:false},aim={x:1,y:0,z:0};
function fixture(){const sim=new GameSimulation();ensureAdventureSites(sim,sim.adventure.state,true);sim.adventure.state.enemies=[];sim.fluid.restore([]);const sites=new AdventureSites(sim.adventure);return {sim,sites,world:sim.adventure.state.siteWorld!};}
function atGuide(sim:GameSimulation,id:number){const site=SITES.find(s=>s.id===id)!,y=sim.adventure.state.siteWorld!.bases[id];Object.assign(sim.player,{x:site.x,y:y+.18,z:site.z+5.5,grounded:true,vy:0});}
it('stamps supported pieces once without rewriting terrain, water, trial markers or original wildlife',()=>{
 const sim=new GameSimulation(),state=sim.adventure.state;const edits=JSON.stringify(sim.world.edits),water=[...sim.fluid.cells.values()].reduce((sum,c)=>sum+c.volume,0),markers=state.resources.filter(n=>n.id>=810001&&n.id<=830003).map(n=>({...n})),enemies=state.enemies.length;ensureAdventureSites(sim,state,true);expect(state.buildings.filter(b=>b.site)).toHaveLength(SITES.reduce((n,s)=>n+sitePieces(s.id,s.x,0,s.z).length+siteAnnexPieces(s.id,s.x,0,s.z).length,0)-Object.values(state.siteWorld!.skipped).reduce((n,v)=>n+v,0));sim.adventure.support();expect(state.buildings.filter(b=>b.site)).toHaveLength(SITES.reduce((n,s)=>n+sitePieces(s.id,s.x,0,s.z).length+siteAnnexPieces(s.id,s.x,0,s.z).length,0)-Object.values(state.siteWorld!.skipped).reduce((n,v)=>n+v,0));ensureAdventureSites(sim,state,true);expect(state.buildings.filter(b=>b.site)).toHaveLength(SITES.reduce((n,s)=>n+sitePieces(s.id,s.x,0,s.z).length+siteAnnexPieces(s.id,s.x,0,s.z).length,0)-Object.values(state.siteWorld!.skipped).reduce((n,v)=>n+v,0));expect(JSON.stringify(sim.world.edits)).toBe(edits);expect([...sim.fluid.cells.values()].reduce((sum,c)=>sum+c.volume,0)).toBe(water);expect(state.resources.filter(n=>n.id>=810001&&n.id<=830003)).toEqual(markers);expect(state.enemies).toHaveLength(enemies);expect(state.buildings.every(b=>Object.keys(b.salvage??{}).length===0)).toBe(true);
});
it('has two measured capsule-clear entrances and three rooms in each layer',()=>{
 const {sim,world}=fixture();for(const site of SITES){const y=world.bases[site.id]+.19;for(const route of Object.values(SITE_ROUTES))for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i];for(let t=0;t<=1;t+=.1){const p={x:site.x+a.x+(b.x-a.x)*t,y,z:site.z+a.z+(b.z-a.z)*t};expect(siteClear(sim,p),`${site.name} ${JSON.stringify(p)}`).toBe(true);}}for(const room of SITE_ROOMS)expect(siteClear(sim,{x:site.x+room.x,y,z:site.z+room.z})).toBe(true);}
});
it('preserves edited/private occupied areas on old-save installation and never restamps destroyed pieces',()=>{
 const sim=new GameSimulation(),state=sim.adventure.state;state.buildings=state.buildings.filter(b=>!b.site);delete state.siteWorld;const p={x:24,y:sim.groundAt(24,-32),z:-32};sim.world.apply({id:1,kind:'dig',position:p,radius:2,material:'stone',tick:1});state.buildings.push({id:999,definition:'chest',x:28,y:p.y,z:-30,rotation:0,support:3,contents:{wood:9},creator:'someone',shared:false});ensureAdventureSites(sim,state,false);expect(state.siteWorld!.storyMode).toBe('side');expect(state.siteWorld!.skipped[850001]).toBeGreaterThan(0);expect(state.buildings.find(b=>b.id===999)?.contents.wood).toBe(9);const count=state.buildings.length;state.buildings.splice(state.buildings.findIndex(b=>b.site===850001),1);ensureAdventureSites(sim,state,false);expect(state.buildings.length).toBe(count-1);
});
it('allows a real walking entrance, a stair roof route, mining and vertical passage without ruin salvage',()=>{
 const {sim,world}=fixture(),site=SITES[0],base=world.bases[site.id];Object.assign(sim.player,{x:site.x,y:sim.groundAt(site.x,site.z+5),z:site.z+5,grounded:true,vy:0});for(let i=0;i<32;i++)sim.step({x:0,z:-1,jump:false});expect(sim.player.z).toBeLessThan(site.z+2.5);
 Object.assign(sim.player,{x:site.x-3,y:sim.groundAt(site.x-3,site.z-6.5),z:site.z-6.5,grounded:true,vy:0});for(let i=0;i<35;i++)sim.step({x:0,z:1,jump:false});expect(sim.player.y).toBeGreaterThan(base+2);
 Object.assign(sim.player,{x:site.x+4,y:base+.18,z:site.z+3,grounded:true,vy:0});sim.adventure.action('sky-ascend-preview','',undefined,{x:0,y:1,z:0});sim.adventure.action('sky-ascend','',undefined,{x:0,y:1,z:0});expect(sim.player.y).toBeGreaterThan(base+2);
 Object.assign(sim.player,{x:site.x+6,y:base+.2,z:site.z+1});sim.adventure.state.equipment='axe';const before=sim.adventure.state.resources.filter(n=>n.drop).reduce((sum,n)=>sum+n.amount,0);for(let i=0;i<12;i++)strikeVoxels(sim.adventure,{x:-1,y:0,z:0},3,true);expect(sim.adventure.state.buildings.some(b=>b.site===site.id&&b.removed?.length)).toBe(true);expect(sim.adventure.state.resources.filter(n=>n.drop).reduce((sum,n)=>sum+n.amount,0)).toBe(before);
});
it('reports cargo only after real stable placement, one shared reward and late-join growth, including restart',()=>{
 const {sim,sites,world}=fixture();atGuide(sim,850001);sites.action('site-accept','850001');const cargo=sim.skybound.state.parts.find(p=>p.loan?.site===850001&&p.kind==='block')!;expect(cargo).toBeTruthy();const o=SITES[0],base=world.bases[850001];cargo.position={x:o.x+2,y:base+.8,z:o.z-2};cargo.velocity={x:0,y:0,z:0};for(let i=0;i<35;i++){sim.tick++;sim.skybound.step(1/30,skyContext(sim));sites.step(1/30);}expect(world.evidence[850001]&1).toBe(1);atGuide(sim,850001);expect(sites.action('site-report','850001').message).toContain('番人');const boss=sim.adventure.state.enemies.find(e=>e.definition==='loadwarden')!;expect(boss).toBeTruthy();sites.onBossDefeated(boss);boss.health=0;sites.action('site-report','850001');const drops=sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='wood').reduce((sum,n)=>sum+n.amount,0);sites.action('site-report','850001');expect(sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='wood').reduce((sum,n)=>sum+n.amount,0)).toBe(drops);expect(world.completed).toEqual([850001]);const saved=validateSave(sim.save()),room=new SessionAuthority(saved),guest=room.join('late');expect(guest.adventure.state.siteWorld!.completed).toEqual([850001]);expect(guest.adventure.state.inventory.wood??0).toBe(0);expect(room.save().members![0].adventure.siteWorld).toBeUndefined();expect(participantSave(room,'late').adventure!.siteWorld!.completed).toEqual([850001]);
});
it('keeps ruin loans unrewarding to salvage and reissues after holes without restoring custom terrain',()=>{
 const {sim,sites}=fixture();atGuide(sim,850001);sites.action('site-reset','850001');let cargo=sim.skybound.state.parts.find(p=>p.loan?.site===850001&&p.kind==='block')!;Object.assign(sim.player,{x:cargo.position.x,y:cargo.position.y+.5,z:cargo.position.z+2});sim.skybound.action('host','sky-grab',String(cargo.id),undefined,aim,skyContext(sim));expect(sim.skybound.action('host','sky-salvage',String(cargo.id),undefined,aim,skyContext(sim)).drops).toEqual([]);atGuide(sim,850001);sim.adventure.state.buildings=sim.adventure.state.buildings.filter(b=>!(b.site===850001&&b.definition==='foundation'));sites.action('site-reset','850001');cargo=sim.skybound.state.parts.find(p=>p.loan?.site===850001&&p.kind==='block')!;expect(cargo).toBeTruthy();expect(sim.adventure.state.buildings.some(b=>b.site===850001&&b.definition==='foundation')).toBe(false);
});
it('rejects malformed site persistence and clears transient escort claims when loading',()=>{
 const {world}=fixture();world.rescue!.following='guest';expect(validateSiteWorld(world).rescue!.following).toBeUndefined();expect(()=>validateSiteWorld({...world,layout:2})).toThrow();expect(()=>validateSiteWorld({...world,completed:[850001,850001]})).toThrow();expect(()=>validateSiteWorld({...world,evidence:{constructor:1}})).toThrow();
});
it('escorts a real rescue body through rooms, stops at walls, and releases the caller for another participant',()=>{
 const {sim,sites,world}=fixture(),site=SITES[1],base=world.bases[site.id],rescue=world.rescue!;Object.assign(sim.player,{x:site.x+2,y:base+.18,z:site.z-1,vy:0,grounded:true});sites.action('site-rescue',String(site.id));
 const blocker={id:99991,definition:'wall',x:site.x+2,y:base+.15,z:site.z-.7,rotation:0,support:4,contents:{}};sim.adventure.state.buildings.push(blocker);Object.assign(sim.player,{x:site.x+2,y:base+.18,z:site.z+2});for(let i=0;i<60;i++){sim.tick++;sites.step(1/30);}expect(rescue.position.z).toBeLessThan(site.z-.7);sim.adventure.state.buildings=sim.adventure.state.buildings.filter(b=>b!==blocker);
 for(const point of [{x:site.x+2,z:site.z+1},{x:site.x,z:site.z+2},{x:site.x,z:site.z+5.5}]){Object.assign(sim.player,{...point,y:base+.18});for(let i=0;i<100;i++){sim.tick++;sites.step(1/30);}}
 expect(rescue.arrived).toBe(true);expect(world.evidence[site.id]&1).toBe(1);
 const room=new SessionAuthority(sim.save()),guest=room.join('guest');room.sim.adventure.state.siteWorld!.rescue={position:{x:site.x+2,y:base+.18,z:site.z-2},arrived:false};Object.assign(guest.player,{x:site.x+2,y:base+.18,z:site.z-1});room.action('guest',{type:'game-action',action:'site-rescue',id:String(site.id),aim});room.leave('guest');expect(room.sim.adventure.state.siteWorld!.rescue!.following).toBeUndefined();const next=room.join('next');Object.assign(next.player,{x:site.x+2,y:base+.18,z:site.z-1});expect(()=>room.action('next',{type:'game-action',action:'site-rescue',id:String(site.id),aim})).not.toThrow();
});
it('latches real powered light and a thaw-then-water device sequence, letting later reports survive restarts',()=>{
 const {sim,sites,world}=fixture(),id=850003;atGuide(sim,id);sites.action('site-accept',String(id));const parts=sim.skybound.state.parts.filter(p=>p.loan?.site===id),battery=parts.find(p=>p.kind==='battery')!,lamp=parts.find(p=>p.kind==='lamp')!,device=parts.find(p=>p.kind==='block')!;expect(parts).toHaveLength(4);
 const emitter=parts.find(p=>p.kind==='emitter')!;battery.links=[lamp.id,emitter.id];lamp.links=[battery.id];emitter.links=[battery.id];lamp.enabled=true;emitter.enabled=true;for(let i=0;i<75;i++){sim.tick++;sim.skybound.step(1/30,skyContext(sim));sites.step(1/30);}expect(world.evidence[id]&2).toBe(2);expect(world.evidence[id]&8).toBe(8);
 const wet={...skyContext(sim),immersion:(p:{x:number;y:number;z:number})=>Math.hypot(p.x-device.position.x,p.y-device.position.y,p.z-device.position.z)<1?1:0};for(let i=0;i<30;i++){sim.tick++;wet.tick=sim.tick;sim.skybound.step(1/30,wet);sites.step(1/30);}expect(world.evidence[id]&1).toBe(1);const restored=new GameSimulation(validateSave(sim.save()));expect(restored.adventure.state.siteWorld!.evidence[id]&1).toBe(1);
});
it('keeps failed accept/reset transactions unchanged and commits a boss spawn as a successful report',()=>{
 const {sim,sites,world}=fixture();atGuide(sim,850001);sim.skybound.state.parts=Array.from({length:64},(_,i)=>({id:i+100,kind:'block' as const,material:'wood' as const,position:{x:100+i,y:4,z:100},velocity:{x:0,y:0,z:0},mass:6,rotation:0,links:[],epoch:0}));const before=JSON.stringify(sim.adventure.state.siteJournal);expect(()=>sites.action('site-accept','850001')).toThrow('枠');expect(JSON.stringify(sim.adventure.state.siteJournal)).toBe(before);expect(world.epochs[850001]).toBeUndefined();world.evidence[850001]=1;expect(sites.action('site-report','850001').message).toContain('番人');expect(sim.adventure.state.enemies.filter(e=>e.definition==='loadwarden')).toHaveLength(1);expect(world.completed).toEqual([]);sites.action('site-report','850001');expect(sim.adventure.state.enemies.filter(e=>e.definition==='loadwarden')).toHaveLength(1);
});
it('commits a shared report once across two actors and never pays regional boss loot twice',()=>{
 const {sim,world}=fixture();world.evidence[850001]=1;sim.adventure.state.defeated.push('loadwarden');atGuide(sim,850001);const room=new SessionAuthority(sim.save()),guest=room.join('guest');Object.assign(guest.player,room.sim.player);const before=room.sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='wood').reduce((sum,n)=>sum+n.amount,0);for(const id of ['host','guest'])room.action(id,{type:'game-action',action:'site-report',id:'850001',aim});expect(room.sim.adventure.state.siteWorld!.completed).toEqual([850001]);expect(room.sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='wood').reduce((sum,n)=>sum+n.amount,0)).toBe(before+4);
 const boss={id:99912,definition:'echowarden',x:room.sim.player.x+2,y:room.sim.player.y,z:room.sim.player.z,tier:1,health:1,cooldown:0,windup:0,slow:0,boss:true,homeX:room.sim.player.x,homeZ:room.sim.player.z};room.sim.adventure.state.enemies.push(boss);const crystal=()=>room.sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='crystal').reduce((sum,n)=>sum+n.amount,0);const count=crystal();room.sim.adventure.hit(boss,100,'fire');room.sim.adventure.hit(boss,100,'fire');expect(crystal()).toBe(count+2);expect(room.sim.adventure.state.resources.some(n=>n.drop&&n.kind==='hardAntler')).toBe(false);
});
