import {it,expect} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {validateSave} from '../../src/save/format';
import {trailCraftPanel} from '../../src/ui/trail-craft';
const aim={x:0,y:0,z:-1};
function game(){const sim=new GameSimulation();sim.fluid.restore([]);sim.adventure.state.enemies=[];sim.adventure.state.inventory={wood:35,stone:20,resin:15,iron:8,crystal:12};return sim;}
it('makes a basic shield and bow with world resources without a roofed station; preserves failed transactions',()=>{const sim=game(),a=sim.adventure;sim.adventure.action('craft','shield',undefined,aim);expect(a.state.meadows!.gear.offhand).toBe('shield');sim.adventure.action('craft','crudeBow',undefined,aim);expect(a.state.equipment).toBe('crudeBow');sim.adventure.action('craft','woodArrow',undefined,aim);expect(a.state.inventory.woodArrow).toBe(12);const before=structuredClone(a.state);expect(()=>a.action('craft','shield',undefined,aim)).toThrow('持っています');expect(a.state).toEqual(before);});
it('requires regional completion for stronger weapons and quality; repairs selected gear with finite materials',()=>{const sim=game(),a=sim.adventure;expect(()=>a.action('craft','ironSword',undefined,aim)).toThrow('地域');a.state.siteWorld!.completed=[850001];a.action('craft','ironSword',undefined,aim);expect(a.state.equipment).toBe('ironSword');a.action('upgrade','ironSword',undefined,aim);expect(a.state.meadows!.quality.ironSword).toBe(2);expect(()=>a.action('upgrade','ironSword',undefined,aim)).toThrow('地域');a.gear.edit('ironSword',lot=>lot.durability=0);const stone=a.state.inventory.stone;a.action('repair','ironSword',undefined,aim);expect(a.state.inventory.stone).toBe(stone-1);expect(a.state.meadows!.durability.ironSword).toBe(150);expect(()=>a.action('repair','ironSword',undefined,aim)).toThrow('必要ありません');const restored=new GameSimulation(validateSave(sim.save()));expect(restored.adventure.state.meadows!.quality.ironSword).toBe(2);expect(trailCraftPanel(restored.adventure.snapshot())).toContain('品質2');});
it('does not consume materials when projected carrying weight exceeds capacity',()=>{const sim=game(),a=sim.adventure;a.state.inventory={wood:2,stone:1,iron:300};const before={...a.state.inventory};expect(()=>a.action('craft','woodArrow',undefined,aim)).toThrow('空き');expect(a.state.inventory).toEqual(before);});
