import {expect,it} from 'vitest';
import {SessionAuthority} from '../../src/simulation/session';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {stepAdventureEnemy,adventureGuardMultiplier,encounterMetrics,adventureSees,ENCOUNTER_LIMITS} from '../../src/game/adventure-enemies';
import {makeAdventureEnemy,populateAdventureTiles,advanceAdventureWater,validateExploration,EXPLORATION_LIMITS} from '../../src/game/adventure-exploration';
import {ADVENTURE_ENEMY_IDS} from '../../src/content/adventure-encounters';
import {validateSave} from '../../src/save/format';
import {participantSave} from '../../src/save/participant';
import {legacySimulation} from '../helpers/legacy';
const idle={x:0,z:0,jump:false};
function fixture(kind='walker'){const room=new SessionAuthority(),sim=room.sim;sim.world.density=p=>p.y;sim.fluid.restore([]);sim.bodies.length=0;sim.skybound.state.parts=[];sim.companions.state.creatures=[];sim.adventure.state.resources=[];sim.adventure.state.buildings=[];sim.adventure.state.enemies=[];sim.adventure.state.inventory={};sim.adventure.state.meadows!.gear={};sim.adventure.state.exploration={version:1,tiles:[-1,0,1].flatMap(x=>[-1,0,1].map(z=>`surface:${x},${z}`)),pending:[],generated:0,exhausted:false,waterJobs:[]};Object.assign(sim.player,{x:20,y:0,z:8,grounded:true,vy:0});const e=makeAdventureEnemy(sim,kind,{x:25,y:0,z:8});e.cooldown=0;sim.adventure.state.enemies.push(e);return {room,sim,e};}
function brain(sim:GameSimulation,frames:number){for(let i=0;i<frames;i++){sim.tick++;sim.adventure.state.seconds+=1/30;for(const e of sim.adventure.state.enemies)stepAdventureEnemy(sim.adventure,e,1/30);}}
it('keeps all six roles authoritative: approach, front shield/flank, real ranged shot, fixed charge, and 3D hovering',()=>{
 const {room,sim,e}=fixture();const start=e.x;for(let i=0;i<35;i++)room.step(idle);expect(e.x).toBeLessThan(start);expect(e.attackKind).toBeDefined();
 const guard=makeAdventureEnemy(sim,'shellguard',{x:23,y:0,z:8});guard.heading=0;expect(adventureGuardMultiplier(sim.adventure,guard,'physical',{x:23,y:0,z:12})).toBe(.25);expect(adventureGuardMultiplier(sim.adventure,guard,'physical',{x:23,y:0,z:4})).toBe(1);expect(adventureGuardMultiplier(sim.adventure,guard,'fire',{x:23,y:0,z:12})).toBe(1);
 const ranged=fixture('reedspitter');ranged.e.x=30;ranged.e.homeX=30;let fired=false;for(let i=0;i<85;i++){ranged.room.step(idle);fired||=ranged.sim.adventure.projectiles.some(p=>p.owner==='enemy:'+ranged.e.id);}expect(fired).toBe(true);expect(ranged.sim.adventure.state.health).toBeLessThan(25);
 const charging=fixture('cinderunner');brain(charging.sim,1);const heading=charging.e.attackYaw;charging.sim.player.z+=5;brain(charging.sim,45);expect(charging.e.x).toBeLessThan(24);expect(charging.e.z).toBeCloseTo(8);expect(charging.e.attackYaw).toBe(heading);expect(charging.sim.adventure.state.health).toBe(25);
 const flying=fixture('veilray');flying.sim.player.y=5;brain(flying.sim,60);expect(flying.e.y).toBeGreaterThan(2);expect(flying.e.y).toBeLessThan(6.8);
});
it('respects full 3D walls/ceilings, never fires through a wall, and does not affect legacy generator three AI',()=>{
 const {sim,e}=fixture('reedspitter');e.x=30;e.homeX=30;sim.adventure.state.buildings.push({id:9991,definition:'wall',x:25,y:0,z:8,rotation:Math.PI/2,support:4,contents:{}});expect(adventureSees(sim.adventure,e,sim.player)).toBe(false);brain(sim,90);expect(sim.adventure.projectiles).toHaveLength(0);expect(sim.adventure.state.health).toBe(25);
 sim.adventure.state.buildings=[];sim.player.y=10;sim.world.density=p=>p.y<0||p.y>4&&p.y<5?-1:1;sim.tick++;expect(adventureSees(sim.adventure,e,sim.player)).toBe(false);brain(sim,45);expect(sim.adventure.projectiles).toHaveLength(0);
 const old=legacySimulation();expect(stepAdventureEnemy(old.adventure,e,1/30)).toBe(false);
});
it('drops physical currency and material once, stores home altitude, and only respawns away from players',()=>{
 const {sim,e}=fixture();sim.adventure.hit(e,999,'fire');sim.adventure.hit(e,999,'fire');expect(sim.adventure.state.resources.filter(n=>n.drop&&n.kind==='coins').reduce((n,r)=>n+r.amount,0)).toBe(2);expect(sim.adventure.state.resources.some(n=>n.kind==='iron'&&n.drop)).toBe(true);e.respawnAt=0;brain(sim,2);expect(e.health).toBeLessThanOrEqual(0);sim.player.x=55;brain(sim,2);expect(e.health).toBeGreaterThan(0);expect(e.y).toBe(e.homeY);delete e.homeY;const valid=validateSave(sim.save());expect(valid.adventure!.enemies[0].homeY).toBeUndefined();const before=e.y;sim.adventure.state.enemies=valid.adventure!.enemies;brain(sim,1);expect(sim.adventure.state.enemies[0].homeY).toBe(before);
});
it('caps processing at 64 close ordinary enemies and rotates fairly over a larger saved set',()=>{
 const {sim}=fixture();sim.adventure.state.enemies=Array.from({length:128},(_,i)=>makeAdventureEnemy(sim,ADVENTURE_ENEMY_IDS[i%6],{x:30+(i%5),y:0,z:5+(i%8)}));brain(sim,1);expect(encounterMetrics(sim).processed).toBe(ENCOUNTER_LIMITS.active);expect(sim.adventure.state.enemies.filter(e=>e.attackKind)).toHaveLength(64);brain(sim,1);expect(sim.adventure.state.enemies.every(e=>e.attackKind)).toBe(true);
});
it('generates layer-aware original resources/enemies once with persisted pending tiles and budget exhaustion',()=>{
 const sim=new GameSimulation();sim.adventure.state.enemies=[];const p={x:130,y:sim.groundAt(130,-20),z:-20};Object.assign(sim.player,p);const before=sim.adventure.state.resources.length;for(let i=0;i<12;i++){sim.tick++;populateAdventureTiles(sim,sim.adventure.state,p);}expect(sim.adventure.state.resources.length).toBeGreaterThan(before);expect(sim.adventure.state.enemies.every(e=>ADVENTURE_ENEMY_IDS.includes(e.definition))).toBe(true);expect(sim.adventure.state.enemies.every(e=>Math.hypot(e.x-p.x,e.y-p.y,e.z-p.z)>18)).toBe(true);const generated=sim.adventure.state.exploration!.generated,count=sim.adventure.state.resources.length;const restored=new GameSimulation(validateSave(sim.save()));for(let i=0;i<12;i++){restored.tick++;populateAdventureTiles(restored,restored.adventure.state,p);}expect(restored.adventure.state.resources).toHaveLength(count);expect(restored.adventure.state.exploration!.generated).toBe(generated);
 restored.adventure.state.exploration!.generated=EXPLORATION_LIMITS.resources;restored.tick++;populateAdventureTiles(restored,restored.adventure.state,{x:300,y:2,z:20});expect(restored.adventure.state.exploration!.exhausted).toBe(true);expect(restored.adventure.state.resources).toHaveLength(count);expect(restored.adventure.snapshot().exploration).toBeUndefined();expect(restored.adventure.snapshot().explorationStatus?.exhausted).toBe(true);
});
it('persists shared exploration only once and resumes legacy water cursors without duplication or truncation',()=>{
 const {room,sim}=fixture();sim.adventure.state.exploration=undefined;sim.adventure.state.meadows!.worldTiles=['4,0'];sim.adventure.state.meadows!.pendingWaterTiles=Array.from({length:130},(_,i)=>({x:-20+Math.floor(i/10),z:i%10,column:4095}));populateAdventureTiles(sim,sim.adventure.state,{x:140,y:0,z:8});expect(sim.adventure.state.exploration!.waterJobs).toHaveLength(130);expect(sim.adventure.state.exploration!.tiles).toContain('surface:4,0');expect(advanceAdventureWater(sim,sim.adventure.state)).toBe(16);expect(sim.adventure.state.exploration!.waterJobs).toHaveLength(114);const guest=room.join('guest');expect(guest.adventure.state.exploration).toBe(sim.adventure.state.exploration);expect(room.save().members![0].adventure.exploration).toBeUndefined();expect(participantSave(room,'guest').adventure!.exploration!.waterJobs).toHaveLength(114);expect(()=>validateExploration({...sim.adventure.state.exploration,tiles:['sky:NaN,0']})).toThrow();
});
it('supplies all six environments plus the cavern and keeps underground/sky nodes in their actual layer',async()=>{
 const {adventureRegion}=await import('../../src/environment/adventure'),{REGION_RESOURCES}=await import('../../src/content/adventure-encounters');const sim=new GameSimulation(),regions=new Set<string>();sim.adventure.state.enemies=[];
 for(const p of [{x:130,y:2,z:40},{x:-130,y:2,z:-30},{x:150,y:2,z:-20},{x:-60,y:1,z:40},{x:60,y:2,z:-100},{x:80,y:-10.5,z:30},{x:0,y:-10.5,z:80},{x:-76,y:36,z:-70}]){Object.assign(sim.player,p);const before=sim.adventure.state.resources.length;for(let i=0;i<9;i++){sim.tick++;populateAdventureTiles(sim,sim.adventure.state,p);}const added=sim.adventure.state.resources.slice(before);expect(added.length).toBeGreaterThan(0);for(const n of added){const region=adventureRegion(n);regions.add(region);expect(REGION_RESOURCES[region]).toContain(n.kind);if(p.y<-3)expect(n.y).toBeLessThan(-3);if(p.y>17)expect(n.y).toBeGreaterThan(17);}}
 expect([...regions].sort()).toEqual(['cavern','cinder','forest','frost','rock','shore','windfield']);
});
it('lets an actual Session input walk while only one tile transaction is generated per authority tick',()=>{
 const room=new SessionAuthority(),sim=room.sim;sim.adventure.state.enemies=[];sim.fluid.restore([]);Object.assign(sim.player,{x:130,y:sim.groundAt(130,40),z:40,grounded:true});const guest=room.join('guest');Object.assign(guest.player,{x:132,y:sim.player.y,z:40});const x=sim.player.x;for(let i=0;i<32;i++){const count=sim.adventure.state.exploration?.tiles.length??0;room.step({x:1,z:0,jump:false});expect((sim.adventure.state.exploration?.tiles.length??0)-count).toBeLessThanOrEqual(1);}expect(sim.player.x).toBeGreaterThan(x+1);expect(sim.adventure.state.exploration!.tiles.length).toBeGreaterThan(0);const before=sim.adventure.state.exploration!.tiles.length;populateAdventureTiles(sim,sim.adventure.state,sim.player);populateAdventureTiles(sim,sim.adventure.state,guest.player);expect(sim.adventure.state.exploration!.tiles.length-before).toBeLessThanOrEqual(1);expect(room.view('guest').adventure.exploration).toBeUndefined();
});
it('gives the slime an actual wet-healing role without reducing higher-tier saved health',()=>{
 const {sim,e}=fixture('slime');sim.fluid.immersion=()=>1;e.health=12;brain(sim,4);expect(e.health).toBeGreaterThan(12);e.stars=1;e.health=35;brain(sim,4);expect(e.health).toBeGreaterThan(35);expect(e.health).toBeLessThanOrEqual(48);
});
