import {seedInventory} from '../helpers/equipment';
import {it,expect} from 'vitest';
import {SessionAuthority} from '../../src/simulation/session';
import {validateSave} from '../../src/save/format';
import {MARKET} from '../../src/content/adventure-market';
const aim={x:0,y:0,z:-1};
function room(){const room=new SessionAuthority(),a=room.join('alice'),b=room.join('bob'),npc=room.sim.adventure.state.resources.find(n=>n.id===855001)!;for(const actor of[a,b]){Object.assign(actor.player,{x:npc.x,y:npc.y,z:npc.z+1});seedInventory(actor.adventure,{coins:30,wood:5});}return {room,a,b,npc};}
it('trades personal supplies atomically and resumes balances after save/rejoin',()=>{const {room:r,a,b}=room();r.action('alice',{type:'game-action',action:'trade',id:'buy:iron',aim});expect(a.adventure.state.inventory.iron).toBe(2);expect(a.adventure.state.inventory.coins).toBe(22);expect(b.adventure.state.inventory.coins).toBe(30);r.sim.tick+=4;r.action('alice',{type:'game-action',action:'trade',id:'sell:wood',aim});expect(a.adventure.state.inventory.coins).toBe(23);const restored=new SessionAuthority(validateSave(r.save()));expect(restored.join('alice').adventure.state.inventory.coins).toBe(23);for(const offer of MARKET)expect(offer.buy).toBeGreaterThan(offer.sell);});
it('rejects remote, cross-layer, blocked, malformed and overweight exchanges without spending',()=>{const {room:r,a,npc}=room(),before={...a.adventure.state.inventory};a.player.y+=20;expect(()=>r.action('alice',{type:'game-action',action:'trade',id:'buy:iron',aim})).toThrow('案内人');expect(a.adventure.state.inventory).toEqual(before);a.player.y=npc.y;r.sim.adventure.state.buildings.push({id:999998,definition:'wall',x:npc.x,y:npc.y,z:npc.z+.5,rotation:0,support:1,contents:{}});r.sim.tick+=4;expect(()=>r.action('alice',{type:'game-action',action:'trade',id:'buy:iron',aim})).toThrow('案内人');expect(a.adventure.state.inventory).toEqual(before);r.sim.adventure.state.buildings=r.sim.adventure.state.buildings.filter(b=>b.id!==999998);r.sim.tick+=4;expect(()=>r.action('alice',{type:'game-action',action:'trade',id:'buy:iron:extra',aim})).toThrow('一覧');r.sim.tick+=4;seedInventory(a.adventure,{coins:30,iron:299});const overloaded={...a.adventure.state.inventory};expect(()=>r.action('alice',{type:'game-action',action:'trade',id:'buy:iron',aim})).toThrow('空き');expect(a.adventure.state.inventory).toEqual(overloaded);});
