import {afterEach,describe,expect,it,vi} from 'vitest';
import {createArchiveCleanupConfirmation,type ArchiveCleanupInfo} from '../../src/prototype/archive-cleanup-view';
import {campaignSaveControls} from '../../src/prototype/campaign-ui';
class Element extends EventTarget {
 children:Element[]=[];attributes=new Map<string,string>();className='';type='';disabled=false;checked=false;private text='';constructor(readonly tag:string){super();}
 get textContent():string{return this.text+this.children.map(child=>child.textContent).join('');}set textContent(value:string){this.text=value;this.children=[];}
 append(...children:Element[]){this.children.push(...children);}setAttribute(key:string,value:string){this.attributes.set(key,value);}
}
const find=(root:Element,test:(value:Element)=>boolean):Element|undefined=>test(root)?root:root.children.map(child=>find(child,test)).find(Boolean);
const info=(request=1):ArchiveCleanupInfo=>({request,filename:'seven-lights-exact.json',entry:{id:'rs-12345678',scope:'world',savedAt:1000,archivedAt:2000,sizeBytes:2048,reason:'import'}});
function setup(){vi.stubGlobal('document',{createElement:(tag:string)=>new Element(tag),createTextNode:(text:string)=>{const el=new Element('#text');el.textContent=text;return el;}});const abort=new AbortController(),confirm=vi.fn(),cancel=vi.fn();let current=1,allowed=true;const render=(request=1)=>createArchiveCleanupConfirmation(info(request),()=>allowed&&current===request,confirm,cancel,abort.signal) as unknown as Element;const root=render(),check=find(root,el=>el.tag==='input')!,remove=find(root,el=>el.textContent==='選んだ履歴を完全に削除')!,cancelButton=find(root,el=>el.textContent==='やめる')!;return {root,check,remove,cancelButton,confirm,cancel,abort,render,setCurrent:(value:number)=>{current=value;},setAllowed:(value:boolean)=>{allowed=value;}};}
const acknowledge=(check:Element)=>{check.checked=true;check.dispatchEvent(new Event('change'));};
afterEach(()=>vi.unstubAllGlobals());
describe('per-snapshot permanent-deletion confirmation',()=>{
 it('shows exact target, timestamp, bytes, irreversible warning and local export filename',()=>{const {root,remove}=setup();expect(root.attributes.get('aria-label')).toBe('履歴の完全削除の確認');for(const text of ['rs-12345678','保存日時','2.0 KiB','seven-lights-exact.json','完全に削除','元に戻せません','移行用原本は保持','端末でファイルを確認'])expect(root.textContent).toContain(text);expect(remove.disabled).toBe(true);});
 it('requires a separate file-receipt acknowledgement and consumes confirmation exactly once',()=>{const {check,remove,confirm}=setup();remove.dispatchEvent(new Event('click'));expect(confirm).not.toHaveBeenCalled();acknowledge(check);expect(remove.disabled).toBe(false);remove.dispatchEvent(new Event('click'));remove.dispatchEvent(new Event('click'));expect(confirm).toHaveBeenCalledTimes(1);expect(remove.disabled).toBe(true);});
 it('cancel followed by reopen resets acknowledgement and makes the old confirmation unusable',()=>{const s=setup();acknowledge(s.check);s.cancelButton.dispatchEvent(new Event('click'));s.remove.dispatchEvent(new Event('click'));expect(s.cancel).toHaveBeenCalledTimes(1);expect(s.confirm).not.toHaveBeenCalled();s.setCurrent(2);const reopened=s.render(2),newCheck=find(reopened,el=>el.tag==='input')!,newRemove=find(reopened,el=>el.textContent==='選んだ履歴を完全に削除')!;expect(newCheck.checked).toBe(false);expect(newRemove.disabled).toBe(true);s.remove.dispatchEvent(new Event('click'));expect(s.confirm).not.toHaveBeenCalled();acknowledge(newCheck);newRemove.dispatchEvent(new Event('click'));expect(s.confirm).toHaveBeenCalledTimes(1);});
 it('rejects detached confirmations after newer selection, guest transition or lost permission',()=>{const s=setup();acknowledge(s.check);s.setCurrent(2);s.remove.dispatchEvent(new Event('click'));expect(s.confirm).not.toHaveBeenCalled();s.setCurrent(1);s.setAllowed(false);s.remove.dispatchEvent(new Event('click'));expect(s.confirm).not.toHaveBeenCalled();});
 it('aborting the view prevents stale pointer or keyboard-driven clicks',()=>{const s=setup();acknowledge(s.check);s.abort.abort();s.remove.dispatchEvent(new Event('click'));s.cancelButton.dispatchEvent(new Event('click'));expect(s.confirm).not.toHaveBeenCalled();expect(s.cancel).not.toHaveBeenCalled();});
 it('does not render snapshot text as executable markup',()=>{const s=setup();expect(find(s.root,el=>el.tag==='script')).toBeUndefined();});
 it('blocks world switching while recovery is pending and all save actions for guests',()=>{expect(campaignSaveControls({available:true,label:'',status:'',cleanupPending:'recovery'})).toEqual({save:true,continue:true,newGame:false,restore:false});expect(campaignSaveControls({available:true,label:'',status:'',disabledForGuest:true})).toEqual({save:false,continue:false,newGame:false,restore:false});});
});
