import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {createBuildGhost} from '../../src/prototype/rendering/campaign-decor';
import type {PlacementPreview} from '../../src/prototype/core/survival';
const result=(ok=true):PlacementPreview=>({ok,message:ok?'設置可能':'支えが必要',bounds:{min:{x:1,y:2,z:3},max:{x:3,y:3,z:6}},target:{x:2,y:2,z:4.5},recipe:'wall',rotation:1});
describe('bounded reusable building ghost',()=>{
 it('throttles placement validation to ten times per second',()=>{const scene=new THREE.Scene(),preview=vi.fn(()=>result()),ghost=createBuildGhost(scene,preview);for(let t=0;t<1000;t+=10)ghost.update(true,t);expect(preview).toHaveBeenCalledTimes(10);ghost.dispose();});
 it('uses validated bounds and green/red state without new geometry',()=>{const scene=new THREE.Scene();let value=result();const ghost=createBuildGhost(scene,()=>value),group=scene.getObjectByName('building-preview')!;const mesh=group.children[0] as THREE.Mesh<THREE.BoxGeometry,THREE.MeshBasicMaterial>,geometry=mesh.geometry;ghost.update(true,0);expect(group.visible).toBe(true);expect(group.position.toArray()).toEqual([2,2.5,4.5]);expect(group.scale.toArray()).toEqual([2,1,3]);expect(mesh.material.color.getHex()).toBe(0x68db94);value=result(false);ghost.update(true,100);expect(mesh.geometry).toBe(geometry);expect(mesh.material.color.getHex()).toBe(0xee736c);expect(group.userData.message).toBe('支えが必要');ghost.dispose();});
 it('hides immediately when cancelled or target is missing',()=>{const scene=new THREE.Scene();let value:PlacementPreview|null=result();const ghost=createBuildGhost(scene,()=>value),group=scene.getObjectByName('building-preview')!;ghost.update(true,0);ghost.update(false,1);expect(group.visible).toBe(false);value=null;ghost.update(true,2);expect(group.visible).toBe(false);value=result();value.bounds.max.x=Infinity;ghost.update(true,102);expect(group.visible).toBe(false);ghost.dispose();});
 it('disposes every GPU resource once and detaches from scene',()=>{const scene=new THREE.Scene(),preview=vi.fn(()=>result()),ghost=createBuildGhost(scene,preview),group=scene.getObjectByName('building-preview')!,disposed=vi.fn();for(const object of group.children){const mesh=object as THREE.Mesh;mesh.geometry.addEventListener('dispose',disposed);(mesh.material as THREE.Material).addEventListener('dispose',disposed);}ghost.dispose();ghost.dispose();ghost.update(true,0);expect(disposed).toHaveBeenCalledTimes(4);expect(preview).not.toHaveBeenCalled();expect(scene.getObjectByName('building-preview')).toBeUndefined();});
});
