import {describe,it,expect} from 'vitest';
import {REGIONS,REGIONAL_POINTS,REGIONAL_ENEMIES,REGIONAL_UPGRADES} from '../../src/prototype/core/regions';
import {CampaignSystem,CAMPAIGN_ITEMS,CAMPAIGN_RECIPES,CAMPAIGN_POINTS,validCampaignState,isShrouded,isDeepShroud} from '../../src/prototype/core/campaign';
const position=(id:string)=>({...CAMPAIGN_POINTS.find(p=>p.id===id)!.position});
const setup=()=>{const materials:Record<number,number>={2:0,3:100,4:100,6:100,7:100,10:100};return new CampaignSystem(materials);};
const rescue=(c:CampaignSystem)=>{expect(c.interact('hearth',position('hearth')).ok).toBe(true);expect(c.interact('artisan',position('artisan')).ok).toBe(true);};
const gear=(c:CampaignSystem,weapon='iron-blade')=>{for(const id of [weapon,'hide-coat','grapple','glider']){expect(c.craft(id,position('hearth')).ok).toBe(true);expect(c.equip(id).ok).toBe(true);}};
describe('original campaign progression',()=>{
 it('finishes a finite arc and retains free play after the final destination',()=>{const c=setup();rescue(c);gear(c);expect(c.objective().id).toBe('cache');expect(c.interact('mist-cache',position('mist-cache')).ok).toBe(true);expect(c.defeat(1,'warden').ok).toBe(true);expect(c.interact('hearth',position('hearth')).ok).toBe(true);expect(c.state.flameTier).toBe(2);expect(c.interact('ridge-gate',position('ridge-gate')).ok).toBe(true);expect(c.interact('nextcamp',position('nextcamp')).ok).toBe(true);expect(c.complete).toBe(true);expect(c.objective().id).toBe('region-hearthfield');expect(c.overallComplete).toBe(false);expect(c.travel('nextcamp').position).toEqual(position('nextcamp'));expect(c.craft('berry-meal',position('hearth')).ok).toBe(true);expect(validCampaignState(c.snapshot())).toBe(true);});
 it.each(['bow','staff'])('supports %s as the main weapon without requiring a sword',weapon=>{const c=setup();expect(c.craft(weapon,position('hearth')).ok).toBe(true);rescue(c);for(const id of ['hide-coat','grapple','glider'])c.craft(id,position('hearth'));for(const id of [weapon,'hide-coat','grapple','glider'])c.equip(id);expect(c.state.completed).toContain('forge');expect(c.equippedWeapon).toBe(weapon);expect(c.spellMultiplier).toBe(weapon==='staff'?1.2:1);});
 it('cannot bypass station, proximity, traversal gear, or region gates',()=>{const c=setup();expect(c.craft('iron-blade',position('hearth')).ok).toBe(false);expect(c.interact('artisan',position('artisan')).ok).toBe(false);expect(c.interact('hearth',{x:0,y:0,z:100}).ok).toBe(false);expect(c.travel('nextcamp').ok).toBe(false);rescue(c);expect(c.craft('iron-blade',position('artisan')).ok).toBe(false);expect(c.interact('mist-cache',position('mist-cache')).ok).toBe(false);expect(c.interact('ridge-gate',position('ridge-gate')).ok).toBe(false);expect(c.interact('nextcamp',position('nextcamp')).ok).toBe(false);});
 it('keeps starter progression acyclic with enough rescue fabric for gear and traversal',()=>{const c=new CampaignSystem({3:6,4:18,6:4,7:2,10:0});rescue(c);gear(c);expect(c.materials[10]).toBe(2);expect(c.materials[6]).toBe(0);expect(c.materials[4]).toBe(0);});
 it('does not repeat artisan, quest, cache, or enemy rewards',()=>{const c=setup();rescue(c);const resources={...c.materials};c.interact('artisan',position('artisan'));expect(c.materials).toEqual(resources);gear(c);c.interact('mist-cache',position('mist-cache'));const xp=c.state.xp;c.interact('mist-cache',position('mist-cache'));c.objective();c.questRows();expect(c.state.xp).toBe(xp);expect(c.state.items['mist-core']).toBe(1);c.defeat(1,'warden');const after=c.snapshot();expect(c.defeat(1,'warden').ok).toBe(false);expect(c.snapshot()).toEqual(after);});
 it('awards an early boss kill without softlocking later quests',()=>{const c=setup();c.defeat(1,'warden');rescue(c);gear(c);c.interact('mist-cache',position('mist-cache'));c.interact('hearth',position('hearth'));expect(c.state.flameTier).toBe(2);expect(c.state.items['warden-core']).toBe(0);});
});
describe('campaign transactions and effects',()=>{
 it('has a complete linked item and recipe catalogue',()=>{expect(new Set(Object.values(CAMPAIGN_ITEMS).map(i=>i.id)).size).toBe(Object.keys(CAMPAIGN_ITEMS).length);for(const i of Object.values(CAMPAIGN_ITEMS)){expect(i.label&&i.description&&i.icon&&i.source).toBeTruthy();expect(i.stackLimit).toBeGreaterThan(0);}for(const r of CAMPAIGN_RECIPES){expect(CAMPAIGN_ITEMS[r.output]).toBeDefined();expect(Object.values(r.cost).every(n=>Number.isInteger(n)&&n>0)).toBe(true);}});
 it('crafts quantities atomically and refuses unknown, invalid, missing, or over-cap requests',()=>{const c=setup();rescue(c);const before={...c.materials};expect(c.craft('arrows',position('hearth'),2).ok).toBe(true);expect(c.state.items.arrows).toBe(16);expect(c.materials[3]).toBe(before[3]-2);expect(c.materials[4]).toBe(before[4]-2);const saved=c.snapshot(),m={...c.materials};for(const [id,n] of [['arrows',0],['arrows',NaN],['arrows',100000],['unknown',1]] as const)expect(c.craft(id,position('hearth'),n).ok).toBe(false);expect(c.snapshot()).toEqual(saved);expect(c.materials).toEqual(m);c.craft('iron-blade',position('hearth'));const next={...c.materials};expect(c.craft('iron-blade',position('hearth')).ok).toBe(false);expect(c.materials).toEqual(next);c.materials[7]=0;expect(c.craft('berry-meal',position('hearth')).ok).toBe(false);});
 it('consumes exactly one arrow and does not go negative',()=>{const c=setup();expect(c.consumeAmmo()).toBe(false);c.craft('arrows',position('hearth'));expect(c.consumeAmmo()).toBe(true);expect(c.state.items.arrows).toBe(7);expect(c.consumeAmmo(-1)).toBe(false);expect(c.consumeAmmo(8)).toBe(false);expect(c.state.items.arrows).toBe(7);});
 it('equipment, timed meal, and skills change actual modifier outputs',()=>{const c=setup();rescue(c);gear(c);expect(c.attackMultiplier).toBe(1.3);expect(c.damageReduction).toBe(.2);c.craft('berry-meal',position('hearth'));c.consume('berry-meal');expect(c.maxHp).toBe(120);expect(c.maxStamina).toBe(115);expect(c.learn('attunement').ok).toBe(false);expect(c.learn('endurance').ok).toBe(true);expect(c.moveMultiplier).toBe(1.08);const points=c.state.skillPoints;c.resetSkills();expect(c.state.skillPoints).toBe(points+1);expect(c.moveMultiplier).toBe(1);for(let i=0;i<180;i++)c.tick(1,{position:position('hearth')});expect(c.maxHp).toBe(100);});
 it('rejects bandaging at full health, consumes for actual missing health',()=>{const c=setup();c.craft('bandage',position('hearth'));expect(c.consume('bandage',100).ok).toBe(false);expect(c.has('bandage')).toBe(true);expect(c.consume('bandage',90).heal).toBe(10);expect(c.has('bandage')).toBe(false);});
 it('requires a roof and lit camp for rest, bounds shelter and food sidequest rewards',()=>{const c=setup();expect(c.rest(position('hearth'),true).ok).toBe(false);rescue(c);expect(c.rest(position('hearth'),false).ok).toBe(false);c.craft('berry-meal',position('hearth'));c.consume('berry-meal');expect(c.rest(position('hearth'),true).ok).toBe(true);expect(c.staminaRegenMultiplier).toBe(1.4);c.recordBuild('wall');c.recordBuild('floor');expect(c.state.completed).toEqual(expect.arrayContaining(['shelter','prepared']));const xp=c.state.xp;c.recordBuild('wall');c.recordBuild('floor');c.rest(position('hearth'),true);expect(c.state.xp).toBe(xp);});
 it('depletes shroud time, applies damage only at expiry, refills outside and respects stronger flame',()=>{const c=setup(),p=position('mist-cache');expect(isShrouded(p)).toBe(true);for(let i=0;i<59;i++)expect(c.tick(1,{position:p}).damage).toBe(0);expect(c.tick(1,{position:p}).damage).toBe(20);expect(c.tick(1,{position:position('hearth')}).damage).toBe(0);expect(c.state.shroudSeconds).toBe(5);const deep={x:0,y:.25,z:-22};expect(isDeepShroud(deep)).toBe(true);c.state.shroudSeconds=60;c.tick(1,{position:deep});expect(c.state.shroudSeconds).toBe(54);c.state.flameTier=2;c.state.shroudSeconds=90;c.tick(1,{position:deep});expect(c.state.shroudSeconds).toBe(89);});
 it('30 and 120 Hz shroud damage and elapsed timers agree',()=>{const run=(hz:number)=>{const c=setup();let damage=0;c.state.shroudSeconds=0;for(let i=0;i<hz*3;i++)damage+=c.tick(1/hz,{position:position('mist-cache')}).damage;return damage;};expect(run(30)).toBeCloseTo(run(120),7);});
});
describe('death, recovery, and atomic save hydration',()=>{
 it('drops a quarter of materials once, retains equipment/quest items, and recovers once',()=>{const c=setup();rescue(c);gear(c);c.defeat(1,'warden');const before={...c.materials},p=position('artisan');expect(c.die(p).ok).toBe(true);const bag=c.snapshot().deathBag;expect(c.die(p).ok).toBe(false);expect(c.state.deathBag).toEqual(bag);expect(c.has('warden-core')).toBe(true);expect(c.canGlide).toBe(true);c.respawn();expect(c.recover(position('hearth')).ok).toBe(false);expect(c.recover(p).ok).toBe(true);expect(c.materials).toEqual(before);expect(c.recover(p).ok).toBe(false);});
 it('preserves a previous unrecovered bag when dying again',()=>{const c=setup();const before={...c.materials};c.die(position('artisan'));c.respawn();c.die(position('mist-cache'));c.respawn();c.recover(position('mist-cache'));expect(c.materials).toEqual(before);});
 it('round-trips all campaign state without replacing shared materials',()=>{const c=setup();rescue(c);gear(c);c.learn('vigor');c.die(position('artisan'));const saved=c.snapshot(),m=c.materials;expect(c.restore(saved)).toBe(true);expect(c.materials).toBe(m);expect(c.snapshot()).toEqual(saved);saved.items.grapple=0;expect(c.state.items.grapple).toBe(1);});
 it('rejects malformed values atomically including unknown items, NaN, duplicated rewards and impossible equipment',()=>{const c=setup();rescue(c);gear(c);const before=c.snapshot();const corruptions=[{xp:NaN},{items:{unknown:1}},{claimedEnemies:['1','1']},{skills:['attunement']},{skillPoints:99},{equipment:{...before.equipment,armor:'grapple'}},{deathBag:{position:{x:NaN,y:0,z:0},materials:{4:1}}},{completed:['gather','gather']},{shroudSeconds:-1},{campUnlocked:true,gateOpen:false}];for(const change of corruptions){expect(c.restore({...before,...change})).toBe(false);expect(c.snapshot()).toEqual(before);}expect(c.restore(null)).toBe(false);});
});
describe('durability, upgrades, sockets and salvage',()=>{
 it('warns when durability gets low, preserves attacks when broken, and repairs transactionally',()=>{const c=setup();rescue(c);gear(c);expect(c.consumeAttackDurability(80).message).toContain('20');expect(c.gearInfo('iron-blade').durability).toBe(20);expect(c.consumeAttackDurability(20).message).toContain('破損');expect(c.attackMultiplier).toBe(.65);const before=c.materials[6];expect(c.repair('iron-blade',position('artisan')).ok).toBe(false);expect(c.repair('iron-blade',position('hearth')).ok).toBe(true);expect(c.materials[6]).toBe(before-4);expect(c.attackMultiplier).toBe(1.3);expect(c.repair('iron-blade',position('hearth')).ok).toBe(false);});
 it('applies armor wear without removing all damage protection',()=>{const c=setup();rescue(c);gear(c);c.consumeArmorDurability(100);expect(c.damageReduction).toBe(.1);expect(c.repair('hide-coat',position('hearth')).ok).toBe(true);expect(c.damageReduction).toBe(.2);});
 it('upgrades through region gates to +3 and rejects further material consumption',()=>{const c=setup();rescue(c);gear(c);expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(true);expect(c.attackMultiplier).toBeCloseTo(1.43);expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(false);c.state.flameTier=2;expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(true);expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(false);c.state.gateOpen=true;c.state.campUnlocked=true;expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(true);const m={...c.materials};expect(c.upgrade('iron-blade',position('hearth')).ok).toBe(false);expect(c.materials).toEqual(m);expect(c.gearInfo('iron-blade').upgrade).toBe(3);});
 it('socket attach/remove conserves gems and rejects incompatible slots and duplicate applications',()=>{const c=setup();rescue(c);gear(c);c.craft('ember-gem',position('hearth'));expect(c.socket('grapple','ember-gem',position('hearth')).ok).toBe(false);expect(c.socket('iron-blade','ember-gem',position('hearth')).ok).toBe(true);expect(c.state.items['ember-gem']).toBe(0);expect(c.attackMultiplier).toBeCloseTo(1.456);expect(c.socket('iron-blade','ember-gem',position('hearth')).ok).toBe(false);expect(c.socket('iron-blade',null,position('hearth')).ok).toBe(true);expect(c.state.items['ember-gem']).toBe(1);expect(c.attackMultiplier).toBe(1.3);});
 it('refuses unsafe salvage, previews exact return, and cannot duplicate returned materials',()=>{const c=setup();rescue(c);gear(c);expect(c.salvage('iron-blade',true).ok).toBe(false);expect(c.salvage('grapple',true).ok).toBe(false);expect(c.salvage('warden-core',true).ok).toBe(false);c.unequip('weapon');const preview=c.salvagePreview('iron-blade');expect(preview.materials).toEqual({4:2,6:3});const before={...c.materials};expect(c.salvage('iron-blade').ok).toBe(false);expect(c.materials).toEqual(before);expect(c.salvage('iron-blade',true).ok).toBe(true);expect(c.materials[4]).toBe(before[4]+2);expect(c.materials[6]).toBe(before[6]+3);expect(c.salvage('iron-blade',true).ok).toBe(false);expect(c.has('iron-blade')).toBe(false);expect(validCampaignState(c.snapshot())).toBe(true);});
 it('saves gear state and keeps the shared item ledger identity on restore',()=>{const c=setup();rescue(c);gear(c);c.consumeAttackDurability(25);c.upgrade('iron-blade',position('hearth'));c.craft('ember-gem',position('hearth'));c.socket('iron-blade','ember-gem',position('hearth'));const saved=c.snapshot(),ledger=c.state.items;expect(c.restore(saved)).toBe(true);expect(c.state.items).toBe(ledger);expect(c.gearInfo('iron-blade')).toEqual({durability:75,maxDurability:100,upgrade:1,socket:'ember-gem'});expect(c.restore({...saved,gearState:{...saved.gearState,'iron-blade':{...saved.gearState['iron-blade'],durability:NaN}}})).toBe(false);});
});
const finishChapter=(c:CampaignSystem)=>{rescue(c);gear(c);c.interact('mist-cache',position('mist-cache'));c.defeat(1,'warden');c.interact('hearth',position('hearth'));c.interact('ridge-gate',position('ridge-gate'));c.interact('nextcamp',position('nextcamp'));};
const regionalPosition=(id:string)=>({...REGIONAL_POINTS.find(p=>p.id===id)!.position});
describe('seven-region continuation and canonical rewards',()=>{
 it('finishes all seven pockets in dependency order with finite final completion',()=>{const c=setup();finishChapter(c);expect(c.regionUnlocked('hearthfield')).toBe(true);expect(c.regionUnlocked('resinwood')).toBe(false);expect(c.interactRegional('rg-field-cache',regionalPosition('rg-field-cache')).ok).toBe(true);expect(c.interactRegional('rg-field-herb',regionalPosition('rg-field-herb')).ok).toBe(true);
  const caches=['rg-wood-cache','rg-fen-cache','rg-mesa-cache','rg-ash-cache','rg-rime-cache','rg-lake-cache'];
  for(let i=0;i<REGIONAL_UPGRADES.length;i++){const u=REGIONAL_UPGRADES[i];expect(c.upgradeRegion(u.id,position('hearth')).ok).toBe(true);expect(c.regionUnlocked(u.opens)).toBe(true);for(const e of REGIONAL_ENEMIES.filter(e=>e.region===u.opens&&e.boss))expect(c.defeatRegional(e.id).ok).toBe(true);expect(c.interactRegional(caches[i],regionalPosition(caches[i])).ok).toBe(true);}
  expect(c.regionTier).toBe(5);expect(c.overallComplete).toBe(true);expect(c.objective().id).toBe('complete');expect(c.regionQuestRows().every(q=>q.status==='complete')).toBe(true);expect(validCampaignState(c.snapshot())).toBe(true);expect(c.shroudMaximum).toBe(180);expect(c.craft('berry-meal',position('hearth')).ok).toBe(true);
 });
 it('shows the next upgrade and rejects skipping ahead or collecting a locked region',()=>{const c=setup();finishChapter(c);expect(c.interactRegional('rg-lake-cache',regionalPosition('rg-lake-cache')).ok).toBe(false);expect(c.defeatRegional(111).ok).toBe(false);expect(c.upgradeRegion('lake-access',position('hearth')).ok).toBe(false);c.interactRegional('rg-field-cache',regionalPosition('rg-field-cache'));expect(c.objective().label).toContain('琥珀枝の森');expect(c.interact('hearth',position('hearth')).ok).toBe(false);c.interactRegional('rg-field-herb',regionalPosition('rg-field-herb'));expect(c.interact('hearth',position('hearth')).ok).toBe(true);const count=c.state.items['sun-herb'];expect(c.upgradeRegion('wood-access',position('hearth')).ok).toBe(false);expect(c.state.items['sun-herb']).toBe(count);});
 it('honors night gates and one-time POI, exploration, and enemy XP',()=>{const c=setup();finishChapter(c);c.interactRegional('rg-field-cache',regionalPosition('rg-field-cache'));c.interactRegional('rg-field-herb',regionalPosition('rg-field-herb'));c.upgradeRegion('wood-access',position('hearth'));expect(c.interactRegional('rg-night-lore',regionalPosition('rg-night-lore'),12).ok).toBe(false);expect(c.interactRegional('rg-night-lore',regionalPosition('rg-night-lore'),23).ok).toBe(true);const xp=c.state.xp;expect(c.interactRegional('rg-night-lore',regionalPosition('rg-night-lore'),23).ok).toBe(false);expect(c.state.xp).toBe(xp);c.tick(.1,{position:regionalPosition('rg-night-lore')});const explored=c.state.xp;c.tick(.1,{position:regionalPosition('rg-night-lore')});expect(c.state.xp).toBe(explored);expect(c.defeatRegional(102).ok).toBe(true);const killed=c.state.xp;expect(c.defeatRegional(102).ok).toBe(false);expect(c.state.xp).toBe(killed);});
 it('uses discovered hearths only for regional fast travel',()=>{const c=setup();finishChapter(c);expect(c.travel('rg-field-hearth').ok).toBe(false);expect(c.interactRegional('rg-field-hearth',regionalPosition('rg-field-hearth')).ok).toBe(true);expect(c.travel('rg-field-hearth').position).toEqual(regionalPosition('rg-field-hearth'));});
 it('does not claim a reward when capacity blocks it and permits a later retry',()=>{const c=setup();finishChapter(c);c.state.items['sun-herb']=200;const xp=c.state.xp;expect(c.interactRegional('rg-field-herb',regionalPosition('rg-field-herb')).ok).toBe(false);expect(c.state.claimedPoints).not.toContain('rg-field-herb');expect(c.state.xp).toBe(xp);c.state.items['sun-herb']=197;expect(c.interactRegional('rg-field-herb',regionalPosition('rg-field-herb')).ok).toBe(true);expect(c.state.items['sun-herb']).toBe(200);});
 it('has catalogue definitions for every regional item reward and upgrade cost',()=>{for(const reward of [...REGIONAL_POINTS.map(p=>p.reward),...REGIONAL_ENEMIES.map(e=>e.reward)])for(const id of Object.keys(reward.items??{}))expect(CAMPAIGN_ITEMS[id],id).toBeDefined();for(const u of REGIONAL_UPGRADES)for(const id of [...Object.keys(u.cost),...u.requires])expect(CAMPAIGN_ITEMS[id],id).toBeDefined();expect(REGIONS).toHaveLength(7);});
});
