import {describe,it,expect,vi,afterEach} from 'vitest';
import {CampaignRelayRoom,validRelayCheckpoint,type RoomWire} from '../../src/prototype/network/relay-room';
import {CampaignCoopClient,type CampaignCoopCallbacks} from '../../src/prototype/network/coop-client';
import {CAMPAIGN_PROTOCOL,MAX_PACKET_BYTES,freshGuestInput,validCommand,splitSnapshot,snapshotChecksum,randomRoomCode,inviteFragment,roomFromFragment,type ServerPacket} from '../../src/prototype/network/protocol';
const key=(n:string)=>n.repeat(64),epoch='epoch-test-001';
function harness(){let now=0;const room=new CampaignRelayRoom(epoch,()=>now);const outputs=new Map<string,ServerPacket[]>(),closed=new Map<string,number>();const connect=(id:string,mode:'create'|'join',resumeKey=key(mode==='create'?'a':'b'))=>{outputs.set(id,[]);const wire:RoomWire={send:p=>outputs.get(id)!.push(p),close:code=>{closed.set(id,code);}};room.connect(id,wire);room.receive(id,JSON.stringify({type:'hello',protocol:CAMPAIGN_PROTOCOL,mode,resumeKey}));};const send=(id:string,p:Record<string,unknown>)=>room.receive(id,JSON.stringify({epoch,...p}));const publish=(text='{"world":1}',sequence=1)=>{const t=splitSnapshot(text,sequence);send('host',{type:'snapshot-begin',manifest:t.manifest});for(let i=0;i<t.chunks.length;i++)send('host',{type:'snapshot-chunk',sequence,index:i,data:t.chunks[i]});send('host',{type:'snapshot-end',sequence});};return {room,outputs,closed,connect,send,publish,advance:(ms:number)=>{now+=ms;room.tick();}};}
describe('campaign bounded relay',()=>{
 it('rejects nested prototype keys and unbounded command values',()=>{expect(validCommand(JSON.parse('{"action":"craft","payload":{"__proto__":{"polluted":true}}}'))).toBe(false);expect(validCommand({action:'craft',payload:{n:Infinity}})).toBe(false);expect(validCommand({action:'craft',payload:{recipe:'wall',count:2}})).toBe(true);});
 it('routes bounded latest input and host frames without durable receipts',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.publish();const input={x:1,z:0,yaw:0,pitch:0,block:false,sprint:true},before=h.room.checkpoint();h.send('guest',{type:'input',sequence:1,input});h.send('guest',{type:'input',sequence:1,input});expect(h.outputs.get('host')!.filter(p=>p.type==='input')).toHaveLength(1);h.send('host',{type:'frame',sequence:1,payload:{players:[{x:1,hp:100}]}});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'frame',sequence:1});expect(h.room.checkpoint()).toEqual(before);h.send('guest',{type:'frame',sequence:2,payload:{}});expect(h.outputs.get('guest')!.at(-1)?.type).toBe('notice');h.send('guest',{type:'input',sequence:2,input:{...input,x:2}});expect(h.outputs.get('guest')!.at(-1)?.type).toBe('notice');expect(freshGuestInput(input,0,351)).toMatchObject({x:0,z:0,block:false,sprint:false});});
 it('requires explicit host creation, two identities, protocol handshake and private host resume',()=>{const h=harness();h.connect('early','join');expect(h.outputs.get('early')!.at(-1)?.type).toBe('notice');h.room.disconnect('early');h.connect('host','create');h.connect('guest','join');h.connect('third','join',key('c'));expect(h.outputs.get('third')!.at(-1)).toMatchObject({type:'notice',message:'This room is limited to two players'});h.room.disconnect('third');h.connect('takeover','create',key('c'));expect(h.outputs.get('takeover')!.at(-1)).toMatchObject({type:'notice',message:'Host already exists'});expect(h.outputs.get('host')!.some(p=>p.type==='welcome'&&p.role==='host')).toBe(true);});
 it('requires host snapshot before guest commands and pauses on host disconnect',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.send('guest',{type:'command',sequence:1,commandId:'command-0001',command:{action:'interact',payload:{target:'hearth'}}});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'notice',message:'World paused: awaiting host snapshot'});h.publish();h.send('guest',{type:'command',sequence:1,commandId:'command-0001',command:{action:'interact',payload:{target:'hearth'}}});expect(h.outputs.get('host')!.at(-1)?.type).toBe('command');h.room.disconnect('host');expect(h.outputs.get('guest')!.some(p=>p.type==='status'&&!p.hostOnline)).toBe(true);expect(h.outputs.get('guest')!.some(p=>p.type==='ack'&&p.accepted===null)).toBe(true);});
 it('denies editing by default and only host may grant it',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.publish();h.send('guest',{type:'permission',guestBuild:true});h.send('guest',{type:'command',sequence:1,commandId:'command-build1',command:{action:'build',payload:{recipe:'wall'}}});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'ack',accepted:false});h.send('host',{type:'permission',guestBuild:true});h.send('guest',{type:'command',sequence:2,commandId:'command-build2',command:{action:'build',payload:{recipe:'wall'}}});expect(h.outputs.get('host')!.at(-1)).toMatchObject({type:'command',commandId:'command-build2'});});
 it('deduplicates commands before and after host acknowledgment',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.publish();const packet={type:'command',sequence:1,commandId:'command-unique',command:{action:'interact',payload:{id:'cache'}}};h.send('guest',packet);h.send('guest',packet);expect(h.outputs.get('host')!.filter(p=>p.type==='command')).toHaveLength(1);h.send('host',{type:'ack',commandId:'command-unique',accepted:true,message:'opened'});h.send('guest',packet);expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'ack',accepted:true});expect(h.outputs.get('host')!.filter(p=>p.type==='command')).toHaveLength(1);h.send('guest',{...packet,commandId:'command-different'});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'notice',message:'Stale command sequence'});});
 it('rejects stale epochs, malformed poses, reused IDs and unauthorized snapshots',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.publish();h.send('guest',{type:'pose',epoch:'old-epoch',sequence:1,pose:{}});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'notice',message:'Stale room epoch'});h.send('guest',{type:'pose',sequence:1,pose:{x:Infinity}});expect(h.outputs.get('guest')!.at(-1)?.type).toBe('notice');h.send('guest',{type:'snapshot-begin',manifest:splitSnapshot('{}',2).manifest});expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'notice',message:'Only the host publishes world state'});});
 it('checksums complete chunked snapshots before publishing, including Unicode boundaries',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');const text='x'.repeat(8191)+'🌲'+'木'.repeat(15000);h.publish(text);const chunks=h.outputs.get('guest')!.filter((p):p is Extract<ServerPacket,{type:'snapshot-chunk'}>=>p.type==='snapshot-chunk');expect(chunks.map(p=>p.data).join('')).toBe(text);expect(h.outputs.get('guest')!.at(-1)).toMatchObject({type:'snapshot-end',sequence:1});const bad=splitSnapshot('bad',2);bad.manifest.checksum='00000000';h.send('host',{type:'snapshot-begin',manifest:bad.manifest});h.send('host',{type:'snapshot-chunk',sequence:2,index:0,data:'bad'});h.send('host',{type:'snapshot-end',sequence:2});expect(h.outputs.get('host')!.at(-1)).toMatchObject({type:'notice',message:'Snapshot checksum mismatch'});expect(h.room.checkpoint().snapshotSequence).toBe(1);});
 it('bounds packets and rate, expires leases and incomplete handshakes',()=>{const h=harness();h.connect('host','create');h.room.receive('host','x'.repeat(MAX_PACKET_BYTES+1));expect(h.closed.get('host')).toBe(1009);const g=harness();g.connect('host','create');g.connect('guest','join');g.publish();g.advance(13000);expect(g.closed.get('host')).toBe(4000);expect(g.room.online).toBe(false);const r=harness();r.connect('host','create');for(let i=0;i<241;i++)r.send('host',{type:'ping'});expect(r.closed.get('host')).toBe(1008);});
 it('persists identity/receipt metadata across new epochs without persisting worlds',()=>{const h=harness();h.connect('host','create');h.connect('guest','join');h.publish();h.send('guest',{type:'command',sequence:1,commandId:'command-pending',command:{action:'attack',payload:{}}});const saved=h.room.checkpoint();expect(validRelayCheckpoint(saved)).toBe(true);expect(JSON.stringify(saved)).not.toContain('world');const room=new CampaignRelayRoom('epoch-restart-002',()=>0,saved),out:ServerPacket[]=[];room.connect('intruder',{send:p=>out.push(p),close:()=>{}});room.receive('intruder',JSON.stringify({type:'hello',protocol:1,mode:'create',resumeKey:key('c')}));expect(out.at(-1)).toMatchObject({type:'notice',message:'Host already exists'});expect(room.checkpoint().receipts[0][1].accepted).toBeNull();expect(room.checkpoint().snapshotSequence).toBe(1);});
 it('does not leak host resume keys through invites or outgoing packets',()=>{const room=randomRoomCode();expect(room).toHaveLength(64);expect(roomFromFragment(inviteFragment(room))).toBe(room);expect(roomFromFragment('#campaign-room=short')).toBeNull();const h=harness();h.connect('host','create');h.connect('guest','join');expect(JSON.stringify([...h.outputs])).not.toContain(key('a'));});
});
class MockSocket {
 static sockets:MockSocket[]=[];readyState=0;bufferedAmount=0;sent:string[]=[];onopen:(()=>void)|null=null;onclose:((e:{code:number})=>void)|null=null;onmessage:((e:{data:string})=>void)|null=null;onerror:(()=>void)|null=null;
 constructor(readonly url:string){MockSocket.sockets.push(this);}send(text:string){this.sent.push(text);}close(){this.readyState=3;this.onclose?.({code:1000});}open(){this.readyState=1;this.onopen?.();}packet(p:ServerPacket){this.onmessage?.({data:JSON.stringify(p)});}
}
const callbacks=():CampaignCoopCallbacks=>({onSnapshot:vi.fn(),onCommand:vi.fn(),onPlayers:vi.fn(),onRole:vi.fn(),onStatus:vi.fn(),onAck:vi.fn(),onChat:vi.fn(),onPermission:vi.fn(),onSnapshotRequested:vi.fn()});
afterEach(()=>{vi.useRealTimers();MockSocket.sockets=[];});
describe('campaign browser client',()=>{
 it('does not connect automatically, uses its independent route, and synchronizes before guest commands',()=>{vi.useFakeTimers();const cb=callbacks(),client=new CampaignCoopClient({room:key('1'),resumeKey:key('2'),mode:'join',endpoint:'https://example.test',socketFactory:url=>new MockSocket(url) as unknown as WebSocket},cb);expect(MockSocket.sockets).toHaveLength(0);client.connect();const s=MockSocket.sockets[0];expect(s.url).toBe('wss://example.test/campaign-room/'+key('1'));s.open();s.packet({type:'welcome',protocol:1,role:'guest',epoch,lastCommandSequence:0,lastPoseSequence:0,snapshotSequence:1,guestBuild:false,hostOnline:true});expect(client.guestRequest({action:'attack',payload:{}})).toBeNull();const transfer=splitSnapshot('{"state":1}',1);s.packet({type:'snapshot-begin',epoch,manifest:transfer.manifest});s.packet({type:'snapshot-chunk',epoch,sequence:1,index:0,data:transfer.chunks[0]});s.packet({type:'snapshot-end',epoch,sequence:1});expect(cb.onSnapshot).toHaveBeenCalledWith('{"state":1}',1);expect(client.online).toBe(true);expect(client.guestRequest({action:'attack',payload:{}})).not.toBeNull();s.packet({type:'status',epoch,hostOnline:false,message:'paused'});expect(client.online).toBe(false);expect(client.guestRequest({action:'attack',payload:{}})).toBeNull();client.disconnect();});
 it('mute suppresses chat callbacks and reconnect does not replay uncertain commands',()=>{vi.useFakeTimers();const cb=callbacks(),client=new CampaignCoopClient({room:key('1'),resumeKey:key('2'),mode:'create',endpoint:'https://example.test',socketFactory:url=>new MockSocket(url) as unknown as WebSocket},cb);client.connect();const s=MockSocket.sockets[0];s.open();s.packet({type:'welcome',protocol:1,role:'host',epoch,lastCommandSequence:0,lastPoseSequence:0,snapshotSequence:0,guestBuild:false,hostOnline:true});client.setMuted(true);s.packet({type:'chat',epoch,playerId:'guest',text:'<script>ignored</script>'});expect(cb.onChat).not.toHaveBeenCalled();client.setMuted(false);s.packet({type:'chat',epoch,playerId:'guest',text:'plain text'});expect(cb.onChat).toHaveBeenCalledWith('guest','plain text');s.close();expect(client.online).toBe(false);vi.advanceTimersByTime(501);expect(MockSocket.sockets).toHaveLength(2);expect(MockSocket.sockets[1].sent).toHaveLength(0);client.disconnect();});
});
