import {beforeAll,describe,it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,defaultSettings,isCampaignSave,type CampaignSave} from '../../src/prototype/campaign-session';
import {createCampaignSamplePrototype,LEGACY_CAMPAIGN_V2_BASELINE,CAMPAIGN_SAMPLE_MANIFEST} from '../../src/prototype/core/campaign-sample-provider';
import {StreamedCampaignField} from '../../src/prototype/core/streamed-campaign-field';
import {migrateLegacyCampaignField,prepareLegacyCampaignMigration,preserveLegacyMigrationBackup,migrationBackupKey} from '../../src/save/campaign-migration';
import {CheckpointStore,type SaveStorage} from '../../src/save/checkpoint';
import {checksum} from '../../src/save/validation';
import {key,type Cell,type Vec3} from '../../src/prototype/core/voxel';
import {setDoor} from '../../src/prototype/core/world';
import {SurvivalSystem} from '../../src/prototype/core/survival';
import {ensureCampaignAnchor} from '../../src/prototype/core/campaign-repairs';
let legacy:CoreSimulation,save:CampaignSave,prototype:ReturnType<typeof createCampaignSamplePrototype>;
const point=(cell:Cell):Vec3=>({x:(cell.x+.5)*.25,y:(cell.y+.5)*.25,z:(cell.z+.5)*.25});
const units=(state:CampaignSave)=>Object.values(state.survival.inventory).reduce((a,b)=>a+b,0)+[...state.survival.drops,...state.survival.pendingDrops,...state.elements.drops].reduce((a,b)=>a+b.count,0);
const compare=(old:Cell|undefined,now:Cell|undefined,id:string)=>expect(now?[now.distance,now.material,now.object]:null,id).toEqual(old?[old.distance,old.material,old.object]:null);
beforeAll(()=>{
 legacy=new CoreSimulation(true);prototype=createCampaignSamplePrototype(8);expect(legacy.arena.field.exportState().baseline).toBe(LEGACY_CAMPAIGN_V2_BASELINE);
 legacy.survival.inventory[4]=40;const wood=[...legacy.arena.field.cells.values()].find(c=>c.object==='sample-wood'&&c.material===4&&c.distance<0)!;
 legacy.elements.damage({cell:wood,point:point(wood),normal:{x:0,y:1,z:0},distance:0},1000,0);legacy.survival.addDrops(legacy.elements.drainDrops());
 const grass=[...legacy.arena.field.cells.values()].find(c=>c.object==='sample-grass'&&c.distance<0)!;legacy.elements.cast('fire',{cell:grass,point:point(grass),normal:{x:0,y:1,z:0},distance:0},{x:0,y:0,z:1});for(let i=0;i<12;i++)legacy.elements.tick(.1);legacy.survival.addDrops(legacy.elements.drainDrops());
 legacy.arena.field.carve({x:2,y:.1,z:6},.3);legacy.arena.field.removeObject('tree0');setDoor(legacy.arena.field,true);legacy.arena.objects.get('door')!.open=true;
 const player={x:0,y:.25,z:7};expect(legacy.survival.place({x:0,y:.25,z:8},player).ok).toBe(true);legacy.survival.selected='door';expect(legacy.survival.place({x:2,y:.25,z:8.5},player).ok).toBe(true);const door=legacy.survival.exportState().buildings.find(b=>b.recipe==='door')!;expect(legacy.survival.toggleDoor(door.id,player).ok).toBe(true);
 save=captureCampaign(legacy,defaultSettings());expect(isCampaignSave(save)).toBe(true);
},20000);

describe('explicit certified legacy-to-streamed migration',()=>{
 it('preserves exact mined/burned/deleted/re-created/build samples and the resource ledger',()=>{const before=JSON.stringify(save),candidate=prepareLegacyCampaignMigration(save,prototype);expect(candidate).not.toBeNull();if(!candidate)throw new Error('Missing candidate');expect(candidate.world).toBe('campaign-v3');expect(candidate.field.baseline).toBe(CAMPAIGN_SAMPLE_MANIFEST);expect(candidate.field.suppressed).toContain('tree0');expect(candidate.field.order).toEqual(save.field.order);expect(candidate.field.base).toEqual(save.field.base);expect(candidate.field.removedBase).toEqual(save.field.removedBase);expect(candidate.field.layers).toEqual(save.field.layers);expect(candidate.survival).toEqual(save.survival);expect(candidate.elements).toEqual(save.elements);expect(candidate.entities).toEqual(save.entities);expect(units(candidate as unknown as CampaignSave)).toBe(units(save));expect(JSON.stringify(save)).toBe(before);
  const field=new StreamedCampaignField(prototype.provider);expect(field.restoreState(candidate.field)).toBe(true);expect(field.cells.size).toBe(0);const coordinates=new Set<string>();for(const c of candidate.field.base)coordinates.add(key(c[0],c[1],c[2]));for(const id of candidate.field.removedBase)coordinates.add(id);for(const layer of candidate.field.layers){for(const c of layer.cells)coordinates.add(key(c[0],c[1],c[2]));for(const id of layer.removed)coordinates.add(id);}const b=prototype.provider.layerBounds.get('tree0')!;for(let x=b.minX;x<=b.maxX;x++)for(let y=b.minY;y<=b.maxY;y++)for(let z=b.minZ;z<=b.maxZ;z++)coordinates.add(key(x,y,z));
  for(const id of coordinates){const [x,y,z]=id.split(',').map(Number);compare(legacy.arena.field.cells.get(id),field.sampleCell(x,y,z),id);}prototype.provider.clearCache();for(const id of [...coordinates].filter((_,i)=>i%7===0)){const [x,y,z]=id.split(',').map(Number);compare(legacy.arena.field.cells.get(id),field.sampleCell(x,y,z),id);}
  for(const origin of [{x:0,y:1.4,z:4},{x:2,y:2,z:7},{x:0,y:3,z:8}])expect(field.ray(origin,{x:0,y:0,z:1},6)).toEqual(legacy.arena.field.ray(origin,{x:0,y:0,z:1},6));
  const survival=new SurvivalSystem(field);expect(survival.restoreState(candidate.survival)).toBe(true);expect(survival.inventory).toEqual(legacy.survival.inventory);expect(survival.hasWorkbench({x:0,y:.25,z:7})).toBe(true);for(const building of candidate.survival.buildings){const tuples=[...field.objectSamples(building.id)].sort((a,b)=>a.x-b.x||a.y-b.y||a.z-b.z).map(c=>[c.x,c.y,c.z,c.distance,c.material]);const original=[...legacy.arena.field.objectSamples(building.id)].sort((a,b)=>a.x-b.x||a.y-b.y||a.z-b.z).map(c=>[c.x,c.y,c.z,c.distance,c.material]);expect(tuples,building.id).toEqual(original);if(building.recipe==='door')expect(checksum(JSON.stringify(tuples))).toBe(building.signature);}expect(field.get(28,15,-28)?.object).toBe('grapple-mist');expect(ensureCampaignAnchor(field)).toBe(false);const builtDoor=candidate.survival.buildings.find(b=>b.recipe==='door')!,wood=survival.inventory[4];expect(survival.toggleDoor(builtDoor.id,{x:0,y:.25,z:7}).ok).toBe(true);expect(survival.toggleDoor(builtDoor.id,{x:0,y:.25,z:7}).ok).toBe(true);expect(survival.inventory[4]).toBe(wood);
  expect(prototype.provider.stats.numericBytes).toBeLessThanOrEqual(8*4096*12);
 },20000);
 it('retains whole-layer tombstones when a migrated authored ID is removed and re-created again',()=>{const migrated=migrateLegacyCampaignField(save.field,prototype.provider)!;const field=new StreamedCampaignField(prototype.provider);expect(field.restoreState(migrated)).toBe(true);setDoor(field,false);const snapshot=field.exportState();expect(snapshot.suppressed).toContain('door');expect(snapshot.order).toContain('door');const loaded=new StreamedCampaignField(prototype.provider);expect(loaded.restoreState(JSON.parse(JSON.stringify(snapshot)))).toBe(true);expect(loaded.exportState()).toEqual(snapshot);const bounds=prototype.provider.layerBounds.get('door')!;for(let x=bounds.minX;x<=bounds.maxX;x++)for(let y=bounds.minY;y<=bounds.maxY;y++)for(let z=bounds.minZ;z<=bounds.maxZ;z++)compare(field.sampleCell(x,y,z),loaded.sampleCell(x,y,z),key(x,y,z));});
 it('rejects unknown fingerprints, malformed tuples and nonexistent legacy removals without changing input or target',()=>{const field=new StreamedCampaignField(prototype.provider),before=field.exportState(),source=JSON.stringify(save.field);for(const bad of [{...save.field,baseline:'campaign-v2:unknown'},{...save.field,size:.5},{...save.field,base:[[0,0,0,NaN,3]]},{...save.field,removedBase:['8192,8192,8192']},{...save.field,suppressed:['door']}]){expect(migrateLegacyCampaignField(bad,prototype.provider)).toBeNull();expect(field.restoreState(bad)).toBe(false);expect(field.exportState()).toEqual(before);}expect(JSON.stringify(save.field)).toBe(source);});
 it('rejects malformed or unknown component data before producing a migrated campaign',()=>{const source=JSON.stringify(save);for(const edit of [(d:CampaignSave)=>{d.campaign.items.unknown=1;},(d:CampaignSave)=>{d.entities[17].reward=999;},(d:CampaignSave)=>{d.objects[0].id='unknown-object';}]){const value=JSON.parse(source) as CampaignSave;edit(value);expect(prepareLegacyCampaignMigration(value,prototype)).toBeNull();}expect(JSON.stringify(save)).toBe(source);});
 it('validates streamed restore atomically and never implicitly accepts the legacy backend',()=>{const field=new StreamedCampaignField(prototype.provider),converted=migrateLegacyCampaignField(save.field,prototype.provider)!;expect(field.restoreState(converted,true)).toBe(true);expect(field.editSampleCount).toBe(0);expect(field.restoreState(converted)).toBe(true);const before=field.exportState(),revision=field.revision,dirty=[...field.dirty];for(const bad of [{...before,baseline:'unrecognized-manifest'},{...before,suppressed:undefined},{...before,suppressed:['unknown-object']},{...before,base:[[0,0,0,Infinity,3]]},save.field]){expect(field.restoreState(bad)).toBe(false);expect(field.exportState()).toEqual(before);expect(field.revision).toBe(revision);expect([...field.dirty]).toEqual(dirty);}expect(()=>field.captureBaseline('wrong')).toThrow();});
});
class MemoryStorage implements SaveStorage {data=new Map<string,string>();fail='';getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){if(k===this.fail)throw new Error('quota');this.data.set(k,v);}removeItem(k:string){this.data.delete(k);}}
describe('write-once legacy migration archive',()=>{
 it('preserves exact original bytes independently of rotating autosave backups',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'legacy',isCampaignSave);expect(store.write(save).ok).toBe(true);const original=storage.getItem('legacy');expect(preserveLegacyMigrationBackup(storage,'legacy')).toEqual({ok:true,key:migrationBackupKey('legacy'),alreadyPresent:false});expect(preserveLegacyMigrationBackup(storage,'legacy')).toEqual({ok:true,key:migrationBackupKey('legacy'),alreadyPresent:true});const later=JSON.parse(JSON.stringify(save));later.seconds++;expect(store.write(later).ok).toBe(true);later.seconds++;expect(store.write(later).ok).toBe(true);expect(storage.getItem(migrationBackupKey('legacy'))).toBe(original);expect(storage.getItem('legacy:backup')).not.toBe(original);const current=storage.getItem('legacy');expect(preserveLegacyMigrationBackup(storage,'legacy')).toEqual({ok:false,reason:'conflict'});expect(storage.getItem('legacy')).toBe(current);expect(storage.getItem(migrationBackupKey('legacy'))).toBe(original);});
 it('quota/corruption failures leave the source untouched and never claim success',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'legacy',isCampaignSave);store.write(save);const original=storage.getItem('legacy');storage.fail=migrationBackupKey('legacy');expect(preserveLegacyMigrationBackup(storage,'legacy')).toEqual({ok:false,reason:'storage'});expect(storage.getItem('legacy')).toBe(original);expect(storage.getItem(migrationBackupKey('legacy'))).toBeNull();storage.fail='';storage.setItem('legacy','broken');expect(preserveLegacyMigrationBackup(storage,'legacy')).toEqual({ok:false,reason:'invalid-source'});expect(storage.getItem('legacy')).toBe('broken');expect(storage.getItem(migrationBackupKey('legacy'))).toBeNull();});
});
