import {describe,it,expect,vi} from 'vitest';
import preview from '../../apps/campaign-room/src/preview-worker';
import relay from '../../apps/campaign-room/src/index';
const room='a'.repeat(64),origin='https://pr-4-threejs-game.example.workers.dev';
const environment=(enabled='false')=>({CAMPAIGN_RELAY_ENABLED:enabled,ASSETS:{fetch:vi.fn(async()=>new Response('game asset'))},CAMPAIGN_ROOMS:{idFromName:vi.fn((name:string)=>name),get:vi.fn(()=>({fetch:vi.fn(async()=>new Response('relay accepted'))}))}});
describe('PR4 isolated relay HTTP entry',()=>{
 it('serves health without enabling or allocating a room',async()=>{const env=environment();const response=await preview.fetch(new Request(origin+'/campaign-room/health'),env);expect(response.status).toBe(200);expect(await response.json()).toEqual({service:'pr4-campaign-room',protocol:1,enabled:false,authority:'browser-host',maxPlayers:2});expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();expect(response.headers.get('cache-control')).toBe('no-store');});
 it('keeps assets reachable and relay disabled by default',async()=>{const env=environment();expect(await (await preview.fetch(new Request(origin+'/deployment.json'),env)).text()).toBe('game asset');expect((await preview.fetch(new Request(origin+'/campaign-room/'+room),env)).status).toBe(503);expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();});
 it('rejects missing/foreign origins before namespace lookup and permits exact same origin',async()=>{const env=environment('true');for(const wrong of [undefined,'https://malicious.example','null']){const headers:Record<string,string>={Upgrade:'websocket'};if(wrong)headers.Origin=wrong;expect((await relay.fetch(new Request(origin+'/campaign-room/'+room,{headers}),env)).status).toBe(403);}expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();const response=await relay.fetch(new Request(origin+'/campaign-room/'+room,{headers:{Upgrade:'websocket',Origin:origin}}),env);expect(response.status).toBe(200);expect(env.CAMPAIGN_ROOMS.idFromName).toHaveBeenCalledWith(room);});
 it('rejects malformed codes and non-WebSocket requests; health is GET-only',async()=>{const env=environment('true');expect((await relay.fetch(new Request(origin+'/campaign-room/short'),env)).status).toBe(404);expect((await relay.fetch(new Request(origin+'/campaign-room/'+room),env)).status).toBe(426);expect((await preview.fetch(new Request(origin+'/campaign-room/health',{method:'POST'}),env)).status).toBe(405);expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();});
});
