import {describe,expect,it,vi} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,createCampaignStore,defaultSettings,isCampaignSave,type CampaignSave} from '../../src/prototype/campaign-session';
import * as campaignSession from '../../src/prototype/campaign-session';
import {commitPreparedCampaignImport,exportCampaignFile,importCampaignFile,inspectCampaignImport,MAX_CHECKPOINT_FILE_BYTES,readCampaignImportFile} from '../../src/save/campaign-file-transfer';
import type {SaveStorage} from '../../src/save/checkpoint';
import {checksum} from '../../src/save/validation';
class MemoryStorage implements SaveStorage {data=new Map<string,string>();writes:string[]=[];getItem(key:string){return this.data.get(key)??null;}setItem(key:string,value:string){this.writes.push(key);this.data.set(key,value);}removeItem(key:string){this.data.delete(key);}}
const encode=(data:CampaignSave)=>{const payload=JSON.stringify(data);return JSON.stringify({format:'voxel-campaign',version:1,savedAt:1000,payload,checksum:checksum(payload)});};
const clone=<T>(data:T):T=>JSON.parse(JSON.stringify(data));
const campaign=(western=false)=>captureCampaign(new CoreSimulation(true,false,true,western),defaultSettings());

describe('offline campaign file semantic validation',()=>{
 it('round trips a current-world campaign with full domain validation and exact file bytes',()=>{const source=campaign(),storage=new MemoryStorage(),store=createCampaignStore(true,storage),raw=' \n'+encode(source)+'\n';expect(inspectCampaignImport(store,raw)).toMatchObject({ok:true,data:{world:'campaign-v3'},savedAt:1000});expect(storage.writes).toEqual([]);expect(importCampaignFile(store,raw)).toEqual({ok:true});expect(exportCampaignFile(store)).toMatchObject({ok:true,raw,savedAt:1000});expect(storage.getItem(store.key)).toBe(raw);},15000);
 it.each([{streamed:false,western:false},{streamed:true,western:true}])('preserves the selected legacy/western format without migration: %j',({streamed,western})=>{const storage=new MemoryStorage(),store=createCampaignStore(streamed,storage,western),source=captureCampaign(new CoreSimulation(true,false,streamed,western),defaultSettings()),raw=encode(source);expect(importCampaignFile(store,raw)).toEqual({ok:true});expect(exportCampaignFile(store)).toMatchObject({ok:true,raw});expect([...storage.data.keys()]).toEqual([store.key]);},30000);
 it('rejects corrupt inventory, terrain, entity and ledger data that pass shallow validation before any mutation',()=>{const source=campaign(),storage=new MemoryStorage(),store=createCampaignStore(true,storage);store.write(source);const before=new Map(storage.data),writes=storage.writes.length;const invalid:CampaignSave[]=[];
  const inventory=clone(source);inventory.survival.inventory[4]=-1;invalid.push(inventory);
  const terrain=clone(source);terrain.field.base.push([0,0,0,999999,4]);invalid.push(terrain);
  const body=clone(source);body.entities[0].field.base.push([0,0,0,999999,4]);invalid.push(body);
  const ledger=clone(source);ledger.campaign.version=99 as 1;invalid.push(ledger);
  for(const candidate of invalid){expect(isCampaignSave(candidate)).toBe(true);expect(inspectCampaignImport(store,encode(candidate)).ok).toBe(false);expect(importCampaignFile(store,encode(candidate)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toHaveLength(writes);}
 },20000);
 it('rejects known but different world formats without migration, selectors or cross-namespace writes',()=>{const v3=campaign(),storage=new MemoryStorage(),store=createCampaignStore(true,storage,true);storage.data.set('ash-campaign-active-format','campaign-v4');storage.data.set('unrelated-key','untouched');const before=new Map(storage.data);expect(inspectCampaignImport(store,encode(v3)).ok).toBe(false);expect(importCampaignFile(store,encode(v3)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toEqual([]);});
 it('fully checks the western geometry ledger before replacement',()=>{const source=campaign(true),storage=new MemoryStorage(),store=createCampaignStore(true,storage,true);expect(store.write(source).ok).toBe(true);const before=new Map(storage.data),writes=storage.writes.length;source.western!.claimed=['west-mine-switch'];source.western!.gateOpen=true;for(const object of source.objects)if(['west-mine-switch','west-shortcut-gate'].includes(object.id))object.open=true;expect(isCampaignSave(source)).toBe(true);expect(importCampaignFile(store,encode(source)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toHaveLength(writes);},15000);
 it('does not export a known-world checkpoint whose nested domain state is corrupt',()=>{const source=campaign(),storage=new MemoryStorage(),store=createCampaignStore(true,storage);source.survival.inventory[4]=-1;storage.data.set(store.key,encode(source));const before=new Map(storage.data);expect(store.exportFile().ok).toBe(true);expect(exportCampaignFile(store).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toEqual([]);});
});

describe('bounded local File reads',()=>{
 it('rejects invalid declared file sizes before reading content',async()=>{const store=createCampaignStore(true,new MemoryStorage()),text=vi.fn(async()=>'{');for(const size of [0,-1,NaN,Infinity,.5,MAX_CHECKPOINT_FILE_BYTES+1])expect((await readCampaignImportFile(store,{size,text})).ok).toBe(false);expect(text).not.toHaveBeenCalled();});
 it('reads a valid bounded file into memory without changing browser storage',async()=>{const source=campaign(),storage=new MemoryStorage(),store=createCampaignStore(true,storage),raw=encode(source),size=new TextEncoder().encode(raw).byteLength;expect(await readCampaignImportFile(store,{size,text:async()=>raw})).toMatchObject({ok:true,raw,sizeBytes:size,savedAt:1000});expect(storage.writes).toEqual([]);},10000);
 it('binds a frozen semantic proof to exact store/raw bytes and rejects forged, wrong-store and replayed tokens',async()=>{const storage=new MemoryStorage(),store=createCampaignStore(true,storage),raw=encode(campaign()),size=new TextEncoder().encode(raw).byteLength,prepared=await readCampaignImportFile(store,{size,text:async()=>raw});expect(prepared.ok).toBe(true);if(!prepared.ok)throw new Error(prepared.error);expect(Object.isFrozen(prepared.prepared)).toBe(true);expect(Reflect.set(prepared.prepared,'savedAt',999)).toBe(false);expect(Reflect.set(prepared.prepared,'raw','forged')).toBe(false);for(const fake of [null,undefined,'raw',{},JSON.parse(JSON.stringify(prepared.prepared)),{...prepared.prepared}])expect(commitPreparedCampaignImport(store,fake).ok).toBe(false);expect(commitPreparedCampaignImport(createCampaignStore(true,storage),prepared.prepared).ok).toBe(false);const future=JSON.parse(raw);future.version=2;storage.data.set(store.key,JSON.stringify(future));expect(commitPreparedCampaignImport(store,prepared.prepared).ok).toBe(false);expect(storage.getItem(store.key)).toBe(JSON.stringify(future));expect(storage.writes).toEqual([]);storage.data.delete(store.key);prepared.raw='mutated public raw';prepared.data.survival.inventory[4]=-1;const hydrate=vi.spyOn(campaignSession,'hydrateCampaign').mockImplementation(()=>{throw new Error('proof must avoid repeated hydration');});try{expect(commitPreparedCampaignImport(store,prepared.prepared)).toEqual({ok:true});expect(hydrate).not.toHaveBeenCalled();expect(storage.getItem(store.key)).toBe(raw);expect(commitPreparedCampaignImport(store,prepared.prepared).ok).toBe(false);}finally{hydrate.mockRestore();}},10000);
 it('handles unreadable, truncated, mismatched-size and oversized text without storage mutation',async()=>{const storage=new MemoryStorage(),store=createCampaignStore(true,storage),raw=encode(campaign());expect((await readCampaignImportFile(store,{size:12,text:async()=>{throw new Error('unreadable');}})).ok).toBe(false);expect((await readCampaignImportFile(store,{size:raw.length-1,text:async()=>raw.slice(0,-1)})).ok).toBe(false);expect((await readCampaignImportFile(store,{size:1,text:async()=>raw})).ok).toBe(false);expect((await readCampaignImportFile(store,{size:1,text:async()=>' '.repeat(MAX_CHECKPOINT_FILE_BYTES+1)})).ok).toBe(false);expect(storage.writes).toEqual([]);},10000);
});
