import {beforeAll,describe,it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,createCampaignStore,defaultSettings,LEGACY_CAMPAIGN_STORE_KEY,STREAMED_CAMPAIGN_STORE_KEY,type CampaignSave} from '../../src/prototype/campaign-session';
import {selectCampaignStore,CAMPAIGN_FORMAT_SELECTOR} from '../../src/save/campaign-store-selection';
import {migrationBackupKey} from '../../src/save/campaign-migration';
import {checksum} from '../../src/save/validation';
import type {SaveStorage} from '../../src/save/checkpoint';
let source:CampaignSave;
beforeAll(()=>{source=captureCampaign(new CoreSimulation(true),defaultSettings());source.survival.inventory[4]=27;},20000);
class Storage implements SaveStorage {values=new Map<string,string>();fail='';getItem(k:string){return this.values.get(k)??null;}setItem(k:string,v:string){if(k===this.fail)throw new Error('quota');this.values.set(k,v);}removeItem(k:string){this.values.delete(k);}}
const seeded=()=>{const storage=new Storage();expect(createCampaignStore(false,storage).write(source).ok).toBe(true);return storage;};
describe('opt-in save-store selection and migration transaction',()=>{
 it('keeps ordinary v2 startup unchanged and performs no selection/archive writes',()=>{const storage=seeded(),before=[...storage.values];const selected=selectCampaignStore(storage);expect(selected.streamed).toBe(false);expect(selected.blocked).toBe(false);expect(selected.loaded.status).toBe('loaded');expect(selected.store.key).toBe(LEGACY_CAMPAIGN_STORE_KEY);expect([...storage.values]).toEqual(before);});
 it('archives before separate-key v3 commit, preserves v2 bytes and keeps v3 selected through New Game',()=>{const storage=seeded(),original=storage.getItem(LEGACY_CAMPAIGN_STORE_KEY),selected=selectCampaignStore(storage,true);expect(selected.blocked).toBe(false);expect(selected.migrated).toBe(true);expect(selected.streamed).toBe(true);expect(selected.loaded.status).toBe('loaded');if(selected.loaded.status==='loaded'){expect(selected.loaded.data.world).toBe('campaign-v3');expect(selected.loaded.data.survival.inventory[4]).toBe(27);}expect(storage.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe(original);expect(storage.getItem(migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY))).toBe(original);expect(storage.getItem(CAMPAIGN_FORMAT_SELECTOR)).toBe('campaign-v3');expect(selected.store.reset().ok).toBe(true);const next=selectCampaignStore(storage,false);expect(next.streamed).toBe(true);expect(next.loaded.status).toBe('empty');expect(next.migrated).toBe(false);expect(storage.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe(original);},15000);
 it.each([migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY),STREAMED_CAMPAIGN_STORE_KEY,CAMPAIGN_FORMAT_SELECTOR])('never changes old saves when a migration write fails at %s',key=>{const storage=seeded(),original=storage.getItem(LEGACY_CAMPAIGN_STORE_KEY);storage.fail=key;const selected=selectCampaignStore(storage,true);expect(selected.blocked).toBe(true);expect(selected.error).toBeTruthy();expect(storage.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe(original);expect(storage.getItem(CAMPAIGN_FORMAT_SELECTOR)).toBeNull();if(key!==migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY))expect(storage.getItem(migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY))).toBe(original);},15000);
 it('preserves unknown selectors, future envelopes and uncertified old baselines without silent reset',()=>{const selector=seeded();selector.setItem(CAMPAIGN_FORMAT_SELECTOR,'campaign-v9');const before=[...selector.values];expect(selectCampaignStore(selector,true).loaded.status).toBe('unsupported');expect([...selector.values]).toEqual(before);const future=seeded(),envelope=JSON.parse(future.getItem(LEGACY_CAMPAIGN_STORE_KEY)!);envelope.version=9;future.setItem(LEGACY_CAMPAIGN_STORE_KEY,JSON.stringify(envelope));expect(selectCampaignStore(future,true).loaded.status).toBe('unsupported');expect(future.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBeNull();const unknown=seeded(),bad={...source,field:{...source.field,baseline:'campaign-v2:uncertified'}};expect(createCampaignStore(false,unknown).write(bad).ok).toBe(true);const raw=unknown.getItem(LEGACY_CAMPAIGN_STORE_KEY);expect(selectCampaignStore(unknown,true).blocked).toBe(true);expect(unknown.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe(raw);expect(unknown.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBeNull();});
 it('does not downgrade a checksummed future v3 payload to an older backup',()=>{const storage=seeded(),selected=selectCampaignStore(storage,true);expect(selected.blocked).toBe(false);if(selected.loaded.status!=='loaded')throw new Error('Expected migrated checkpoint');expect(selected.store.write({...selected.loaded.data,seconds:3}).ok).toBe(true);const envelope=JSON.parse(storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)!);const data=JSON.parse(envelope.payload);data.world='campaign-v4';envelope.payload=JSON.stringify(data);envelope.checksum=checksum(envelope.payload);storage.setItem(STREAMED_CAMPAIGN_STORE_KEY,JSON.stringify(envelope));const before=[...storage.values];expect(selectCampaignStore(storage,false).loaded.status).toBe('unsupported');expect([...storage.values]).toEqual(before);},15000);
 it('aborts if another tab updates the source between validation and archive',()=>{const storage=seeded(),other=new Storage();createCampaignStore(false,other).write({...source,seconds:123});const newer=other.getItem(LEGACY_CAMPAIGN_STORE_KEY)!;let reads=0;const get=storage.getItem.bind(storage);storage.getItem=key=>{if(key===LEGACY_CAMPAIGN_STORE_KEY&&++reads===4)storage.values.set(key,newer);return get(key);};const selected=selectCampaignStore(storage,true);expect(selected.blocked).toBe(true);expect(storage.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe(newer);expect(storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBeNull();expect(storage.getItem(migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY))).toBeNull();expect(storage.getItem(CAMPAIGN_FORMAT_SELECTOR)).toBeNull();},15000);
 it('can migrate a verified old backup without overwriting the corrupt old primary',()=>{const storage=seeded(),store=createCampaignStore(false,storage);expect(store.write({...source,seconds:1}).ok).toBe(true);const good=storage.getItem(store.backupKey);storage.setItem(LEGACY_CAMPAIGN_STORE_KEY,'corrupt-primary');const selected=selectCampaignStore(storage,true);expect(selected.blocked).toBe(false);expect(selected.migrated).toBe(true);expect(storage.getItem(LEGACY_CAMPAIGN_STORE_KEY)).toBe('corrupt-primary');expect(storage.getItem(migrationBackupKey(LEGACY_CAMPAIGN_STORE_KEY))).toBe(good);},15000);
});
