import {describe,it,expect} from 'vitest';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import type {Socket} from 'node:net';
import {CampaignRelayRoom} from '../../src/prototype/network/relay-room';
import {splitSnapshot,type ServerPacket} from '../../src/prototype/network/protocol';
/** Test-only RFC6455 text frame adapter. Production uses platform WebSockets.
 * Both peers below are real Node WebSocket clients on distinct TCP connections. */
const frame=(text:string,opcode=1)=>{const body=Buffer.from(text),header=Buffer.alloc(body.length<126?2:body.length<=65535?4:10);header[0]=0x80|opcode;if(body.length<126)header[1]=body.length;else if(body.length<=65535){header[1]=126;header.writeUInt16BE(body.length,2);}else{header[1]=127;header.writeBigUInt64BE(BigInt(body.length),2);}return Buffer.concat([header,body]);};
async function peer(url:string){const ws=new WebSocket(url),packets:ServerPacket[]=[];ws.addEventListener('message',event=>packets.push(JSON.parse(String(event.data))));await new Promise<void>((resolve,reject)=>{ws.addEventListener('open',()=>resolve(),{once:true});ws.addEventListener('error',()=>reject(new Error('Socket failed')),{once:true});});return {ws,packets,send:(p:unknown)=>ws.send(JSON.stringify(p)),wait:async(predicate:(p:ServerPacket)=>boolean)=>{const until=Date.now()+3000;while(Date.now()<until){const found=packets.find(predicate);if(found)return found;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error('Timed out waiting for actual socket packet: '+JSON.stringify(packets));}};}
describe('campaign relay over two actual WebSockets',()=>{
 it('joins, transfers chunked state, routes one-time commands, rejects guest edits and pauses after host disconnect',async()=>{
  const room=new CampaignRelayRoom('socket-epoch-001'),rawSockets=new Set<Socket>();let sequence=0;
  const server=createServer((_req,res)=>{res.writeHead(426);res.end();});
  server.on('upgrade',(request,duplex)=>{const socket=duplex as Socket;rawSockets.add(socket);const key=request.headers['sec-websocket-key'];if(typeof key!=='string'){socket.destroy();return;}const accept=createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');const id='socket-'+(++sequence);room.connect(id,{send:packet=>{if(!socket.destroyed)socket.write(frame(JSON.stringify(packet)));},close:()=>socket.end(frame('',8))});let buffer=Buffer.alloc(0);
   socket.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.length>=2){const opcode=buffer[0]&15,masked=!!(buffer[1]&128);let length=buffer[1]&127,offset=2;if(length===126){if(buffer.length<4)return;length=buffer.readUInt16BE(2);offset=4;}else if(length===127){if(buffer.length<10)return;const large=buffer.readBigUInt64BE(2);if(large>BigInt(65536)){socket.destroy();return;}length=Number(large);offset=10;}const maskBytes=masked?4:0;if(buffer.length<offset+maskBytes+length)return;const mask=buffer.subarray(offset,offset+maskBytes);offset+=maskBytes;const payload=Buffer.from(buffer.subarray(offset,offset+length));buffer=buffer.subarray(offset+length);if(masked)for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4];if(opcode===8){room.disconnect(id);socket.end(frame('',8));return;}if(opcode===1)room.receive(id,payload.toString('utf8'));}});
   socket.on('close',()=>{room.disconnect(id);rawSockets.delete(socket);});socket.on('error',()=>room.disconnect(id));
  });
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('Missing local address');const url=`ws://127.0.0.1:${address.port}/campaign-room/${'1'.repeat(64)}`;
  let host:Awaited<ReturnType<typeof peer>>|undefined,guest:Awaited<ReturnType<typeof peer>>|undefined;
  try {host=await peer(url);host.send({type:'hello',protocol:1,mode:'create',resumeKey:'a'.repeat(64)});await host.wait(p=>p.type==='welcome');guest=await peer(url);guest.send({type:'hello',protocol:1,mode:'join',resumeKey:'b'.repeat(64)});await guest.wait(p=>p.type==='welcome');await host.wait(p=>p.type==='snapshot-request');expect(rawSockets.size).toBe(2);
   const text=JSON.stringify({world:'x'.repeat(22000),marker:'shared'}),transfer=splitSnapshot(text,1),epoch='socket-epoch-001';host.send({type:'snapshot-begin',epoch,manifest:transfer.manifest});for(let index=0;index<transfer.chunks.length;index++)host.send({type:'snapshot-chunk',epoch,sequence:1,index,data:transfer.chunks[index]});host.send({type:'snapshot-end',epoch,sequence:1});await guest.wait(p=>p.type==='snapshot-end');expect(guest.packets.filter((p):p is Extract<ServerPacket,{type:'snapshot-chunk'}>=>p.type==='snapshot-chunk').map(p=>p.data).join('')).toBe(text);
   guest.send({type:'input',epoch,sequence:1,input:{x:1,z:0,yaw:0,pitch:0,block:false,sprint:true}});expect(await host.wait(p=>p.type==='input')).toMatchObject({input:{x:1}});host.send({type:'frame',epoch,sequence:1,payload:{players:[{id:'guest',x:1,hp:100}]}});expect(await guest.wait(p=>p.type==='frame')).toMatchObject({sequence:1});
   guest.send({type:'command',epoch,sequence:1,commandId:'socket-build-001',command:{action:'build',payload:{recipe:'wall'}}});const denied=await guest.wait(p=>p.type==='ack'&&p.commandId==='socket-build-001');expect(denied).toMatchObject({accepted:false});
   host.send({type:'permission',epoch,guestBuild:true});await guest.wait(p=>p.type==='permission'&&p.guestBuild);const command={type:'command',epoch,sequence:2,commandId:'socket-build-002',command:{action:'build',payload:{recipe:'wall'}}};guest.send(command);guest.send(command);await host.wait(p=>p.type==='command'&&p.commandId==='socket-build-002');host.send({type:'ack',epoch,commandId:'socket-build-002',accepted:true,message:'host applied'});await guest.wait(p=>p.type==='ack'&&p.commandId==='socket-build-002');expect(host.packets.filter(p=>p.type==='command'&&p.commandId==='socket-build-002')).toHaveLength(1);
   host.ws.close();await guest.wait(p=>p.type==='status'&&!p.hostOnline);guest.send({type:'command',epoch,sequence:3,commandId:'socket-build-003',command:{action:'build',payload:{recipe:'wall'}}});await guest.wait(p=>p.type==='notice'&&p.message.includes('paused'));expect(room.online).toBe(false);
   host=await peer(url);host.send({type:'hello',protocol:1,mode:'create',resumeKey:'a'.repeat(64)});const resumed=await host.wait(p=>p.type==='welcome');expect(resumed).toMatchObject({role:'host',snapshotSequence:1});await host.wait(p=>p.type==='snapshot-request');const fresh=splitSnapshot('{"world":"resumed"}',2);host.send({type:'snapshot-begin',epoch,manifest:fresh.manifest});host.send({type:'snapshot-chunk',epoch,sequence:2,index:0,data:fresh.chunks[0]});host.send({type:'snapshot-end',epoch,sequence:2});await guest.wait(p=>p.type==='snapshot-end'&&p.sequence===2);expect(room.online).toBe(true);expect(rawSockets.size).toBe(2);
  }finally {host?.ws.close();guest?.ws.close();for(const socket of rawSockets)socket.destroy();await new Promise<void>(resolve=>server.close(()=>resolve()));}
 },10000);
});
