import {describe,it,expect} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {captureCampaign,hydrateCampaign,defaultSettings,isCampaignSave} from '../../src/prototype/campaign-session';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false};
describe('integrated campaign world and persistent session',()=>{
 it('starts safely, authors reachable progression objects and ticks the real campaign',()=>{const s=new CoreSimulation(true);expect(s.arena.field.overlaps(s.player.position)).toBe(false);expect(s.enemies).toHaveLength(18);expect(s.arena.objects.has('artisan')).toBe(true);expect(s.arena.objects.has('rg-lake-cache')).toBe(true);s.tick(1/60,idle);expect(s.campaign.objective().id).toBe('gather');expect(s.player.hp).toBe(100);expect(s.safePosition(s.campaign.spawn)).not.toEqual(s.campaign.spawn);},20000);
 it('preserves edited terrain, canonical material/items, home jobs, gear and enemy rewards through reload',()=>{const s=new CoreSimulation(true);s.survival.inventory[4]=30;s.survival.inventory[3]=20;s.campaign.interact('hearth',{x:-3,y:.25,z:4});s.campaign.interact('artisan',{x:-2.5,y:.25,z:-3.5});s.campaign.craft('grapple',{x:-3,y:.25,z:4});s.campaign.equip('grapple');s.home.startProcessing('weave',{position:{x:-3,y:.25,z:4},basePosition:{x:-3,y:.25,z:4},baseActive:true,artisanRescued:true});s.arena.field.carve({x:2,y:.1,z:6},.35);s.enemyElements[0].deathDrops({x:0,y:.25,z:-6});const saved=captureCampaign(s,defaultSettings());expect(isCampaignSave(saved)).toBe(true);const restored=hydrateCampaign(saved)!;expect(restored).not.toBeNull();expect(restored.sim.survival.inventory).toEqual(s.survival.inventory);expect(restored.sim.campaign.state).toEqual(s.campaign.state);expect(restored.sim.home.snapshot()).toEqual(s.home.snapshot());expect(restored.sim.arena.field.distance({x:2,y:.1,z:6})).toBeCloseTo(s.arena.field.distance({x:2,y:.1,z:6}));expect(restored.sim.enemyElements[0].deathDrops({x:0,y:0,z:0})).toEqual([]);expect(restored.sim.home.items).toBe(restored.sim.campaign.state.items);},30000);
 it('rejects malformed component data without replacing a live world and preserves death rules',()=>{const s=new CoreSimulation(true);s.survival.inventory[4]=20;s.player.hp=0;s.campaign.die({x:0,y:.25,z:6});expect(s.survival.inventory[4]).toBe(15);s.respawn();expect(s.player.hp).toBe(100);expect(s.arena.field.overlaps(s.player.position)).toBe(false);const save=captureCampaign(s,defaultSettings());save.campaign.items['nonexistent']=1;expect(hydrateCampaign(save)).toBeNull();expect(s.survival.inventory[4]).toBe(15);},30000);
});
