import {SessionAuthority} from '../../src/simulation/session';
import {expect,it} from 'vitest';
import {legacySimulation} from '../helpers/legacy';
function setup(){const sim=legacySimulation(),a=sim.adventure;a.state.resources=[];a.state.buildings=[];a.state.enemies=[];Object.assign(sim.player,{x:0,y:10,z:0,heading:Math.PI,grounded:true});sim.world.density=()=>1;const e={id:sim.allocateEntityId(),definition:'slime',tier:1,x:0,y:10,z:-.6,homeX:0,homeZ:-.6,health:100,cooldown:10,windup:0,slow:0,boss:false,alerted:10};a.state.enemies.push(e);return {a,e};}
it('uses authority hold time to scale one melee release, with no damage while holding',()=>{const {a,e}=setup();a.action('charge-start');a.stepPersonal(1.5);expect(a.chargeProgress).toBe(1);expect(e.health).toBe(100);a.action('charge-release');a.stepPersonal(.33);expect(e.health).toBeCloseTo(100-7*1.7*1.5);const health=e.health;a.action('charge-release');a.stepPersonal(.3);expect(e.health).toBe(health);});
it('does not let repeat start inflate the charge, and cancels without spending on interruption',()=>{const {a,e}=setup();a.action('charge-start');a.stepPersonal(.3);a.action('charge-start');expect(a.chargeProgress).toBeCloseTo(.2);const stamina=a.state.stamina;a.action('charge-cancel');a.action('charge-release');expect(a.state.stamina).toBe(stamina);expect(e.health).toBe(100);a.action('charge-start');a.hurtPlayer(1,'physical');expect(a.chargeProgress).toBeUndefined();});
it('keeps a valid long hold capped, clears weapon changes, and ignores client-supplied charge duration',()=>{const {a}=setup();a.action('charge-start','999999');expect(a.chargeProgress).toBe(0);a.stepPersonal(30);expect(a.chargeProgress).toBe(1);a.action('charge-cancel');expect(a.chargeProgress).toBeUndefined();a.action('charge-start');a.state.equipment='axe';a.stepPersonal(.01);expect(a.chargeProgress).toBeUndefined();});

it('allows same-tick authority release/cancel without bypassing attack recovery',()=>{const room=new SessionAuthority(null,true);const a=room.actors.get('host')!.adventure,send=(action:'charge-start'|'charge-release'|'charge-cancel')=>room.action('host',{type:'game-action',action,aim:{x:0,y:0,z:-1}});send('charge-start');expect(()=>send('charge-cancel')).not.toThrow();expect(a.chargeProgress).toBeUndefined();for(let i=0;i<4;i++)room.step();send('charge-start');expect(()=>send('charge-release')).not.toThrow();expect(a.chargeProgress).toBeUndefined();expect(a.attack).toBeGreaterThan(0);expect(()=>send('charge-start')).toThrow();});

it('does not persist a held charge across save/restart or member disconnect',()=>{const room=new SessionAuthority(null,true),actor=room.join('held-member');room.action('held-member',{type:'game-action',action:'charge-start',aim:{x:0,y:0,z:1}});expect(actor.adventure.chargeProgress).toBe(0);const saved=room.save();expect(new SessionAuthority(saved,true).join('held-member').adventure.chargeProgress).toBeUndefined();room.leave('held-member');expect(room.join('held-member').adventure.chargeProgress).toBeUndefined();});
