import {afterEach,describe,expect,it,vi} from 'vitest';
import {CheckpointStore,MAX_CHECKPOINT_ARCHIVES,MAX_CHECKPOINT_FILE_BYTES,type SaveStorage} from '../../src/save/checkpoint';
import {checksum,integer,record} from '../../src/save/validation';

interface World {world:'current';wood:number;label?:string}
const validate=(value:unknown):value is World=>record(value)&&value.world==='current'&&integer(value.wood);
class MemoryStorage implements SaveStorage {
 data=new Map<string,string>();reads:string[]=[];writes:string[]=[];removes:string[]=[];
 failKey='';dropKey='';corruptKey='';unavailable=false;beforeWrite:((key:string)=>void)|null=null;
 getItem(key:string){this.reads.push(key);if(this.unavailable)throw new Error('unavailable');return this.data.get(key)??null;}
 setItem(key:string,value:string){this.writes.push(key);this.beforeWrite?.(key);if(key===this.failKey)throw new Error('quota');if(key!==this.dropKey)this.data.set(key,key===this.corruptKey?'corrupt-write':value);}
 removeItem(key:string){this.removes.push(key);this.data.delete(key);}
}
const fixture=(key='world')=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,key,validate);return {storage,store};};
const raw=(wood=3,savedAt=1000,extra:Record<string,unknown>={})=>{const payload=JSON.stringify({world:'current',wood,...extra});return JSON.stringify({format:'voxel-campaign',version:1,savedAt,payload,checksum:checksum(payload)});};
const rawId=(value:string)=>`${JSON.parse(value).savedAt.toString(36)}-${checksum(value)}`;
const entries=(store:CheckpointStore<World>)=>{const result=store.listArchives();if(!result.ok)throw new Error(result.error);return result.entries;};
afterEach(()=>vi.restoreAllMocks());

describe('portable exact checkpoint files',()=>{
 it('exports exact envelope bytes and imports with no reserialization or clock replacement',()=>{
  const {store,storage}=fixture(),original=' \n'+raw(7,1234,{label:'七つの灯'})+'\n';storage.data.set('world',original);const before=new Map(storage.data),exported=store.exportFile();expect(exported).toMatchObject({ok:true,raw:original,savedAt:1234,sizeBytes:new TextEncoder().encode(original).byteLength,source:'current'});if(!exported.ok)throw new Error(exported.error);
  expect(exported.filename).toMatch(/^seven-lights-[0-9a-z]+-[0-9a-f]{8}\.json$/);expect(storage.data).toEqual(before);expect(storage.writes).toEqual([]);const destination=fixture();expect(destination.store.importFile(exported.raw)).toEqual({ok:true});expect(destination.storage.getItem('world')).toBe(original);expect(destination.store.exportFile()).toEqual(exported);expect(destination.storage.removes).toEqual([]);
 });
 it('preserves paired Unicode and rejects lone surrogates before Blob encoding can change the envelope',()=>{const {store,storage}=fixture();const paired=raw(1,1000,{label:'星🌟'});expect(store.importFile(paired).ok).toBe(true);expect(store.exportFile()).toMatchObject({ok:true,raw:paired});const malformed=paired.replace('🌟',String.fromCharCode(0xd800));const before=new Map(storage.data);expect(store.inspectImport(malformed)).toMatchObject({ok:false,error:expect.stringContaining('UTF-8')});expect(store.importFile(malformed).ok).toBe(false);expect(storage.data).toEqual(before);});
 it('inspects only bounded input without reading storage and exposes detached validated data',()=>{const {store,storage}=fixture(),source=raw(5);const inspection=store.inspectImport(source);expect(inspection).toMatchObject({ok:true,data:{world:'current',wood:5},savedAt:1000});if(!inspection.ok)throw new Error(inspection.error);inspection.data.wood=900;expect(store.inspectImport(source)).toMatchObject({data:{wood:5}});expect(storage.reads).toEqual([]);expect(storage.writes).toEqual([]);});
 it('exports only the chosen validated archive and never trusts arbitrary IDs as keys',()=>{const {store,storage}=fixture();const original=raw(1);storage.data.set('world',original);expect(store.reset().ok).toBe(true);const id=entries(store)[0].id;storage.data.set('world',raw(2));storage.data.set('private-token','secret');const before=new Map(storage.data);expect(store.exportFile(id)).toMatchObject({ok:true,raw:original,source:'archive'});expect(store.exportFile('../private-token').ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.reads.every(key=>key==='world'||key.startsWith('world:'))).toBe(true);});
 it('exports a recovered backup without modifying corrupted primary, but never exports old backup after New Game',()=>{const {store,storage}=fixture();storage.data.set('world','broken');storage.data.set('world:backup',raw(1));const before=new Map(storage.data);expect(store.exportFile()).toMatchObject({ok:true,source:'backup',raw:raw(1)});expect(storage.data).toEqual(before);storage.data.delete('world');expect(store.exportFile().ok).toBe(false);});
 it.each(['future envelope','future world','future payload'])('never disguises %s as an older fallback',kind=>{const {store,storage}=fixture();const e=JSON.parse(raw(2));if(kind==='future envelope')e.version=2;else {const data=JSON.parse(e.payload);if(kind==='future world')data.world='future';else data.world='version-2';e.payload=JSON.stringify(data);e.checksum=checksum(e.payload);}storage.data.set('world',JSON.stringify(e));storage.data.set('world:backup',raw(1));expect(store.exportFile().ok).toBe(false);expect(store.importFile(raw(3)).ok).toBe(false);expect(storage.writes).toEqual([]);});
});

describe('untrusted file validation before mutations',()=>{
 it.each(['empty','malformed','html','truncated','wrong format','future version','wrong world','bad checksum','bad payload','invalid values','invalid time','oversized ascii','oversized utf8'])('rejects %s and leaves every original unchanged',damage=>{
  const {store,storage}=fixture();storage.data.set('world',raw(1));storage.data.set('world:backup',raw(0));let bad=raw(2),e=JSON.parse(bad);
  if(damage==='empty')bad='';if(damage==='malformed')bad='{';if(damage==='html')bad='<script>globalThis.importExecuted=true</script>';if(damage==='truncated')bad=bad.slice(0,-1);
  if(damage==='wrong format'){e.format='other';bad=JSON.stringify(e);}if(damage==='future version'){e.version=2;bad=JSON.stringify(e);}if(damage==='wrong world')bad=raw(2,1000,{world:'other'});
  if(damage==='bad checksum'){e.checksum='00000000';bad=JSON.stringify(e);}if(damage==='bad payload'){e.payload='{';e.checksum=checksum(e.payload);bad=JSON.stringify(e);}if(damage==='invalid values')bad=raw(-1);if(damage==='invalid time'){e.savedAt=-1;bad=JSON.stringify(e);}
  if(damage==='oversized ascii')bad=' '.repeat(MAX_CHECKPOINT_FILE_BYTES+1);if(damage==='oversized utf8')bad='界'.repeat(Math.floor(MAX_CHECKPOINT_FILE_BYTES/3)+1);
  const before=new Map(storage.data);expect(store.inspectImport(bad).ok).toBe(false);expect(store.importFile(bad).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toEqual([]);expect(storage.removes).toEqual([]);
 });
 it('does not interpolate stored labels into export filenames or execute JSON strings',()=>{const {store,storage}=fixture(),source=raw(4,1000,{label:'../../<script>globalThis.__checkpointExecuted=true</script>'});expect(store.importFile(source).ok).toBe(true);const exported=store.exportFile();expect(exported).toMatchObject({ok:true,raw:source});if(!exported.ok)throw new Error(exported.error);expect(exported.filename).not.toMatch(/[<>/]/);expect((globalThis as typeof globalThis&{__checkpointExecuted?:boolean}).__checkpointExecuted).toBeUndefined();expect(storage.getItem('world')).toBe(source);});
 it('requires semantic preflight before reading or writing current storage',()=>{const {store,storage}=fixture();storage.data.set('world',raw(1));const before=new Map(storage.data);expect(store.importFile(raw(2),()=>false).ok).toBe(false);expect(store.importFile(raw(2),()=>{throw new Error('malformed geometry');}).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.reads).toEqual([]);expect(storage.writes).toEqual([]);});
 it('rejects corrupt existing primary even when a fallback is usable',()=>{const {store,storage}=fixture();storage.data.set('world','broken');storage.data.set('world:backup',raw(1));storage.data.set('world:corrupt','prior diagnostic');const before=new Map(storage.data);expect(store.importFile(raw(2)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toEqual([]);});
});

describe('non-destructive import transaction',()=>{
 it('archives both original slots immutably and preserves backup, diagnostic and old archives',()=>{const {store,storage}=fixture();storage.data.set('world',raw(0));store.reset();storage.removes.length=0;const archived=raw(0),backup=raw(1),primary=raw(2),incoming=raw(3);storage.data.set('world',primary);storage.data.set('world:backup',backup);storage.data.set('world:corrupt','diagnostic');expect(store.importFile(incoming)).toEqual({ok:true});expect(storage.getItem('world')).toBe(incoming);expect(storage.getItem('world:backup')).toBe(backup);expect(storage.getItem('world:corrupt')).toBe('diagnostic');expect(entries(store)).toHaveLength(3);expect(entries(store).filter(entry=>entry.reason==='import')).toHaveLength(2);for(const source of [archived,backup,primary])expect(storage.getItem('world:archive:'+rawId(source))).toBe(source);expect(storage.removes).toEqual([]);});
 it('archives a valid fallback when the primary is empty and leaves invalid fallback bytes untouched',()=>{const {store,storage}=fixture();const backup=raw(1);storage.data.set('world:backup',backup);expect(store.importFile(raw(2)).ok).toBe(true);expect(storage.getItem('world:archive:'+rawId(backup))).toBe(backup);storage.data.set('world:backup','broken-backup');expect(store.importFile(raw(3)).ok).toBe(true);expect(storage.getItem('world:backup')).toBe('broken-backup');});
 it('re-imports the same exact file without writes or archive growth',()=>{const {store,storage}=fixture(),source=raw(1);storage.data.set('world',source);storage.data.set('world:backup',raw(0));expect(store.importFile(source)).toEqual({ok:true});expect(storage.writes).toEqual([]);expect(entries(store)).toEqual([]);});
 it.each(['first record','second record','index','primary'])('retains original bytes on quota failure at %s and permits safe retry',stage=>{const {store,storage}=fixture(),primary=raw(2),backup=raw(1);storage.data.set('world',primary);storage.data.set('world:backup',backup);storage.data.set('world:corrupt','diagnostic');storage.failKey=stage==='first record'?'world:archive:'+rawId(primary):stage==='second record'?'world:archive:'+rawId(backup):stage==='index'?'world:archives':'world';expect(store.importFile(raw(3)).ok).toBe(false);expect(storage.getItem('world')).toBe(primary);expect(storage.getItem('world:backup')).toBe(backup);expect(storage.getItem('world:corrupt')).toBe('diagnostic');expect(storage.removes).toEqual([]);storage.failKey='';expect(store.importFile(raw(3)).ok).toBe(true);expect(entries(store)).toHaveLength(2);for(const value of [primary,backup])expect(storage.getItem('world:archive:'+rawId(value))).toBe(value);});
 it.each(['record','index','primary'])('detects silently dropped %s writes',stage=>{const {store,storage}=fixture(),original=raw(1);storage.data.set('world',original);storage.dropKey=stage==='record'?'world:archive:'+rawId(original):stage==='index'?'world:archives':'world';expect(store.importFile(raw(2)).ok).toBe(false);expect(storage.getItem('world')).toBe(original);expect(storage.removes).toEqual([]);});
 it('retains immutable original even if an injected backend corrupts the final primary write',()=>{const {store,storage}=fixture(),original=raw(1);storage.data.set('world',original);storage.corruptKey='world';expect(store.importFile(raw(2))).toMatchObject({ok:false,error:expect.stringContaining('履歴')});expect(storage.getItem('world:archive:'+rawId(original))).toBe(original);expect(entries(store)).toHaveLength(1);});
 it.each(['record collision','batch collision','full history','corrupt index'])('preflights %s before writing any original or archive',stage=>{const {store,storage}=fixture();if(stage==='full history'){for(let wood=0;wood<MAX_CHECKPOINT_ARCHIVES;wood++){storage.data.set('world',raw(wood));expect(store.reset().ok).toBe(true);}}const primary=raw(99),backup=raw(98);storage.data.set('world',primary);storage.data.set('world:backup',backup);if(stage==='record collision')storage.data.set('world:archive:'+rawId(primary),'immutable other');if(stage==='batch collision')storage.data.set('world:archive:'+rawId(backup),'immutable other');if(stage==='corrupt index')storage.data.set('world:archives','broken');const before=new Map(storage.data),writes=storage.writes.length;expect(store.importFile(raw(100)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toHaveLength(writes);});
 it.each(['existing archive','both original slots'])('rejects a real checksum collision in %s without replacing either byte sequence',kind=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',(v:unknown):v is {wood:number}=>record(v)&&integer(v.wood));const encoded=(label:string)=>{const payload=JSON.stringify({wood:7,label});return JSON.stringify({format:'voxel-campaign',version:1,savedAt:1000,payload,checksum:checksum(payload)});};const first=encoded('variant-22008'),second=encoded('variant-51641');expect(checksum(first)).toBe(checksum(second));expect(first).not.toBe(second);storage.data.set('world',first);if(kind==='existing archive'){expect(store.reset().ok).toBe(true);storage.data.set('world',second);}else storage.data.set('world:backup',second);const before=new Map(storage.data),writes=storage.writes.length;expect(store.importFile(encoded('incoming'))).toMatchObject({ok:false,error:expect.stringContaining('ID')});expect(storage.data).toEqual(before);expect(storage.writes).toHaveLength(writes);});
 it('preflights capacity for both originals together rather than partially extending history',()=>{const {store,storage}=fixture();for(let wood=0;wood<MAX_CHECKPOINT_ARCHIVES-1;wood++){storage.data.set('world',raw(wood));store.reset();}storage.data.set('world',raw(99));storage.data.set('world:backup',raw(98));const before=new Map(storage.data),writes=storage.writes.length;expect(store.importFile(raw(100)).ok).toBe(false);expect(storage.data).toEqual(before);expect(storage.writes).toHaveLength(writes);});
 it('deduplicates exact original slots at the history cap',()=>{const {store,storage}=fixture();for(let wood=0;wood<MAX_CHECKPOINT_ARCHIVES;wood++){storage.data.set('world',raw(wood));store.reset();}storage.data.set('world',raw(1));storage.data.set('world:backup',raw(1));expect(store.importFile(raw(100)).ok).toBe(true);expect(entries(store)).toHaveLength(MAX_CHECKPOINT_ARCHIVES);});
 it('does not overwrite a primary changed by another tab during archive persistence',()=>{const {store,storage}=fixture(),original=raw(1),otherTab=raw(9);storage.data.set('world',original);storage.beforeWrite=key=>{if(key.startsWith('world:archive:'))storage.data.set('world',otherTab);};expect(store.importFile(raw(2)).ok).toBe(false);expect(storage.getItem('world')).toBe(otherTab);expect(storage.getItem('world:archive:'+rawId(original))).toBe(original);});
 it('handles unavailable storage and never reads or writes a different namespace',()=>{const {store,storage}=fixture('campaign-v4');storage.data.set('other:archive:secret','untouched');expect(store.importFile(raw(2)).ok).toBe(true);expect(storage.reads.every(key=>key==='campaign-v4'||key.startsWith('campaign-v4:'))).toBe(true);expect(storage.writes.every(key=>key==='campaign-v4'||key.startsWith('campaign-v4:'))).toBe(true);expect(storage.getItem('other:archive:secret')).toBe('untouched');storage.unavailable=true;expect(store.exportFile().ok).toBe(false);expect(store.importFile(raw(3)).ok).toBe(false);});
});
