import {describe,it,expect} from 'vitest';
import {VoxelField} from '../../src/prototype/core/voxel';
import {SurvivalSystem} from '../../src/prototype/core/survival';
import {LadderTraversal,type ClimbingActor} from '../../src/prototype/core/climbing';
const actor=(x=0,z=.7):ClimbingActor=>({position:{x,y:.03,z},vx:0,vy:0,vz:0,hp:100,stamina:100,phase:'idle',grounded:true});
function fixture(rotation=0){const f=new VoxelField(.25);f.box({x:-4,y:-.5,z:-4},{x:4,y:0,z:4},2);const damaged=new Set<string>(),s=new SurvivalSystem(f,undefined,damaged);s.inventory[4]=30;expect(s.place({x:-1.5,y:0,z:.5},{x:0,y:0,z:2}).ok).toBe(true);s.selected='ladder';s.rotation=rotation;expect(s.place({x:0,y:0,z:0},{x:0,y:0,z:2}).ok).toBe(true);const id=s.exportState().buildings.at(-1)!.id;return {f,s,id,damaged,climb:new LadderTraversal(s,f)};}
describe('real constructed ladder traversal',()=>{
 it('spends wood once, climbs and descends using bounded input, and releases at the ground',()=>{const {s,id,climb}=fixture(),p=actor();expect(s.inventory[4]).toBe(16);expect(climb.start(id,p)).toBe(true);for(let i=0;i<90;i++)climb.step(p,1,0,1/60);expect(p.position.y).toBeCloseTo(1.83,2);expect(p.stamina).toBeCloseTo(82,2);for(let i=0;i<100;i++)climb.step(p,-1,0,1/60);expect(p.position.y).toBeLessThan(.05);expect(climb.active(p)).toBe(false);expect(s.inventory[4]).toBe(16);});
 it('does not phase through a ceiling or another climbing actor',()=>{const {f,id,climb}=fixture(),p=actor();f.box({x:-2,y:2,z:-2},{x:2,y:2.4,z:2},3,'ceiling');expect(climb.start(id,p)).toBe(true);for(let i=0;i<100;i++)climb.step(p,1,0,1/60);expect(p.position.y).toBeLessThan(.5);expect(f.overlaps(p.position)).toBe(false);const before=p.position.y;climb.step(p,1,0,.1,[{...p.position,y:p.position.y+1}]);expect(p.position.y).toBe(before);});
 it('supports both ladder faces and quarter-turn placement; denies side/remote grabbing',()=>{for(const rotation of [0,1,2,3]){const {id,climb}=fixture(rotation);for(const sign of [-1,1]){const p=rotation%2?actor(sign*.7,0):actor(0,sign*.7);expect(climb.start(id,p)).toBe(true);climb.step(p,1,0,.1);expect(p.position.y).toBeGreaterThan(.1);}const side=rotation%2?actor(0,1.4):actor(1.4,0);expect(climb.start(id,side)).toBe(false);}});
 it('releases on destroyed rungs, exhaustion, lateral exit, death and explicit reset without free resources',()=>{const {f,s,id,damaged,climb}=fixture();const p=actor();expect(climb.start(id,p)).toBe(true);climb.step(p,1,0,.1);f.carve({x:.45,y:1,z:0},.3);damaged.add(id);expect(climb.step(p,1,0,.1)).toBe(false);expect(climb.start(id,p)).toBe(false);expect(s.inventory[4]).toBe(16);
 const next=fixture(),q=actor();expect(next.climb.start(next.id,q)).toBe(true);q.stamina=0;expect(next.climb.step(q,1,0,.1)).toBe(false);q.stamina=100;expect(next.climb.start(next.id,q)).toBe(true);expect(next.climb.step(q,0,1,.1)).toBe(false);expect(next.climb.start(next.id,q)).toBe(true);q.hp=0;expect(next.climb.step(q,0,0,.1)).toBe(false);q.hp=100;expect(next.climb.start(next.id,q)).toBe(true);q.impact=1;expect(next.climb.step(q,0,0,.1)).toBe(false);q.impact=0;expect(next.climb.start(next.id,q)).toBe(true);next.climb.clear();expect(next.climb.active(q)).toBe(false);});
 it('retains geometry and paid construction through a save restore, never a transient grip',()=>{const {f,s,id}=fixture(),state=s.exportState(),snapshot=f.exportState(),copy=new VoxelField(.25);expect(copy.restoreState(snapshot)).toBe(true);const restored=new SurvivalSystem(copy);expect(restored.restoreState(state)).toBe(true);expect(restored.ladder(id)).not.toBeNull();expect(restored.inventory).toEqual(s.inventory);expect(new LadderTraversal(restored,copy).active(actor())).toBe(false);});
});
