import {describe,it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {DISPLAY_BASE,DISPLAY_ITEM,validCollectibleDisplaySave,validCollectibleDisplay} from '../../src/prototype/core/collectible-display';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {captureCampaign,defaultSettings,restoreCampaignInto,getCampaignRestoreFailure} from '../../src/prototype/campaign-session';
import {collectibleDisplayRows} from '../../src/prototype/collectible-display-presenter';
import {validCampaignState} from '../../src/prototype/core/campaign';
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function setup(){const sim=new CoreSimulation(true,false,true);Object.assign(sim.survival.inventory,{4:40,3:40,6:20});sim.campaign.interact('hearth',{x:-3,y:.25,z:4});sim.player.position={x:-3.5,y:.25,z:5.3};return sim;}
const command=(s:CoreSimulation,id:string)=>executeGameCommand(s,{type:'homestead',id});
describe('paid collectible display and escrow',()=>{
 it('charges once, uses solid protected SDF, and returns exact costs once only when empty',()=>{
  const s=setup(),before={...s.survival.inventory};expect(command(s,'display-build').ok).toBe(true);expect(s.survival.inventory[4]).toBe(before[4]-4);expect(s.survival.inventory[3]).toBe(before[3]-3);expect(command(s,'display-build').ok).toBe(false);
  const hit=s.arena.field.ray({x:-2,y:.75,z:2.5},{x:1,y:0,z:0},2)!;expect(hit.cell.object).toBe(DISPLAY_BASE);expect(s.arena.field.overlaps({x:-1,y:.25,z:2.5})).toBe(true);expect(s.elements.damage(hit,1000,.4).destroyed).toBe(0);expect(s.elements.drainDrops()).toEqual([]);
  expect(command(s,'display-remove').ok).toBe(true);expect(command(s,'display-remove').ok).toBe(false);expect(s.survival.inventory).toEqual(before);expect([...s.arena.field.objectSamples(DISPLAY_BASE)]).toHaveLength(0);
 });
 it('moves an actual owned collectible once, reserves storage, and returns it once',()=>{
  const s=setup();s.campaign.state.items.herbs=2;expect(command(s,'display-build').ok).toBe(true);expect(command(s,'display-deposit:herbs').ok).toBe(true);expect(s.campaign.state.items.herbs).toBe(1);expect(s.home.state.storage.items.herbs).toBe(1);expect(s.home.storedCount).toBe(1);expect([...s.arena.field.objectSamples(DISPLAY_ITEM)].some(c=>c.distance<0)).toBe(true);
  for(const id of ['display-deposit:herbs','display-deposit:echo-vault-seal','display-remove'])expect(command(s,id).ok).toBe(false);expect(s.home.withdraw('herbs',1,s.homeContext).ok).toBe(false);
  expect(s.home.deposit('herbs',1,s.homeContext).ok).toBe(true);expect(s.home.withdraw('herbs',1,s.homeContext).ok).toBe(true);expect(s.home.withdraw('herbs',1,s.homeContext).ok).toBe(false);
  expect(command(s,'display-withdraw').ok).toBe(true);expect(command(s,'display-withdraw').ok).toBe(false);expect(s.campaign.state.items.herbs).toBe(2);expect(s.home.state.storage.items.herbs).toBe(0);expect([...s.arena.field.objectSamples(DISPLAY_ITEM)]).toHaveLength(0);
 });
 it('preserves equipment wear, upgrade and socket; denies equipped deposit, use, salvage and duplicate craft while displayed',()=>{
  const s=setup();s.campaign.interact('artisan',{x:-2.5,y:.25,z:-3.5});expect(s.campaign.craft('dagger',s.player.position).ok).toBe(true);s.campaign.state.gearState.dagger={durability:37.5,maxDurability:100,upgrade:1,socket:'ember-gem'};const gear=s.campaign.gearInfo('dagger');s.campaign.equip('dagger');expect(command(s,'display-build').ok).toBe(true);expect(command(s,'display-deposit:dagger').ok).toBe(false);s.campaign.unequip('weapon');expect(command(s,'display-deposit:dagger').ok).toBe(true);
  expect(validCampaignState(s.campaign.snapshot())).toBe(true);expect(s.campaign.has('dagger')).toBe(false);expect(s.campaign.equip('dagger').ok).toBe(false);expect(s.campaign.salvage('dagger',true).ok).toBe(false);expect(s.campaign.craft('dagger',s.player.position).ok).toBe(false);expect(command(s,'display-withdraw').ok).toBe(true);expect(s.campaign.gearInfo('dagger')).toEqual(gear);expect(s.campaign.state.items.dagger).toBe(1);expect(s.campaign.equip('dagger').ok).toBe(true);
 });
 it('keeps all inventories unchanged on full storage, full return inventory, wrong location, death or missing ownership',()=>{
  const s=setup();command(s,'display-build');const before=JSON.stringify([s.home.snapshot(),s.campaign.snapshot(),s.survival.inventory]);for(const id of ['unknown','echo-vault-key','field-seal','mist-core','herbs'])expect(command(s,'display-deposit:'+id).ok).toBe(false);expect(JSON.stringify([s.home.snapshot(),s.campaign.snapshot(),s.survival.inventory])).toBe(before);
  s.campaign.state.items.herbs=1;s.home.state.storage.materials[4]=500;expect(command(s,'display-deposit:herbs').ok).toBe(false);s.home.state.storage.materials[4]=0;expect(command(s,'display-deposit:herbs').ok).toBe(true);s.campaign.state.items.herbs=200;expect(command(s,'display-withdraw').ok).toBe(false);expect(s.display.state.item).toBe('herbs');s.campaign.state.items.herbs=0;
  s.player.position.x=50;expect(command(s,'display-withdraw').ok).toBe(false);s.player.position={x:-3.5,y:.25,z:5.3};s.player.hp=0;expect(command(s,'display-withdraw').ok).toBe(false);expect(s.home.state.storage.items.herbs).toBe(1);
 });
 it('enforces host edit permissions even when guest invokes production command directly, including allowed guest return',()=>{
  const s=setup();s.campaign.state.items.herbs=1;const guest=s.enableCompanion({x:-4,y:.25,z:5.3});expect(guest).not.toBeNull();expect(s.withCompanion(()=>command(s,'display-build'))?.ok).toBe(false);expect(command(s,'display-build').ok).toBe(true);expect(s.withCompanion(()=>command(s,'display-deposit:herbs'))?.ok).toBe(false);s.companionCanEdit=true;expect(s.withCompanion(()=>command(s,'display-deposit:herbs'))?.ok).toBe(true);s.companionCanEdit=false;expect(s.withCompanion(()=>command(s,'display-withdraw'))?.ok).toBe(false);expect(s.withCompanion(()=>command(s,'display-remove'))?.ok).toBe(false);s.companionCanEdit=true;expect(s.withCompanion(()=>command(s,'display-withdraw'))?.ok).toBe(true);expect(s.campaign.state.items.herbs).toBe(1);
 });
 it('refuses overlap, unsupported ground, missing cost and invalid position before payment',()=>{
  const s=setup(),before={...s.survival.inventory},c=s.displayContext;for(const ctx of [{...c,baseActive:false},{...c,position:{x:NaN,y:0,z:0}},{...c,blockers:[{x:-1,y:.25,z:2.5}]}])expect(s.display.build(ctx).ok).toBe(false);expect(s.survival.inventory).toEqual(before);
  s.arena.field.box({x:-1.5,y:.5,z:2},{x:-.5,y:2,z:3},3,'test:overlap');expect(command(s,'display-build').ok).toBe(false);s.arena.field.removeObject('test:overlap');s.arena.field.carve({x:-1,y:.15,z:2.5},1);expect(command(s,'display-build').ok).toBe(false);expect(s.survival.inventory).toEqual(before);
 });
 it('saves exact escrow/geometry and accepts old saves with no display; corrupt candidates cannot mutate the live world',()=>{
  const s=setup();const old=captureCampaign(s,defaultSettings());delete old.display;expect(restoreCampaignInto(s,old)).not.toBeNull();expect(s.display.state.built).toBe(false);s.campaign.craft('dagger',s.player.position);s.campaign.state.gearState.dagger.durability=41;command(s,'display-build');command(s,'display-deposit:dagger');const saved=captureCampaign(s,defaultSettings());const restored=new CoreSimulation(true,false,true);expect(restoreCampaignInto(restored,clone(saved))).not.toBeNull();expect(restored.display.snapshot()).toEqual(s.display.snapshot());expect(restored.home.snapshot()).toEqual(s.home.snapshot());expect(restored.campaign.craft('dagger',restored.player.position).ok).toBe(false);expect(command(restored,'display-withdraw').ok).toBe(true);expect(restored.campaign.gearInfo('dagger').durability).toBe(41);
  const before=captureCampaign(s,defaultSettings());const bad=[clone(saved),clone(saved),clone(saved),clone(saved),clone(saved)];bad[0].home.storage.items.dagger=0;bad[1].campaign.items.dagger=1;bad[1].campaign.gearState.dagger={...saved.display!.gear!};bad[2].display!.gear!.durability=Infinity;bad[3].field.layers.find(l=>l.id===DISPLAY_ITEM)!.cells[0][0]=999;delete bad[4].display;
  for(const value of bad){expect(restoreCampaignInto(s,value)).toBeNull();expect(getCampaignRestoreFailure(s)).not.toBeNull();expect(captureCampaign(s,defaultSettings())).toEqual(before);}
 });
 it('validates unique vault ownership while the earned seal is on display',()=>{
  const s=setup(),actor=(x:number,z:number)=>({position:{x,y:.25,z},alive:true,mayEdit:true});s.dungeon.interact('vault-note',actor(8.5,9));s.arena.field.removeObject('vault-crust');expect(s.dungeon.interact('vault-key',actor(7.5,11.35)).ok).toBe(true);expect(s.dungeon.interact('vault-switch',actor(10,13.6)).ok).toBe(true);expect(s.dungeon.interact('vault-cache',actor(8.5,16.2)).ok).toBe(true);command(s,'display-build');expect(command(s,'display-deposit:echo-vault-seal').ok).toBe(true);const save=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,save)).not.toBeNull();save.campaign.items['echo-vault-seal']=1;expect(restoreCampaignInto(s,save)).toBeNull();expect(getCampaignRestoreFailure(s)).toBe('dungeon');expect(command(s,'display-withdraw').ok).toBe(true);expect(s.campaign.state.items['echo-vault-seal']).toBe(1);expect(s.dungeon.interact('vault-cache',actor(8.5,16.2)).ok).toBe(false);
 });
 it('presents owned selections, costs, current display, preserved gear and disabled removal without mutating state',()=>{
  const s=setup();s.campaign.craft('dagger',s.player.position);const before=s.display.snapshot();expect(collectibleDisplayRows(s.display,s.displayContext).find(r=>r.id==='display-build')).toMatchObject({available:true,detail:expect.stringContaining('木材4・石3')});command(s,'display-build');const row=collectibleDisplayRows(s.display,s.displayContext).find(r=>r.id==='display-deposit:dagger');expect(row?.available).toBe(true);expect(collectibleDisplayRows(s.display,s.displayContext).some(r=>r.id==='display-deposit:echo-vault-seal')).toBe(false);command(s,'display-deposit:dagger');const rows=collectibleDisplayRows(s.display,s.displayContext);expect(rows.find(r=>r.id==='display-status')?.label).toContain('短剣');expect(rows.find(r=>r.id==='display-remove')?.available).toBe(false);expect(rows.find(r=>r.id==='display-withdraw')?.detail).toContain('耐久 100/100');expect(before.built).toBe(false);
 });
 it('rejects malformed schemas and geometry with no paid owner',()=>{
  const s=setup(),fresh=s.display.snapshot();for(const value of [null,{}, {...fresh,extra:1},{...fresh,item:'herbs'},{...fresh,built:true,item:'dagger',gear:null},{...fresh,built:true,item:'herbs',gear:{}}])expect(validCollectibleDisplay(value)).toBe(false);command(s,'display-build');expect(validCollectibleDisplaySave(undefined,s.arena.field.exportState(),s.campaign.state,s.home.state)).toBe(false);
 });
});
