import {afterEach,describe,it,expect,vi} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {validCompanionSnapshot} from '../../src/prototype/core/companion';
vi.mock('../../src/prototype/core/world',async(importOriginal)=>{const original=await importOriginal<typeof import('../../src/prototype/core/world')>();const {VoxelField}=await import('../../src/prototype/core/voxel');return {...original,createArena:()=>{const field=new VoxelField(.25);field.box({x:-12,y:-.5,z:-14},{x:12,y:.25,z:12},3);return {field,objects:new Map()};}};});
const idle:Controls={x:0,z:0,block:false,sprint:false,water:false};
const input={x:0,z:0,yaw:0,pitch:0,block:false,sprint:false};
function simulation(campaign=false){const sim=new CoreSimulation();if(campaign)Object.defineProperty(sim,'campaignMode',{value:true});for(const enemy of sim.enemies){enemy.position={x:40,y:.25,z:40};enemy.hp=0;enemy.phase='dead';}return sim;}
function steps(sim:CoreSimulation,count:number,controls=idle){for(let i=0;i<count;i++)sim.tick(1/60,controls);}
afterEach(()=>vi.useRealTimers());
describe('host-owned second actor',()=>{
 it('moves independently from bounded controls and collides with the same solid wall',()=>{const s=simulation(),primary=s.player,guest=s.enableCompanion();guest.position={x:1,y:.25,z:3};s.arena.field.box({x:3,y:.25,z:1},{x:3.5,y:3,z:5},3);s.setCompanionInput({...input,x:1});steps(s,120);expect(s.player).toBe(primary);expect(s.player.position.x).toBe(0);expect(guest.position.x).toBeGreaterThan(2);expect(guest.position.x).toBeLessThan(2.8);expect(s.arena.field.overlaps(guest.position)).toBe(false);expect(s.setCompanionInput({...input,x:2})).toBe(false);});
 it('treats both live actors as colliders and never drives host position from guest input',()=>{const s=simulation(),guest=s.enableCompanion();s.player.position={x:0,y:.25,z:3};guest.position={x:2,y:.25,z:3};s.setCompanionInput({...input,x:-1});steps(s,90);expect(guest.position.x).toBeGreaterThanOrEqual(.54);expect(s.player.position.x).toBe(0);expect(Math.hypot(guest.position.x-s.player.position.x,guest.position.z-s.player.position.z)).toBeGreaterThanOrEqual(.54);});
 it('neutralizes stale input and explicit disconnect controls without advancing offline commands',()=>{vi.useFakeTimers();vi.setSystemTime(1000);const s=simulation(),guest=s.enableCompanion();guest.position={x:2,y:.25,z:3};s.setCompanionInput({...input,x:1,sprint:true,block:false});s.tick(.1,idle);expect(guest.position.x).toBeGreaterThan(2);vi.advanceTimersByTime(400);const start=guest.position.x;steps(s,60);expect(guest.position.x-start).toBeLessThan(.25);s.setCompanionInput({...input,x:-1});s.neutralCompanionInput();steps(s,20);expect(guest.position.x).toBeGreaterThan(start-.1);});
 it('restores primary actor context and transient settings even if a callback throws',()=>{const s=simulation(),primary=s.player;s.enableCompanion();s.selectedElement='water';s.oxygen=13;s.buildMode=false;s.survival.selected='wall';expect(()=>s.withCompanion(()=>{s.selectedElement='lightning';s.oxygen=5;s.buildMode=true;s.survival.selected='floor';s.player.hp=22;throw new Error('test');})).toThrow('test');expect(s.player).toBe(primary);expect(s.player.hp).toBe(100);expect(s.selectedElement).toBe('water');expect(s.oxygen).toBe(13);expect(s.survival.selected).toBe('wall');expect(s.getCompanionSnapshot()).toMatchObject({player:{hp:22},aux:{selectedElement:'lightning',oxygen:5,buildMode:true,recipe:'floor'}});});
 it('advances character attacks independently, with a single hit from each strike',()=>{const s=simulation(),g=s.enableCompanion();s.player.position={x:-2,y:.25,z:1.4};g.position={x:2,y:.25,z:1.4};for(let i=0;i<2;i++){Object.assign(s.enemies[i],{position:{x:i?2:-2,y:.25,z:0},hp:100,phase:'stagger',time:0});}s.action('attack',idle);s.companionAction('attack');steps(s,45);expect(s.enemies[0].hp).toBeLessThan(100);expect(s.enemies[1].hp).toBeLessThan(100);const hp=s.enemies.map(e=>e.hp);steps(s,10);expect(s.enemies.map(e=>e.hp)).toEqual(hp);expect(s.player.combo).toBe(1);expect(g.combo).toBe(1);});
 it('keeps cast cooldown, stamina, heal timers and flasks per actor',()=>{const s=simulation(),g=s.enableCompanion();s.player.hp=30;g.hp=20;s.companionAction('heal');expect(g.phase).toBe('heal');expect(g.flasks).toBe(0);expect(s.player.phase).toBe('idle');expect(s.player.flasks).toBe(1);steps(s,100);expect(g.hp).toBe(75);expect(s.player.hp).toBe(30);s.withCompanion(()=>{s.player.phase='idle';s.player.stamina=12;});s.companionAction('heavy');expect(g.phase).toBe('idle');expect(s.player.stamina).toBe(100);});
 it('enemies choose the closest alive actor rather than always the primary',()=>{const s=simulation(),g=s.enableCompanion();s.player.position={x:-5,y:.25,z:0};g.position={x:2,y:.25,z:0};Object.assign(s.enemies[0],{position:{x:0,y:.25,z:0},hp:100,phase:'idle',time:0});s.tick(.1,idle);expect(s.enemies[0].position.x).toBeGreaterThan(0);g.hp=0;s.enemies[0].phase='idle';s.tick(.1,idle);expect(s.enemies[0].yaw).toBeGreaterThan(0);expect(s.player.hp).toBe(100);});
 it('tests projectile collision against both bodies and consumes each projectile once',()=>{const s=simulation(),g=s.enableCompanion();g.position={x:2,y:.25,z:3};s.enemyShots.push({position:{x:2,y:1.2,z:3.5},velocity:{x:0,y:0,z:-5},life:2,damage:12,radius:.15});s.tick(.1,idle);expect(g.hp).toBe(88);expect(s.player.hp).toBe(100);expect(s.enemyShots).toHaveLength(0);s.tick(.1,idle);expect(g.hp).toBe(88);});
 it('advances world, drops, fluid, home and campaign timers once per frame',()=>{const s=simulation(true),g=s.enableCompanion();g.position={x:5,y:.25,z:5};s.campaign.state.foodSeconds=100;s.campaign.state.restSeconds=100;const element=vi.spyOn(s.elements,'tick'),drop=vi.spyOn(s.survival,'tick'),fluid=vi.spyOn(s.water,'step'),home=vi.spyOn(s.home,'tick'),campaign=vi.spyOn(s.campaign,'tick');s.tick(.1,idle);for(const fn of [element,drop,fluid,home,campaign])expect(fn).toHaveBeenCalledTimes(1);expect(s.seconds).toBe(.1);expect(s.worldHour).toBeCloseTo(10+.1/90);expect(s.campaign.state.foodSeconds).toBeCloseTo(99.9);expect(s.campaign.state.restSeconds).toBeCloseTo(99.9);});
 it('lets either body collect a shared drop without duplicate resources or double physics',()=>{const s=simulation(),g=s.enableCompanion();s.player.position={x:0,y:.25,z:3};g.position={x:.8,y:.25,z:3};s.survival.addDrops([{material:4,count:7,position:{x:.4,y:1,z:3},id:'shared-drop'}]);const before=s.survival.inventory[4];s.tick(.05,idle);expect(s.survival.inventory[4]).toBe(before+7);expect(s.survival.drops).toHaveLength(0);s.tick(.05,idle);expect(s.survival.inventory[4]).toBe(before+7);});
 it('guest death and respawn never kill the host or duplicate party death-bag penalties',()=>{const s=simulation(true),g=s.enableCompanion();s.survival.inventory[4]=40;expect(s.companionRespawn()).toBe(false);g.hp=0;steps(s,5);expect(s.player.hp).toBe(100);expect(s.campaign.state.deaths).toBe(0);expect(s.campaign.state.deathBag).toBeNull();expect(s.survival.inventory[4]).toBe(40);expect(s.companionRespawn()).toBe(true);expect(g.hp).toBe(100);expect(s.campaign.state.deaths).toBe(0);expect(s.survival.inventory[4]).toBe(40);});
 it('keeps world running for a living guest after host actor dies',()=>{const s=simulation(true),g=s.enableCompanion();g.position={x:3,y:.25,z:3};s.player.hp=0;s.setCompanionInput({...input,x:1});s.tick(.1,idle);expect(g.position.x).toBeGreaterThan(3);expect(s.player.hp).toBe(0);expect(s.campaign.state.deaths).toBe(1);s.tick(.1,idle);expect(s.campaign.state.deaths).toBe(1);});
 it('round-trips validated companion state without accepting malformed shapes or replacing primary',()=>{const s=simulation(),primary=s.player;s.enableCompanion();s.withCompanion(()=>{s.player.hp=45;s.cold=12;s.oxygen=8;});const snapshot=s.getCompanionSnapshot()!;expect(validCompanionSnapshot(snapshot)).toBe(true);expect(s.restoreCompanionSnapshot(snapshot)).toBe(true);expect(s.player).toBe(primary);snapshot.player.hp=1;expect(s.companion!.hp).toBe(45);const before=s.getCompanionSnapshot();expect(s.restoreCompanionSnapshot({...before,player:{...before!.player,position:{x:NaN,y:0,z:0}}})).toBe(false);expect(s.getCompanionSnapshot()).toEqual(before);s.disableCompanion();expect(s.companion).toBeNull();expect(s.player).toBe(primary);});
});
describe('host-controlled guest editing permission',()=>{
 it('blocks tool attacks, casts, build and dismantle without consuming host resources',()=>{const s=simulation(),guest=s.enableCompanion();s.survival.inventory[4]=40;guest.position={x:2,y:.25,z:3};s.companionAction('chisel');const stamina=guest.stamina,revision=s.arena.field.revision;for(const action of ['attack','cast','build','dismantle'] as const)s.companionAction(action);expect(guest.stamina).toBe(stamina);expect(guest.phase).toBe('idle');expect(s.arena.field.revision).toBe(revision);expect(s.survival.inventory[4]).toBe(40);expect(s.events.some(e=>e.text?.includes('ホストの許可'))).toBe(true);expect(s.player.tool).toBe(false);});
 it('checks a sword terrain hit at impact even if permission was revoked during windup',()=>{const s=simulation(),guest=s.enableCompanion();guest.position={x:2,y:.25,z:3};s.arena.field.box({x:1,y:.25,z:1.3},{x:3,y:2,z:1.6},4,'target-wood');s.companionCanEdit=true;s.companionAction('attack');s.companionCanEdit=false;const revision=s.arena.field.revision;steps(s,50);expect(s.arena.field.revision).toBe(revision);expect(s.elements.states.size).toBe(0);expect(s.events.some(e=>e.text?.includes('ホストの許可'))).toBe(true);});
 it('does not restore edit authority from an actor snapshot and resets on a new companion',()=>{const s=simulation();s.enableCompanion();const snapshot=s.getCompanionSnapshot()!;s.companionCanEdit=true;expect(s.restoreCompanionSnapshot(snapshot)).toBe(true);expect(s.companionCanEdit).toBe(true);s.disableCompanion();s.enableCompanion();expect(s.companionCanEdit).toBe(false);});
});
describe('independent environmental and ability state',()=>{
 it('runs oxygen and cold for the guest without changing primary environmental status',()=>{const s=simulation(true),g=s.enableCompanion();s.arena.field.box({x:-9,y:4.5,z:-51},{x:-5,y:5.25,z:-47},3);g.position={x:-7,y:5.25,z:-49};s.tick(.1,idle);expect(s.cold).toBe(0);expect(s.getCompanionSnapshot()!.aux.cold).toBeGreaterThan(0);s.arena.field.box({x:11,y:.5,z:-52},{x:16,y:1.25,z:-47},3);g.position={x:13,y:1.25,z:-50};g.vy=0;s.tick(.1,idle);expect(s.oxygen).toBe(20);expect(s.swimming).toBe(false);expect(s.getCompanionSnapshot()!.aux.oxygen).toBeCloseTo(19.9);expect(s.getCompanionSnapshot()!.aux.swimming).toBe(true);});
 it('casts independently with its own cooldown, selected element and stamina',()=>{const s=simulation(),g=s.enableCompanion();s.companionCanEdit=true;s.player.position={x:-2,y:.25,z:3};g.position={x:2,y:.25,z:3};for(const x of [-2,2])s.arena.field.box({x:x-.4,y:.25,z:1},{x:x+.4,y:2.5,z:1.5},4,'wood-'+x);s.selectedElement='water';s.companionAction('cast');expect(g.phase).toBe('cast');expect(s.player.phase).toBe('idle');expect(g.stamina).toBe(82);s.action('cast',idle);expect(s.player.phase).toBe('cast');expect(s.player.stamina).toBe(82);expect(s.getCompanionSnapshot()!.aux.selectedElement).toBe('fire');expect(s.selectedElement).toBe('water');s.tick(.1,idle);expect(s.getCompanionSnapshot()!.aux.castCooldown).toBeCloseTo(.6);});
 it('uses an independent fog timer without ticking the party food timer twice',()=>{const s=simulation(true),g=s.enableCompanion();s.campaign.state.foodSeconds=100;s.arena.field.box({x:5,y:-.5,z:-11},{x:9,y:.25,z:-7},3);g.position={x:7,y:.25,z:-9};const remaining=s.getCompanionSnapshot()!.aux.shroudSeconds;s.tick(.1,idle);expect(s.getCompanionSnapshot()!.aux.shroudSeconds).toBeCloseTo(remaining-.1);expect(s.campaign.state.shroudSeconds).toBe(s.campaign.shroudMaximum);expect(s.campaign.state.foodSeconds).toBeCloseTo(99.9);});
});
describe('absent or disconnected companion suspension',()=>{
 it('preserves body, health and hazard state on disconnect/reconnect without targeting or ticking an invisible actor',()=>{const s=simulation(true),g=s.enableCompanion();s.player.position={x:-5,y:.25,z:3};g.position={x:2,y:.25,z:3};g.hp=43;g.stamina=61;g.phase='windup';g.time=.1;s.withCompanion(()=>{s.oxygen=9;s.cold=12;});s.setCompanionConnected(false);const before=s.getCompanionSnapshot()!;Object.assign(s.enemies[0],{position:{x:0,y:.25,z:3},hp:100,phase:'idle',time:0});s.tick(.1,idle);expect(s.enemies[0].position.x).toBeLessThan(0);expect(s.getCompanionSnapshot()).toEqual(before);expect(s.setCompanionInput({...input,x:1})).toBe(false);expect(s.companionAction('attack')).toBe(false);s.setCompanionConnected(true);expect(s.companion).toBe(g);expect(g.position).toEqual(before.player.position);expect(g.hp).toBe(43);expect(g.stamina).toBe(61);expect(s.getCompanionSnapshot()!.aux.oxygen).toBe(9);expect(s.companionSuspended).toBe(false);});
 it('does not collect resources or block the primary while absent, then collects once after returning',()=>{const s=simulation(),g=s.enableCompanion();s.player.position={x:0,y:.25,z:3};g.position={x:2,y:.25,z:3};s.setCompanionConnected(false);s.survival.addDrops([{id:'absent-guest-drop',material:4,count:5,position:{x:2,y:1,z:3}}]);s.tick(.01,idle);expect(s.survival.inventory[4]).toBe(0);steps(s,50,{...idle,x:1});expect(s.player.position.x).toBeGreaterThan(1.6);const saved={...g.position};s.player.position={x:-5,y:.25,z:3};s.player.vx=0;s.player.vz=0;s.setCompanionConnected(true);expect(g.position).toEqual(saved);s.tick(.01,idle);expect(s.survival.inventory[4]).toBe(5);s.tick(.01,idle);expect(s.survival.inventory[4]).toBe(5);});
 it('keeps a dead companion dead across disconnect and reconnect',()=>{const s=simulation(),g=s.enableCompanion();g.hp=0;s.setCompanionConnected(false);steps(s,5);s.setCompanionConnected(true);expect(g.hp).toBe(0);expect(s.companionRespawn()).toBe(true);expect(g.hp).toBe(100);});
});
