import {afterEach,describe,it,expect,vi} from 'vitest';
import {setMaxListeners} from 'node:events';
import {createCooperationPanel} from '../../src/prototype/cooperation-panel';
import {cooperationControls,cooperationChatText,type CooperationSnapshot} from '../../src/prototype/campaign-ui';
class Element extends EventTarget {
 children:Element[]=[];parent:Element|null=null;dataset:Record<string,string>={};attributes=new Map<string,string>();id='';className='';type='';value='';disabled=false;hidden=false;readOnly=false;maxLength=0;placeholder='';scrollTop=0;clientHeight=100;select=vi.fn();private text='';
 constructor(readonly tag:string){super();}
 get textContent():string{return this.text+this.children.map(c=>c.textContent).join('');}set textContent(value:string){this.text=value;this.replaceChildren();}
 get scrollHeight(){return this.children.length*30;}
 append(...children:Element[]){for(const c of children){c.parent?.remove(c);c.parent=this;this.children.push(c);}}
 remove(child:Element){this.children=this.children.filter(c=>c!==child);child.parent=null;}
 replaceChildren(...children:Element[]){for(const c of this.children)c.parent=null;this.children=[];this.append(...children);}
 contains(child:Element):boolean{return child===this||this.children.some(c=>c.contains(child));}
 setAttribute(key:string,value:string){this.attributes.set(key,value);}getAttribute(key:string){return this.attributes.get(key)??null;}
}
const find=(root:Element,predicate:(node:Element)=>boolean):Element|undefined=>predicate(root)?root:root.children.map(c=>find(c,predicate)).find(Boolean);
const state=(extra:Partial<CooperationSnapshot>={}):CooperationSnapshot=>({enabled:true,status:'同期済み',role:'guest',invite:'https://example.test/#campaign-room=example',guestBuild:false,muted:false,players:2,messages:[],canJoin:true,...extra});
function setup(){vi.stubGlobal('document',{createElement:(tag:string)=>new Element(tag),createTextNode:(value:string)=>{const n=new Element('#text');n.textContent=value;return n;}});const abort=new AbortController();setMaxListeners(50,abort.signal);const action=vi.fn(),panel=createCooperationPanel(action,cooperationControls,cooperationChatText,abort.signal),root=panel.root as unknown as Element;panel.update(state());return {panel,root,action,abort,input:find(root,n=>n.id==='cooperation-chat')!,send:find(root,n=>n.dataset.coop==='chat')!};}
const type=(input:Element,text:string)=>{input.value=text;input.dispatchEvent(new Event('input'));};
afterEach(()=>vi.unstubAllGlobals());
describe('stable cooperation controls under live snapshots',()=>{
 it('retains composer identity and draft through repeated status and incoming-message updates',()=>{const {panel,root,input,send,action}=setup();type(input,'  合流しよう <b>text</b>  ');for(let i=0;i<100;i++){panel.update(state({status:'更新'+i,messages:[{from:'ホスト',text:'更新'+i}]}));expect(find(root,n=>n.id==='cooperation-chat')).toBe(input);expect(find(root,n=>n.dataset.coop==='chat')).toBe(send);expect(root.contains(send)).toBe(true);expect(input.value).toBe('  合流しよう <b>text</b>  ');}send.dispatchEvent(new Event('click'));expect(action).toHaveBeenCalledExactlyOnceWith('chat','合流しよう <b>text</b>');expect(input.value).toBe('');expect(send.disabled).toBe(true);});
 it('updates permissions on the same button using current state and never auto-joins',()=>{const {panel,root,action}=setup();panel.update(state({role:'host'}));const permission=find(root,n=>n.dataset.coop==='allow-build')!;permission.dispatchEvent(new Event('click'));expect(action).toHaveBeenLastCalledWith('allow-build');panel.update(state({role:'host',guestBuild:true}));expect(find(root,n=>n.dataset.coop==='deny-build')).toBe(permission);permission.dispatchEvent(new Event('click'));expect(action).toHaveBeenLastCalledWith('deny-build');panel.update(state({role:null,guestPreview:true}));expect(action).toHaveBeenCalledTimes(2);expect(find(root,n=>n.dataset.coop==='create')!.disabled).toBe(true);expect(find(root,n=>n.dataset.coop==='join')!.disabled).toBe(false);});
 it('preserves drafts but prevents pointer and Enter sends while muted or disconnected',()=>{const {panel,input,send,action}=setup();type(input,'draft');panel.update(state({muted:true}));expect(input.disabled).toBe(true);expect(input.value).toBe('draft');send.dispatchEvent(new Event('click'));input.dispatchEvent(Object.assign(new Event('keydown',{cancelable:true}),{code:'Enter',isComposing:false}));expect(action).not.toHaveBeenCalled();panel.update(state({enabled:false}));expect(send.disabled).toBe(true);panel.update(state());expect(send.disabled).toBe(false);input.dispatchEvent(Object.assign(new Event('keydown',{cancelable:true}),{code:'Enter',isComposing:true}));expect(action).not.toHaveBeenCalled();input.dispatchEvent(Object.assign(new Event('keydown',{cancelable:true}),{code:'Enter',isComposing:false}));expect(action).toHaveBeenCalledExactlyOnceWith('chat','draft');});
 it('keeps incoming markup as text and bounds displayed messages',()=>{const {panel,root}=setup();panel.update(state({messages:Array.from({length:110},(_,i)=>({from:'host',text:i===109?'<b>plain</b>':'message'+i}))}));const log=find(root,n=>n.getAttribute('role')==='log')!;expect(log.children).toHaveLength(100);expect(log.textContent).toContain('<b>plain</b>');expect(find(log,n=>n.tag==='b')).toBeUndefined();});
 it('leaves unchanged log nodes intact and aborts all interaction listeners',()=>{const {panel,root,input,send,abort,action}=setup();panel.update(state({messages:[{from:'host',text:'hello'}]}));const log=find(root,n=>n.getAttribute('role')==='log')!,entry=log.children[0];panel.update(state({status:'different status',messages:[{from:'host',text:'hello'}]}));expect(log.children[0]).toBe(entry);type(input,'unsent');abort.abort();send.dispatchEvent(new Event('click'));expect(action).not.toHaveBeenCalled();});
});
