import { expect,it,vi } from 'vitest';
import { GameSimulation } from '../../src/simulation/game-simulation';
import { SdfWorld } from '../../src/world/density';
import { FluidGrid } from '../../src/fluid/fluid';
import { validateSave } from '../../src/save/format';
import { buildingVoxels,carveVoxels,occupied,localPoint,footSurface } from '../../src/game/voxel/model';
import { interactionTarget } from '../../src/game/interaction/target';
import { dropItem,pickupItem } from '../../src/game/interaction/drops';
import { landscapeDelta,landscapePoint,landscapeSize,viewportSize } from '../../src/platform/viewport/landscape';
import { snapBuilding } from '../../src/game/placement';
it('maps portrait display and touch coordinates into a landscape game',()=>{expect(landscapeSize(390,844)).toEqual({width:844,height:390,rotated:true});expect(landscapePoint(195,422,390,844)).toEqual({x:422,y:195});expect(landscapeDelta(0,25,390,844)).toEqual({x:25,y:0});});
it('uses an eighth-volume water cell and migrates old volume without losing it',()=>{const world=new SdfWorld();world.density=p=>p.y;const f=new FluidGrid(world,.5);f.restore([{x:0,y:2,z:0,volume:.75,vx:2}]);expect(f.cells.size).toBe(8);expect(f.snapshot().reduce((n,c)=>n+c.volume,0)).toBeCloseTo(.75);expect(f.surfaceHeight(.25,.25)).toBeCloseTo(2.75);expect(f.add({x:1,y:2,z:0},1)).toBe(.125);const before=f.snapshot().reduce((n,c)=>n+c.volume,0);f.step();expect(f.snapshot().reduce((n,c)=>n+c.volume,0)).toBeCloseTo(before,8);});
it('carves persistent cells, keeps adjacent cells, and targets only occupied building surfaces',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.resources=[];g.state.buildings=[{id:12,definition:'wall',x:0,y:10,z:0,rotation:0,support:4,contents:{}}];const b=g.state.buildings[0],model=buildingVoxels('wall'),point={x:0,y:1,z:0};b.removed=[];expect(carveVoxels(model,point,.65,b.removed).length).toBeGreaterThan(0);expect(occupied(model,point,new Set(b.removed))).toBe(false);expect(occupied(model,{x:.9,y:1,z:0},new Set(b.removed))).toBe(true);Object.assign(sim.player,{x:0,y:10,z:2});expect(interactionTarget(g.snapshot(),sim.player,{x:0,y:11,z:3},{x:0,y:0,z:-1})).toBeNull();expect(validateSave(sim.save()).adventure!.buildings[0].removed).toEqual(b.removed);});
it('picks the aimed resource instead of a nearer off-axis resource and rejects remote interactions',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.buildings=[];g.state.resources=[{id:100,kind:'branch',amount:2,ready:0,x:0,y:10,z:0},{id:101,kind:'stone',amount:1,ready:0,x:1,y:10,z:1}];Object.assign(sim.player,{x:0,y:10,z:2});const hit=interactionTarget(g.snapshot(),sim.player,{x:0,y:10.4,z:5},{x:0,y:0,z:-1});expect(hit?.id).toBe('r:100');expect(()=>g.action('interact','r:100',{x:0,y:10,z:0})).not.toThrow();expect(g.state.inventory.wood).toBe(2);Object.assign(sim.player,{x:20,y:10,z:2});expect(()=>g.action('interact','r:101',{x:1,y:10,z:1})).toThrow('近づいて');});
it('preserves partial pickup counts, merges stacks, and restores physical drops',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.resources=[];g.state.inventory={wood:149};dropItem(g,'wood',10,sim.player);const n=g.state.resources[0];expect(pickupItem(g,n.id)).toBe(1);expect(n.amount).toBe(9);expect(g.state.inventory.wood).toBe(150);dropItem(g,'wood',3,sim.player);expect(g.state.resources).toHaveLength(1);expect(n.amount).toBe(12);expect(new GameSimulation(validateSave(sim.save())).adventure.state.resources[0].drop).toBe(true);});
it('commits stamina at attack start and hits only after windup, without aim assistance',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.buildings=[];g.state.resources=[];Object.assign(sim.player,{x:0,y:20,z:0});const enemy={...g.state.enemies[0],x:0,y:20,z:-1,health:50,alerted:1};g.state.enemies=[enemy];g.action('attack','',undefined,{x:0,y:0,z:-1});expect(enemy.health).toBe(50);expect(g.state.stamina).toBeLessThan(50);g.stepPersonal(.1);expect(enemy.health).toBe(50);g.stepPersonal(.1);expect(enemy.health).toBeLessThan(50);const hp=enemy.health,stamina=g.state.stamina;g.action('attack');expect(enemy.health).toBe(hp);expect(g.state.stamina).toBe(stamina);});
it('snaps a wall to the side and top sockets of an existing piece',()=>{const anchor={id:1,definition:'wall',x:0,y:5,z:0,rotation:0,support:4,contents:{}};expect(snapBuilding('wall',{x:.9,y:6,z:0},{x:1,y:0,z:0},0,anchor)).toEqual({x:2,y:5,z:0});expect(snapBuilding('wall',anchor,{x:0,y:1,z:0},0,anchor).y).toBe(7);expect(localPoint({x:0,y:6,z:-1},anchor,Math.PI/2).x).toBeCloseTo(1);});

it('lets an attack follow guard release and shares the visible cell height for landing',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.resources=[];g.state.buildings=[];g.state.enemies=[];g.action('guard','on');expect(g.guarding).toBe(true);g.action('guard','off');expect(g.guarding).toBe(false);expect(()=>g.action('attack')).not.toThrow();const model=buildingVoxels('floor');expect(footSurface(model,{x:0,y:.25,z:0},.3)).toBe(.25);});

it('aims at the actual upper roof voxels rather than the old thin bounding box',()=>{const sim=new GameSimulation(),g=sim.adventure;g.state.resources=[];g.state.equipment='hammer';g.state.buildings=[{id:12,definition:'roof',x:0,y:10,z:0,rotation:0,support:4,contents:{}}];Object.assign(sim.player,{x:0,y:10,z:2});expect(interactionTarget(g.snapshot(),sim.player,{x:0,y:11.1,z:3},{x:0,y:0,z:-1})?.id).toBe('b:12');});

it('exits the specifically aimed raft after boarding it',()=>{const sim=new GameSimulation(),g=sim.adventure,p=sim.player;g.state.buildings=[{id:12,definition:'raft',x:p.x,y:p.y,z:p.z-1,rotation:0,support:4,contents:{}}];const target={x:p.x,y:p.y,z:p.z-1};g.action('interact','b:12',target);expect(g.state.meadows!.riding).toBe(12);g.action('interact','b:12',target);expect(g.state.meadows!.riding).toBeUndefined();});

it('measures the fixed mobile viewport instead of transformed overflow during rotation',()=>{vi.stubGlobal('document',{documentElement:{clientWidth:390,clientHeight:844}});vi.stubGlobal('innerWidth',844);vi.stubGlobal('innerHeight',1827);try{const size=viewportSize();expect(size).toEqual({width:390,height:844});expect(landscapeSize(size.width,size.height)).toEqual({width:844,height:390,rotated:true});}finally{vi.unstubAllGlobals();}});
