import {expect,it} from 'vitest';
import {createdPreview,movedPreview,rebuiltPreview,attachmentPoints,constructionCost} from '../../src/game/skybound/preview';
import {SkyboundPowers} from '../../src/game/skybound/powers';
import type {SkyPart,SkyContext} from '../../src/game/skybound/types';
import {WORLD} from '../../src/world/types';
const aim={x:0,y:0,z:1};
it('builds non-mutating grid previews with exact material cost and preserves quaternion assembly geometry',()=>{const a=createdPreview('beam','metal',{x:3.04,y:2.12,z:0}).parts[0];a.id=1;const b={...createdPreview('block','wood',{x:4,y:2.125,z:0}).parts[0],id:2};a.links=[2];b.links=[1];const parts=[a,b],before=structuredClone(parts),preview=movedPreview(parts,1,{x:3,y:3,z:0},Math.PI/2);expect(preview.parts).toHaveLength(2);expect(preview.parts[0].position).toEqual({x:3,y:3,z:0});expect(preview.parts[1].position.z).toBeCloseTo(-1);expect(constructionCost(parts)).toEqual({iron:2,wood:3});expect(parts).toEqual(before);});
it('previews blueprint costs and attachment face positions without modifying a blueprint',()=>{const a={...createdPreview('block','wood',{x:0,y:2,z:0}).parts[0],id:1},b={...a,id:2,position:{x:1.1,y:2,z:0}};const[one,two]=attachmentPoints(a,b);expect(one.x).toBe(.5);expect(two.x).toBeCloseTo(.6);const plan={id:3,owner:'a',name:'箱',parts:[{kind:'block' as const,material:'wood' as const,offset:{x:0,y:0,z:0},rotation:0,links:[]}]};expect(rebuiltPreview(plan,{x:2.03,y:3,z:4}).parts[0].position).toEqual({x:2,y:3,z:4});expect(plan.parts[0].offset).toEqual({x:0,y:0,z:0});});
function fixture(){const powers=new SkyboundPowers(),ctx:SkyContext={tick:1,bounds:WORLD,player:{x:0,y:2,z:0},inventory:{woodArrow:3,resin:2,fireArrow:0},actors:[],solid:()=>false};return{powers,ctx};}
it('fuses one arrow atomically into an existing fire projectile and preserves state on capacity or material rejection',()=>{const{powers,ctx}=fixture();powers.action('a','sky-fuse','woodArrow:resin',undefined,aim,ctx);expect(ctx.inventory).toEqual({woodArrow:2,resin:1,fireArrow:1});const before={...ctx.inventory};ctx.canReceiveItem=()=>false;expect(()=>powers.action('a','sky-fuse','woodArrow:resin',undefined,aim,ctx)).toThrow('空き');expect(ctx.inventory).toEqual(before);ctx.canReceiveItem=()=>true;ctx.inventory.resin=0;expect(()=>powers.action('a','sky-fuse','woodArrow:resin',undefined,aim,ctx)).toThrow('素材');expect(ctx.inventory.woodArrow).toBe(2);});
it('still refuses a previewed placement that becomes occupied without consuming materials',()=>{const{powers,ctx}=fixture();ctx.inventory.wood=5;const preview=createdPreview('block','wood',{x:0,y:2,z:3});ctx.solid=p=>p.z>2;expect(()=>powers.action('a','sky-part','block:wood',preview.parts[0].position,aim,ctx)).toThrow('重な');expect(ctx.inventory.wood).toBe(5);expect(powers.state.parts).toHaveLength(0);});
it('filters and sorts designs without rewriting their IDs, original order, or names',async()=>{const {filterBlueprints}=await import('../../src/game/skybound/preview');const a={id:10,owner:'a',name:'空の舟',parts:[]},b={id:20,owner:'a',name:'旅の橋',parts:[]};expect(filterBlueprints([a,b],'舟','name').map(p=>p.id)).toEqual([10]);expect(filterBlueprints([a,b],'20','original').map(p=>p.id)).toEqual([20]);expect(filterBlueprints([a,b],'見つからない','parts')).toEqual([]);expect([a.id,b.id]).toEqual([10,20]);});
