import {expect,it} from 'vitest';
import {CharacterMotor,CHARACTER_HEIGHT,CROUCH_HEIGHT} from '../../src/physics/character';
import {SdfWorld} from '../../src/world/density';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {SessionAuthority} from '../../src/simulation/session';
import {canStand} from '../../src/game/crouch';
import {createdPreview} from '../../src/game/skybound/preview';
import {collidePlayerRocks} from '../../src/physics/contacts';
import {createAvatarAssets} from '../../src/rendering/game/avatar';
import * as THREE from 'three';
const idle={x:0,z:0,jump:false};
function setup(){const sim=new GameSimulation();sim.world.density=p=>p.y;sim.fluid.restore([]);sim.bodies.length=0;sim.skybound.state.parts=[];sim.adventure.state.buildings=[];sim.adventure.state.resources=[];sim.adventure.state.enemies=[];Object.assign(sim.player,{x:30,y:0,z:30,vy:0,grounded:true});return sim;}
it('uses a lower capsule to cross a genuinely low terrain passage while the original standing body cannot fit',()=>{const world=new SdfWorld();world.density=p=>Math.min(p.y,Math.max(1-p.x,1.12-p.y,p.y-2.5,Math.abs(p.z)-2));for(const crouching of[false,true]){const motor=new CharacterMotor(world),p={x:0,y:0,z:0,vy:0,grounded:true,crouching};for(let i=0;i<45;i++)motor.step(p,.07,0,false,1/30);expect(p.y).toBeGreaterThan(-.05);expect(p.y).toBeLessThan(.05);if(crouching)expect(p.x).toBeGreaterThan(2);else expect(p.x).toBeLessThan(1);}});
it('keeps feet fixed while crouching, blocks standing beneath terrain, and stands after reaching free space',()=>{const sim=setup(),game=sim.adventure;game.state.meadows!.sneaking=true;game.traversal.beforeMove(idle,1/30);expect(sim.player.crouching).toBe(true);expect(sim.player.y).toBe(0);sim.world.density=p=>Math.min(p.y,p.x<31?1.12-p.y:100);game.state.meadows!.sneaking=false;game.traversal.beforeMove(idle,1/30);expect(sim.player.crouching).toBe(true);expect(game.traversal.snapshot().warning).toContain('頭上');expect(sim.player.y).toBe(0);sim.player.x=32;game.traversal.beforeMove(idle,1/30);expect(sim.player.crouching).toBe(false);expect(CHARACTER_HEIGHT).toBe(1.45);expect(CROUCH_HEIGHT).toBe(1);});
it('checks carved building ceilings, oriented creative parts and rocks before expanding the capsule',()=>{for(const kind of['building','part','rock']){const sim=setup();sim.player.crouching=true;if(kind==='building')sim.adventure.state.buildings=[{id:1,definition:'floor',x:30,y:1.12,z:30,rotation:0,support:4,contents:{}}];if(kind==='part')sim.skybound.state.parts=[{...createdPreview('slab','wood',{x:30,y:1.25,z:30}).parts[0],id:1}];if(kind==='rock')sim.bodies.push({id:1,position:{x:30,y:1.4,z:30},radius:.2,velocity:{x:0,y:0,z:0},sleeping:true});expect(canStand(sim.adventure),kind).toBe(false);const before={...sim.player};sim.adventure.collidePlayer(0);collidePlayerRocks(sim.player,sim.bodies,0,0,1/30);expect(sim.player.x).toBe(before.x);expect(sim.player.z).toBe(before.z);expect(sim.player.y).toBeCloseTo(0);}});
it('replicates actual crouch to peers and restores an old-compatible save without adding a root player save field',()=>{const room=new SessionAuthority(),guest=room.join('friend');room.sim.adventure.state.enemies=[];guest.adventure.state.meadows!.sneaking=true;room.step(idle);expect(guest.player.crouching).toBe(true);expect(room.sim.player.crouching??false).toBe(false);expect(room.view('host').peers.find(p=>p.id==='friend')?.appearance?.crouching).toBe(true);expect(room.view('friend').player.crouching).toBe(true);const save=room.save();expect(save.player).not.toHaveProperty('crouching');const restored=new SessionAuthority(save),returning=restored.join('friend');expect(returning.player.crouching).toBe(true);});
it('shows a visibly lower original avatar pose and restores standing geometry',()=>{const assets=createAvatarAssets(),avatar=assets.create();avatar.setPose({crouching:false,grounded:true});avatar.animate(1/30);const standing=new THREE.Box3().setFromObject(avatar.group).max.y;avatar.setPose({crouching:true,grounded:true});avatar.animate(1/30);const crouched=new THREE.Box3().setFromObject(avatar.group).max.y;expect(crouched).toBeLessThan(standing*.8);avatar.setPose({crouching:false,grounded:true});avatar.animate(1/30);expect(new THREE.Box3().setFromObject(avatar.group).max.y).toBeCloseTo(standing);assets.dispose();});
it('preserves an actually crouched body across a save even when its requested stand is blocked, and rejects forged posture values',async()=>{const {validateSave}=await import('../../src/save/format');const sim=setup();sim.player.crouching=true;sim.adventure.state.meadows!.sneaking=false;const save=sim.save();expect(save.player.crouching).toBe(true);expect(new GameSimulation(save).player.crouching).toBe(true);const forged=structuredClone(save);(forged.player as unknown as {crouching:unknown}).crouching='small';expect(()=>validateSave(forged)).toThrow('姿勢');delete save.player.crouching;expect(new GameSimulation(save).player.crouching??false).toBe(false);});
