import {describe,expect,it} from 'vitest';
import {createActor,DungeonSimulation} from '../../src/dungeon/simulation';
import {activeBastionSkill,BASTION_SKILLS,bastionSkillReadyIn,bastionTrainingStats,getBastionTraining,validBastionSkillState,validBastionTraining} from '../../src/dungeon/training';
import {parsePacket,validRaidState} from '../../src/dungeon/protocol';
import {blocked,distance} from '../../src/dungeon/world';
import type {Actor,BastionSkill,BastionTraining} from '../../src/dungeon/types';
const none:BastionTraining={skill:null,perk:null};
function lobby(){const sim=new DungeonSimulation(),p=sim.join('a'.repeat(64),'A')!,q=sim.join('b'.repeat(64),'B')!;return {sim,p,q};}
function game(training:BastionTraining=none){const {sim,p,q}=lobby();if(training.skill||training.perk)sim.command(p.actor.id,1,{kind:'configure-training',...training});sim.command(p.actor.id,2,{kind:'ready'});sim.command(q.actor.id,1,{kind:'ready'});sim.command(p.actor.id,3,{kind:'start'});sim.state.enemies=[];return {sim,p,q};}
function walk(sim:DungeonSimulation,a:Actor,x:number,z:number,steps:number){for(let i=0;i<steps;i++){sim.input(a.id,a.seq+1,{x,z,yaw:a.yaw,pitch:0,block:a.input.block,crouch:a.input.crouch});sim.step();}}
function fireAt(sim:DungeonSimulation,target:Actor,from:{x:number;y:number;z:number}){sim.state.shots.push({id:'test-shot',owner:'p2',position:from,velocity:{x:(target.position.x-from.x)*20,y:0,z:(target.position.z-from.z)*20},life:1,damage:100,magic:true});sim.step();}

describe('optional bastion training selection and unchanged defaults',()=>{
 it('keeps legacy actors empty and exact base stats without a selection',()=>{const {sim,p}=game();expect(p.actor.training).toBeUndefined();expect(p.actor.skillState).toBeUndefined();expect(getBastionTraining(p.actor)).toEqual(none);expect(bastionTrainingStats(none)).toEqual({maxHp:125,speed:3});expect(p.actor.maxHp).toBe(125);const x=p.actor.position.x;walk(sim,p.actor,1,0,1);expect(p.actor.position.x-x).toBeCloseTo(.15);expect(sim.command(p.actor.id,4,{kind:'skill'})).toContain('選んで');expect(p.actor.skillState).toBeUndefined();expect(validRaidState(sim.state)).toBe(true);});
 it('applies exactly one selected perk and resets lobby HP without changing assets',()=>{const {sim,p}=lobby();p.gold=37;p.quests=[{id:'first-return',progress:0,claimed:false}];const before=structuredClone({gold:p.gold,quests:p.quests,bag:p.actor.bag,stash:p.stash,pending:p.pendingReturn,receipt:p.receipt});sim.command(p.actor.id,1,{kind:'configure-training',skill:'rush',perk:'vigor'});expect(p.actor.training).toEqual({skill:'rush',perk:'vigor'});expect([p.actor.hp,p.actor.maxHp,p.actor.recoverable]).toEqual([135,135,135]);expect(bastionTrainingStats(p.actor.training!)).toEqual({maxHp:135,speed:3});sim.command(p.actor.id,2,{kind:'configure-training',skill:'brace',perk:'stride'});expect([p.actor.hp,p.actor.maxHp,p.actor.recoverable]).toEqual([125,125,125]);expect(bastionTrainingStats(p.actor.training!)).toEqual({maxHp:125,speed:3.15});expect({gold:p.gold,quests:p.quests,bag:p.actor.bag,stash:p.stash,pending:p.pendingReturn,receipt:p.receipt}).toEqual(before);expect(validRaidState(sim.state)).toBe(true);});
 it('preserves selection when switching classes but does not apply it to other classes',()=>{const {sim,p}=lobby();sim.command(p.actor.id,1,{kind:'configure-training',skill:'rush',perk:'vigor'});sim.command(p.actor.id,2,{kind:'class',classId:'hunter'});expect(p.actor.maxHp).toBe(100);expect(p.actor.training?.perk).toBe('vigor');expect(sim.command(p.actor.id,3,{kind:'configure-training',skill:null,perk:null})).toContain('城塞兵');sim.command(p.actor.id,4,{kind:'class',classId:'bastion'});expect(p.actor.maxHp).toBe(135);expect(p.actor.training?.skill).toBe('rush');});
 it('rejects selection while ready, alive, dead, extracted or while another raid is ongoing',()=>{for(const status of ['lobby','alive','dead','extracted'] as const){const {sim,p}=lobby();p.actor.status=status;if(status==='lobby')p.actor.ready=true;expect(sim.command(p.actor.id,1,{kind:'configure-training',skill:'rush',perk:'vigor'})).toContain('準備を解除');expect(p.actor.training).toBeUndefined();}const {sim,p}=lobby();sim.state.phase='raid';expect(sim.command(p.actor.id,1,{kind:'configure-training',skill:'rush',perk:'vigor'})).toContain('準備を解除');expect(p.actor.training).toBeUndefined();});
 it('applies vigor to normal raid initialization and never creates extra items',()=>{const base=game(),vigor=game({skill:'brace',perk:'vigor'});expect(vigor.p.actor.hp).toBe(135);expect(vigor.p.actor.recoverable).toBe(135);expect(vigor.p.actor.bag).toEqual(base.p.actor.bag);expect(validRaidState(vigor.sim.state)).toBe(true);});
});

describe('server-authoritative active training',()=>{
 it.each(['rush','brace'] as BastionSkill[])('uses finite %s duration/cooldown, rejects replays and expires exactly',skill=>{const {sim,p}=game({skill,perk:null});sim.state.elapsed=20;expect(sim.command(p.actor.id,4,{kind:'skill'})).toContain('発動');const state=structuredClone(p.actor.skillState);expect(state).toEqual({skill,activeUntil:20+BASTION_SKILLS[skill].duration,readyAt:20+BASTION_SKILLS[skill].cooldown});expect(activeBastionSkill(p.actor,20)).toBe(skill);expect(activeBastionSkill(p.actor,state!.activeUntil)).toBeNull();expect(bastionSkillReadyIn(p.actor,20)).toBe(BASTION_SKILLS[skill].cooldown);for(let i=0;i<10;i++)expect(sim.command(p.actor.id,4,{kind:'skill'})).toContain('処理済み');expect(sim.command(p.actor.id,5,{kind:'skill'})).toContain('再使用待ち');expect(p.actor.skillState).toEqual(state);sim.state.elapsed=state!.readyAt;expect(sim.command(p.actor.id,6,{kind:'skill'})).toContain('発動');expect(validRaidState(sim.state)).toBe(true);});
 it('does not consume or reset cooldown on invalid phase, cast, interaction or extraction',()=>{for(const patch of [{phase:'windup'},{phase:'heal'},{cast:.8},{cast:-.55},{interaction:'chest0'},{extract:.5}] as Partial<Actor>[]){const {sim,p}=game({skill:'rush',perk:null});Object.assign(p.actor,patch);expect(sim.command(p.actor.id,4,{kind:'skill'})).toContain('終了');expect(p.actor.skillState).toBeUndefined();}const {sim,p}=game({skill:'brace',perk:null});p.actor.bag=p.actor.bag.filter(i=>i.kind!=='shield');expect(sim.command(p.actor.id,4,{kind:'skill'})).toContain('盾');expect(p.actor.skillState).toBeUndefined();});
 it('cannot activate from the lobby, death, extraction or a different class',()=>{for(const patch of [{status:'lobby'},{status:'dead'},{status:'extracted'},{classId:'hunter'}] as Partial<Actor>[]){const {sim,p}=game({skill:'rush',perk:null});Object.assign(p.actor,patch);sim.command(p.actor.id,4,{kind:'skill'});expect(p.actor.skillState).toBeUndefined();}});
 it('gives exact stride + rush movement, retains crouch/block slowdown and does not heal',()=>{for(const [crouch,block,multiplier] of [[false,false,1],[true,false,.55],[false,true,.48]] as const){const {sim,p}=game({skill:'rush',perk:'stride'});p.actor.hp=41;p.actor.input.crouch=crouch;p.actor.input.block=block;sim.command(p.actor.id,4,{kind:'skill'});const x=p.actor.position.x;walk(sim,p.actor,1,0,1);expect(p.actor.position.x-x).toBeCloseTo(3.15*1.4*.05*multiplier);expect(p.actor.hp).toBe(41);}});
 it('keeps boosted movement outside solid walls, closed doors and living bodies',()=>{for(const destination of ['wall','door','body']){const {sim,p,q}=game({skill:'rush',perk:'stride'});p.actor.position=destination==='wall'?{x:-15,y:0,z:10}:{x:0,y:0,z:destination==='door'?-3:2};q.actor.position={x:0,y:0,z:1};sim.command(p.actor.id,4,{kind:'skill'});walk(sim,p.actor,destination==='wall'?-1:0,destination==='wall'?0:1,25);expect(blocked(p.actor.position,sim.state.seed,sim.state.doors)).toBe(false);if(destination==='wall')expect(p.actor.position.x).toBeGreaterThanOrEqual(-15.2);if(destination==='door')expect(p.actor.position.z).toBeGreaterThan(-4.3);if(destination==='body')expect(distance(p.actor.position,q.actor.position)).toBeGreaterThanOrEqual(.62);}});
 it('reveals selected and active training to opponents without revealing their bags',()=>{const {sim,p,q}=game({skill:'rush',perk:'stride'});sim.command(p.actor.id,4,{kind:'skill'});const other=sim.snapshot(q.actor.id).actors.find(a=>a.id===p.actor.id)!;expect(other.training).toEqual(p.actor.training);expect(other.skillState).toEqual(p.actor.skillState);expect(other.bag).toEqual([]);});
 it('preserves cooldown on disconnect/rejoin, death disables effect, and next raid resets state',()=>{const {sim,p,q}=game({skill:'rush',perk:'vigor'});sim.command(p.actor.id,4,{kind:'skill'});const state=structuredClone(p.actor.skillState);sim.disconnect(p.actor.id);sim.join(p.key,'A');expect(p.actor.skillState).toEqual(state);p.actor.status='dead';expect(activeBastionSkill(p.actor,0)).toBeNull();q.actor.status='dead';sim.state.phase='finished';sim.command(p.actor.id,5,{kind:'return'});sim.command(q.actor.id,2,{kind:'return'});sim.command(p.actor.id,6,{kind:'ready'});sim.command(q.actor.id,3,{kind:'ready'});sim.command(p.actor.id,7,{kind:'start'});expect(sim.state.phase).toBe('raid');expect(p.actor.skillState).toBeUndefined();expect(p.actor.training).toEqual({skill:'rush',perk:'vigor'});expect(p.actor.hp).toBe(135);expect(validRaidState(sim.state)).toBe(true);});
});

describe('brace is enhanced frontal shield guarding, not invulnerability',()=>{
 it.each([
  ['front',0,true,'idle',true,true,6],['side',Math.PI/2,true,'idle',true,true,100],['rear',Math.PI,true,'idle',true,true,100],
  ['unguarded',0,false,'idle',true,true,100],['no shield',0,true,'idle',false,true,100],['attacking',0,true,'windup',true,true,12],['expired',0,true,'idle',true,false,12]
 ] as const)('respects %s conditions',(_name,yaw,guard,phase,shield,active,damage)=>{const {sim,p}=game({skill:'brace',perk:null});p.actor.position={x:0,y:0,z:0};sim.command(p.actor.id,4,{kind:'skill'});p.actor.yaw=yaw;p.actor.guard=guard?1:0;p.actor.input.block=guard;p.actor.inputAt=sim.state.elapsed;p.actor.phase=phase;if(!shield)p.actor.bag=p.actor.bag.filter(i=>i.kind!=='shield');if(!active){sim.state.elapsed=4;p.actor.inputAt=4;}fireAt(sim,p.actor,{x:0,y:1,z:-1});expect(p.actor.damageTaken).toBe(damage);expect(validRaidState(sim.state)).toBe(true);});
});

describe('strict optional training protocol and durable compatibility',()=>{
 it('accepts old saves and only exact well-formed new actions',()=>{const {sim}=game();expect(validRaidState(sim.state)).toBe(true);for(const action of [{kind:'skill'},{kind:'configure-training',skill:null,perk:null},{kind:'configure-training',skill:'rush',perk:'stride'}])expect(parsePacket(JSON.stringify({type:'action',sequence:1,action}))).not.toBeNull();for(const action of [{kind:'skill',duration:1000},{kind:'configure-training',skill:'fly',perk:null},{kind:'configure-training',skill:'rush'},{kind:'configure-training',skill:null,perk:'vigor',actor:'p2'}])expect(parsePacket(JSON.stringify({type:'action',sequence:1,action}))).toBeNull();});
 it('rejects absent subfields, unknown selections and nonfinite or fabricated cooldowns',()=>{for(const value of [null,{},[],{skill:'rush'},{skill:'rush',perk:'unknown'},{skill:null,perk:null,extra:true}])expect(validBastionTraining(value)).toBe(false);for(const value of [null,{},[],{skill:'rush',activeUntil:NaN,readyAt:14},{skill:'rush',activeUntil:2.5,readyAt:Infinity},{skill:'brace',activeUntil:4,readyAt:14},{skill:'rush',activeUntil:-1,readyAt:10.5},{skill:'rush',activeUntil:2.5,readyAt:14,extra:true}])expect(validBastionSkillState(value)).toBe(false);});
 it('rejects present-invalid optional fields and cross-field impossible state without resetting',()=>{const {sim,p}=game({skill:'rush',perk:null});sim.command(p.actor.id,4,{kind:'skill'});expect(validRaidState(sim.state)).toBe(true);for(const patch of [{maxHp:999},{training:undefined},{training:null},{skillState:undefined},{skillState:null},{classId:'hunter'},{training:{skill:'brace',perk:null}},{skillState:{skill:'rush',activeUntil:3.5,readyAt:15}}]){const saved=structuredClone(sim.state);Object.assign(saved.profiles[0].actor,patch);expect(validRaidState(saved)).toBe(false);}});
 it('ignores training bonuses and active state for other classes even in direct helper calls',()=>{const a=createActor('a','A','hunter');a.training={skill:'rush',perk:'vigor'};a.skillState={skill:'rush',activeUntil:2.5,readyAt:14};a.status='alive';expect(activeBastionSkill(a,0)).toBeNull();expect(bastionSkillReadyIn(a,0)).toBe(0);});
});
