import {it,expect} from 'vitest';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import type {Socket} from 'node:net';
import {DungeonServer} from '../../src/dungeon/server';
function frame(text:string,opcode=1){const body=Buffer.from(text),header=Buffer.alloc(body.length<126?2:4);header[0]=0x80|opcode;if(body.length<126)header[1]=body.length;else{header[1]=126;header.writeUInt16BE(body.length,2);}return Buffer.concat([header,body]);}
async function peer(url:string){const ws=new WebSocket(url),messages:{type:string;snapshot?:{you:string;actors:{id:string;position:{x:number}}[];phase:string}}[]=[];ws.onmessage=e=>messages.push(JSON.parse(String(e.data)));await new Promise<void>((resolve,reject)=>{ws.onopen=()=>resolve();ws.onerror=()=>reject(new Error('connect failed'));});return {ws,messages,send:(p:unknown)=>ws.send(JSON.stringify(p)),wait:async(check:()=>boolean)=>{const deadline=Date.now()+5000;while(!check()){if(Date.now()>deadline)throw new Error('Socket state timed out');await new Promise(r=>setTimeout(r,10));}}};}
it('synchronizes two independent actual TCP/WebSocket clients with server-owned movement and restartable profiles',async()=>{const sockets=new Set<Socket>(),room=new DungeonServer({save:async()=>{}});let next=0;const server=createServer((_req,res)=>res.end());server.on('upgrade',(req,duplex)=>{const socket=duplex as Socket,id=String(++next);sockets.add(socket);const key=req.headers['sec-websocket-key'];if(typeof key!=='string'){socket.destroy();return;}const accept=createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);room.connect(id,{send:text=>socket.write(frame(text)),close:()=>socket.end(frame('',8))});let buffer=Buffer.alloc(0);socket.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.length>=2){const opcode=buffer[0]&15,masked=!!(buffer[1]&128);let size=buffer[1]&127,offset=2;if(size===126){if(buffer.length<4)return;size=buffer.readUInt16BE(2);offset=4;}if(size===127||size>4096){socket.destroy();return;}const bytes=masked?4:0;if(buffer.length<offset+bytes+size)return;const mask=buffer.subarray(offset,offset+bytes);offset+=bytes;const body=Buffer.from(buffer.subarray(offset,offset+size));buffer=buffer.subarray(offset+size);if(masked)for(let i=0;i<body.length;i++)body[i]^=mask[i%4];if(opcode===8){socket.end(frame('',8));return;}if(opcode===1)void room.receive(id,body.toString());}});socket.on('close',()=>{sockets.delete(socket);void room.disconnect(id);});socket.on('error',()=>{void room.disconnect(id);});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw new Error('No address');const timer=setInterval(()=>{void room.tick();},50);let a:Awaited<ReturnType<typeof peer>>|undefined,b:Awaited<ReturnType<typeof peer>>|undefined;
 try{a=await peer(`ws://127.0.0.1:${address.port}`);b=await peer(`ws://127.0.0.1:${address.port}`);a.send({type:'hello',protocol:1,key:'a'.repeat(64),name:'A'});b.send({type:'hello',protocol:1,key:'b'.repeat(64),name:'B'});await a.wait(()=>a!.messages.some(p=>p.snapshot?.actors.length===2));expect(sockets.size).toBe(2);a.send({type:'action',sequence:1,action:{kind:'ready'}});b.send({type:'action',sequence:1,action:{kind:'ready'}});await a.wait(()=>room.sim.state.profiles.every(p=>p.actor.ready));a.send({type:'action',sequence:2,action:{kind:'start'}});await a.wait(()=>a!.messages.some(p=>p.snapshot?.phase==='raid'));const id=room.sim.state.profiles[0].actor.id,x=room.sim.state.profiles[0].actor.position.x;a.send({type:'input',sequence:1,input:{x:1,z:0,yaw:0,pitch:0,block:false,crouch:false}});await b.wait(()=>b!.messages.some(p=>p.snapshot?.phase==='raid'&&(p.snapshot.actors.find(p=>p.id===id)?.position.x??-999)>x+.3));expect(room.sim.state.profiles[0].actor.position.x).toBeGreaterThan(x+.3);expect(a.messages.some(p=>p.snapshot?.you!==b!.messages.find(p=>p.snapshot)?.snapshot?.you)).toBe(true);
 }finally{a?.ws.close();b?.ws.close();clearInterval(timer);for(const socket of sockets)socket.destroy();await new Promise<void>(r=>server.close(()=>r()));}
});
