import {describe,it,expect} from 'vitest';
import {DungeonServer,type DungeonCheckpoint,type DungeonPort} from '../../src/dungeon/server';
const key='a'.repeat(64);
function port(){const messages:string[]=[],closed:{code:number;reason:string}[]=[];return {messages,closed,send:(text:string)=>messages.push(text),close:(code:number,reason:string)=>closed.push({code,reason})};}
const hello=(k=key)=>JSON.stringify({type:'hello',protocol:1,key:k,name:'探索者'});
describe('dungeon durable server',()=>{
 it('persists identities before sending state, and rejoining returns the same avatar',async()=>{let saved:DungeonCheckpoint|undefined;const order:string[]=[];const server=new DungeonServer({save:async c=>{saved=c;order.push('save');}},()=>1000),a=port();server.connect('first',{...a,send:text=>{order.push('send');a.send(text);}});await server.receive('first',hello());expect(order[0]).toBe('save');expect(a.messages.length).toBeGreaterThan(0);const actor=server.sim.state.profiles[0].actor.id;const restored=new DungeonServer({save:async()=>{}},()=>1000,saved),b=port();restored.connect('second',b);await restored.receive('second',hello());expect(restored.sim.state.profiles[0].actor.id).toBe(actor);expect(restored.sim.state.profiles).toHaveLength(1);expect(JSON.stringify(JSON.parse(b.messages[0]).snapshot)).not.toContain(key);});
 it('does not acknowledge or reveal uncommitted changes after storage fails',async()=>{const server=new DungeonServer({save:async()=>{throw new Error('full');}},()=>1000),a=port();server.connect('a',a);await server.receive('a',hello());expect(a.messages).toHaveLength(0);expect(a.closed[0].code).toBe(1011);await server.tick();expect(a.messages).toHaveLength(0);});
 it('rejects unknown protocols, unjoined inputs, bad messages and excessive frequency',async()=>{const server=new DungeonServer({save:async()=>{}},()=>1000),a=port();server.connect('a',a);await server.receive('a',JSON.stringify({type:'hello',protocol:0,key,name:'A'}));expect(a.closed[0].code).toBe(1002);const b=port();server.connect('b',b);await server.receive('b',JSON.stringify({type:'action',sequence:1,action:{kind:'start'}}));expect(b.closed[0].code).toBe(1008);const c=port();server.connect('c',c);await server.receive('c','x'.repeat(5000));expect(c.closed[0].code).toBe(1008);});
 it('keeps raid time moving without clients and makes expired raids fatal on process restore',async()=>{let time=1000,saved:DungeonCheckpoint|undefined;const server=new DungeonServer({save:async c=>{saved=c;}},()=>time),a=port();server.connect('a',a);await server.receive('a',hello());await server.receive('a',JSON.stringify({type:'action',sequence:1,action:{kind:'ready'}}));await server.receive('a',JSON.stringify({type:'action',sequence:2,action:{kind:'start'}}));await server.disconnect('a');time+=481000;const restored=new DungeonServer({save:async()=>{}},()=>time,saved);await restored.tick();expect(restored.sim.state.phase).toBe('finished');expect(restored.sim.state.profiles[0].actor.status).toBe('dead');});
 it('rejects corrupt stash instead of silently constructing a new profile',()=>{expect(()=>new DungeonServer({save:async()=>{}},Date.now,{version:1,savedAt:1,state:{version:999} as never})).toThrow('refusing reset');});
 it('replaces an old connection with the same private identity without exposing a second avatar',async()=>{const server=new DungeonServer({save:async()=>{}},()=>1000),a=port(),b=port();server.connect('a',a);await server.receive('a',hello());server.connect('b',b);await server.receive('b',hello());expect(a.closed.at(-1)?.code).toBe(4001);expect(server.sim.state.profiles).toHaveLength(1);});
});

 it('persists and restores legitimate downward arrows without treating velocity as position',async()=>{let time=1000,saved:DungeonCheckpoint|undefined;const server=new DungeonServer({save:async c=>{saved=c;}},()=>time),a=port();server.connect('a',a);await server.receive('a',hello());for(const [sequence,action] of [[1,{kind:'class',classId:'hunter'}],[2,{kind:'ready'}],[3,{kind:'start'}]] as const)await server.receive('a',JSON.stringify({type:'action',sequence,action}));await server.receive('a',JSON.stringify({type:'input',sequence:1,input:{x:0,z:0,yaw:0,pitch:-1.4,block:false,crouch:false}}));await server.receive('a',JSON.stringify({type:'action',sequence:4,action:{kind:'shoot'}}));for(let i=0;i<6;i++){time+=100;await server.tick();}expect(saved?.state.shots.length).toBeGreaterThan(0);expect(saved?.state.shots[0].velocity.y).toBeLessThan(-10);expect(()=>new DungeonServer({save:async()=>{}},()=>time,saved)).not.toThrow();});

 it('does not reinterpret existing falsy corrupt records as an empty room',()=>{for(const saved of [null,false,0,''])expect(()=>new DungeonServer({save:async()=>{}},Date.now,saved as never)).toThrow('refusing reset');});
