import {describe,it,expect,vi,afterEach} from 'vitest';
import {createDungeonInput,movementAxes,normalizeYaw,pointerLook} from '../../src/dungeon/input';
class Element extends EventTarget {
 tagName='DIV';isContentEditable=false;style={setProperty:vi.fn()};classList={add:vi.fn(),remove:vi.fn()};setPointerCapture=vi.fn();requestPointerLock=vi.fn();
 getBoundingClientRect(){return {left:0,top:0,width:100,height:100};}
}
function event(target:EventTarget,type:string,properties:Record<string,unknown>={}){const e=new Event(type,{cancelable:true});const {target: overrideTarget,...other}=properties;Object.assign(e,other);if(overrideTarget)Object.defineProperty(e,'target',{value:overrideTarget});target.dispatchEvent(e);return e;}
function harness(){const window=new EventTarget(),document=Object.assign(new EventTarget(),{hidden:false,pointerLockElement:null,exitPointerLock:vi.fn()});vi.stubGlobal('window',window);vi.stubGlobal('document',document);vi.stubGlobal('HTMLElement',Element);const canvas=new Element(),movePad=new Element(),lookPad=new Element(),attack=new Element(),block=new Element(),action=vi.fn();const input=createDungeonInput({canvas:canvas as unknown as HTMLCanvasElement,movePad:movePad as unknown as HTMLElement,lookPad:lookPad as unknown as HTMLElement,actionButtons:new Map([['attack',attack],['block',block]]) as unknown as Map<string,HTMLElement>},{action});input.setActive(true);return {window,document,canvas,movePad,lookPad,attack,block,action,input};}
afterEach(()=>vi.unstubAllGlobals());
describe('dungeon keyboard and independent touch controls',()=>{
 it('normalizes diagonal movement and clamps view pitch',()=>{const axis=movementAxes(new Set(['KeyW','KeyD']));expect(Math.hypot(axis.x,axis.z)).toBeCloseTo(1);expect(movementAxes(new Set(['KeyW','KeyS']))).toEqual({x:0,z:0});expect(pointerLook(0,0,100,-10000)).toEqual({yaw:-.3,pitch:1.32});});
 it('keeps yaw valid after repeated full turns from touch, keyboard and restored look',()=>{let yaw=0;for(let i=0;i<1000;i++){yaw=pointerLook(yaw,0,300,0).yaw;expect(Math.abs(yaw)).toBeLessThanOrEqual(Math.PI);}expect(normalizeYaw(Infinity)).toBe(0);const h=harness();h.input.setLook(120*Math.PI,0);expect(Math.abs(h.input.sample().yaw)).toBeLessThanOrEqual(Math.PI);event(h.window,'keydown',{code:'ArrowLeft',repeat:false});for(let i=0;i<100;i++)expect(Math.abs(h.input.sample(1).yaw)).toBeLessThanOrEqual(Math.PI);h.input.dispose();});
 it('supports concurrent move, look, attack and held shield without synthetic repeat',()=>{const h=harness();event(h.movePad,'pointerdown',{pointerId:1,pointerType:'touch',clientX:50,clientY:10});event(h.lookPad,'pointerdown',{pointerId:2,pointerType:'touch',clientX:50,clientY:50});event(h.lookPad,'pointermove',{pointerId:2,clientX:100,clientY:20});event(h.attack,'pointerdown',{pointerId:3,pointerType:'touch'});event(h.attack,'click',{detail:1});event(h.block,'pointerdown',{pointerId:4,pointerType:'touch'});expect(h.input.sample()).toMatchObject({x:0,z:40/42,yaw:-.2,pitch:.12,block:true});expect(h.action).toHaveBeenCalledTimes(1);expect(h.action).toHaveBeenCalledWith('attack');event(h.attack,'pointerup',{pointerId:3});expect(h.input.sample().z).toBeGreaterThan(0);event(h.block,'lostpointercapture',{pointerId:4});expect(h.input.sample().block).toBe(false);event(h.movePad,'pointerup',{pointerId:1});expect(h.input.sample().z).toBe(0);h.input.dispose();});
 it('releases every control on blur, rotation, menu and disposal',()=>{const h=harness();for(const type of ['blur','resize','orientationchange']){event(h.window,'keydown',{code:'KeyW',repeat:false});event(h.block,'pointerdown',{pointerId:4});expect(h.input.sample().z).toBe(1);event(h.window,type);expect(h.input.sample()).toMatchObject({x:0,z:0,block:false});}event(h.window,'keydown',{code:'KeyW',repeat:false});h.input.setActive(false);expect(h.input.sample().z).toBe(0);h.input.setActive(true);expect(h.input.sample().z).toBe(0);h.input.dispose();event(h.window,'keydown',{code:'KeyT',repeat:false});expect(h.action).not.toHaveBeenCalled();});
 it('does not turn focused typing into gameplay or repeated keydown into attacks',()=>{const h=harness();const field=new Element();field.tagName='INPUT';event(h.window,'keydown',{code:'KeyT',repeat:false,target:field});expect(h.action).not.toHaveBeenCalled();event(h.window,'keydown',{code:'KeyT',repeat:false});event(h.window,'keydown',{code:'KeyT',repeat:true});expect(h.action).toHaveBeenCalledTimes(1);h.input.setActive(false);event(h.window,'keydown',{code:'KeyE',repeat:false});expect(h.action).toHaveBeenCalledTimes(1);h.input.dispose();});
});


describe('dungeon desktop camera and pointer recovery',()=>{
 it.each(['ShiftLeft','ShiftRight'])('slows keyboard aiming while %s is held and restores it on release',code=>{const h=harness();event(h.window,'keydown',{code:'ArrowLeft'});event(h.window,'keydown',{code});expect(h.input.sample(1).yaw).toBeCloseTo(.65);event(h.window,'keyup',{code});h.input.setLook(0,0);expect(h.input.sample(1).yaw).toBeCloseTo(1.65);h.input.dispose();});
 it('uses the first click for capture, then attacks and guards while locked',()=>{const h=harness();event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0,clientX:10,clientY:10});expect(h.canvas.requestPointerLock).toHaveBeenCalledTimes(1);expect(h.action).not.toHaveBeenCalled();Object.assign(h.document,{pointerLockElement:h.canvas});event(h.document,'pointerlockchange');event(h.window,'pointerup',{pointerId:1});event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});expect(h.action).toHaveBeenCalledExactlyOnceWith('attack');event(h.lookPad,'pointerdown',{pointerId:1,pointerType:'mouse',button:2});expect(h.input.sample().block).toBe(true);event(h.window,'pointerup',{pointerId:1});expect(h.input.sample().block).toBe(false);event(h.window,'mousemove',{movementX:20,movementY:10});expect(h.input.sample()).toMatchObject({yaw:-.06,pitch:-.03});h.input.dispose();});
 it.each(['throw','promise','event','missing'])('retains mouse look and combat after pointer lock fails via %s',async failure=>{
  const h=harness();if(failure==='throw')h.canvas.requestPointerLock.mockImplementation(()=>{throw Error('Denied');});if(failure==='promise')h.canvas.requestPointerLock.mockImplementation(()=>Promise.reject(Error('Denied')));if(failure==='missing')Object.assign(h.canvas,{requestPointerLock:undefined});
  event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0,clientX:10,clientY:10});if(failure==='event')event(h.document,'pointerlockerror');await Promise.resolve();event(h.window,'pointerup',{pointerId:1});expect(h.action).not.toHaveBeenCalled();
  event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0,clientX:10,clientY:10});event(h.window,'pointermove',{pointerId:1,clientX:60,clientY:30});event(h.window,'pointerup',{pointerId:1});expect(h.input.sample()).toMatchObject({yaw:-.15,pitch:-.06});expect(h.action).not.toHaveBeenCalled();
  event(h.lookPad,'pointerdown',{pointerId:1,pointerType:'mouse',button:0,clientX:20,clientY:20});event(h.lookPad,'pointerup',{pointerId:1});event(h.window,'pointerup',{pointerId:1});expect(h.action).toHaveBeenCalledExactlyOnceWith('attack');
  event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:2,clientX:20,clientY:20});expect(h.input.sample().block).toBe(true);event(h.window,'pointerup',{pointerId:1});expect(h.input.sample().block).toBe(false);if(failure!=='missing')expect(h.canvas.requestPointerLock).toHaveBeenCalledTimes(1);h.input.dispose();
 });
 it('retries camera capture after closing a menu without attacking on the recapture click',()=>{const h=harness();h.canvas.requestPointerLock.mockImplementationOnce(()=>{throw Error('Transient denial');});event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});event(h.window,'pointerup',{pointerId:1});h.input.setActive(false);h.input.setActive(true);event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});expect(h.canvas.requestPointerLock).toHaveBeenCalledTimes(2);Object.assign(h.document,{pointerLockElement:h.canvas});event(h.document,'pointerlockchange');event(h.window,'pointerup',{pointerId:1});expect(h.action).not.toHaveBeenCalled();event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});expect(h.action).toHaveBeenCalledExactlyOnceWith('attack');h.input.dispose();});
 it('ignores an earlier capture rejection after reactivation',async()=>{const h=harness();let reject:(reason:Error)=>void=()=>{};h.canvas.requestPointerLock.mockImplementationOnce(()=>new Promise<void>((_resolve,fail)=>{reject=fail;}));event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});h.input.setActive(false);h.input.setActive(true);reject(Error('Old request'));await Promise.resolve();event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});expect(h.canvas.requestPointerLock).toHaveBeenCalledTimes(2);event(h.window,'pointerup',{pointerId:1});expect(h.action).not.toHaveBeenCalled();h.input.dispose();});
 it('does not turn a canceled fallback drag into an attack',()=>{const h=harness();h.canvas.requestPointerLock.mockImplementation(()=>{throw Error('Denied');});event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});event(h.window,'pointerup',{pointerId:1});event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});event(h.window,'pointercancel',{pointerId:1});event(h.window,'pointerup',{pointerId:1});expect(h.action).not.toHaveBeenCalled();h.input.dispose();});
 it('releases a canceled finger without dropping other movement, camera or guard fingers',()=>{const h=harness();event(h.movePad,'pointerdown',{pointerId:1,pointerType:'touch',clientX:50,clientY:8});event(h.lookPad,'pointerdown',{pointerId:2,pointerType:'touch',clientX:50,clientY:50});event(h.block,'pointerdown',{pointerId:3,pointerType:'touch'});event(h.attack,'pointerdown',{pointerId:4,pointerType:'touch'});event(h.window,'pointercancel',{pointerId:4});event(h.lookPad,'pointermove',{pointerId:2,clientX:75,clientY:50});expect(h.input.sample()).toMatchObject({z:1,block:true,yaw:-.1});event(h.window,'pointercancel',{pointerId:2});event(h.lookPad,'pointermove',{pointerId:2,clientX:100,clientY:50});expect(h.input.sample().yaw).toBeCloseTo(-.1);event(h.window,'pointercancel',{pointerId:1});expect(h.input.sample()).toMatchObject({z:0,block:true});event(h.window,'pointercancel',{pointerId:3});expect(h.input.sample().block).toBe(false);h.input.dispose();});
 it('releases controls on a window pointerup even when capture is unavailable',()=>{const h=harness();h.movePad.setPointerCapture.mockImplementation(()=>{throw Error('No capture');});event(h.movePad,'pointerdown',{pointerId:1,pointerType:'touch',clientX:50,clientY:8});event(h.block,'pointerdown',{pointerId:2,pointerType:'touch'});event(h.window,'pointerup',{pointerId:1});expect(h.input.sample()).toMatchObject({z:0,block:true});event(h.window,'pointerup',{pointerId:2});expect(h.input.sample().block).toBe(false);h.input.dispose();});
 it('keeps guarding until the last finger on the same guard button releases',()=>{const h=harness();event(h.block,'pointerdown',{pointerId:3,pointerType:'touch'});event(h.block,'pointerdown',{pointerId:4,pointerType:'touch'});h.block.classList.remove.mockClear();event(h.block,'pointerup',{pointerId:3});expect(h.input.sample().block).toBe(true);expect(h.block.classList.remove).not.toHaveBeenCalled();event(h.block,'pointerup',{pointerId:4});expect(h.input.sample().block).toBe(false);expect(h.block.classList.remove).toHaveBeenCalledWith('pressed');h.input.dispose();});
 it('toggles inventory while inactive without key repeat, typing or leaked movement',()=>{const h=harness();event(h.window,'keydown',{code:'KeyW'});h.input.setActive(false);event(h.window,'keydown',{code:'KeyI',repeat:false});event(h.window,'keydown',{code:'KeyI',repeat:true});expect(h.action).toHaveBeenCalledExactlyOnceWith('inventory');expect(h.input.sample().z).toBe(0);const field=new Element();field.tagName='INPUT';event(h.window,'keydown',{code:'KeyI',repeat:false,target:field});expect(h.action).toHaveBeenCalledTimes(1);h.input.setActive(true);expect(h.input.sample().z).toBe(0);h.input.dispose();});
 it('immediately releases a pointer lock that resolves after inventory opens',()=>{const h=harness();event(h.canvas,'pointerdown',{pointerId:1,pointerType:'mouse',button:0});h.input.setActive(false);Object.assign(h.document,{pointerLockElement:h.canvas});event(h.document,'pointerlockchange');expect(h.document.exitPointerLock).toHaveBeenCalledTimes(1);expect(h.input.sample()).toMatchObject({x:0,z:0,block:false});h.input.dispose();});
});
