import {describe,it,expect,vi,afterEach} from 'vitest';
import {boundedName,DungeonClient,inviteURL,randomToken,roomFromText,roomIdentity,socketURL,type DungeonSocket,type RandomSource} from '../../src/dungeon/client';
import {DungeonSimulation} from '../../src/dungeon/simulation';
import type {Input,Snapshot} from '../../src/dungeon/types';
const room='a'.repeat(64),key='b'.repeat(64);
const random:RandomSource={getRandomValues<T extends ArrayBufferView>(array:T):T{if(array instanceof Uint8Array)array.fill(7);return array;}};
function snapshot():Snapshot{const sim=new DungeonSimulation();const p=sim.join(key,'Player')!;p.actor.seq=28;p.lastAction=12;return sim.snapshot(p.actor.id);}
class MockSocket implements DungeonSocket {
 readyState=0;onopen:((event:Event)=>void)|null=null;onmessage:((event:MessageEvent)=>void)|null=null;onclose:((event:CloseEvent)=>void)|null=null;onerror:((event:Event)=>void)|null=null;
 sent:string[]=[];closed=false;send(data:string){this.sent.push(data);}close(){this.closed=true;this.readyState=3;}
 open(){this.readyState=1;this.onopen?.(new Event('open'));}receive(value:unknown){this.onmessage?.({data:JSON.stringify(value)} as MessageEvent);}disconnect(code=1006,reason=''){this.readyState=3;this.onclose?.({code,reason} as CloseEvent);}
}
const neutral:Input={x:0,z:0,yaw:0,pitch:0,block:false,crouch:false};
function harness(){const sockets:MockSocket[]=[];const state=vi.fn(),notice=vi.fn(),receive=vi.fn();const client=new DungeonClient({base:'https://game.example/?mode=dungeon',room,identity:{key,name:'Player',persistent:true},socket:()=>{const socket=new MockSocket();sockets.push(socket);return socket;},callbacks:{state,notice,snapshot:receive}});return {client,sockets,state,notice,receive};}
afterEach(()=>vi.useRealTimers());
describe('private dungeon client sessions',()=>{
 it('uses 256-bit room IDs and never places the private key in an invite',()=>{expect(randomToken(random)).toBe('07'.repeat(32));const url=inviteURL('https://game.example/campaign?debug=1#old',room);expect(url).toBe(`https://game.example/campaign?mode=dungeon#dungeon=${room}`);expect(url).not.toContain(key);expect(socketURL(url,room)).toBe(`wss://game.example/dungeon-room/${room}`);expect(socketURL('http://localhost:5173/',room)).toBe(`ws://localhost:5173/dungeon-room/${room}`);});
 it('requires a valid 64-hex room even for parsed invitation URLs',()=>{expect(roomFromText(room)).toBe(room);expect(roomFromText(inviteURL('https://game.example/',room))).toBe(room);expect(roomFromText('https://game.example/#dungeon=<img>')).toBeNull();expect(()=>socketURL('file:///game.html',room)).toThrow();expect(()=>roomIdentity('../private','name',null,random)).toThrow();});
 it('keeps identity separate per room and reads no campaign save keys',()=>{const storage=new Map<string,string>();const read=vi.fn((name:string)=>storage.get(name)??null),write=vi.fn((name:string,value:string)=>storage.set(name,value));const first=roomIdentity(room,'  A\u0000lice  ',{getItem:read,setItem:write},random);expect(first.name).toBe('Alice');expect(first.persistent).toBe(true);expect(first.key).toHaveLength(64);expect(roomIdentity(room,'Alice',{getItem:read,setItem:write},random).key).toBe(first.key);expect(read.mock.calls.every(([name])=>name.startsWith('ashen-dungeon:v1:identity:'))).toBe(true);expect([...storage.keys()]).toEqual(['ashen-dungeon:v1:identity:'+room]);});
 it.each(['', 'broken-key', 'c'.repeat(63), '{\"key\":\"old\"}'])('preserves malformed existing identity without generating a replacement (%s)',saved=>{const read=vi.fn(()=>saved),write=vi.fn(),generate=vi.fn();expect(()=>roomIdentity(room,'Player',{getItem:read,setItem:write},{getRandomValues<T extends ArrayBufferView>(array:T):T{generate();return random.getRandomValues(array);}})).toThrow('保存済み参加情報が壊れています');expect(write).not.toHaveBeenCalled();expect(generate).not.toHaveBeenCalled();expect(read()).toBe(saved);});
 it('reports unavailable browser persistence without pretending it is saved',()=>{const storage={getItem(){throw Error('denied');},setItem(){throw Error('denied');}};expect(roomIdentity(room,'x',storage,random).persistent).toBe(false);expect(roomIdentity(room,'x',null,random).persistent).toBe(false);expect(boundedName('a'.repeat(100))).toHaveLength(20);expect(boundedName(' ')).toBe('探索者');expect(boundedName('<Alice>')).toBe('Alice');});
 it('waits for a server snapshot, resumes both sequences and sends only inputs/actions',()=>{const h=harness();h.client.connect();expect(h.client.action({kind:'ready'})).toBe(false);h.sockets[0].open();expect(JSON.parse(h.sockets[0].sent[0])).toEqual({type:'hello',protocol:1,key,name:'Player'});expect(h.client.input(neutral)).toBe(false);h.sockets[0].receive({type:'snapshot',snapshot:snapshot()});expect(h.client.connected).toBe(true);h.client.input(neutral);h.client.action({kind:'ready'});expect(JSON.parse(h.sockets[0].sent[1])).toEqual({type:'input',sequence:29,input:neutral});expect(JSON.parse(h.sockets[0].sent[2])).toEqual({type:'action',sequence:13,action:{kind:'ready'}});h.sockets[0].receive({type:'snapshot',snapshot:snapshot()});h.client.action({kind:'ready'});expect(JSON.parse(h.sockets[0].sent[3]).sequence).toBe(14);h.client.dispose();expect(h.sockets[0].closed).toBe(true);expect(h.client.action({kind:'ready'})).toBe(false);});
 it('does not replay gameplay actions across reconnect and cancels retry on disposal',()=>{vi.useFakeTimers();const h=harness();h.client.connect();const old=h.sockets[0];old.open();old.receive({type:'snapshot',snapshot:snapshot()});h.client.action({kind:'attack'});old.disconnect();expect(h.client.connected).toBe(false);expect(h.client.action({kind:'attack'})).toBe(false);vi.advanceTimersByTime(750);expect(h.sockets).toHaveLength(2);h.sockets[1].open();expect(h.sockets[1].sent).toHaveLength(1);expect(JSON.parse(h.sockets[1].sent[0]).type).toBe('hello');h.sockets[1].disconnect();h.client.dispose();vi.advanceTimersByTime(60000);expect(h.sockets).toHaveLength(2);});
 it('ignores stale sockets and invalid protocol, and stops retries after refusal',()=>{vi.useFakeTimers();const h=harness();h.client.connect();const old=h.sockets[0];old.open();h.client.reconnect();expect(old.onmessage).toBeNull();expect(old.closed).toBe(true);const current=h.sockets[1];current.open();current.receive({type:'snapshot',snapshot:{...snapshot(),protocol:99}});expect(h.client.connected).toBe(false);expect(h.receive).not.toHaveBeenCalled();expect(h.notice).toHaveBeenCalled();current.disconnect(1008);vi.advanceTimersByTime(60000);expect(h.sockets).toHaveLength(2);h.client.dispose();});
 it.each([1002,4001])('does not reconnect-loop on terminal close %s',code=>{vi.useFakeTimers();const h=harness();h.client.connect();h.sockets[0].open();h.sockets[0].disconnect(code);vi.advanceTimersByTime(60000);expect(h.sockets).toHaveLength(1);expect(h.notice).toHaveBeenCalled();h.client.dispose();});
});

it('shows allowlisted rate-limit diagnostics without echoing arbitrary close text',()=>{
 for(const [reason,expected] of [['送信が多すぎます','受信頻度'],['操作が多すぎます','短時間'],['不正な操作です','通信形式'],['参加確認が時間切れです','時間切れ'],['untrusted secret message','この部屋には入れません'],['__proto__','この部屋には入れません']]){
  const h=harness();h.client.connect();h.sockets[0].open();h.sockets[0].disconnect(1008,reason);expect(h.notice).toHaveBeenCalledWith(expect.stringContaining(expected));expect(h.notice).not.toHaveBeenCalledWith(expect.stringContaining('untrusted secret'));h.client.dispose();
 }
});
