import {describe,it,expect} from 'vitest';
import {DungeonSimulation} from '../../src/dungeon/simulation';
import {parsePacket,validRaidState} from '../../src/dungeon/protocol';
import {transfer,place,validInventory} from '../../src/dungeon/inventory';
import {wallRay,blocked,dungeonField} from '../../src/dungeon/world';
import type {Item} from '../../src/dungeon/types';
const key=(n:string)=>n.repeat(64);
function game(){const sim=new DungeonSimulation(),a=sim.join(key('a'),'一人目')!,b=sim.join(key('b'),'二人目')!;sim.command(a.actor.id,1,{kind:'ready'});sim.command(b.actor.id,1,{kind:'ready'});sim.command(a.actor.id,2,{kind:'start'});return {sim,a,b};}
function ticks(sim:DungeonSimulation,n:number){for(let i=0;i<n;i++)sim.step();}
const item=(id:string,kind:Item['kind']='relic'):Item=>({id,kind,quality:1,count:1,x:0,y:0,rotated:false,found:false});
describe('dungeon G1/G2 authority and conservation',()=>{
 it('begins only after all connected participants ready and separate free kits get unique IDs',()=>{const sim=new DungeonSimulation(),a=sim.join(key('a'),'A')!,b=sim.join(key('b'),'B')!;sim.command(a.actor.id,1,{kind:'ready'});expect(sim.command(a.actor.id,2,{kind:'start'})).toContain('全員');sim.command(b.actor.id,1,{kind:'ready'});sim.command(a.actor.id,3,{kind:'start'});expect(sim.state.phase).toBe('raid');expect(validRaidState(sim.state)).toBe(true);expect(new Set(sim.state.profiles.flatMap(p=>p.actor.bag.map(i=>i.id))).size).toBe(6);});
 it('cannot teleport, assign damage, spoof another actor, or inject unknown action fields',()=>{for(const action of [{kind:'hp',hp:1000},{kind:'attack',damage:1000},{kind:'loot',item:'x',target:'chest0',actor:'p2'}])expect(parsePacket(JSON.stringify({type:'action',sequence:1,action}))).toBeNull();expect(parsePacket(JSON.stringify({type:'input',sequence:1,input:{x:50,z:0,yaw:0,pitch:0,block:false,crouch:false}}))).toBeNull();});
 it('has bounded movement, stale input neutralization, solid walls and opaque line of sight',()=>{const {sim,a}=game(),actor=a.actor;actor.position={x:-14,y:0,z:10};sim.input(actor.id,1,{x:-1,z:0,yaw:0,pitch:0,block:false,crouch:false});ticks(sim,20);expect(actor.position.x).toBeGreaterThan(-15.3);const x=actor.position.x;ticks(sim,20);expect(actor.position.x).toBe(x);expect(blocked({x:-16,y:0,z:0},1,[])).toBe(true);expect(wallRay({x:-10,y:1,z:-6},{x:-10,y:1,z:0},1,[])).not.toBeNull();});
 it('runs server enemies and gives a visible windup before damage',()=>{const {sim,a}=game();a.actor.position={x:-2,y:0,z:1.3};const hp=a.actor.hp;ticks(sim,3);expect(sim.state.enemies[0].phase).toBe('windup');expect(a.actor.hp).toBe(hp);ticks(sim,35);expect(a.actor.hp).toBeLessThan(hp);});
 it('uses the actual authored melee blade against another player',()=>{const {sim,a,b}=game();sim.state.enemies=[];a.actor.position={x:0,y:0,z:2};a.actor.yaw=0;b.actor.position={x:0,y:0,z:.6};const hp=b.actor.hp;sim.command(a.actor.id,3,{kind:'attack'});ticks(sim,24);expect(b.actor.hp).toBeLessThan(hp);const after=b.actor.hp;ticks(sim,20);expect(b.actor.hp).toBe(after);});
 it('prevents attacks across the shared closed dungeon door',()=>{const {sim,a,b}=game();sim.state.enemies=[];a.actor.position={x:0,y:0,z:-3.8};a.actor.yaw=0;b.actor.position={x:0,y:0,z:-5.4};sim.command(a.actor.id,3,{kind:'attack'});ticks(sim,30);expect(b.actor.hp).toBe(b.actor.maxHp);});
 it('permits only one winner of competing loot intents and rejects 100 replays',()=>{const {sim,a,b}=game();sim.state.enemies=[];const chest=sim.state.containers[0];chest.opened=true;a.actor.position={...chest.position};b.actor.position={...chest.position};const id=chest.items[0].id;expect(sim.command(a.actor.id,3,{kind:'loot',target:chest.id,item:id})).toContain('拾い');for(let i=0;i<100;i++)sim.command(a.actor.id,3,{kind:'loot',target:chest.id,item:id});sim.command(b.actor.id,2,{kind:'loot',target:chest.id,item:id});expect(a.actor.bag.filter(i=>i.id===id)).toHaveLength(1);expect(b.actor.bag.some(i=>i.id===id)).toBe(false);expect(chest.items.some(i=>i.id===id)).toBe(false);expect(validRaidState(sim.state)).toBe(true);});
 it('requires uninterrupted extraction, moves loot exactly once, and restores a separate personal stash',()=>{const {sim,a}=game();sim.state.enemies=[];const exit=sim.state.exits[0];sim.state.elapsed=46;a.actor.position={...exit.position};const carried=a.actor.bag.map(i=>i.id);sim.command(a.actor.id,3,{kind:'interact',target:exit.id});ticks(sim,81);expect(a.actor.status).toBe('extracted');expect(a.actor.bag).toHaveLength(0);expect(a.stash.map(i=>i.id)).toEqual(carried);expect(exit.remaining).toBe(1);const restored=new DungeonSimulation(structuredClone(sim.state));const p=restored.join(key('a'),'同じ人')!;expect(p.stash.map(i=>i.id)).toEqual(carried);restored.command(p.actor.id,3,{kind:'interact',target:exit.id});expect(p.stash).toHaveLength(carried.length);expect(validRaidState(restored.state)).toBe(true);});
 it('keeps disconnected bodies vulnerable, loss on timeout and corpse ownership exclusive',()=>{const {sim,a}=game();const carried=a.actor.bag.map(i=>i.id);sim.disconnect(a.actor.id);sim.state.elapsed=479.98;sim.step();expect(a.actor.status).toBe('dead');expect(a.stash).toHaveLength(0);expect(a.actor.bag).toHaveLength(0);expect(sim.state.containers.find(c=>c.id.includes(a.actor.id))?.items.map(i=>i.id)).toEqual(carried);expect(validRaidState(sim.state)).toBe(true);});
 it('never reveals reconnect secrets, other backpacks or unopened chest contents in snapshots',()=>{const {sim,a,b}=game();const snapshot=sim.snapshot(a.actor.id);expect(JSON.stringify(snapshot)).not.toContain(key('a'));expect(snapshot.actors.find(p=>p.id===b.actor.id)?.bag).toHaveLength(0);expect(snapshot.containers.every(c=>!c.items.length)).toBe(true);expect(snapshot.lastInput).toBe(0);});
 it('rejects corrupted state and duplicate item ownership instead of resetting',()=>{const {sim,a}=game();a.stash.push({...a.actor.bag[0]});expect(validRaidState(sim.state)).toBe(false);a.stash=[];a.actor.position.x=NaN;expect(validRaidState(sim.state)).toBe(false);});
});
describe('dungeon inventory and geometry',()=>{
 it('honors grid occupancy and atomic full destination rejection',()=>{const from=[item('source')],to:Item[]=[];for(let i=0;i<10;i++)expect(place(to,item(String(i)))).toBe(true);expect(transfer(from,to,'source')).toBe(false);expect(from).toHaveLength(1);expect(validInventory(to)).toBe(true);});
 it('rejects invalid quantities and overlaps',()=>{const a=item('a'),b=item('b');expect(validInventory([a,b])).toBe(false);a.count=999;expect(validInventory([a])).toBe(false);});
 it('generates actual signed-distance voxel geometry for the same authored walls',()=>{const field=dungeonField(1,[]);expect(field.distance({x:-15.8,y:1,z:0})).toBeLessThan(0);expect(field.distance({x:0,y:1,z:0})).toBeGreaterThan(0);});
});

 it('connects every original spawn to every extraction area in both seed variants',()=>{for(const seed of [1,2]){const visited=new Set<string>(['-11,11']),queue:[number,number][]=[[-11,11]];for(let at=0;at<queue.length;at++){const [x,z]=queue[at];for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const px=x+dx,pz=z+dz,key=`${px},${pz}`;if(Math.abs(px)>15||Math.abs(pz)>15||visited.has(key)||blocked({x:px,y:0,z:pz},seed,[]))continue;visited.add(key);queue.push([px,pz]);}}for(const [x,z]of [[-11,11],[11,-11],[-11,-11],[11,11],[-12,0],[12,0],[-12,12],[12,-12],[0,-13]])expect(visited.has(`${x},${z}`),`seed${seed} disconnected ${x},${z}`).toBe(true);}});

 it('keeps all enemy and player spawn bodies outside geometry in both seed variants',()=>{for(const raid of [0,1]){const sim=new DungeonSimulation();sim.state.raid=raid;for(const char of ['a','b','c','d','e','f']){const p=sim.join(char.repeat(64),char)!;sim.command(p.actor.id,1,{kind:'ready'});}sim.command('p1',2,{kind:'start'});for(const a of [...sim.state.profiles.map(p=>p.actor),...sim.state.enemies])expect(blocked(a.position,sim.state.seed,sim.state.doors),a.id).toBe(false);for(const p of sim.state.profiles)for(const e of sim.state.enemies)expect(Math.hypot(p.actor.position.x-e.position.x,p.actor.position.z-e.position.z)).toBeGreaterThan(8);}});

 it('does not let a player walk through another living body',()=>{const {sim,a,b}=game();sim.state.enemies=[];a.actor.position={x:0,y:0,z:2};b.actor.position={x:0,y:0,z:1};for(let i=1;i<30;i++){sim.input(a.actor.id,i,{x:0,z:1,yaw:0,pitch:0,block:false,crouch:false});sim.step();}expect(a.actor.position.z-b.actor.position.z).toBeGreaterThanOrEqual(.62);});

 it('lowers the shield during attack and spell/recovery actions instead of allowing permanent guarded offense',()=>{const {sim,a}=game();sim.state.enemies=[];for(let i=1;i<=8;i++){sim.input(a.actor.id,i,{x:0,z:0,yaw:0,pitch:0,block:true,crouch:false});sim.step();}expect(a.actor.guard).toBe(1);sim.command(a.actor.id,3,{kind:'attack'});ticks(sim,5);expect(a.actor.guard).toBe(0);expect(a.actor.phase).toBe('windup');});
