import {describe,it,expect,vi} from 'vitest';
import preview from '../../apps/campaign-room/src/preview-worker';
const origin='https://pr-4-threejs-game.example.workers.dev',room='b'.repeat(64);
const environment=(enabled='true')=>({CAMPAIGN_RELAY_ENABLED:enabled,ASSETS:{fetch:vi.fn(async()=>new Response('asset'))},CAMPAIGN_ROOMS:{idFromName:vi.fn((name:string)=>name),get:vi.fn(()=>({fetch:vi.fn(async()=>new Response('dungeon accepted'))}))}});
describe('dungeon HTTP isolation boundary',()=>{
 it('allocates a separate namespace name within the existing binding only for same-origin WebSocket requests',async()=>{const env=environment();const response=await preview.fetch(new Request(origin+'/dungeon-room/'+room,{headers:{Upgrade:'websocket',Origin:origin}}),env);expect(response.status).toBe(200);expect(env.CAMPAIGN_ROOMS.idFromName).toHaveBeenCalledWith('dungeon-v1:'+room);});
 it('denies disabled routes, hostile origins, missing origins, malformed rooms and HTTP requests before allocation',async()=>{const env=environment();for(const bad of ['https://evil.test','null',''])expect((await preview.fetch(new Request(origin+'/dungeon-room/'+room,{headers:{Upgrade:'websocket',Origin:bad}}),env)).status).toBe(403);expect((await preview.fetch(new Request(origin+'/dungeon-room/'+room),env)).status).toBe(426);expect((await preview.fetch(new Request(origin+'/dungeon-room/../x'),env)).status).toBe(200);expect((await preview.fetch(new Request(origin+'/dungeon-room/bad'),env)).status).toBe(404);expect((await preview.fetch(new Request(origin+'/dungeon-room/'+room),environment('false'))).status).toBe(503);expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();});
 it('reports server authority honestly while old campaign remains browser-host and health allocates no room',async()=>{const env=environment();const health=await (await preview.fetch(new Request(origin+'/dungeon-room/health'),env)).json();expect(health).toMatchObject({authority:'server',maxPlayers:6,stashScope:'room-player'});const old=await (await preview.fetch(new Request(origin+'/campaign-room/health'),env)).json();expect(old.authority).toBe('browser-host');expect(env.CAMPAIGN_ROOMS.get).not.toHaveBeenCalled();});
});
