import {describe,it,expect} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {captureCampaign,restoreCampaignInto,hydrateCampaign,defaultSettings,type CampaignSave} from '../../src/prototype/campaign-session';
import {captureSharedCampaign,applySharedCampaign} from '../../src/prototype/campaign-network-state';
import {prepareLegacyCampaignMigration} from '../../src/save/campaign-migration';
import {createCampaignSamplePrototype} from '../../src/prototype/core/campaign-sample-provider';
import {prepareWesternMigrationPlan} from '../../src/save/western-campaign-migration';
import {VAULT_KEY,VAULT_REWARD} from '../../src/prototype/core/echo-vault';
import {createEchoVaultView} from '../../src/prototype/rendering/echo-vault-view';
import * as THREE from 'three';
const neutral:Controls={x:0,z:0,sprint:false,water:false,block:false};
const copy=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
function legacySave(sim:CoreSimulation){const saved=copy(captureCampaign(sim,defaultSettings()));delete saved.dungeon;saved.objects=saved.objects.filter(o=>!o.id.startsWith('vault-'));saved.field.order=saved.field.order.filter(id=>!id.startsWith('vault-'));saved.field.layers=saved.field.layers.filter(l=>!l.id.startsWith('vault-'));return saved;}
function aim(s:CoreSimulation,id:string,position:{x:number;z:number},target:{x:number;y:number;z:number}){s.player.position={...position,y:.3};s.player.phase='idle';s.player.yaw=Math.atan2(-(target.x-position.x),-(target.z-position.z));s.player.pitch=Math.atan2(target.y-s.player.position.y-1.52,Math.hypot(target.x-position.x,target.z-position.z));expect(s.target()?.hit.cell.object).toBe(id);s.action('interact',neutral);}
function finish(s:CoreSimulation){aim(s,'vault-note',{x:8.5,z:9},{x:6.5,y:1,z:9});s.arena.field.removeObject('vault-crust');aim(s,'vault-key',{x:7.5,z:11.35},{x:6.5,y:1,z:11.95});aim(s,'vault-switch',{x:10,z:13.6},{x:10.6,y:1,z:14.4});aim(s,'vault-cache',{x:8.5,z:16.2},{x:8.5,y:.7,z:17.8});expect(s.campaign.state.items[VAULT_REWARD]).toBe(1);}
describe('runtime overlay checkpoint and authority boundary',()=>{
 it.each([false,true])('accepts old campaign saves, installing safely without changing the frozen baseline (streamed %s)',streamed=>{const sim=new CoreSimulation(true,false,streamed),old=legacySave(sim),baseline=old.field.baseline;expect(restoreCampaignInto(sim,old)).not.toBeNull();expect(sim.dungeon.enabled).toBe(true);expect(sim.arena.field.exportState().baseline).toBe(baseline);expect(sim.campaign.state.items[VAULT_REWARD]).toBeUndefined();});
 it('mirrors an older host snapshot without inventing client-only room geometry or claims',()=>{const host=new CoreSimulation(true,false,true),remote=new CoreSimulation(true,false,true),old=legacySave(host);expect(applySharedCampaign(remote,old).ok).toBe(true);expect(remote.dungeon.enabled).toBe(false);expect([...remote.arena.objects.keys()].some(id=>id.startsWith('vault-'))).toBe(false);expect(remote.arena.field.exportState().layers.some(l=>l.id.startsWith('vault-'))).toBe(false);expect(remote.campaign.state.items[VAULT_REWARD]).toBeUndefined();});
 it('retains legacy construction conflicts byte-for-byte and never silently buries a build',()=>{const sim=new CoreSimulation(true,false,true),old=legacySave(sim);old.field.order.push('build:old');old.field.layers.push({id:'build:old',cells:[[30,3,50,-.25,4]],removed:[]});expect(restoreCampaignInto(sim,old)).not.toBeNull();expect(sim.dungeon.enabled).toBe(false);expect(sim.arena.field.get(30,3,50)?.object).toBe('build:old');expect(captureCampaign(sim,defaultSettings()).field.layers.find(l=>l.id==='build:old')).toEqual(old.field.layers.at(-1));expect(captureCampaign(sim,defaultSettings()).dungeon).toBeUndefined();expect(hydrateCampaign(captureCampaign(sim,defaultSettings()))?.sim.dungeon.enabled).toBe(false);});
 it('does not place a new legacy wall through a saved actor',()=>{const sim=new CoreSimulation(true,false,true),old=legacySave(sim);old.player.position={x:5.65,y:.3,z:10.75};expect(restoreCampaignInto(sim,old)).not.toBeNull();expect(sim.dungeon.enabled).toBe(false);expect(sim.player.position).toEqual(old.player.position);});
 it('rejects an out-of-yard legacy animal before any overlay installation or live mutation',()=>{const sim=new CoreSimulation(true,false,true),old=legacySave(sim),before=JSON.stringify(captureCampaign(sim,defaultSettings()));old.home.animal.physical!.position={x:5.65,y:.3,z:10.75};expect(restoreCampaignInto(sim,old)).toBeNull();expect(JSON.stringify(captureCampaign(sim,defaultSettings()))).toBe(before);});
 it('bounds the additive snapshot footprint without a roster or provider change',()=>{const sim=new CoreSimulation(true,false,true),saved=captureCampaign(sim,defaultSettings()),layers=saved.field.layers.filter(l=>l.id.startsWith('vault-'));expect(layers).toHaveLength(9);expect(layers.reduce((n,l)=>n+l.cells.length,0)).toBeLessThan(25000);expect(JSON.stringify(layers).length).toBeLessThan(1000000);expect(sim.enemies).toHaveLength(18);expect(saved.field.baseline).toBe('campaign-samples-v1/c1602605');});
 it('rolls back every ledger, object, unique-item or owned-geometry corruption including cached snapshots',()=>{const sim=new CoreSimulation(true,false,true);finish(sim);const saved=captureSharedCampaign(sim,defaultSettings());expect(applySharedCampaign(sim,saved).ok).toBe(true);const before=JSON.stringify(captureCampaign(sim,defaultSettings())),revision=sim.arena.field.revision;
  const corruptions:((d:CampaignSave)=>void)[]=[d=>{delete d.dungeon;},d=>{d.dungeon!.keyTaken=false;},d=>{d.dungeon!.rewardTaken=false;},d=>{d.home.storage.items[VAULT_REWARD]=1;},d=>{d.campaign.items[VAULT_KEY]=1;},d=>{d.objects.find(o=>o.id==='vault-gate')!.open=false;},d=>{d.field.layers.find(l=>l.id==='vault-gate')!.cells[3][3]=.4;},d=>{d.field.layers.find(l=>l.id==='vault-shell')!.cells.push([100,4,50,-.25,3]);},d=>{d.objects.pop();},d=>{d.entities.at(-1)!.reward=999;}];
  for(const corrupt of corruptions){const data=copy(saved);data.survival.inventory[4]=999;corrupt(data);expect(applySharedCampaign(sim,data).ok).toBe(false);expect(JSON.stringify(captureCampaign(sim,defaultSettings()))).toBe(before);expect(sim.arena.field.revision).toBe(revision);}
 });
 it('retains claims across death/reload, blocks default guests, and deduplicates authorized reconnect interactions',()=>{const host=new CoreSimulation(true,false,true);finish(host);const reward=host.campaign.state.xp;host.player.hp=0;host.respawn();expect(host.campaign.state.items[VAULT_REWARD]).toBe(1);const loaded=hydrateCampaign(captureCampaign(host,defaultSettings()))!.sim;expect(loaded.dungeon.snapshot().rewardTaken).toBe(true);const guest=loaded.enableCompanion();guest.position={x:8.5,y:.3,z:16.2};guest.yaw=Math.PI;guest.pitch=-.68;loaded.withCompanion(()=>aim(loaded,'vault-cache',{x:8.5,z:16.2},{x:8.5,y:.7,z:17.8}));expect(loaded.events.at(-1)?.text).toContain('編集許可');loaded.companionCanEdit=true;loaded.withCompanion(()=>aim(loaded,'vault-cache',{x:8.5,z:16.2},{x:8.5,y:.7,z:17.8}));expect(loaded.events.at(-1)?.text).toContain('回収済み');expect(loaded.campaign.state.items[VAULT_REWARD]).toBe(1);expect(loaded.campaign.state.xp).toBe(reward);
  const remote=new CoreSimulation(true,false,true);for(let i=0;i<3;i++){expect(applySharedCampaign(remote,captureSharedCampaign(loaded,defaultSettings())).ok).toBe(true);expect(remote.campaign.state.items[VAULT_REWARD]).toBe(1);expect(remote.campaign.state.xp).toBe(reward);}expect(remote.dungeon.snapshot()).toEqual(loaded.dungeon.snapshot());
 });
 it('physically damages host and permitted companion once per warned pulse and preserves cooldown across reload',()=>{const s=new CoreSimulation(true,false,true);s.player.position={x:8,y:.35,z:13};const guest=s.enableCompanion();guest.position={x:9,y:.35,z:13};s.seconds=4.17;const hp=s.player.hp,ghp=guest.hp;s.tick(.05,neutral);expect(s.player.hp).toBe(hp-22);expect(guest.hp).toBe(ghp-22);const restored=hydrateCampaign(captureCampaign(s,defaultSettings()))!.sim;const loadedHp=restored.player.hp;restored.tick(.05,neutral);expect(restored.player.hp).toBe(loadedHp);s.player.position={x:10,y:.3,z:13};s.seconds=10.17;s.tick(.05,neutral);expect(s.player.hp).toBe(hp-22);expect(s.deathCause).toBe('鳴動床');});
 it('migrates the same runtime overlay through certified v2→v3→v4 without rebasing its samples',()=>{const sim=new CoreSimulation(true);finish(sim);const old=captureCampaign(sim,defaultSettings()),v3=prepareLegacyCampaignMigration(old,createCampaignSamplePrototype());expect(v3).not.toBeNull();expect(v3!.dungeon).toEqual(old.dungeon);expect(v3!.field.layers.filter(l=>l.id.startsWith('vault-'))).toEqual(old.field.layers.filter(l=>l.id.startsWith('vault-')));const west=prepareWesternMigrationPlan(v3);expect(west.ok).toBe(true);if(!west.ok)return;const restored=hydrateCampaign(west.candidate);expect(restored).not.toBeNull();expect(restored!.sim.dungeon.snapshot()).toEqual(sim.dungeon.snapshot());expect(restored!.sim.campaign.state.items[VAULT_REWARD]).toBe(1);},30000);
 it('keeps non-color-only trap cues aligned and disposes all owned view resources',()=>{const sim=new CoreSimulation(true,false,true),scene=new THREE.Scene(),view=createEchoVaultView(scene,sim);sim.seconds=3.6;view.update();const root=scene.getObjectByName('echo-vault-cues')!,teeth=root.getObjectByName('vault-warning-teeth') as THREE.InstancedMesh,m=new THREE.Matrix4(),pos=new THREE.Vector3(),scale=new THREE.Vector3(),q=new THREE.Quaternion();teeth.getMatrixAt(0,m);m.decompose(pos,q,scale);expect(pos.x).toBe(7.5);expect(pos.z).toBeCloseTo(12.45);expect(scale.y).toBeGreaterThan(.4);expect(root.getObjectByName('vault-safe-side-lane')).toBeDefined();view.dispose();view.dispose();expect(scene.getObjectByName('echo-vault-cues')).toBeUndefined();});
});
