import {describe,it,expect} from 'vitest';
import {VoxelField} from '../../src/prototype/core/voxel';
import {CampaignSystem} from '../../src/prototype/core/campaign';
import {EchoVaultSystem,VAULT_POINTS,VAULT_KEY,VAULT_REWARD,VAULT_OBJECT_IDS,canInstallEchoVault,freshEchoVaultState,validEchoVaultState,validEchoVaultGeometry,validEchoVaultSave} from '../../src/prototype/core/echo-vault';
import type {ObjectState} from '../../src/prototype/core/world';
const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
function setup(){const field=new VoxelField(),arena={field,objects:new Map<string,ObjectState>()},campaign=new CampaignSystem({2:0,3:0,4:0,6:0,7:0,10:0}),vault=new EchoVaultSystem(campaign,arena);expect(vault.install()).toBe(true);return {field,arena,campaign,vault};}
const actor=(x:number,z:number,extra={})=>({position:{x,y:.25,z},alive:true,mayEdit:true,...extra});
function claimKey(v:ReturnType<typeof setup>){expect(v.vault.interact('vault-note',actor(8.5,9)).ok).toBe(true);v.field.removeObject('vault-crust');expect(v.vault.interact('vault-key',actor(7.5,11.35)).ok).toBe(true);}
function open(v:ReturnType<typeof setup>){claimKey(v);expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(true);}
describe('one bounded original seal-vault',()=>{
 it('has a roof, walkable entrance and return, safe lane, physical closed/open barrier',()=>{const {field,vault}=setup();expect(field.overlaps({x:8.5,y:.3,z:10.5})).toBe(false);expect(field.ray({x:8.5,y:1.8,z:12},{x:0,y:1,z:0},2)).not.toBeNull();expect(field.overlaps({x:10,y:.3,z:13})).toBe(false);expect(field.overlaps({x:8.5,y:.3,z:15.25})).toBe(true);expect(validEchoVaultGeometry(field.exportState(),vault.snapshot())).toBe(true);});
 it('requires clue and real mining before a key, then consumes that key exactly once',()=>{const v=setup();expect(v.vault.interact('vault-key',actor(7.5,11.35)).ok).toBe(false);expect(v.vault.interact('vault-note',actor(8.5,9)).ok).toBe(true);expect(v.vault.interact('vault-key',actor(7.5,11.35)).ok).toBe(false);expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(false);v.field.removeObject('vault-crust');expect(v.vault.interact('vault-key',actor(7.5,11.35)).ok).toBe(true);expect(v.campaign.state.items[VAULT_KEY]).toBe(1);expect(v.vault.interact('vault-key',actor(7.5,11.35)).ok).toBe(false);expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(true);expect(v.campaign.state.items[VAULT_KEY]).toBe(0);expect(v.field.overlaps({x:8.5,y:.3,z:15.25})).toBe(false);expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(false);expect(validEchoVaultGeometry(v.field.exportState(),v.vault.snapshot())).toBe(true);});
 it('permits avoiding rather than disarming the trap, with one unique reward and fixed XP',()=>{const v=setup();open(v);expect(v.vault.snapshot().disarmed).toBe(false);const xp=v.campaign.state.xp;expect(v.vault.interact('vault-cache',actor(8.5,16.2)).ok).toBe(true);expect(v.campaign.state.items[VAULT_REWARD]).toBe(1);expect(v.campaign.state.xp).toBe(xp+40);for(let i=0;i<4;i++)expect(v.vault.interact('vault-cache',actor(8.5,16.2)).ok).toBe(false);expect(v.campaign.state.xp).toBe(xp+40);});
 it('keeps claims and inventory unchanged for dead, denied, non-finite, remote or occluded actors',()=>{const v=setup(),before=v.vault.snapshot(),held=v.campaign.snapshot();for(const a of [actor(8.5,9,{alive:false}),actor(8.5,9,{mayEdit:false}),actor(NaN,9),actor(8.5,18)])expect(v.vault.interact('vault-note',a).ok).toBe(false);v.field.box({x:7.3,y:.3,z:8.5},{x:7.6,y:2.5,z:9.5},3,'build:wall');expect(v.vault.interact('vault-note',actor(8.5,9)).ok).toBe(false);expect(v.vault.snapshot()).toEqual(before);expect(v.campaign.snapshot()).toEqual(held);});
 it('does not consume a stored key or create a duplicate when held items are full',()=>{const v=setup();claimKey(v);v.campaign.state.items[VAULT_KEY]=0;expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(false);expect(v.vault.snapshot().gateOpen).toBe(false);v.campaign.state.items[VAULT_KEY]=1;expect(v.vault.interact('vault-switch',actor(10,13.6)).ok).toBe(true);v.campaign.state.items[VAULT_REWARD]=1;const before=v.vault.snapshot();expect(v.vault.interact('vault-cache',actor(8.5,16.2)).ok).toBe(false);expect(v.vault.snapshot()).toEqual(before);});
 it('telegraphs for 1.2s, hits only at pulse edges, and is invariant at 30/120Hz',()=>{const {vault}=setup();expect(vault.trapPhase(2.99)).toBe('quiet');expect(vault.trapPhase(3)).toBe('warning');expect(vault.trapPhase(4.19)).toBe('warning');expect(vault.trapPhase(4.2)).toBe('strike');expect(vault.trapPhase(4.7)).toBe('quiet');const at={x:8.25,y:.35,z:13},damage=(hz:number)=>{let n=0;for(let i=1;i<=12*hz;i++)n+=vault.trapDamage(at,(i-1)/hz,i/hz);return n;};expect(damage(30)).toBe(44);expect(damage(120)).toBe(44);expect(vault.trapDamage(at,4.2,4.25)).toBe(0);expect(vault.trapDamage(at,4.1,5)).toBe(0);for(const position of [{...at,x:10},{...at,z:11},{...at,y:2},{...at,x:NaN}])expect(vault.trapDamage(position,4.15,4.25)).toBe(0);expect(vault.interact('vault-brake',actor(10,11.35)).ok).toBe(true);expect(vault.trapPhase(4.2)).toBe('disarmed');expect(damage(30)).toBe(0);});
 it('does not send a floor pulse through solid cover or above the actual tooth height',()=>{const {field,vault}=setup();const at={x:8.25,y:.8,z:13};expect(vault.trapDamage(at,4.15,4.25)).toBe(22);field.box({x:7.8,y:.5,z:12.5},{x:8.7,y:.7,z:13.5},4,'build:cover');expect(vault.trapDamage(at,4.15,4.25)).toBe(0);expect(vault.trapDamage({...at,y:1.1},4.15,4.25)).toBe(0);});
 it('strictly validates dependencies, named objects, all gate samples and cross-inventory unique counts',()=>{const v=setup();open(v);expect(v.vault.interact('vault-cache',actor(8.5,16.2)).ok).toBe(true);const state=v.vault.snapshot(),field=v.field.exportState(),objects=[...v.arena.objects.values()],items={...v.campaign.state.items};expect(validEchoVaultSave(state,field,objects,items,{})).toBe(true);expect(validEchoVaultSave(state,field,objects,{...items,[VAULT_REWARD]:0},{[VAULT_REWARD]:1})).toBe(true);expect(validEchoVaultSave(state,field,objects,items,{[VAULT_REWARD]:1})).toBe(false);expect(validEchoVaultSave(undefined,field,objects,items,{})).toBe(false);for(const bad of [{...state,keyTaken:false},{...state,installed:false},{...state,version:2},{...state,extra:true}])expect(validEchoVaultState(bad)).toBe(false);const bad=clone(field);bad.layers.find(l=>l.id==='vault-gate')!.cells[5][3]=.49;expect(validEchoVaultGeometry(bad,state)).toBe(false);expect(validEchoVaultGeometry({...field,layers:field.layers.filter(l=>l.id!=='vault-shell')},state)).toBe(false);expect(validEchoVaultSave(state,field,objects.map(o=>({...o,open:o.id==='vault-cache'?false:o.open})),items,{})).toBe(false);});
 it('allows only depletion within the original rock-cover samples',()=>{const v=setup();let field=v.field.exportState();const crust=field.layers.find(l=>l.id==='vault-crust')!;crust.cells.find(c=>c[3]<0)![3]=.25;expect(validEchoVaultGeometry(field,v.vault.snapshot())).toBe(true);crust.cells[0][0]=200;expect(validEchoVaultGeometry(field,v.vault.snapshot())).toBe(false);field=v.field.exportState();field.layers.find(l=>l.id==='vault-crust')!.cells[0][3]=-.5;expect(validEchoVaultGeometry(field,v.vault.snapshot())).toBe(false);});
 it('does not overwrite old builds, tombstones, same-name objects or prior raw claims',()=>{const field=new VoxelField(),empty=field.exportState();expect(canInstallEchoVault(empty,[])).toBe(true);expect(canInstallEchoVault({...empty,removedBase:['30,2,50']},[])).toBe(false);field.box({x:7,y:.25,z:12},{x:8,y:2,z:13},4,'build:wall');expect(canInstallEchoVault(field.exportState(),[])).toBe(false);expect(canInstallEchoVault(empty,[{id:'vault-key'}])).toBe(false);expect(canInstallEchoVault({...empty,order:['vault-injected']},[])).toBe(false);expect(VAULT_OBJECT_IDS.length).toBe(VAULT_POINTS.length);expect(validEchoVaultState(freshEchoVaultState())).toBe(true);});
});
