import {describe,it,expect} from 'vitest';
import {EntityElements} from '../../src/prototype/core/entity-elements';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {VoxelField} from '../../src/prototype/core/voxel';
import {VoxelWater} from '../../src/prototype/core/water';
import {SurvivalSystem} from '../../src/prototype/core/survival';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false};
const hit=(b:EntityElements,material:number)=>{const cell=[...b.field.cells.values()].find(c=>c.distance<0&&c.material===material)!;return {cell,point:{x:(cell.x+.5)*b.field.size,y:(cell.y+.5)*b.field.size,z:(cell.z+.5)*b.field.size},normal:{x:0,y:0,z:1},distance:1};};
describe('material enemies and loose-body physics',()=>{
 it('owns separate voxel health, burns cloth, extinguishes and preserves a finite loot budget',()=>{const a=new EntityElements(),b=new EntityElements(),h=hit(a,10);a.cast('fire',h,{x:0,y:0,z:1});let damage=0;for(let i=0;i<20;i++)damage+=a.tick(.1);expect(damage).toBeGreaterThan(0);expect(a.field.revision).toBeGreaterThan(b.field.revision);expect(a.scars.length).toBe(0);const drops=a.drain({x:0,y:0,z:0},0);expect(a.scars.length).toBeGreaterThan(0);a.cast('water',hit(a,10),{x:0,y:0,z:1});expect(a.wet).toBe(5);expect(a.tick(.1)).toBe(0);expect(drops.reduce((n,d)=>n+d.count,0)+a.deathDrops({x:0,y:0,z:0}).reduce((n,d)=>n+d.count,0)).toBe(12);expect(a.deathDrops({x:0,y:0,z:0})).toEqual([]);});
 it('shock has cooldown and wet amplifies conductive response; impulses are clamped',()=>{const b=new EntityElements(),h=hit(b,6),d={x:100,y:0,z:0};expect(b.cast('lightning',h,d)).toBe(12);expect(b.cast('lightning',h,d)).toBe(0);for(let i=0;i<20;i++)b.tick(.1);expect(b.shock).toBe(0);b.cast('water',h,d);expect(b.cast('lightning',h,d)).toBe(24);for(let i=0;i<100;i++)b.impulse(d,100);expect(b.velocity.x).toBe(5);});
 it('real cast action reaches enemy material instead of rejecting it, and wind moves against wall collision',()=>{const s=new CoreSimulation(),e=s.enemies[0];s.enemies[1].hp=0;s.player.position={x:0,y:.25,z:-3};s.player.pitch=-.2;expect(s.target(7)?.enemy).toBe(e);s.selectedElement='water';s.action('cast',idle);expect(s.enemyElements[0].wet).toBe(0);for(let i=0;i<27;i++)s.tick(1/60,idle);expect(s.enemyElements[0].wet).toBeGreaterThan(4.9);for(let i=0;i<50;i++)s.tick(1/60,idle);s.selectedElement='wind';const before=e.position.z;s.action('cast',idle);for(let i=0;i<40;i++)s.tick(1/60,idle);expect(e.position.z).toBeLessThan(before);expect(s.arena.field.overlaps(e.position,.27,1.7)).toBe(false);});
 it('loose wood has momentum, does not tunnel walls, floats, and mass affects wind',()=>{const f=new VoxelField();f.box({x:1,y:-1,z:-1},{x:1.2,y:3,z:1},3);const w=new VoxelWater(f),s=new SurvivalSystem(f,w);s.addDrops([{material:4,count:1,position:{x:0,y:1,z:0}},{material:6,count:1,position:{x:0,y:1,z:.2}}]);s.pushDrops({x:0,y:1,z:0},{x:1,y:0,z:0});expect(s.drops[0].velocity!.x).toBeGreaterThan(s.drops[1].velocity!.x);for(let i=0;i<15;i++)s.tick(.05,{x:-10,y:0,z:0});expect(s.drops[0].position.x).toBeLessThan(1);s.addDrops([{material:4,count:1,position:{x:4.2,y:-.4,z:-4.5}}]);const d=s.drops.find(d=>d.position.x>4)!;s.tick(.05,{x:-10,y:0,z:0});expect(d.velocity!.y).toBeGreaterThan(0);expect(d.wet).toBeGreaterThan(0);});
});
