import {describe,it,expect} from 'vitest';
import {CampaignSystem,validCampaignState,CAMPAIGN_RECIPES} from '../../src/prototype/core/campaign';
import {EQUIPMENT_ITEMS,LEGACY_EQUIPMENT_SLOTS,toolPower} from '../../src/prototype/core/equipment';
import {attackPose,meleeDefinition} from '../../src/prototype/core/motion';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {createRig} from '../../src/prototype/rendering/rig';
import {VoxelField} from '../../src/prototype/core/voxel';
import {VoxelWater} from '../../src/prototype/core/water';
import {ElementSystem} from '../../src/prototype/core/elements';
import {createPlayerEnvironmentState,stepPlayerEnvironment} from '../../src/prototype/core/player-environment';
import {campaignSnapshot} from '../../src/prototype/campaign-presenter';
import {defaultSettings} from '../../src/prototype/campaign-session';
import type {Mesh,MeshStandardMaterial} from 'three';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false},home={x:-3,y:.25,z:4};
function prepared(){const c=new CampaignSystem({2:100,3:100,4:100,6:100,7:100,10:100});c.state.flameTier=1;c.state.artisanRescued=true;return c;}
const distance=(a:{x:number;y:number;z:number},b:typeof a)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
describe('crafted equipment transactions and backward-compatible slots',()=>{
 it('all added items have bounded recipes, costs and distinct slots; failed repeated crafts never spend materials',()=>{const c=prepared();for(const item of EQUIPMENT_ITEMS){const recipe=CAMPAIGN_RECIPES.find(r=>r.output===item.id)!;expect(recipe).toBeDefined();expect(Object.values(recipe.cost).every(v=>v>0&&Number.isSafeInteger(v))).toBe(true);expect(c.craft(item.id,home).ok).toBe(true);const before={...c.materials};expect(c.craft(item.id,home).ok).toBe(false);expect(c.materials).toEqual(before);expect(c.state.items[item.id]).toBe(1);}expect(validCampaignState(c.snapshot())).toBe(true);});
 it('enforces head/torso/legs, shield/two-hand and shared accessory slots without losing owned gear',()=>{const c=prepared();for(const id of ['cloth-hood','hide-coat','copper-greaves','copper-shield','greatsword','dagger','traveler-ring']){c.craft(id,home);expect(c.equip(id).ok).toBe(true);}expect(c.state.equipment).toMatchObject({head:'cloth-hood',armor:'hide-coat',legs:'copper-greaves',shield:null,weapon:'dagger',charm:'traveler-ring'});expect(c.maxStamina).toBe(115);expect(c.equip('copper-shield').ok).toBe(true);expect(c.guardCost).toBe(12);expect(c.equip('greatsword').ok).toBe(true);expect(c.canGuard).toBe(false);expect(c.state.equipment.shield).toBeNull();expect(c.has('copper-shield')).toBe(true);expect(c.equip('copper-shield').ok).toBe(false);expect(c.damageReduction).toBeCloseTo(.43);expect(c.moveMultiplier).toBe(.97);expect(c.armorMaterial).toBe(6);const valid=c.snapshot();for(const equipment of [{...valid.equipment,head:'hide-coat'},{...valid.equipment,shield:'copper-shield'},{...valid.equipment,accessory:'traveler-ring'}])expect(c.restore({...valid,equipment})).toBe(false);expect(c.snapshot()).toEqual(valid);});
 it('wears all armor pieces, repairs only missing finite durability, and never duplicates salvage',()=>{const c=prepared();for(const id of ['cloth-hood','hide-coat','cloth-leggings']){c.craft(id,home);c.equip(id);}expect(c.damageReduction).toBeCloseTo(.38);c.consumeArmorDurability(100);expect(c.damageReduction).toBeCloseTo(.19);for(const id of c.armorIds)expect(c.gearInfo(id).durability).toBe(0);c.craft('wood-axe',home);c.equip('wood-axe');c.consumeToolDurability(27);const stone=c.materials[3];expect(c.repairStatus('wood-axe',{x:30,y:0,z:30}).materials).toEqual({3:2});expect(c.repair('wood-axe',{x:30,y:0,z:30}).ok).toBe(true);expect(c.materials[3]).toBe(stone-2);expect(c.repair('wood-axe',home).ok).toBe(false);c.unequip('tool');expect(c.salvage('wood-axe',true).ok).toBe(true);const after={...c.materials};expect(c.salvage('wood-axe',true).ok).toBe(false);expect(c.materials).toEqual(after);});
 it('accepts the exact old five-slot save and hydrates new slots empty while rejecting partial and unknown slots',()=>{const c=prepared();c.craft('hide-coat',home);c.equip('hide-coat');const legacy=JSON.parse(JSON.stringify(c.snapshot()));legacy.equipment=Object.fromEntries(LEGACY_EQUIPMENT_SLOTS.map(slot=>[slot,legacy.equipment[slot]]));expect(validCampaignState(legacy)).toBe(true);const target=prepared(),ledger=target.state.items;expect(target.restore(legacy)).toBe(true);expect(target.state.items).toBe(ledger);expect(target.state.equipment).toMatchObject({armor:'hide-coat',tool:null,head:null,legs:null,shield:null});expect(target.damageReduction).toBe(.2);expect(validCampaignState({...legacy,equipment:{...legacy.equipment,head:null}})).toBe(false);});
});
describe('authored weapon archetypes share presentation and sweep timing',()=>{
 it('keeps every weapon length and first derivative continuous at all phase joins',()=>{for(const archetype of ['sword','greatsword','dagger'] as const)for(const kind of ['slash','return','overhead'] as const){const def=meleeDefinition(kind,archetype);for(const [left,time,right] of [['windup',def.windup,'strike'],['strike',def.strike,'recover']] as const){const a=attackPose(kind,left,time-1e-6,1,archetype),b=attackPose(kind,right,0,1,archetype),c=attackPose(kind,right,1e-6,1,archetype);expect(distance(a.tip,b.tip)).toBeLessThan(.001);expect(distance(b.tip,c.tip)).toBeLessThan(.001);for(const axis of ['x','y','z'] as const)expect(Math.abs((b.tip[axis]-a.tip[axis])/1e-6-(c.tip[axis]-b.tip[axis])/1e-6)).toBeLessThan(.02);}for(let t=0;t<def.strike;t+=.01){const pose=attackPose(kind,'strike',t,1,archetype);expect(distance(pose.grip,pose.tip)).toBeCloseTo(def.reach,7);}}});
 it('uses different trajectories, reach, speed, stamina, damage and stagger',()=>{const sword=meleeDefinition('slash'),great=meleeDefinition('slash','greatsword'),dagger=meleeDefinition('slash','dagger');expect(great.reach).toBeGreaterThan(sword.reach);expect(dagger.reach).toBeLessThan(sword.reach);expect(great.windup+great.recover).toBeGreaterThan(sword.windup+sword.recover);expect(dagger.windup+dagger.recover).toBeLessThan(sword.windup+sword.recover);expect(great.cost).toBeGreaterThan(sword.cost);expect(dagger.cost).toBeLessThan(sword.cost);expect(great.stagger).toBeGreaterThan(0);expect(dagger.stagger).toBe(0);expect(meleeDefinition('overhead','dagger').stagger).toBeGreaterThan(0);const a=attackPose('slash','strike',great.strike*.5,1,'greatsword'),b=attackPose('slash','strike',dagger.strike*.5,1,'dagger');expect(distance(a.grip,b.grip)).toBeGreaterThan(.25);});
 it.each(['greatsword','dagger'] as const)('%s spends its actual stamina and blocks mid-swing gear changes',id=>{const s=new CoreSimulation(true,false,true);Object.assign(s.survival.inventory,{3:50,4:50,6:50});s.campaign.state.flameTier=1;s.campaign.state.artisanRescued=true;s.campaign.craft(id,home);expect(executeGameCommand(s,{type:'equip',id}).ok).toBe(true);s.action('attack',idle);expect(s.player.stamina).toBe(100-meleeDefinition('slash',id).cost);expect(s.player.phase).toBe('windup');expect(executeGameCommand(s,{type:'gear',id:'unequip:weapon'}).ok).toBe(false);for(let i=0;i<120;i++)s.tick(1/60,idle);expect(s.player.phase).toBe('idle');expect(s.campaign.gearInfo(id).durability).toBe(99);});
});
describe('material-specific tools and equipped presentation',()=>{
 it('specializes per sample rather than leaking the front material multiplier into other materials',()=>{for(const heavy of [false,true]){expect(toolPower('wood-axe',4,heavy)).toBeGreaterThan(toolPower('wood-axe',3,heavy)*4);expect(toolPower('stone-pick',6,heavy)).toBeGreaterThan(toolPower('stone-pick',4,heavy)*4);expect(toolPower('terrain-rake',6,heavy)).toBe(0);}const field=new VoxelField(),water=new VoxelWater(field),elements=new ElementSystem(field,water);field.box({x:0,y:0,z:0},{x:.5,y:.5,z:.5},4,'wood');field.box({x:.5,y:0,z:0},{x:1,y:.5,z:.5},6,'metal');const hit=field.ray({x:.45,y:1,z:.25},{x:0,y:-1,z:0},2)!;const metal=field.get(2,0,0)!;elements.damage(hit,150,.6,c=>toolPower('wood-axe',c.material,true));expect(elements.durability(metal)).toBe(102);expect(elements.drainDrops().every(d=>d.material===4)).toBe(true);});
 it('head or legs metal participates in actual player shock, and cloth in burning',()=>{const c=prepared();c.craft('copper-helm',home);c.equip('copper-helm');const field=new VoxelField(),water=new VoxelWater(field),elements=new ElementSystem(field,water);field.box({x:.5,y:0,z:-.5},{x:.75,y:1.75,z:.5},6,'hazard');const hit=field.ray({x:.2,y:.875,z:0},{x:1,y:0,z:0},2)!;elements.cast('lightning',hit,{x:1,y:0,z:0});const armored=stepPlayerEnvironment(createPlayerEnvironmentState(),.1,{position:{x:.2,y:0,z:0},field,water,elements,armorMaterial:c.armorMaterial});const bare=stepPlayerEnvironment(createPlayerEnvironmentState(),.1,{position:{x:.2,y:0,z:0},field,water,elements,armorMaterial:0});expect(armored.shockDamage).toBeGreaterThan(bare.shockDamage);});
 it('shows specific tool meshes, actual weapon reach, per-slot armor and accessories without recoloring another rig',()=>{const c=prepared(),rig=createRig(),other=createRig();for(const id of ['copper-helm','hide-coat','cloth-leggings','traveler-ring','copper-shield']){c.craft(id,home);c.equip(id);}const others=other.root.children.map(mesh=>(mesh as Mesh).material);rig.setEquipmentStyle(c.state.equipment);for(const id of ['wood-axe','stone-pick','terrain-rake','build-hammer']){rig.update(attackPose('slash','idle',0),0,0,0,true,0,0,null,id);expect(rig.root.userData.weapon).toBe(id);const tools=rig.root.children.filter(o=>o.name.startsWith('tool-')&&o.visible);expect(tools).toHaveLength(1);}for(const id of ['greatsword','dagger'] as const){const pose=attackPose('slash','strike',.1,1,id);rig.update(pose,0,0,0,false,0,0,id);expect(rig.root.userData.bladeLength).toBeCloseTo(meleeDefinition('slash',id).reach);expect(rig.root.getObjectByName('shield-copper')!.visible).toBe(id==='dagger');}expect(rig.root.getObjectByName('accessory-ring')!.visible).toBe(true);for(const slot of ['head','armor','legs'])expect(rig.root.children.some(mesh=>((mesh as Mesh).material as MeshStandardMaterial).name.startsWith('player-slot-'+slot+'-'))).toBe(true);expect(other.root.children.map(mesh=>(mesh as Mesh).material)).toEqual(others);rig.dispose();other.dispose();});
});

describe('actual SDF melee contact authority',()=>{
 function fight(id:'greatsword'|'dagger',distanceFromPlayer:number,wall=false){const s=new CoreSimulation(true,false,true);Object.assign(s.survival.inventory,{3:20,4:20,6:20});s.campaign.state.flameTier=1;s.campaign.state.artisanRescued=true;s.campaign.craft(id,home);executeGameCommand(s,{type:'equip',id});for(const e of s.enemies){e.hp=0;e.phase='dead';}const e=s.enemies[0];e.position={x:0,y:.25,z:6-distanceFromPlayer};e.hp=100;e.phase='stagger';e.time=0;if(wall)s.arena.field.box({x:-1,y:.25,z:5.1},{x:1,y:3,z:5.5},3,'test-contact-wall');if(wall)expect(s.arena.field.distance({x:0,y:1.5,z:5.25})).toBeLessThan(0);s.action('attack',idle);for(let i=0;i<55;i++)s.tick(1/60,idle);return {s,e};}
 it('long greatsword contacts a target beyond dagger reach and stuns it without granting an aim-cone hit',()=>{const great=fight('greatsword',2.05),dagger=fight('dagger',2.05);expect(great.e.hp).toBeLessThan(100);expect(great.e.phase).toBe('stagger');expect(dagger.e.hp).toBe(100);});
 it.each(['greatsword','dagger'] as const)('%s hits nearby bodies once and cannot damage a body behind SDF stone',id=>{const close=fight(id,1.2),blocked=fight(id,1.2,true);expect(close.e.hp).toBeLessThan(100);expect(close.e.hp).toBeGreaterThanOrEqual(100-meleeDefinition('slash',id).damage*1.35);expect(blocked.e.hp).toBe(100);});
});

it('equipment presenter exposes each slot and finite tool repair beside production inventory actions',()=>{const s=new CoreSimulation(true,false,true);Object.assign(s.survival.inventory,{3:10,4:10});s.campaign.craft('wood-axe',home);executeGameCommand(s,{type:'equip',id:'wood-axe'});s.campaign.consumeToolDurability(2);const snapshot=campaignSnapshot(s,defaultSettings(),{available:false,label:'',status:''},[]);expect(snapshot.items.find(row=>row.id==='wood-axe')?.action).toBe('equip');for(const slot of ['head','armor','legs','shield','tool','charm'])expect(snapshot.equipment.find(row=>row.id==='unequip:'+slot)).toBeDefined();expect(snapshot.equipment.find(row=>row.id==='repair:wood-axe')).toMatchObject({available:true,detail:'修理: 石1'});});

it('shield upgrades and gems provide real armor reduction while the building hammer explicitly refuses useless upgrades',()=>{const c=prepared();c.craft('copper-shield',home);c.equip('copper-shield');expect(c.armorMaterial).toBe(6);expect(c.damageReduction).toBe(0);expect(c.upgrade('copper-shield',home).ok).toBe(true);expect(c.damageReduction).toBe(.03);c.craft('ember-gem',home);expect(c.socket('copper-shield','ember-gem',home).ok).toBe(true);expect(c.damageReduction).toBe(.08);c.craft('build-hammer',home);const before={...c.materials};expect(c.upgrade('build-hammer',home).ok).toBe(false);expect(c.socket('build-hammer','ember-gem',home).ok).toBe(false);expect(c.materials).toEqual(before);expect(validCampaignState({...c.snapshot(),equipment:{...c.state.equipment,head:undefined}})).toBe(false);});

it('a shared loadout cannot change either actors authoritative blade midway through an attack',()=>{const s=new CoreSimulation(true,false,true);Object.assign(s.survival.inventory,{3:10,4:10});s.campaign.craft('dagger',home);const guest=s.enableCompanion();guest.phase='windup';expect(executeGameCommand(s,{type:'equip',id:'dagger'}).ok).toBe(false);guest.phase='idle';expect(executeGameCommand(s,{type:'equip',id:'dagger'}).ok).toBe(true);s.player.phase='strike';let result=true;s.withCompanion(()=>{result=executeGameCommand(s,{type:'gear',id:'unequip:weapon'}).ok;});expect(result).toBe(false);});
