import {expect,it} from 'vitest';
import {emptyGear,migrateGear,mutateGear,transferGear,mintGear,selectedGear,projectGear,validateGear,selectGear,fuseBridge,GEAR_LIMITS} from '../../src/game/equipment/items';
const allocator=()=>{let n=3000001;return()=>n++;};
it('migrates one hundred million legacy duplicate gear compactly and assigns fusion exactly once',()=>{const next=allocator(),items={club:100000000,wood:5};const gear=migrateGear(items,next,{quality:{club:3},durability:{club:7},fusions:[{equipment:'club',material:'resin',damage:4,durability:12,effect:'fire'}]});expect(gear.lots).toHaveLength(2);expect(gear.lots.reduce((n,l)=>n+l.count,0)).toBe(100000000);expect(gear.lots.filter(l=>l.fusion)).toHaveLength(1);expect(selectedGear(gear,'club')).toMatchObject({count:1,quality:3,durability:7,fusion:{durability:12}});expect(projectGear(gear,items)).toEqual(items);});
it('splits only the selected homogeneous unit before wear and never mutates old source or another copy',()=>{const next=allocator(),source=migrateGear({club:100000000},next,{quality:{club:2},durability:{club:50}}),changed=mutateGear(source,'club',next,l=>l.durability=49);expect(source.lots).toHaveLength(1);expect(source.lots[0].durability).toBe(50);expect(changed.lots).toHaveLength(2);expect(selectedGear(changed,'club')).toMatchObject({count:1,durability:49});expect(changed.lots[0]).toMatchObject({count:99999999,durability:50});expect(projectGear(changed,{})).toEqual({club:100000000});});
it('keeps whole-lot identity and exact metadata across handoff without replacing a receiver selection',()=>{const next=allocator(),a=migrateGear({club:1},next,{quality:{club:3},durability:{club:7},fusions:[{equipment:'club',material:'resin',damage:4,durability:12,effect:'fire'}]}),b=mintGear(emptyGear(),'club',1,next),oldB=selectedGear(b,'club')!,moved=transferGear(a,b,'club',1,next);expect(moved.source.lots).toEqual([]);expect(moved.destination.lots).toContainEqual(a.lots[0]);expect(selectedGear(moved.destination,'club')).toEqual(oldB);expect(projectGear(moved.destination,{})).toEqual({club:2});expect(selectedGear(selectGear(moved.destination,a.lots[0].id),'club')).toEqual(a.lots[0]);});
it('preflights metadata capacity, quantities and ID failures without mutating either side',()=>{const next=allocator(),source=migrateGear({club:5},next),destination=emptyGear();destination.lots=Array.from({length:GEAR_LIMITS.lots},()=>({id:next(),kind:'club',count:1}));const before=structuredClone({source,destination});expect(()=>transferGear(source,destination,'club',1,next)).toThrow('いっぱい');expect({source,destination}).toEqual(before);for(const n of[0,-1,1.5,6])expect(()=>transferGear(source,emptyGear(),'club',n,next)).toThrow();expect(()=>transferGear(source,emptyGear(),'club',1,()=>GEAR_LIMITS.id)).toThrow('識別子');expect(source).toEqual(before.source);});
it('rejects count projection divergence, duplicate holder IDs and invalid new-schema metadata',()=>{const next=allocator(),gear=mintGear(emptyGear(),'club',1,next);expect(()=>validateGear(gear,{club:2})).toThrow('一致');const seen=new Set<number>();validateGear(gear,{club:1},seen);expect(()=>validateGear(gear,{club:1},seen)).toThrow('重複');const invalid=structuredClone(gear);invalid.lots[0].durability=NaN;expect(()=>validateGear(invalid)).toThrow();});
it('makes fusion writes transactional and canonical while old references remain detached',()=>{const next=allocator();let gear=migrateGear({club:2},next,{durability:{club:50}});const bridge=fuseBridge(()=>gear,g=>gear=g,next),commit=bridge.prepare('club',{equipment:'club',material:'stone',damage:6,durability:30,effect:'impact'});expect(bridge.get('club')).toBeUndefined();commit();expect(()=>commit()).toThrow('更新');expect(gear.lots).toHaveLength(2);expect(gear.lots.filter(l=>l.fusion)).toHaveLength(1);bridge.wear('club');expect(selectedGear(gear,'club')?.fusion?.durability).toBe(29);const returned=bridge.get('club')!;returned.durability=0;expect(bridge.get('club')?.durability).toBe(29);});
it('new craft does not use metadata of an old grave or change a differently selected item',()=>{const next=allocator(),old=migrateGear({club:1},next,{quality:{club:3},durability:{club:7}}),crafted=mintGear(emptyGear(),'club',1,next),recovered=transferGear(old,crafted,'club',1,next);expect(selectedGear(recovered.destination,'club')).toMatchObject({quality:1,durability:100});expect(recovered.destination.lots).toContainEqual(old.lots[0]);});

it('rejects missing or impossible metadata on new lots while retaining explicit legacy unknown values',()=>{const next=allocator(),fresh=mintGear(emptyGear(),'club',1,next);const missing=structuredClone(fresh);delete missing.lots[0].durability;expect(()=>validateGear(missing)).toThrow('品質');const impossible=structuredClone(fresh);impossible.lots[0].durability=101;expect(()=>validateGear(impossible)).toThrow('品質');const legacy=migrateGear({club:1},next);expect(validateGear(legacy).lots[0]).toMatchObject({legacy:true});expect(legacy.lots[0].quality).toBeUndefined();});
