import {describe,it,expect} from 'vitest';
import {CampaignSystem,validCampaignState} from '../../src/prototype/core/campaign';
import {SampleManifestRecorder} from '../../src/prototype/core/sample-provider';
import {SparseOverlayField} from '../../src/prototype/core/sample-overlay';
import type {ObjectState} from '../../src/prototype/core/world';
import {WEST_EXPEDITION_MANIFEST,WEST_POINTS,WEST_RESOURCES,WEST_ROUTES,authorWesternExpedition,WEST_SHORTCUT_CLEARANCE} from '../../src/prototype/core/expedition-west';
import {WestExpeditionSystem,WEST_RUNTIME_ENEMIES,WEST_SURVEY_QUEST,validWestExpeditionState,type WestActorContext} from '../../src/prototype/core/expedition-west-integration';
const setup=()=>{const recorder=new SampleManifestRecorder(),authored=authorWesternExpedition({field:recorder,objects:new Map<string,ObjectState>()}),field=new SparseOverlayField(recorder.createProvider(WEST_EXPEDITION_MANIFEST,8)),campaign=new CampaignSystem({2:100,3:100,4:100,6:100,7:100,10:100});Object.assign(campaign.state,{flameTier:2,gateOpen:true,campUnlocked:true,unlockedRegions:['hearthfield','resinwood'],completed:['ridge']});expect(validCampaignState(campaign.state)).toBe(true);const arena={field,objects:authored.objects};return{field,campaign,arena,west:new WestExpeditionSystem(campaign,arena,WEST_EXPEDITION_MANIFEST)};};
const point=(id:string)=>[...WEST_POINTS,...WEST_RESOURCES].find(p=>p.id===id)!;
const actor=(id:string):WestActorContext=>({authority:'host',alive:true,position:{...point(id).position,x:point(id).position.x+.9}});
const kill=(west:WestExpeditionSystem,id:string)=>{const e=WEST_RUNTIME_ENEMIES.find(e=>e.key===id)!;return west.defeat(id,{slot:e.slot,hp:0},actor('west-mine-switch'));};

describe('isolated western expedition host integration',()=>{
 it('uses appended encounter slots and existing reusable tactic definitions',()=>{expect(WEST_RUNTIME_ENEMIES.map(e=>e.slot)).toEqual([18,19,20,21]);expect(WEST_RUNTIME_ENEMIES.map(e=>e.definition.id)).toEqual([201,202,203,204]);expect(new Set(WEST_RUNTIME_ENEMIES.map(e=>e.definition.tactic)).size).toBe(4);});
 it('requires opt-in manifest, unlocked forest, living host, range and SDF visibility',()=>{
  const {west,campaign,arena,field}=setup(),id='west-hamlet-cache',a=actor(id);const before=campaign.snapshot();
  expect(new WestExpeditionSystem(campaign,arena,'campaign-samples-v1/c1602605').interact(id,a).ok).toBe(false);expect(west.interact(id,{...a,authority:'guest'}).ok).toBe(false);expect(west.interact(id,{...a,alive:false}).ok).toBe(false);expect(west.interact(id,{...a,position:{x:0,y:0,z:0}}).ok).toBe(false);
  campaign.state.unlockedRegions=['hearthfield'];expect(west.interact(id,a).ok).toBe(false);campaign.restore(before);
  field.box({x:-49.65,y:.75,z:-13.8},{x:-49.5,y:3,z:-12.2},3,'blocking-wall');expect(west.interact(id,a).ok).toBe(false);expect(west.snapshot().claimed).toHaveLength(0);
 });
 it('gates mine treasure on both confirmed defeats and the physical shortcut switch',()=>{
  const {west,field}=setup(),a=actor('west-mine-cache');expect(west.interact('west-mine-cache',a).ok).toBe(false);expect(kill(west,'west-pitguard').ok).toBe(true);expect(west.interact('west-mine-cache',a).ok).toBe(false);expect(kill(west,'west-orewatch').ok).toBe(true);expect(west.interact('west-mine-cache',a).ok).toBe(false);
  expect(field.overlaps(WEST_SHORTCUT_CLEARANCE)).toBe(true);expect(west.interact('west-mine-switch',actor('west-mine-switch')).ok).toBe(true);expect(field.overlaps(WEST_SHORTCUT_CLEARANCE)).toBe(false);expect(west.interact('west-mine-cache',a).ok).toBe(true);expect(west.interact('west-mine-cache',a).ok).toBe(false);
 });
 it('rejects unconfirmed/live/mismatched kills and duplicate rewards',()=>{const {west,campaign}=setup(),e=WEST_RUNTIME_ENEMIES[0],a=actor('west-hamlet-cache');expect(west.defeat(e.key,{slot:e.slot,hp:1},a).ok).toBe(false);expect(west.defeat(e.key,{slot:0,hp:0},a).ok).toBe(false);expect(kill(west,e.key).ok).toBe(true);const saved=campaign.snapshot();expect(kill(west,e.key).ok).toBe(false);expect(campaign.snapshot()).toEqual(saved);});
 it('retains confirmed mutual-kill rewards and permits a capacity-blocked corpse reward retry',()=>{const {west,campaign}=setup(),enemy=WEST_RUNTIME_ENEMIES.find(e=>e.key==='west-pitguard')!;campaign.materials[6]=1000000;const context={...actor('west-mine-switch'),alive:false};expect(west.defeat(enemy.key,{slot:enemy.slot,hp:0},context).ok).toBe(false);expect(west.snapshot().defeated).not.toContain(enemy.key);campaign.materials[6]-=3;expect(west.defeat(enemy.key,{slot:enemy.slot,hp:0},context).ok).toBe(true);expect(west.snapshot().defeated).toContain(enemy.key);});
 it('checks whole reward capacity before changing wallet, claims or resource geometry',()=>{const {west,campaign,field}=setup(),id='west-resin-a';campaign.state.items['amber-resin']=200;const before=campaign.snapshot(),materials={...campaign.materials},revision=field.revision;expect(west.interact(id,actor(id)).ok).toBe(false);expect(campaign.snapshot()).toEqual(before);expect(campaign.materials).toEqual(materials);expect(field.revision).toBe(revision);expect(west.snapshot().claimed).not.toContain(id);campaign.state.items['amber-resin']=198;expect(west.interact(id,actor(id)).ok).toBe(true);expect(campaign.state.items['amber-resin']).toBe(200);expect([...field.objectSamples(id)]).toHaveLength(0);});
 it('awards sidequests after out-of-order acquisition without rewriting the completed main story',()=>{
  const {west,campaign}=setup();kill(west,'west-pitguard');kill(west,'west-orewatch');west.interact('west-mine-switch',actor('west-mine-switch'));west.interact('west-mine-cache',actor('west-mine-cache'));expect(west.snapshot().completed).not.toContain('west-two-mouths');expect(west.interact('west-hamlet-cache',actor('west-hamlet-cache')).ok).toBe(true);expect(west.interact('west-return-hearth',actor('west-return-hearth')).ok).toBe(true);expect(west.snapshot().completed).toEqual(expect.arrayContaining(['west-supply-road','west-two-mouths']));expect(west.interact('west-shortcut-gate',actor('west-shortcut-gate')).ok).toBe(true);expect(west.snapshot().completed).toContain('west-safe-return');expect(campaign.state.completed).toEqual(['ridge']);expect(validCampaignState(campaign.snapshot())).toBe(true);
 });
 it('records both road traversals in order, supports a reverse return, and grants the survey bonus once',()=>{
  const {west,campaign}=setup(),high=WEST_ROUTES[0],low=WEST_ROUTES[1],visit=(position:WestActorContext['position'])=>west.observe({authority:'host',alive:true,position});visit(high.nodes.at(-1)!);expect(west.snapshot().completed).not.toContain(WEST_SURVEY_QUEST);
  for(const p of high.nodes)visit(p);for(const p of [...low.nodes].reverse())visit(p);expect(west.snapshot().completed).toContain(WEST_SURVEY_QUEST);const saved=campaign.snapshot(),wood=campaign.materials[4];for(const p of high.nodes)visit(p);expect(campaign.snapshot()).toEqual(saved);expect(campaign.materials[4]).toBe(wood);
 });
 it('unlocks a safe return camp and roof-checked rest without duplicating camp reward',()=>{const {west,campaign,field}=setup();expect(west.travel('west-return-hearth',actor('west-return-hearth')).ok).toBe(false);expect(west.interact('west-return-hearth',actor('west-return-hearth')).ok).toBe(true);const xp=campaign.state.xp;expect(west.interact('west-return-hearth',actor('west-return-hearth')).ok).toBe(true);expect(campaign.state.xp).toBe(xp);const travel=west.travel('west-return-hearth',actor('west-hamlet-cache'));expect(travel.ok).toBe(true);expect(field.overlaps(travel.position!)).toBe(false);expect(west.rest(actor('west-return-hearth')).ok).toBe(false);expect(west.rest({authority:'host',alive:true,position:{x:-48.3,y:.75,z:-14}}).ok).toBe(true);expect(campaign.state.restSeconds).toBe(180);});
 it('round-trips the separate ledger and terrain, rejects forged dependencies atomically, and never regenerates saved geometry',()=>{const {west,field,campaign,arena}=setup();west.interact('west-mine-switch',actor('west-mine-switch'));const saved=west.snapshot(),terrain=field.exportOverlay();expect(validWestExpeditionState(saved)).toBe(true);expect(west.restore({...saved,claimed:[...saved.claimed,'west-mine-cache']})).toBe(false);expect(west.snapshot()).toEqual(saved);const other=new SparseOverlayField(field.provider);other.restoreOverlay(terrain);const restored=new WestExpeditionSystem(campaign,{field:other,objects:arena.objects},WEST_EXPEDITION_MANIFEST);expect(restored.restore(saved)).toBe(true);const before=other.exportOverlay();expect(restored.reconcileGeometry()).toBe(true);expect(other.exportOverlay()).toEqual(before);expect(other.overlaps(WEST_SHORTCUT_CLEARANCE)).toBe(false);const closed=new WestExpeditionSystem(campaign,{field:new SparseOverlayField(field.provider),objects:arena.objects},WEST_EXPEDITION_MANIFEST);closed.restore(saved);expect(closed.reconcileGeometry()).toBe(false);});
});
