import {describe,it,expect} from 'vitest';
import {VoxelField} from '../../src/prototype/core/voxel';
import {VoxelWater} from '../../src/prototype/core/water';
import {createArena} from '../../src/prototype/core/world';
import {CampaignSystem,CAMPAIGN_ITEMS,CAMPAIGN_RECIPES,validCampaignState} from '../../src/prototype/core/campaign';
import {FishingSystem,createFishingWaterProbe,fishingTargetAlongRay,validFishingState,type FishingActor,type FishingWaterProbe} from '../../src/prototype/core/fishing';
const target={x:5.5,y:0,z:-2},actor:FishingActor={authority:'host',alive:true,swimming:false,position:{x:3,y:.25,z:-2}};
const setup=()=>{const field=new VoxelField(),campaign=new CampaignSystem({2:100,3:100,4:100,6:100,7:100,10:100});campaign.craft('fishing-rod',actor.position);campaign.craft('fish-bait',actor.position);const probe: FishingWaterProbe=()=>({spot:'trial-basin',surfaceY:0,depth:.5}),fish=new FishingSystem(campaign,field,probe);fish.selectRod(true);return{field,campaign,fish};};
const tick=(fish:FishingSystem,seconds:number,a=actor,hz=60)=>{const out=[];for(let i=0;i<Math.round(seconds*hz);i++)out.push(...fish.tick(1/hz,a));return out;};
const bite=(fish:FishingSystem)=>{for(let i=0;i<600&&fish.phase!=='bite';i++)fish.tick(1/60,actor);expect(fish.phase).toBe('bite');};

describe('finite bait and timed original fishing',()=>{
 it('crafts/selects a rod and charges one bait only after all casting checks succeed',()=>{const {campaign,fish}=setup(),bait=campaign.state.items['fish-bait'];expect(fish.cast(target,{...actor,authority:'guest'}).ok).toBe(false);expect(fish.cast(target,{...actor,swimming:true}).ok).toBe(false);expect(fish.cast({...target,x:20},actor).ok).toBe(false);expect(campaign.state.items['fish-bait']).toBe(bait);expect(fish.cast(target,actor).ok).toBe(true);expect(campaign.state.items['fish-bait']).toBe(bait-1);expect(fish.cast(target,actor).ok).toBe(false);expect(campaign.state.items['fish-bait']).toBe(bait-1);expect(validFishingState(fish.snapshot())).toBe(true);});
 it('derives a real cast target from keyboard/mobile first-person aim',()=>{const {fish}=setup();const eye={...actor.position,y:actor.position.y+1.2},aim={x:target.x-eye.x,y:target.y-eye.y,z:target.z-eye.z};const hit=fishingTargetAlongRay(eye,aim,fish.water);expect(hit).not.toBeNull();expect(hit!.x).toBeCloseTo(target.x);expect(hit!.y).toBe(0);expect(fishingTargetAlongRay(eye,{x:1,y:0,z:0},fish.water)).toBeNull();expect(fish.interact(hit,actor).ok).toBe(true);});
 it('requires real sufficient water and a clear cast line',()=>{const {campaign,field}=setup();for(const probe of [()=>null,()=>({spot:'trial-basin' as const,surfaceY:0,depth:.2})]){const f=new FishingSystem(campaign,field,probe);f.selectRod(true);expect(f.cast(target,actor).ok).toBe(false);}const {fish}=setup();fish.field.box({x:4,y:0,z:-3},{x:4.3,y:3,z:-1},3);expect(fish.cast(target,actor).ok).toBe(false);});
 it('advances cast to wait to bite, then awards exactly one fish only on a timely reel',()=>{const {fish,campaign}=setup();fish.cast(target,actor);expect(fish.phase).toBe('casting');tick(fish,.7);expect(fish.phase).toBe('waiting');expect(campaign.state.items.silverfin??0).toBe(0);bite(fish);expect(fish.reel(actor).ok).toBe(true);expect(campaign.state.items.silverfin).toBe(1);expect(fish.reel(actor).ok).toBe(false);expect(campaign.state.items.silverfin).toBe(1);expect(fish.snapshot().resolved).toBe(fish.snapshot().serial);});
 it('does not let guest reel/interact/tick interrupt or advance a host cast',()=>{const {fish,campaign}=setup();fish.cast(target,actor);const before=fish.snapshot(),wallet=campaign.snapshot(),guest={...actor,authority:'guest' as const};expect(fish.reel(guest).ok).toBe(false);expect(fish.interact(target,guest).ok).toBe(false);expect(fish.tick(.5,guest)).toEqual([]);expect(fish.snapshot()).toEqual(before);expect(campaign.snapshot()).toEqual(wallet);});
 it('early reels and missed bite windows lose the finite bait without awarding fish',()=>{const early=setup();early.fish.cast(target,actor);expect(early.fish.reel(actor).ok).toBe(false);expect(early.campaign.state.items.silverfin??0).toBe(0);const late=setup();late.fish.cast(target,actor);bite(late.fish);expect(tick(late.fish,2).some(e=>e.kind==='missed')).toBe(true);expect(late.fish.reel(actor).ok).toBe(false);expect(late.campaign.state.items.silverfin??0).toBe(0);});
 it.each(['move','death','swim','tool','wall'] as const)('interrupts on %s and never refunds spent bait',reason=>{const {fish,campaign,field}=setup();fish.cast(target,actor);const before=campaign.state.items['fish-bait'];let a={...actor,position:{...actor.position}};if(reason==='move')a.position.x-=1;if(reason==='death')a.alive=false;if(reason==='swim')a.swimming=true;if(reason==='tool')fish.selectRod(false);if(reason==='wall')field.box({x:4,y:0,z:-3},{x:4.3,y:3,z:-1},3);fish.tick(.1,a);expect(fish.phase).toBe('idle');expect(campaign.state.items['fish-bait']).toBe(before);expect(campaign.state.items.silverfin??0).toBe(0);});
 it('rejects catches when fish storage becomes full during a cast',()=>{const {fish,campaign}=setup();fish.cast(target,actor);bite(fish);campaign.state.items.silverfin=20;expect(fish.reel(actor).ok).toBe(false);expect(campaign.state.items.silverfin).toBe(20);expect(fish.phase).toBe('idle');});
 it('uses a persisted spot cooldown and renews stock after active time',()=>{const {fish,campaign}=setup();fish.cast(target,actor);bite(fish);fish.reel(actor);const bait=campaign.state.items['fish-bait'];expect(fish.cast(target,actor).ok).toBe(false);expect(campaign.state.items['fish-bait']).toBe(bait);tick(fish,46);expect(fish.cast(target,actor).ok).toBe(true);});
 it('has equivalent bite timing at30Hz and120Hz',()=>{const a=setup(),b=setup();a.fish.cast(target,actor);b.fish.cast(target,actor);tick(a.fish,7,actor,30);tick(b.fish,7,actor,120);expect(a.fish.phase).toBe(b.fish.phase);expect(a.fish.status.remaining).toBeCloseTo(b.fish.status.remaining,6);});
 it('resumes a saved cast without charging bait again and rejects receipt rewind after catching',()=>{const {fish,campaign,field}=setup();fish.cast(target,actor);bite(fish);const state=fish.snapshot(),wallet=campaign.snapshot(),restoredCampaign=new CampaignSystem({...campaign.materials});restoredCampaign.restore(wallet);const restored=new FishingSystem(restoredCampaign,field,fish.water);expect(restored.restore(state)).toBe(true);const bait=restoredCampaign.state.items['fish-bait'];expect(restored.reel(actor).ok).toBe(true);expect(restoredCampaign.state.items['fish-bait']).toBe(bait);expect(restoredCampaign.state.items.silverfin).toBe(1);expect(restored.restore(state)).toBe(false);expect(restored.reel(actor).ok).toBe(false);const next=new FishingSystem(restoredCampaign,field,fish.water);expect(next.restore(restored.snapshot())).toBe(true);expect(next.reel(actor).ok).toBe(false);expect(restoredCampaign.state.items.silverfin).toBe(1);});
 it('rejects malformed phases, cooldowns and impossible receipts atomically',()=>{const {fish}=setup();fish.cast(target,actor);const before=fish.snapshot();for(const bad of [{...before,resolved:20},{...before,readyAt:{'trial-basin':999,mirrorlake:0}},{...before,attempt:{...before.attempt,remaining:100}},{...before,attempt:{...before.attempt,spot:'imaginary'}},{...before,selected:false}]){expect(fish.restore(bad)).toBe(false);expect(fish.snapshot()).toEqual(before);}});
 it('samples actual basin water and rejects the basin after its liquid is drained',()=>{const arena=createArena(),water=new VoxelWater(arena.field),probe=createFishingWaterProbe(arena.field,water);expect(probe(5.5,-2)?.depth).toBeGreaterThanOrEqual(.35);water.volume.fill(0);expect(probe(5.5,-2)).toBeNull();expect(probe(100,100)).toBeNull();});
});
describe('shared fish food recipes and acquisition hints',()=>{
 it('links every added recipe/item with explicit source hints',()=>{for(const id of ['fishing-rod','fish-bait','silverfin','grilled-silverfin','herb-fish-soup'])expect(CAMPAIGN_ITEMS[id].source.length).toBeGreaterThan(5);for(const r of CAMPAIGN_RECIPES)for(const id of Object.keys(r.itemCost??{}))expect(CAMPAIGN_ITEMS[id]).toBeDefined();});
 it('validates all fish/herb/material costs before batch cooking and does not eat raw fish',()=>{const {campaign}=setup();campaign.state.flameTier=1;campaign.state.items.silverfin=2;campaign.state.items.herbs=1;const before=campaign.snapshot(),wood=campaign.materials[4],hearth={x:-3,y:.25,z:4};expect(campaign.craft('herb-fish-soup',hearth,2).ok).toBe(false);expect(campaign.snapshot()).toEqual(before);expect(campaign.materials[4]).toBe(wood);expect(campaign.consume('silverfin').ok).toBe(false);campaign.state.items.herbs=2;expect(campaign.craft('herb-fish-soup',hearth,2).ok).toBe(true);expect(campaign.state.items.silverfin).toBe(0);expect(campaign.state.items.herbs).toBe(0);expect(campaign.materials[4]).toBe(wood-2);expect(campaign.state.items['herb-fish-soup']).toBe(2);expect(campaign.consume('herb-fish-soup').ok).toBe(true);expect(campaign.state.foodSeconds).toBe(180);expect(campaign.maxHp).toBe(120);expect(validCampaignState(campaign.snapshot())).toBe(true);});
 it('grilled fish applies the commonfood buff for120 seconds and does not stack with soup',()=>{const {campaign}=setup();campaign.state.flameTier=1;campaign.state.items.silverfin=1;expect(campaign.craft('grilled-silverfin',{x:-3,y:.25,z:4}).ok).toBe(true);expect(campaign.consume('grilled-silverfin').ok).toBe(true);expect(campaign.state.foodSeconds).toBe(120);expect(campaign.maxStamina).toBe(115);for(let i=0;i<120;i++)campaign.tick(1,{position:{x:-3,y:.25,z:4}});expect(campaign.maxHp).toBe(100);});
});
