import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {createFishingView,type FishingViewSimulation} from '../../src/prototype/rendering/fishing-view';
const setup=()=>{const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(74,1,.035,120);scene.add(camera);camera.position.set(0,2,3);const fishing={selected:false,status:{phase:'idle',remaining:0,spot:null,target:null,message:''}} as FishingViewSimulation['fishing'];const sim={fishing,seconds:0,player:{hp:100}},view=createFishingView(scene,camera,sim);return{scene,camera,sim,view};};
const status=(sim:FishingViewSimulation,phase:'casting'|'waiting'|'bite'|'idle',remaining=0)=>{Object.assign(sim.fishing,{status:{phase,remaining,spot:phase==='idle'?null:'trial-basin',target:phase==='idle'?null:{x:4,y:0,z:0},message:''}});};

describe('bounded fishing scene visuals',()=>{
 it('shows an actual camera-held rod only when selected and the player is alive',()=>{const {scene,camera,sim,view}=setup();view.update();expect(view.stats.rodVisible).toBe(false);Object.assign(sim.fishing,{selected:true});view.update();expect(view.stats.rodVisible).toBe(true);expect(camera.getObjectByName('fishing-rod-shaft')).toBeInstanceOf(THREE.Mesh);expect(view.stats.floatVisible).toBe(false);sim.player.hp=0;view.update();expect(view.stats.rodVisible).toBe(false);view.dispose();expect(scene.getObjectByName('fishing-held-rod')).toBeUndefined();});
 it('places a float at the status water target and connects the line to the rod tip',()=>{const {scene,camera,sim,view}=setup();Object.assign(sim.fishing,{selected:true});status(sim,'waiting');view.update();const buoy=scene.getObjectByName('fishing-float')!,line=scene.getObjectByName('fishing-line') as THREE.Line,position=line.geometry.getAttribute('position'),tip=camera.getObjectByName('fishing-line-origin')!.getWorldPosition(new THREE.Vector3());expect(buoy.position.x).toBe(4);expect(buoy.position.z).toBe(0);expect(buoy.position.y).toBeCloseTo(.08);expect(position.getX(0)).toBeCloseTo(tip.x,5);expect(position.getY(8)).toBeCloseTo(buoy.position.y,5);expect(position.getX(8)).toBe(4);view.dispose();});
 it('makes bite feedback visually distinct with color, bob and a ripple',()=>{const {scene,sim,view}=setup();Object.assign(sim.fishing,{selected:true});status(sim,'waiting');view.update();const mesh=scene.getObjectByName('fishing-float-body') as THREE.Mesh<THREE.BufferGeometry,THREE.MeshBasicMaterial>,waiting=mesh.material.color.getHex(),buoy=scene.getObjectByName('fishing-float')!;const y=buoy.position.y;status(sim,'bite',1.4);sim.seconds=.23;view.update();expect(mesh.material.color.getHex()).not.toBe(waiting);expect(buoy.position.y).not.toBe(y);expect(scene.getObjectByName('fishing-bite-ripple')!.visible).toBe(true);status(sim,'idle');view.update();expect(view.stats.floatVisible).toBe(false);view.dispose();});
 it('animates the cast from the rod rather than instantly placing the float',()=>{const {scene,sim,view}=setup();Object.assign(sim.fishing,{selected:true});status(sim,'casting',.6);view.update();const buoy=scene.getObjectByName('fishing-float')!,start=buoy.position.clone();status(sim,'casting',.3);view.update();expect(buoy.position.distanceTo(start)).toBeGreaterThan(.2);expect(buoy.position.distanceTo(new THREE.Vector3(4,0,0))).toBeGreaterThan(.2);view.dispose();});
 it('reuses all geometry/material/line buffers across updates and never queries water',()=>{const {scene,sim,view}=setup();Object.assign(sim.fishing,{selected:true});status(sim,'waiting');const line=scene.getObjectByName('fishing-line') as THREE.Line,array=line.geometry.getAttribute('position').array,stats=view.stats;const resources=new Set<THREE.BufferGeometry>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line)resources.add(o.geometry);});for(let i=0;i<300;i++){sim.seconds=i/60;view.update();}expect(view.stats.geometries).toBe(stats.geometries);expect(view.stats.materials).toBe(stats.materials);expect(line.geometry.getAttribute('position').array).toBe(array);const after=new Set<THREE.BufferGeometry>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line)after.add(o.geometry);});expect(after).toEqual(resources);view.dispose();});
 it('supports an explicit remote-view disable without altering shared fishing state',()=>{const {sim,view}=setup();Object.assign(sim.fishing,{selected:true});status(sim,'bite',1);view.update();expect(view.stats.rodVisible).toBe(true);expect(view.stats.floatVisible).toBe(true);view.update(false);expect(view.stats.rodVisible).toBe(false);expect(view.stats.floatVisible).toBe(false);expect(sim.fishing.selected).toBe(true);view.update();expect(view.stats.rodVisible).toBe(true);view.dispose();});
 it('disposes every unique owned resource once and removes both scene roots',()=>{const {scene,camera,view}=setup(),geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);}});const disposed=vi.fn();for(const g of geometries)g.addEventListener('dispose',disposed);for(const m of materials)m.addEventListener('dispose',disposed);view.dispose();view.dispose();view.update();expect(disposed).toHaveBeenCalledTimes(geometries.size+materials.size);expect(camera.getObjectByName('fishing-held-rod')).toBeUndefined();expect(scene.getObjectByName('fishing-cast-view')).toBeUndefined();});
});
