import {describe,it,expect} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {captureCampaign,hydrateCampaign,defaultSettings,isCampaignSave,restoreCampaignInto} from '../../src/prototype/campaign-session';
import {fishingTargetAlongRay} from '../../src/prototype/core/fishing';
import {direction,type Vec3} from '../../src/prototype/core/voxel';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false};
// Integration fixtures grant craft materials and disable combat. They never inject
// liquid, force a fishing phase, award fish, or replace the real Core action/tick path.
const setup=()=>{const s=new CoreSimulation(true,false,true);for(const e of s.enemies){e.hp=0;e.phase='dead';}s.survival.inventory[4]=40;s.survival.inventory[7]=30;s.survival.inventory[3]=30;expect(executeGameCommand(s,{type:'craft',id:'fishing-rod'}).ok).toBe(true);expect(executeGameCommand(s,{type:'craft',id:'fish-bait'}).ok).toBe(true);return s;};
const tick=(s:CoreSimulation,seconds:number)=>{for(let n=0;n<Math.round(seconds*60);n++)s.tick(1/60,idle);};
const aim=(s:CoreSimulation,p:Vec3)=>{const eye=s.eye(),dx=p.x-eye.x,dy=p.y-eye.y,dz=p.z-eye.z;s.player.yaw=Math.atan2(-dx,-dz);s.player.pitch=Math.atan2(dy,Math.hypot(dx,dz));};
const walk=(s:CoreSimulation,x:number,z:number)=>{for(let n=0;n<900;n++){if(Math.hypot(s.player.position.x-x,s.player.position.z-z)<.16){tick(s,.2);return;}const dx=x-s.player.position.x,dz=z-s.player.position.z;s.player.yaw=Math.atan2(-dx,-dz);s.player.pitch=0;s.tick(1/60,{...idle,z:1});}throw new Error(`Route blocked toward ${x},${z}: ${JSON.stringify(s.player.position)}`);};
const shore=(s:CoreSimulation)=>{s.player.position={x:5.5,y:.25,z:1.6};s.player.vx=s.player.vz=s.player.vy=0;tick(s,.1);};
const selectAndCast=(s:CoreSimulation)=>{expect(executeGameCommand(s,{type:'gear',id:'fishing-rod'}).ok).toBe(true);const water=s.fishing.water(5.5,-1);expect(water?.depth).toBeGreaterThanOrEqual(.35);aim(s,{x:5.5,y:water!.surfaceY,z:-1});expect(fishingTargetAlongRay(s.eye(),direction(s.player.yaw,s.player.pitch),s.fishing.water)).not.toBeNull();s.action('interact',idle);expect(s.fishing.phase).toBe('casting');};
const waitBite=(s:CoreSimulation)=>{for(let n=0;n<600&&s.fishing.phase!=='bite';n++)s.tick(1/60,idle);expect(s.fishing.phase,s.events.at(-1)?.text).toBe('bite');};
const openValveFixture=(s:CoreSimulation)=>{s.player.position={x:3.25,y:.25,z:-.5};aim(s,{x:3.25,y:.75,z:-2.75});expect(s.target()?.hit.cell.object).toBe('valve');s.action('interact',idle);expect(s.waterOn).toBe(true);};

describe('actual Core fishing action and water integration',()=>{
 it('walks through the real door to operate the valve, reaches the shore, and reels through E',()=>{
  const s=setup();walk(s,0,3);aim(s,{x:0,y:1.4,z:1});expect(s.target()?.hit.cell.object).toBe('door');s.action('interact',idle);expect(s.arena.objects.get('door')?.open).toBe(true);walk(s,0,-.5);walk(s,3.25,-.5);aim(s,{x:3.25,y:.75,z:-2.75});expect(s.target()?.hit.cell.object).toBe('valve');s.action('interact',idle);expect(s.waterOn).toBe(true);walk(s,0,-.5);walk(s,0,2.2);walk(s,5.5,2.2);walk(s,5.5,1.6);tick(s,10);
  expect(s.water.injected).toBeGreaterThan(0);const bait=s.campaign.state.items['fish-bait'];selectAndCast(s);expect(s.campaign.state.items['fish-bait']).toBe(bait-1);waitBite(s);s.action('interact',idle);expect(s.campaign.state.items.silverfin).toBe(1);expect(s.fishing.phase).toBe('idle');s.action('interact',idle);expect(s.campaign.state.items.silverfin).toBe(1);
 },20000);
 it('retains sufficient inlet-side depth after30 seconds of real valve flow without changing the threshold',()=>{const s=setup();openValveFixture(s);tick(s,30);expect(s.fishing.water(5.5,-1)?.depth).toBeGreaterThanOrEqual(.35);expect(s.fishing.water(7,-2)?.depth??0).toBeLessThan(.35);shore(s);selectAndCast(s);waitBite(s);s.action('interact',idle);expect(s.campaign.state.items.silverfin).toBe(1);},15000);
 it('cancels a real cast when selecting a tool and does not refund bait',()=>{const s=setup();shore(s);selectAndCast(s);const bait=s.campaign.state.items['fish-bait'];s.action('chisel',idle);expect(s.fishing.selected).toBe(false);expect(s.fishing.phase).toBe('idle');expect(s.campaign.state.items['fish-bait']).toBe(bait);},10000);
 it('rejects guest rod selection and interaction without cancelling the host cast',()=>{const s=setup();shore(s);selectAndCast(s);const before=s.fishing.snapshot(),items={...s.campaign.state.items};s.enableCompanion({x:0,y:.25,z:6});expect(s.withCompanion(()=>executeGameCommand(s,{type:'gear',id:'fishing-rod'}))?.ok).toBe(false);s.companionAction('interact');expect(s.fishing.snapshot()).toEqual(before);expect(s.campaign.state.items).toEqual(items);},10000);
 it('consumes an actually caught fish through cooking and the shared use-item command',()=>{const s=setup();openValveFixture(s);tick(s,5);shore(s);selectAndCast(s);waitBite(s);s.action('interact',idle);expect(s.campaign.state.items.silverfin).toBe(1);s.selectFishingRod(false);s.player.position={x:-3,y:.25,z:4};expect(s.campaign.interact('hearth',s.player.position).ok).toBe(true);expect(executeGameCommand(s,{type:'craft',id:'grilled-silverfin'}).ok).toBe(true);expect(s.campaign.state.items.silverfin).toBe(0);expect(executeGameCommand(s,{type:'consume',id:'grilled-silverfin'}).ok).toBe(true);expect(s.campaign.maxHp).toBe(120);expect(s.campaign.state.foodSeconds).toBe(120);},15000);
 it('round-trips an actual pending cast and then the catch without duplicate reward or bait charge',()=>{const s=setup();openValveFixture(s);tick(s,5);shore(s);selectAndCast(s);tick(s,1);expect(s.fishing.phase).toBe('waiting');const saved=captureCampaign(s,defaultSettings());expect(isCampaignSave(saved)).toBe(true);const restored=hydrateCampaign(saved)!.sim;expect(restored).toBeDefined();expect(restored.fishing.snapshot()).toEqual(s.fishing.snapshot());const bait=restored.campaign.state.items['fish-bait'];waitBite(restored);restored.action('interact',idle);expect(restored.campaign.state.items.silverfin).toBe(1);expect(restored.campaign.state.items['fish-bait']).toBe(bait);const caught=captureCampaign(restored,defaultSettings());expect(restoreCampaignInto(restored,caught)).not.toBeNull();restored.action('interact',idle);expect(restored.campaign.state.items.silverfin).toBe(1);expect(restored.campaign.state.items['fish-bait']).toBe(bait);},20000);
});
