import {describe,it,expect} from 'vitest';
import {defaultGamepadSettings,validGamepadSettings,copyGamepadSettings,remapGamepadButton,GAMEPAD_ACTIONS,GAMEPAD_BUTTONS} from '../../src/prototype/gamepad-settings';
describe('gamepad configuration boundary',()=>{
 it('keeps every production default and reserves pause/system buttons',()=>{const settings=defaultGamepadSettings();expect(validGamepadSettings(settings)).toBe(true);expect(settings.buttons).toMatchObject({jump:0,attack:7,block:6,sprint:10,build:15});expect(Object.values(settings.buttons).sort((a,b)=>a-b)).toEqual([...GAMEPAD_BUTTONS]);});
 it('atomically swaps every action with every allowed button without losing an action',()=>{const before=defaultGamepadSettings();for(const action of GAMEPAD_ACTIONS)for(const button of GAMEPAD_BUTTONS){const next=remapGamepadButton(before,action,button)!;expect(validGamepadSettings(next)).toBe(true);expect(next.buttons[action]).toBe(button);expect(new Set(Object.values(next.buttons)).size).toBe(GAMEPAD_ACTIONS.length);}expect(before).toEqual(defaultGamepadSettings());});
 it.each([9,16,-1,17,2.5,NaN,Infinity])('refuses reserved, fractional and invalid button %s',button=>{expect(remapGamepadButton(defaultGamepadSettings(),'attack',button)).toBeNull();});
 it('rejects missing, inherited, duplicate and unknown assignments',()=>{for(const bad of [null,[],{}, {...defaultGamepadSettings(),unknown:1},{...defaultGamepadSettings(),invertY:1}])expect(validGamepadSettings(bad)).toBe(false);const settings=defaultGamepadSettings();settings.buttons.attack=settings.buttons.jump;expect(validGamepadSettings(settings)).toBe(false);const missing=defaultGamepadSettings();Reflect.deleteProperty(missing.buttons,'attack');expect(validGamepadSettings(missing)).toBe(false);const inherited={...defaultGamepadSettings(),buttons:Object.assign(Object.create(defaultGamepadSettings().buttons),{...defaultGamepadSettings().buttons})};Reflect.deleteProperty(inherited.buttons,'attack');inherited.buttons.unknown=7;expect(validGamepadSettings(inherited)).toBe(false);});
 it.each([-.1,0,.049,.401,NaN,Infinity])('rejects unsafe deadzone %s',deadzone=>expect(validGamepadSettings({...defaultGamepadSettings(),deadzone})).toBe(false));
 it('copies maps without exposing live configuration references',()=>{const settings=defaultGamepadSettings(),copy=copyGamepadSettings(settings);copy.buttons.attack=0;copy.deadzone=.3;expect(settings).toEqual(defaultGamepadSettings());});
});
