import {describe,it,expect,vi} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {CampaignRoomSession} from '../../src/prototype/network/game-session';
import {defaultSettings} from '../../src/prototype/campaign-session';
import type {GuestCommand} from '../../src/prototype/network/protocol';
vi.mock('../../src/prototype/core/world',async(importOriginal)=>{const original=await importOriginal<typeof import('../../src/prototype/core/world')>();const {VoxelField}=await import('../../src/prototype/core/voxel');return {...original,createArena:()=>{const field=new VoxelField(.25);field.box({x:-8,y:-.5,z:-8},{x:8,y:.25,z:10},3);return {field,objects:new Map()};}};});
vi.mock('../../src/prototype/campaign-network-state',()=>({captureSharedCampaign:()=>({version:1}),applySharedCampaign:()=>({ok:false})}));
/** Test the session transaction boundary directly; room delivery/dedupe itself is
 * covered by the real two-socket relay tests. No DOM, service or account access. */
function setup(){const sim=new CoreSimulation();sim.enableCompanion();sim.setCompanionConnected(true);const hooks={settings:()=>defaultSettings(),save:vi.fn(()=>true),mode:vi.fn(),notice:vi.fn()};const session=new CampaignRoomSession(sim,hooks,'https://example.test');const client={online:true,hostAck:vi.fn(),disconnect:vi.fn()};const access=session as unknown as {roleValue:string;generation:number;connectionGeneration:number;client:typeof client;guestBuild:boolean;publish:()=>Promise<boolean>;executeGuest:(command:GuestCommand,id:string,generation?:number,connection?:number)=>Promise<void>};access.roleValue='host';access.generation=7;access.client=client;access.publish=vi.fn(async()=>true);return {sim,hooks,session,client,access};}
describe('host session authority boundaries',()=>{
 it('ignores a queued command from an earlier room generation',async()=>{const {sim,access,client}=setup();const before=sim.getCompanionSnapshot();await access.executeGuest({action:'jump',payload:{kind:'action',action:'jump'}},'stale-room-command',6);expect(sim.getCompanionSnapshot()).toEqual(before);expect(client.hostAck).not.toHaveBeenCalled();});
 it('does not trust the outer action label to bypass inner editing permission checks',async()=>{const {sim,access,client}=setup();await access.executeGuest({action:'interact',payload:{kind:'action',action:'cast'}},'forged-action',7);expect(sim.companion!.phase).toBe('idle');expect(client.hostAck).toHaveBeenCalledWith('forged-action',false,expect.any(String));await access.executeGuest({action:'repair',payload:{kind:'menu',command:{type:'homestead',id:'furniture:bed'}}},'forged-home',7);expect(client.hostAck).toHaveBeenCalledWith('forged-home',false,expect.any(String));});
 it('disconnects on persistence failure and never acknowledges durable success',async()=>{const {sim,hooks,access,client}=setup();sim.survival.inventory[4]=6;sim.survival.inventory[7]=4;hooks.save.mockReturnValue(false);await access.executeGuest({action:'craft',payload:{kind:'menu',command:{type:'craft',id:'bow'}}},'unsaved-craft',7);expect(sim.campaign.has('bow')).toBe(true);expect(client.disconnect).toHaveBeenCalledOnce();expect(client.hostAck).not.toHaveBeenCalled();expect(hooks.notice).toHaveBeenCalled();});
 it('blocks rescue aliases from healing a living guest for free',async()=>{const {sim,access,client}=setup();sim.companion!.hp=43;for(const id of ['rescue','rescue:anything'])await access.executeGuest({action:'repair',payload:{kind:'menu',command:{type:'gear',id}}},'rescue-'+id.replace(':','-'),7);expect(sim.companion!.hp).toBe(43);expect(client.hostAck.mock.calls.every(call=>call[1]===false)).toBe(true);});
 it('rejects all commands while the companion is suspended',async()=>{const {sim,access,client}=setup();sim.setCompanionConnected(false);sim.survival.inventory[4]=6;sim.survival.inventory[7]=4;await access.executeGuest({action:'craft',payload:{kind:'menu',command:{type:'craft',id:'bow'}}},'offline-craft',7);expect(sim.campaign.has('bow')).toBe(false);expect(sim.survival.inventory[4]).toBe(6);expect(client.hostAck.mock.calls.some(call=>call[1]===true)).toBe(false);});
});

describe('publication lifecycle fencing',()=>{
 it('does not let an old pending publisher send into a replacement room',async()=>{const {access}=setup();let release!:(value:boolean)=>void;const pending=new Promise<boolean>(resolve=>{release=resolve;});const oldClient={online:true,hostPublish:vi.fn(async()=>true)},newClient={online:true,hostPublish:vi.fn(async()=>true)};Object.assign(access,{client:oldClient,pendingPublish:pending});const method=(CampaignRoomSession.prototype as unknown as {publish:()=>Promise<boolean>}).publish;const operation=method.call(access);Object.assign(access,{generation:8,client:newClient,pendingPublish:null});release(true);await operation;expect(oldClient.hostPublish).not.toHaveBeenCalled();expect(newClient.hostPublish).not.toHaveBeenCalled();});
});

describe('socket reconnect command fence',()=>{
 it('rejects a prior-connection command even when room generation and client identity are unchanged',async()=>{const {sim,access,client}=setup();access.connectionGeneration=2;const before=sim.getCompanionSnapshot();await access.executeGuest({action:'jump',payload:{kind:'action',action:'jump'}},'stale-connection',7,1);expect(sim.getCompanionSnapshot()).toEqual(before);expect(client.hostAck).not.toHaveBeenCalled();});
 it('does not send a completed old-connection command receipt into a reconnected transport',async()=>{const {sim,access,client}=setup();sim.survival.inventory[4]=6;sim.survival.inventory[7]=4;let release!:(value:boolean)=>void;access.publish=()=>new Promise<boolean>(resolve=>{release=resolve;});const pending=access.executeGuest({action:'craft',payload:{kind:'menu',command:{type:'craft',id:'bow'}}},'old-connection-craft',7,0);expect(sim.campaign.has('bow')).toBe(true);access.connectionGeneration=1;release(true);await pending;expect(client.hostAck).not.toHaveBeenCalled();});
});

describe('timer-driven guest heartbeat still obeys freshness and pause boundaries',()=>{
 it('retains the exact three-second frame freshness limit and never sends stale held input',()=>{const {sim,session,access}=setup(),date=vi.spyOn(Date,'now');date.mockReturnValue(10000);const client={online:true,sendInput:vi.fn(()=>true)};Object.assign(access,{roleValue:'guest',ready:true,lastFrameAt:10000,client});const held={x:1,z:0,sprint:true,block:true,water:false};date.mockReturnValue(12999);session.tick(.1,held,true);expect(session.online).toBe(true);expect(client.sendInput).toHaveBeenCalledOnce();expect(session.diagnostics()).toMatchObject({sentInputs:1,frameAgeMs:2999});date.mockReturnValue(13000);session.tick(.1,held,true);expect(session.online).toBe(false);expect(client.sendInput).toHaveBeenCalledOnce();expect(sim.player.position.x).toBe(0);date.mockRestore();});
 it('sends neutral input when paused/hidden instead of queuing held movement',()=>{const {session,access}=setup(),date=vi.spyOn(Date,'now').mockReturnValue(10000),client={online:true,sendInput:vi.fn(()=>true)};Object.assign(access,{roleValue:'guest',ready:true,lastFrameAt:10000,client});session.tick(.1,{x:1,z:1,sprint:true,block:true,water:false},false);expect(client.sendInput).toHaveBeenCalledWith(expect.objectContaining({x:0,z:0,block:false,sprint:false}));date.mockRestore();});
});
