import {describe,it,expect,vi} from 'vitest';
import {startGameLoop,gameLoopPolicy,type GameLoopClock} from '../../src/prototype/game-loop';
function harness(){let time=0,next=0;const frames=new Map<number,()=>void>(),timers=new Map<number,{at:number;run:()=>void}>();const clock:GameLoopClock={now:()=>time,frame:run=>{const id=++next;frames.set(id,run);return id;},cancelFrame:id=>{frames.delete(id);},delay:(run,ms)=>{const id=++next;timers.set(id,{at:time+ms,run});return id as unknown as ReturnType<typeof setTimeout>;},cancelDelay:id=>{timers.delete(id as unknown as number);}};return {clock,frames,timers,jump(ms:number){time+=ms;},frame(){const batch=[...frames.values()];frames.clear();for(const run of batch)run();},advance(ms:number){const until=time+ms;for(;;){const entry=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];if(!entry||entry[1].at>until)break;time=entry[1].at;timers.delete(entry[0]);entry[1].run();}time=until;}};}
describe('cooperative clock independent from compositor delivery',()=>{
 it('advances a party without any RAF callbacks, while retaining one bounded update owner',()=>{const h=harness(),update=vi.fn(),render=vi.fn(),loop=startGameLoop(update,render,()=>true,h.clock);h.advance(1000);expect(update.mock.calls.length).toBeGreaterThanOrEqual(59);expect(render).not.toHaveBeenCalled();const calls=update.mock.calls.length;h.frame();h.frame();expect(update).toHaveBeenCalledTimes(calls);expect(render).toHaveBeenCalledTimes(2);expect(update.mock.calls.every(([dt])=>dt>=0&&dt<=.1)).toBe(true);loop.stop();});
 it('leaves solo simulation RAF-driven and switches clock ownership without double ticking',()=>{const h=harness(),update=vi.fn(),render=vi.fn();let party=false;const loop=startGameLoop(update,render,()=>party,h.clock);h.advance(1000);expect(update).not.toHaveBeenCalled();h.frame();expect(update).toHaveBeenCalledTimes(1);expect(update.mock.calls[0][0]).toBe(.1);party=true;h.advance(20);expect(update).toHaveBeenCalledTimes(2);h.frame();expect(update).toHaveBeenCalledTimes(2);party=false;h.advance(20);expect(update).toHaveBeenCalledTimes(2);h.frame();expect(update).toHaveBeenCalledTimes(3);loop.stop();});
 it('caps catch-up after a blocked main thread, uses fresh time, and reports each phase separately',()=>{const h=harness(),update=vi.fn(()=>h.jump(4)),render=vi.fn(()=>h.jump(12000)),loop=startGameLoop(update,render,()=>true,h.clock);h.frame();expect(loop.stats).toMatchObject({renderMs:12000,maxRenderMs:12000,updates:0});h.jump(5000);const pulse=[...h.timers.values()][0].run;h.timers.clear();pulse();expect(update.mock.calls[0]).toEqual([.1,17000]);expect(loop.stats).toMatchObject({updateGapMs:17000,updateMs:4,maxUpdateMs:4});loop.stop();});
 it('cancels both clocks, including callbacks already queued before disposal',()=>{const h=harness(),update=vi.fn(),render=vi.fn(),loop=startGameLoop(update,render,()=>true,h.clock),frame=[...h.frames.values()][0],pulse=[...h.timers.values()][0].run;loop.stop();loop.stop();frame();pulse();h.advance(10000);expect(update).not.toHaveBeenCalled();expect(render).not.toHaveBeenCalled();expect(h.frames.size).toBe(0);expect(h.timers.size).toBe(0);});
 it('stops both clocks on an update or render error instead of leaving an orphaned timer',()=>{for(const phase of ['update','render']){const h=harness(),fail=()=>{throw Error('failure');},loop=startGameLoop(phase==='update'?fail:()=>{},phase==='render'?fail:()=>{},()=>false,h.clock);expect(()=>h.frame()).toThrow('failure');expect(h.frames.size).toBe(0);expect(h.timers.size).toBe(0);loop.stop();}});
});

describe('unchanged pause, visibility and authority policy',()=>{
 const live={active:true,paused:false,portrait:false,hidden:false,guest:false,hostRunning:false,needsRender:false};
 it('simulates and renders active solo, but stops both on pause',()=>{expect(gameLoopPolicy(live)).toEqual({simulate:true,inputActive:true,render:true});expect(gameLoopPolicy({...live,paused:true})).toEqual({simulate:false,inputActive:false,render:false});});
 it('keeps a menu-open host world running without local controls or drawing',()=>{expect(gameLoopPolicy({...live,paused:true,hostRunning:true})).toEqual({simulate:true,inputActive:false,render:false});});
 it('never runs guest simulation while allowing live guest input/presentation',()=>{expect(gameLoopPolicy({...live,guest:true})).toEqual({simulate:false,inputActive:true,render:true});expect(gameLoopPolicy({...live,guest:true,paused:true})).toEqual({simulate:false,inputActive:false,render:false});});
 it.each(['hidden','portrait'] as const)('stops simulation and guest controls when %s, including menu hosts',key=>{for(const guest of [false,true])for(const paused of [false,true]){const policy=gameLoopPolicy({...live,guest,paused,hostRunning:!guest,[key]:true});expect(policy.simulate).toBe(false);expect(policy.inputActive).toBe(false);expect(policy.render).toBe(false);}});
 it('can repaint a paused visible quality change while still suppressing hidden drawing',()=>{expect(gameLoopPolicy({...live,paused:true,needsRender:true})).toEqual({simulate:false,inputActive:false,render:true});expect(gameLoopPolicy({...live,paused:true,needsRender:true,hidden:true}).render).toBe(false);});
});
