import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {createHearthFlames} from '../../src/prototype/rendering/campaign-decor';
import {REGIONAL_POINTS} from '../../src/prototype/core/regions';
const state={flameTier:0,campUnlocked:false,claimedPoints:[] as string[]};
describe('state-driven persistent hearth flames',()=>{
 it('is dark before activation and does not infer flame from proximity',()=>{const scene=new THREE.Scene(),flames=createHearthFlames(scene);flames.update(true,state,{x:-3,y:.25,z:4},1);expect(scene.getObjectByName('hearth-flame:hearth')?.visible).toBe(false);expect((scene.getObjectByName('hearth-nearest-light') as THREE.PointLight).intensity).toBe(0);flames.dispose();});
 it('lights the activated hearth and persists across fresh rendering layers',()=>{for(let i=0;i<2;i++){const scene=new THREE.Scene(),flames=createHearthFlames(scene);flames.update(true,{...state,flameTier:1},{x:-3,y:.25,z:4},4);expect(scene.getObjectByName('hearth-flame:hearth')?.visible).toBe(true);expect(scene.getObjectByName('hearth-flame:nextcamp')?.visible).toBe(false);expect((scene.getObjectByName('hearth-nearest-light') as THREE.PointLight).intensity).toBeGreaterThan(0);flames.dispose();}});
 it('uses exactly one nearest light for all lit camps and turns it off far away',()=>{const scene=new THREE.Scene(),flames=createHearthFlames(scene),unlocked={...state,flameTier:2,campUnlocked:true};flames.update(true,unlocked,{x:0,y:3.25,z:-31},2);const lights:THREE.PointLight[]=[];scene.traverse(o=>{if(o instanceof THREE.PointLight)lights.push(o);});expect(lights).toHaveLength(1);expect(lights[0].position.z).toBe(-31);expect(scene.getObjectByName('hearth-flame:nextcamp')?.visible).toBe(true);flames.update(true,unlocked,{x:900,y:0,z:900},3);expect(lights[0].intensity).toBe(0);flames.dispose();});
 it('shows regional flames only for actually claimed hearths, and preserves trial appearance',()=>{const scene=new THREE.Scene(),flames=createHearthFlames(scene),point=REGIONAL_POINTS.find(p=>p.kind==='hearth')!;flames.update(true,{...state,claimedPoints:[point.id]},point.position,0);expect(scene.getObjectByName('hearth-flame:'+point.id)?.visible).toBe(true);flames.update(false,{...state,flameTier:2,campUnlocked:true,claimedPoints:[point.id]},point.position,1);expect(scene.getObjectByName('hearth-flame:'+point.id)?.visible).toBe(false);expect(scene.getObjectByName('hearth-flame:hearth')?.visible).toBe(false);flames.dispose();});
 it('reuses shared geometry and disposes the layer once',()=>{const scene=new THREE.Scene(),flames=createHearthFlames(scene),root=scene.getObjectByName('hearth-flames')!,mesh=root.getObjectByName('hearth-flame:hearth')!.children[0] as THREE.Mesh,dispose=vi.fn();mesh.geometry.addEventListener('dispose',dispose);flames.update(true,{...state,flameTier:1},{x:-3,y:0,z:4},10);flames.dispose();flames.dispose();expect(dispose).toHaveBeenCalledTimes(1);expect(scene.getObjectByName('hearth-flames')).toBeUndefined();});
});
