import {it,expect,vi} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,restoreCampaignInto,defaultSettings} from '../../src/prototype/campaign-session';
import {captureGameFrame,applyGameFrame,validGameFrame} from '../../src/prototype/network/game-frame';
const idle={x:0,z:0,sprint:false,block:false,water:false};
const tick=(s:CoreSimulation,n:number)=>{for(let i=0;i<Math.ceil(n*30);i++)s.tick(1/30,idle);};
function aim(s:CoreSimulation){const p=s.animal.position,e=s.eye(),yaw=Math.atan2(-(p.x-e.x),-(p.z-e.z)),pitch=Math.atan2(p.y+.7-e.y,Math.hypot(p.x-e.x,p.z-e.z));s.look(-(yaw-s.player.yaw),s.player.pitch-pitch);}
function setup(){const s=new CoreSimulation(true,false,true);s.campaign.state.flameTier=1;s.survival.inventory[7]=10;s.player.position={x:-4.4,y:.25,z:3.7};tick(s,.5);aim(s);expect(s.target()?.animal).toBe(true);return s;}
it('real aimed animal interaction uses canonical costs, waits for production and persists actual motion',()=>{const s=setup();s.action('interact',idle);expect(s.home.state.animal.tamed).toBe(true);expect(s.survival.inventory[7]).toBe(2);s.action('interact',idle);expect(s.survival.inventory[7]).toBe(0);expect(s.home.state.animal.remaining).toBe(45);tick(s,45.1);aim(s);expect(s.target()?.animal).toBe(true);s.action('interact',idle);expect(s.campaign.state.items.milk).toBe(1);s.action('interact',idle);expect(s.campaign.state.items.milk).toBe(1);const saved=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,saved)).not.toBeNull();expect(s.home.snapshot()).toEqual(saved.home);expect(s.animal.position).toEqual(saved.home.animal.physical!.position);});
it('tool/cast contacts never use virtual animal cells for world damage or create protected-body resources',()=>{const s=setup(),damage=vi.spyOn(s.elements,'damage'),revision=s.arena.field.revision,materials={...s.survival.inventory};s.action('chisel',idle);s.action('heavy',idle);tick(s,1.2);for(let i=0;i<90&&s.player.phase!=='idle';i++)s.tick(1/30,idle);expect(s.player.phase).toBe('idle');expect(damage).not.toHaveBeenCalled();expect(s.arena.field.revision).toBe(revision);expect(s.survival.inventory).toEqual(materials);expect(s.survival.drops).toEqual([]);aim(s);expect(s.target(7)?.animal).toBe(true);s.action('cast',idle);expect(s.player.phase).toBe('cast');tick(s,.2);expect(s.animal.state.burning).toBeGreaterThan(0);expect(s.arena.field.revision).toBe(revision);tick(s,.6);s.action('element-next',idle);aim(s);s.action('cast',idle);tick(s,.2);expect(s.animal.state.burning).toBe(0);expect(s.animal.state.wet).toBeGreaterThan(0);expect(s.survival.inventory).toEqual(materials);damage.mockRestore();});
it('guest frames move the protected actor without ticking its physics or replacing production inventory',()=>{const host=setup();host.enableCompanion();tick(host,.5);const frame=captureGameFrame(host),client=new CoreSimulation(true,false,true);client.campaign.state.items.milk=2;expect(applyGameFrame(client,frame)).not.toBeNull();expect(client.animal.state).toEqual(frame.animal);expect(client.campaign.state.items.milk).toBe(2);frame.animal!.position.x=100;expect(validGameFrame(frame,client.enemies.length)).toBe(false);});
