import { objectOcclusion } from '../../src/game/voxel/occlusion';
import { expect,it } from 'vitest';
import { GameSimulation } from '../../src/simulation/game-simulation';
import { assertInteractionReach } from '../../src/game/interaction/reach';
import { interactionTarget } from '../../src/game/interaction/target';
import { buildingPose,buildingVoxels,carveVoxels } from '../../src/game/voxel/model';
function fixture(){const sim=new GameSimulation();sim.adventure.state.buildings=[];sim.adventure.state.enemies=[];sim.adventure.state.resources=[{id:10,kind:'branch',amount:2,ready:0,x:0,y:10,z:0}];Object.assign(sim.player,{x:0,y:10,z:3});sim.world.density=p=>p.y-9;return sim;}
it('rejects a forged nearby hit point for a different selected resource',()=>{const sim=fixture();expect(()=>sim.adventure.action('interact','r:10',{x:2,y:10,z:2})).toThrow('照準');expect(sim.adventure.state.resources[0].ready).toBe(0);});
it('rechecks solid walls on the authority but permits a carved opening',()=>{const sim=fixture(),s=sim.adventure.state;s.buildings=[{id:20,definition:'wall',x:0,y:10,z:1.5,rotation:0,support:4,contents:{}}];const point={x:0,y:10.4,z:0};expect(()=>assertInteractionReach(s,sim.player,'r:10',point,p=>sim.world.density(p))).toThrow('建物');const b=s.buildings[0];b.removed=[];carveVoxels(buildingVoxels('wall'),{x:0,y:.6,z:0},.7,b.removed);expect(()=>assertInteractionReach(s,sim.player,'r:10',point,p=>sim.world.density(p))).not.toThrow();});
it('rejects interactions through a live tree',()=>{const sim=fixture(),s=sim.adventure.state;s.resources.push({id:30,kind:'beech',amount:1,ready:0,x:0,y:10,z:1.5});expect(()=>assertInteractionReach(s,sim.player,'r:10',{x:0,y:10.4,z:0},p=>sim.world.density(p))).toThrow('木');});
it('targets an open door at its visible hinge position and clears the original opening',()=>{const sim=fixture(),g=sim.adventure;g.state.resources=[];const door={id:20,definition:'door',x:0,y:10,z:0,rotation:0,support:4,contents:{},open:true};g.state.buildings=[door];const pose=buildingPose(door);expect(pose.rotation).toBeCloseTo(Math.PI/2);expect(pose.x).toBeCloseTo(-.5);expect(pose.z).toBeCloseTo(-.5);expect(interactionTarget(g.snapshot(),sim.player,{x:0,y:11,z:3},{x:0,y:0,z:-1})).toBeNull();Object.assign(sim.player,{x:1,y:10,z:-.5});expect(interactionTarget(g.snapshot(),sim.player,{x:2,y:11,z:-.5},{x:-1,y:0,z:0})?.id).toBe('b:20');});
it('uses visible voxel boundaries when resolving player wall contact',()=>{const sim=fixture(),g=sim.adventure;g.state.resources=[];g.state.buildings=[{id:20,definition:'wall',x:0,y:10,z:0,rotation:0,support:4,contents:{}}];Object.assign(sim.player,{x:0,y:10,z:.4,vy:0});g.collidePlayer(10);expect(sim.player.z).toBeCloseTo(.425);const before=sim.player.z;g.collidePlayer(10);expect(sim.player.z).toBeCloseTo(before);});
it('lets the player pass through an intact voxel portal opening',()=>{const sim=fixture(),g=sim.adventure;g.state.resources=[];g.state.buildings=[{id:20,definition:'portal',x:0,y:10,z:0,rotation:0,support:4,contents:{}}];Object.assign(sim.player,{x:0,y:10,z:0,vy:0});g.collidePlayer(10);expect(sim.player.x).toBe(0);expect(sim.player.z).toBe(0);});

it('stops the third-person camera at occupied walls and lets it see through carved holes',()=>{const sim=fixture(),s=sim.adventure.state;s.resources=[];const b={id:20,definition:'wall',x:0,y:10,z:0,rotation:0,support:4,contents:{},removed:[] as string[]};s.buildings=[b];const eye={x:0,y:11,z:2},ray={x:0,y:0,z:-1};expect(objectOcclusion(s,eye,ray,5)).toBeGreaterThanOrEqual(1.875);expect(objectOcclusion(s,eye,ray,5)).toBeLessThanOrEqual(1.9375);carveVoxels(buildingVoxels('wall'),{x:0,y:1,z:0},.7,b.removed);expect(objectOcclusion(s,eye,ray,5)).toBe(5);});
