import {describe,it,expect} from 'vitest';
import {CampaignSystem} from '../../src/prototype/core/campaign';
import {HomesteadSystem,STORAGE_CAPACITY,type HomesteadContext} from '../../src/prototype/core/homestead';
import {homesteadRows} from '../../src/prototype/homestead-presenter';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {executeGameCommand,isGameCommand} from '../../src/prototype/campaign-commands';
import {captureCampaign,defaultSettings,restoreCampaignInto} from '../../src/prototype/campaign-session';
const ctx:HomesteadContext={position:{x:0,y:.25,z:0},basePosition:{x:0,y:.25,z:0},baseActive:true,artisanRescued:true};
describe('specified material and ordinary item storage',()=>{
 it('conserves exact food, herbs, arrows and numeric material amounts; matching bulk leaves other kinds alone',()=>{const c=new CampaignSystem({4:30,3:10,7:20});c.state.flameTier=1;c.state.items.herbs=7;expect(c.craft('arrows',ctx.position,2).ok).toBe(true);const h=new HomesteadSystem(c.materials,c.state.items);c.state.items['berry-meal']=4;
  for(const [id,count] of [[4,2],['arrows',5],['herbs',3],['berry-meal',2]] as const)expect(h.deposit(id,count,ctx).ok).toBe(true);expect(h.state.storage).toEqual({materials:{4:2},items:{arrows:5,herbs:3,'berry-meal':2}});
  const before={stone:c.materials[3],grass:c.materials[7]};expect(h.depositMatching(ctx).ok).toBe(true);expect(c.materials[4]).toBe(0);expect(c.state.items.arrows).toBe(0);expect(h.state.storage.items.arrows).toBe(16);expect(c.materials[3]).toBe(before.stone);expect(c.materials[7]).toBe(before.grass);
  for(const [id,count] of [[4,7],['arrows',9],['herbs',2],['berry-meal',3]] as const)expect(h.withdraw(id,count,ctx).ok).toBe(true);expect(c.state.items.arrows+h.state.storage.items.arrows).toBe(16);expect(c.state.items.herbs+h.state.storage.items.herbs).toBe(7);expect(c.state.items['berry-meal']+h.state.storage.items['berry-meal']).toBe(4);
 });
 it('rejects gear and irreplaceable items before escrow can be lost, retaining exact wear and sockets',()=>{const c=new CampaignSystem({4:20,3:20,7:10});expect(c.craft('dagger',ctx.position).ok).toBe(true);c.equip('dagger');c.state.gearState.dagger.durability=41;c.state.items['mist-core']=1;const h=new HomesteadSystem(c.materials,c.state.items),before=c.snapshot();for(const id of ['dagger','mist-core'])expect(h.deposit(id,1,ctx).ok).toBe(false);expect(c.snapshot()).toEqual(before);expect(h.storedCount).toBe(0);expect(homesteadRows(h,ctx).some(r=>r.id==='deposit:item:dagger')).toBe(false);});
 it('keeps display reservations and full storage failure atomic during transfers and matching bulk',()=>{const h=new HomesteadSystem({4:20},{herbs:3,arrows:8});h.state.storage.items.herbs=1;h.reservedItemCount=id=>id==='herbs'?1:0;expect(h.withdraw('herbs',1,ctx).ok).toBe(false);expect(h.deposit('herbs',2,ctx).ok).toBe(true);expect(h.withdraw('herbs',2,ctx).ok).toBe(true);expect(h.state.storage.items.herbs).toBe(1);expect(homesteadRows(h,ctx).find(r=>r.id==='withdraw:item:herbs')?.transfer?.maxCount).toBe(0);expect(h.depositMatching(ctx).ok).toBe(true);expect(h.state.storage.items.herbs).toBe(4);expect(h.withdraw('herbs',3,ctx).ok).toBe(true);expect(h.state.storage.items.herbs).toBe(1);h.state.storage.materials[4]=STORAGE_CAPACITY-1;const before=JSON.stringify([h.snapshot(),h.materials,h.items]);expect(h.depositMatching(ctx).ok).toBe(false);expect(h.deposit('arrows',1,ctx).ok).toBe(false);expect(JSON.stringify([h.snapshot(),h.materials,h.items])).toBe(before);});
 it('rejects invalid quantity, distance, unlit base and item capacity atomically',()=>{const h=new HomesteadSystem({4:10},{milk:20});h.state.storage.items.milk=3;for(const n of [0,-1,.5,NaN,Infinity])expect(h.deposit('milk',n,ctx).ok).toBe(false);expect(h.withdraw('milk',1,ctx).ok).toBe(false);expect(h.deposit('milk',1,{...ctx,baseActive:false}).ok).toBe(false);expect(h.deposit('milk',1,{...ctx,position:{x:10,y:.25,z:0}}).ok).toBe(false);expect(h.items.milk).toBe(20);expect(h.state.storage.items.milk).toBe(3);});
});
describe('inventory runtime save and command transactions',()=>{
 it('revalidates exact count commands, rejects double activation and uses live companion location/permission',()=>{const s=new CoreSimulation(true,false,true);s.campaign.state.flameTier=1;s.campaign.state.items.arrows=16;const command={type:'storage' as const,id:'deposit:item:arrows',count:5,revision:s.campaign.inventory.reconcile().revision,stored:0};expect(isGameCommand(command)).toBe(true);expect(executeGameCommand(s,command).ok).toBe(true);expect(executeGameCommand(s,command).ok).toBe(false);expect(s.campaign.state.items.arrows).toBe(11);expect(s.home.state.storage.items.arrows).toBe(5);const guest=s.enableCompanion({x:0,y:.25,z:6});const withdraw=()=>({type:'storage' as const,id:'withdraw:item:arrows',count:3,revision:s.campaign.inventory.reconcile().revision,stored:s.home.storedCount});expect(s.withCompanion(()=>executeGameCommand(s,withdraw()))?.ok).toBe(false);s.companionCanEdit=true;guest.position.x=40;expect(s.withCompanion(()=>executeGameCommand(s,withdraw()))?.ok).toBe(false);guest.position={x:-3,y:.25,z:5.3};expect(s.withCompanion(()=>executeGameCommand(s,withdraw()))?.ok).toBe(true);expect(s.campaign.state.items.arrows).toBe(14);expect(s.home.state.storage.items.arrows).toBe(2);guest.hp=0;expect(s.withCompanion(()=>executeGameCommand(s,withdraw()))?.ok).toBe(false);});
 it('atomically restores layouts, storage and drops and refuses malformed components and impossible locations',()=>{const s=new CoreSimulation(true,false,true);s.survival.inventory[4]=20;s.campaign.state.items.arrows=16;s.campaign.state.flameTier=1;const i=s.campaign.inventory;const slot=i.reconcile().slots.findIndex(x=>x?.key==='item:arrows');expect(executeGameCommand(s,{type:'inventory',id:'drop',revision:i.state.revision,slot,count:5}).ok).toBe(true);const saved=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,saved)).not.toBeNull();expect(s.campaign.inventory.state.drops[0].count).toBe(5);const before=captureCampaign(s,defaultSettings());for(const mutate of [(data:typeof saved)=>{data.campaign.inventory!.slots[0]!.count=-1;},(data:typeof saved)=>{data.campaign.inventory!.drops[0].position.x=900;},(data:typeof saved)=>{data.campaign.inventory!.drops[0].key='item:fake';},(data:typeof saved)=>{data.home.storage.items.arrows=-1;}]){const bad=structuredClone(saved);bad.survival.inventory[4]=999;mutate(bad);expect(restoreCampaignInto(s,bad)).toBeNull();expect(captureCampaign(s,defaultSettings())).toEqual(before);}const old=structuredClone(saved);old.campaign.items.arrows+=5;delete old.campaign.inventory;expect(restoreCampaignInto(s,old)).not.toBeNull();expect(s.campaign.state.items.arrows).toBe(16);expect(s.campaign.inventory.state.drops).toEqual([]);});
});
