import {it,expect} from 'vitest';
import {NormalPlayer} from './helpers/normal-campaign-player';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {captureCampaign,hydrateCampaign,defaultSettings} from '../../src/prototype/campaign-session';
it('earned wood/stone/leaves, cooked meals, crafted arrows and grown herbs support exact stack/storage/drop/reload workflows',()=>{
 const d=new NormalPlayer(),s=d.sim;d.walk(-.55,6.15);d.act('chisel');d.harvest(4,16,[{x:-1.7,y:.58,z:6.25},{x:-1.7,y:.58,z:6.95},{x:-2.2,y:.58,z:6.25}],'sample-wood');d.walk(-.55,5.25);d.walk(-3.45,5.25);d.walk(-3.45,6.35);d.harvest(3,10,[{x:-4.2,y:.55,z:6.8},{x:-4.5,y:.55,z:6.8},{x:-4.5,y:.65,z:6.5}],'sample-stone');d.walk(-3.45,6.65);d.harvest(7,14,[{x:-3.45,y:.5,z:7.9},{x:-3.1,y:.5,z:7.9},{x:-3.8,y:.5,z:7.9}],'sample-grass');d.walk(-3.45,5.3);d.interact('hearth',{x:-3,y:.9,z:4});
 for(const id of ['arrows','berry-meal'])expect(executeGameCommand(s,{type:'craft',id,count:2}).ok).toBe(true);expect(s.campaign.state.items.arrows).toBe(16);expect(s.campaign.state.items['berry-meal']).toBe(2);
 d.walk(0,5.3);for(let n=0;n<4&&s.survival.inventory[2]<1;n++){d.look({x:0,y:.15,z:4.2});d.act('heavy');d.idle();d.advance(.5);}expect(s.survival.inventory[2]).toBeGreaterThan(0);d.menu('homestead','seed');d.menu('homestead','plant:0');d.advance(60.1);d.menu('homestead','harvest:0');expect(s.campaign.state.items.herbs).toBe(3);
 const transfer=(id:string,count:number)=>{const cmd={type:'storage' as const,id,count,revision:s.campaign.inventory.reconcile().revision,stored:s.home.storedCount};expect(executeGameCommand(s,cmd).ok,id).toBe(true);expect(executeGameCommand(s,cmd).ok,'duplicate '+id).toBe(false);};
 transfer('deposit:4',2);transfer('deposit:item:arrows',5);transfer('deposit:item:berry-meal',1);transfer('deposit:item:herbs',2);transfer('withdraw:item:herbs',1);transfer('withdraw:item:arrows',3);expect(s.home.state.storage.items).toMatchObject({herbs:1,arrows:2,'berry-meal':1});
 const inv=s.campaign.inventory,arrowSlot=inv.reconcile().slots.findIndex(x=>x?.key==='item:arrows'),before=s.campaign.state.items.arrows;expect(executeGameCommand(s,{type:'inventory',id:'split',slot:arrowSlot,target:95,count:3,revision:inv.state.revision}).ok).toBe(true);expect(executeGameCommand(s,{type:'inventory',id:'drop',slot:95,count:3,revision:inv.state.revision}).ok).toBe(true);d.advance(1);const bundle=inv.state.drops[0];d.interact('inventory-drop:'+bundle.id,bundle.position);expect(s.campaign.state.items.arrows).toBe(before);expect(inv.state.drops).toEqual([]);
 const mealSlot=inv.reconcile().slots.findIndex(x=>x?.key==='item:berry-meal');expect(executeGameCommand(s,{type:'inventory',id:'drop',slot:mealSlot,count:1,revision:inv.state.revision}).ok).toBe(true);const save=captureCampaign(s,defaultSettings()),loaded=hydrateCampaign(save);expect(loaded).not.toBeNull();expect(loaded!.sim.home.snapshot()).toEqual(s.home.snapshot());expect(loaded!.sim.campaign.inventory.snapshot()).toEqual(inv.snapshot());const restored=loaded!.sim;expect(executeGameCommand(restored,{type:'inventory',id:'pickup',target:inv.state.drops[0].id,count:1,revision:restored.campaign.inventory.state.revision}).ok).toBe(true);expect(restored.campaign.state.items['berry-meal']+restored.home.state.storage.items['berry-meal']).toBe(2);expect(restored.campaign.state.deaths).toBe(0);
},45000);
