import {describe,it,expect} from 'vitest';
import {CampaignSystem,validCampaignState} from '../../src/prototype/core/campaign';
import {VoxelField} from '../../src/prototype/core/voxel';
import {INVENTORY_SLOTS,INVENTORY_DROPS,validInventoryState,type InventoryCommand,type InventoryState} from '../../src/prototype/core/inventory';
import {isGameCommand} from '../../src/prototype/campaign-commands';
import {inventoryCount} from '../../src/prototype/inventory-view';
import {equipmentComparison} from '../../src/prototype/inventory-presenter';
const actor={x:0,y:.25,z:0};
function setup(){const c=new CampaignSystem({2:0,3:30,4:300,6:0,7:40,10:0}),field=new VoxelField();field.box({x:-3,y:-.5,z:-3},{x:3,y:.25,z:3},3);expect(c.craft('arrows',actor,2).ok).toBe(true);return {c,field};}
const slot=(c:CampaignSystem,key:string)=>c.inventory.reconcile().slots.findIndex(s=>s?.key===key);
function execute(c:CampaignSystem,field:VoxelField,id:InventoryCommand['id'],extra:Partial<InventoryCommand>={}){return c.inventory.execute({type:'inventory',id,revision:c.inventory.reconcile().revision,...extra},actor,field);}
const totals=(c:CampaignSystem)=>JSON.stringify([c.materials,c.state.items]);
describe('bounded inventory stacks over canonical quantities',()=>{
 it('splits, combines selected amounts, moves, and sorts without minting or spending items',()=>{const {c,field}=setup(),before=totals(c),wood=slot(c,'material:4');expect(execute(c,field,'split',{slot:wood,target:90,count:7}).ok).toBe(true);expect(c.inventory.state.slots[90]).toEqual({key:'material:4',count:7});expect(execute(c,field,'combine',{slot:90,target:wood,count:3}).ok).toBe(true);expect(c.inventory.state.slots[90]?.count).toBe(4);expect(execute(c,field,'move',{slot:90,target:80,count:4}).ok).toBe(true);expect(c.inventory.state.slots[90]).toBeNull();expect(c.inventory.state.slots[80]?.count).toBe(4);expect(execute(c,field,'sort').ok).toBe(true);expect(c.inventory.state.slots.filter(s=>s?.key==='material:4')).toHaveLength(1);expect(totals(c)).toBe(before);});
 it('reconciles crafting, ammunition use and old saves without changing authoritative quantities',()=>{const {c,field}=setup();expect(execute(c,field,'split',{slot:slot(c,'item:arrows'),target:95,count:6}).ok).toBe(true);expect(c.consumeAmmo(12)).toBe(true);c.inventory.reconcile();expect(c.inventory.state.slots[95]).toBeNull();expect(c.inventory.state.slots.filter(s=>s?.key==='item:arrows').reduce((n,s)=>n+s!.count,0)).toBe(4);const old=c.snapshot();delete old.inventory;const restored=new CampaignSystem({...c.materials});expect(restored.restore(old)).toBe(true);expect(restored.state.items).toEqual(c.state.items);expect(restored.materials).toEqual(c.materials);expect(restored.inventory.state.slots.some(s=>s?.key==='item:arrows'&&s.count===4)).toBe(true);});
 it('rejects stale double activation and invalid quantities, targets and wrong-kind combinations',()=>{const {c,field}=setup(),wood=slot(c,'material:4'),revision=c.inventory.state.revision;const cmd:InventoryCommand={type:'inventory',id:'split',slot:wood,target:95,count:3,revision};expect(c.inventory.execute(cmd,actor,field).ok).toBe(true);const before=c.snapshot();expect(c.inventory.execute(cmd,actor,field).ok).toBe(false);for(const count of [0,-1,.5,Infinity,NaN,1e9+1])expect(execute(c,field,'drop',{slot:wood,count}).ok).toBe(false);for(const target of [-1,96,NaN,wood])expect(execute(c,field,'move',{slot:wood,target,count:1}).ok).toBe(false);expect(execute(c,field,'combine',{slot:wood,target:slot(c,'item:arrows'),count:1}).ok).toBe(false);expect(c.snapshot()).toEqual(before);});
 it('keeps a full slot layout bounded, denies a pickup needing a new slot and compacts new external rewards',()=>{const {c,field}=setup();expect(execute(c,field,'drop',{slot:slot(c,'item:arrows'),count:16}).ok).toBe(true);const wood=slot(c,'material:4');while(c.inventory.state.slots.includes(null))expect(execute(c,field,'split',{slot:wood,target:c.inventory.state.slots.indexOf(null),count:1}).ok).toBe(true);expect(c.inventory.state.slots.filter(Boolean)).toHaveLength(INVENTORY_SLOTS);const before=c.snapshot();expect(execute(c,field,'pickup',{target:1,count:1}).ok).toBe(false);expect(c.snapshot()).toEqual(before);expect(execute(c,field,'split',{slot:wood,target:95,count:1}).ok).toBe(false);c.state.items.herbs=3;const held=totals(c);c.inventory.reconcile();expect(c.inventory.state.slots.filter(Boolean).length).toBeLessThan(INVENTORY_SLOTS);expect(totals(c)).toBe(held);expect(execute(c,field,'pickup',{target:1,count:16}).ok).toBe(true);expect(c.state.items.arrows).toBe(16);});
 it('has strictly finite persistent bundles and quantity-conserving partial pickups',()=>{const {c,field}=setup(),initial=c.materials[4];for(let i=0;i<INVENTORY_DROPS;i++)expect(execute(c,field,'drop',{slot:slot(c,'material:4'),count:i===0?3:1}).ok).toBe(true);const before=c.snapshot();expect(execute(c,field,'drop',{slot:slot(c,'material:4'),count:1}).ok).toBe(false);expect(c.snapshot()).toEqual(before);for(let i=0;i<30;i++)c.inventory.tick(.1,field);const first=c.inventory.state.drops[0];expect(first.position.y).toBeLessThan(first.origin.y);expect(field.distance(first.position)).toBeGreaterThanOrEqual(.12);expect(execute(c,field,'pickup',{target:first.id,count:2}).ok).toBe(true);expect(first.count).toBe(1);const saved=c.snapshot(),restored=new CampaignSystem({...c.materials});expect(restored.restore(saved)).toBe(true);expect(restored.inventory.snapshot()).toEqual(c.inventory.snapshot());for(const d of [...restored.inventory.state.drops])expect(execute(restored,field,'pickup',{target:d.id,count:d.count}).ok).toBe(true);expect(restored.materials[4]).toBe(initial);expect(restored.inventory.state.drops).toEqual([]);expect(execute(restored,field,'pickup',{target:1,count:1}).ok).toBe(false);});
 it('refuses drop/pickup through solids and protects equipment and quest items',()=>{const {c,field}=setup();expect(c.craft('bow',actor).ok).toBe(true);c.equip('bow');c.state.items['mist-core']=1;for(const key of ['item:bow','item:mist-core'])expect(execute(c,field,'drop',{slot:slot(c,key),count:1}).ok).toBe(false);expect(execute(c,field,'drop',{slot:slot(c,'item:arrows'),count:4}).ok).toBe(true);field.box({x:-.4,y:.6,z:-.5},{x:.4,y:2,z:-.25},3,'wall');const before=c.snapshot();expect(execute(c,field,'pickup',{target:1,count:4}).ok).toBe(false);expect(execute(c,field,'drop',{slot:slot(c,'item:arrows'),count:1}).ok).toBe(false);expect(c.snapshot()).toEqual(before);field.removeObject('wall');c.state.items.arrows=200;const full=c.snapshot();expect(execute(c,field,'pickup',{target:1,count:1}).ok).toBe(false);expect(c.snapshot()).toEqual(full);});
 it('rejects malformed layouts/drops atomically, including sparse arrays and unbounded or duplicate bundles',()=>{const {c,field}=setup();execute(c,field,'drop',{slot:slot(c,'item:arrows'),count:4});const saved=c.snapshot(),before=totals(c),mutations:((s:InventoryState)=>void)[]=[s=>{s.slots[0]!.count=-1;},s=>{s.slots[0]!.key='item:missing';},s=>{delete s.slots[3];},s=>{s.slots.push(null);},s=>{s.drops.push({...s.drops[0]});},s=>{s.drops[0].position.x=Infinity;},s=>{s.drops[0].vy=100;},s=>{s.drops[0].count=.5;},s=>{s.drops[0].key='item:mist-core';},s=>{s.nextDropId=1;},s=>{delete s.drops[0];},s=>{s.slots[90]={key:'item:arrows',count:200};}];for(const mutate of mutations){const bad=structuredClone(saved);mutate(bad.inventory!);expect(validInventoryState(bad.inventory)).toBe(false);expect(c.restore(bad)).toBe(false);expect(c.snapshot()).toEqual(saved);expect(totals(c)).toBe(before);}expect(validInventoryState(Object.assign(Object.create(saved.inventory!),{a:1,b:2,c:3,d:4,e:5}))).toBe(false);expect(validCampaignState(saved)).toBe(true);});
 it('compares actual selected versus equipped numeric modifiers without mutating state',()=>{const {c}=setup();c.craft('dagger',actor);c.craft('bow',actor);c.equip('dagger');c.state.gearState.bow.durability=0;const before=c.snapshot(),text=equipmentComparison(c,'bow');expect(text).toContain('通常攻撃 20→14');expect(text).toContain('矢威力 0→14');expect(text).toContain('耐久 0/100');expect(c.snapshot()).toEqual(before);});
});
describe('inventory wire and count boundaries',()=>{
 it('accepts only exact typed commands and finite integer amounts',()=>{const cmd={type:'inventory',id:'split',slot:0,target:1,count:2,revision:3};expect(isGameCommand(cmd)).toBe(true);expect(isGameCommand({...cmd,materials:{4:100}})).toBe(false);expect(isGameCommand({...cmd,count:'2'})).toBe(false);expect(isGameCommand({...cmd,revision:-1})).toBe(false);expect(isGameCommand({...cmd,id:'unknown'})).toBe(false);expect(isGameCommand(Object.create(cmd))).toBe(false);expect(isGameCommand({type:'inventory',id:'sort',revision:0})).toBe(true);expect(isGameCommand({type:'inventory',id:'sort',revision:0,count:1})).toBe(false);expect(isGameCommand({type:'storage',id:'deposit:item:herbs',count:2,revision:3,stored:0})).toBe(true);expect(isGameCommand({type:'storage',id:'deposit:item:__proto__',count:2,revision:3,stored:0})).toBe(false);});
 it.each(['',' ','0','-1','1.1','NaN','Infinity','21'])('rejects invalid UI count %j',value=>expect(inventoryCount(value,20)).toBeNull());
});
