import { pickupItem } from '../../src/game/interaction/drops';
import { describe,it,expect } from 'vitest';
import { GameSimulation } from '../../src/simulation/game-simulation';
import { validateSave } from '../../src/save/format';
import { foodStats,newMeadows } from '../../src/game/meadows/state';
import { legacySimulation } from '../helpers/legacy';
import { SessionAuthority } from '../../src/simulation/session';
function at(sim:GameSimulation,kind:string){const n=sim.adventure.state.resources.find(n=>n.kind===kind)!;Object.assign(sim.player,{x:n.x,y:n.y,z:n.z});return n;}
function workshop(sim:GameSimulation){const p=sim.player;sim.adventure.state.buildings.push({id:sim.allocateEntityId(),definition:'bench',x:p.x+2,y:p.y,z:p.z,rotation:0,support:4,contents:{}},{id:sim.allocateEntityId(),definition:'roof',x:p.x+2,y:p.y+2.5,z:p.z,rotation:0,support:4,contents:{}});}
describe('Meadows survival',()=>{
 it('starts with three food slots, wildlife and natural moving water, keeps old saves',()=>{const sim=new GameSimulation();expect(sim.world.generator).toBe(3);expect(sim.adventure.state.health).toBe(25);expect(sim.adventure.state.enemies.some(e=>e.definition==='deer')).toBe(true);expect(sim.fluid.snapshot().length).toBeGreaterThan(0);expect(legacySimulation().adventure.state.meadows).toBeUndefined();expect(validateSave(sim.save()).generator).toBe(3);});
 it('gathers branches and fells trees into persistent physical logs before yielding timber',()=>{const sim=new GameSimulation(),g=sim.adventure;at(sim,'branch');g.action('gather');expect(g.state.inventory.wood).toBeGreaterThan(0);const tree=at(sim,'beech');g.state.resources=[tree];expect(()=>g.action('gather')).toThrow('斧');Object.assign(g.state.inventory,{wood:5,stone:4});g.action('craft','axe');for(let i=0;i<4;i++)g.action('gather');expect(g.state.inventory.wood).toBe(0);expect(tree.kind).toBe('stump');expect(g.state.resources.some(n=>n.log)).toBe(true);expect(g.state.meadows!.durability.axe).toBe(96);expect(validateSave(sim.save()).adventure!.resources.some(n=>n.log)).toBe(true);});
 it('requires a sheltered workshop and consumes ammunition only with stamina',()=>{const sim=new GameSimulation(),g=sim.adventure;Object.assign(g.state.inventory,{wood:40,leatherScraps:8});expect(()=>g.action('craft','crudeBow')).toThrow('作業台');workshop(sim);g.action('craft','crudeBow');expect(()=>g.action('attack')).toThrow('矢');g.action('craft','woodArrow');g.state.stamina=0;expect(()=>g.action('attack')).toThrow('スタミナ');expect(g.state.inventory.woodArrow).toBe(20);g.state.stamina=50;g.action('attack');expect(g.state.inventory.woodArrow).toBe(19);expect(g.projectiles.length).toBe(1);});
 it('cooks food over fueled fire, burns unattended food and applies three independent buffs',()=>{const sim=new GameSimulation(),g=sim.adventure,p=sim.player;g.state.buildings=[];g.state.buildings.push({id:sim.allocateEntityId(),definition:'fire',x:p.x,y:p.y,z:p.z,rotation:0,support:4,contents:{},fuel:200},{id:sim.allocateEntityId(),definition:'cook',x:p.x,y:p.y+.7,z:p.z,rotation:0,support:4,contents:{}});g.state.inventory.deerMeat=2;g.action('cook','deerMeat');g.meadowRules.step(26);g.action('cook');expect(g.state.inventory.cookedDeer).toBe(1);g.action('cook','deerMeat');g.meadowRules.step(51);g.action('cook');expect(g.state.inventory.coal).toBe(1);Object.assign(g.state.inventory,{berry:2,mushroom:1,honey:1});for(const id of ['cookedDeer','berry','mushroom'])g.action('eat',id);expect(foodStats(g.state).health).toBe(82);expect(()=>g.action('eat','honey')).toThrow('3種類');expect(()=>g.action('eat','berry')).toThrow('同じ');expect(validateSave(sim.save()).adventure!.meadows!.foods).toHaveLength(3);});
 it('summons, defeats, offers and unlocks the antler pickaxe',()=>{const sim=new GameSimulation(),g=sim.adventure;at(sim,'altar');expect(()=>g.action('summon')).toThrow('トロフィー');g.state.inventory.deerTrophy=2;g.action('summon');const e=g.state.enemies.find(e=>e.boss)!;expect(e.health).toBe(500);e.health=1;e.x=sim.player.x;e.z=sim.player.z-1;e.y=sim.player.y;g.action('attack');g.stepPersonal(.4);for(const n of [...g.state.resources])if(n.drop&&Math.hypot(n.x-sim.player.x,n.z-sim.player.z)<3.5)pickupItem(g,n.id);expect(g.state.inventory.hardAntler).toBe(3);expect(g.state.defeated).toContain('stormstag');at(sim,'sacrifice');g.action('gather');g.action('power');expect(g.state.meadows!.power).toBe(300);workshop(sim);g.state.inventory.wood=10;g.action('craft','antlerPickaxe');expect(g.state.inventory.antlerPickaxe).toBe(1);expect(new GameSimulation(validateSave(sim.save())).adventure.state.meadows!.offered).toBe(true);});
 it('persists deaths, consumes fuel once with guests and rejects corrupt food',()=>{const authority=new SessionAuthority(),g=authority.sim.adventure;g.state.inventory.wood=10;g.hurtPlayer(1000,'physical');expect(g.state.grave!.wood).toBe(10);expect(g.state.inventory.wood).toBe(0);const save=authority.sim.save();save.adventure!.meadows=newMeadows();save.adventure!.meadows.foods=[{id:'berry',remaining:NaN}];expect(()=>validateSave(save)).toThrow('食事');});
});

it('retains older graves across repeated deaths',()=>{
 const sim=new GameSimulation(),g=sim.adventure,m=g.state.meadows!;g.state.inventory.wood=7;g.hurtPlayer(1000,'physical');g.stepPersonal(4);g.state.inventory.stone=5;g.hurtPlayer(1000,'physical');expect(m.graves).toHaveLength(1);expect(m.graves![0].items.wood).toBe(7);
});
it('rejects bad cooking data and places overflow loot on the ground',()=>{
 const sim=new GameSimulation(),g=sim.adventure;g.state.inventory={wood:150};const before=g.state.resources.length;g.meadowRules.grant('stone',5);expect(g.state.resources.length).toBe(before+1);expect(g.state.inventory.stone).toBeUndefined();
 const save=sim.save();save.adventure!.buildings[0].cooking=[{id:'unknown',time:2}];expect(()=>validateSave(save)).toThrow('調理');
});

it('breeds fed tame boars, keeps babies from breeding and pauses taming when frightened',()=>{
 const sim=new GameSimulation(),g=sim.adventure,a=g.state.enemies.find(e=>e.definition==='boar')!,b={...a,id:sim.allocateEntityId(),x:a.x+.5};g.state.enemies=[a,b];Object.assign(a,{tame:1,fed:400,breeding:299});Object.assign(b,{tame:1,fed:400});g.meadowRules.step(2);expect(g.state.enemies.some(e=>(e.baby??0)>0)).toBe(true);Object.assign(a,{x:sim.player.x,z:sim.player.z,tame:0,fed:100});g.meadowRules.step(1);expect(a.tame).toBe(0);
});
it('keeps fuel and cooking progression independent of the number of players',()=>{
 const session=new SessionAuthority(),sim=session.sim,p=sim.player;sim.adventure.state.buildings=[{id:sim.allocateEntityId(),definition:'fire',x:p.x+4,y:p.y,z:p.z,rotation:0,support:4,contents:{},fuel:100}];session.join('a');session.join('b');session.step();expect(sim.adventure.state.buildings[0].fuel).toBeCloseTo(100-1/30);expect(session.actors.get('a')!.adventure.state.meadows).not.toBe(sim.adventure.state.meadows);
});
it('allocates new dropped items after the highest saved resource identity',()=>{
 const sim=new GameSimulation(),g=sim.adventure;g.state.inventory.wood=20;g.action('drop','wood');const last=Math.max(...g.state.resources.map(n=>n.id));const restored=new GameSimulation(validateSave(sim.save()));restored.player.x+=2;restored.adventure.action('drop','wood');expect(Math.max(...restored.adventure.state.resources.map(n=>n.id))).toBeGreaterThan(last);expect(()=>validateSave(restored.save())).not.toThrow();
});
