import {expect,it} from 'vitest';
import {SkyboundPowers} from '../../src/game/skybound/powers';
import {deckPassengers,passengersClear,carryPassengers} from '../../src/game/skybound/platform';
import {yawQuaternion} from '../../src/game/skybound/orientation';
import type {SkyPart,SkyContext} from '../../src/game/skybound/types';
import {WORLD} from '../../src/world/types';
function setup(){const part:SkyPart={id:1,kind:'slab',material:'wood',mass:8,position:{x:30,y:1,z:30},velocity:{x:2,y:0,z:0},rotation:0,links:[],epoch:0};const player={x:30.5,y:1.125,z:30,vy:0,grounded:true};const context:SkyContext={tick:0,bounds:WORLD,player,inventory:{},solid:p=>p.y<0,actors:[{id:'walker',position:player}]};return{part,player,context};}
it('carries a free-standing walker by the exact translating and rotating deck transform',()=>{const {part,player,context}=setup(),passengers=deckPassengers([part],context.actors,new Set());expect(passengers).toHaveLength(1);const pose={...part,position:{x:32,y:1,z:30},q:yawQuaternion(Math.PI/2),rotation:Math.PI/2};expect(passengersClear(passengers,[pose],[part],context)).toBe(true);carryPassengers(passengers,[pose]);expect(player.x).toBeCloseTo(32);expect(player.z).toBeCloseTo(29.5);expect(player.y).toBe(1.125);});
it('does not carry jumpers, non-supported people or seated riders as deck walkers',()=>{const {part,player,context}=setup();player.vy=3;expect(deckPassengers([part],context.actors,new Set())).toHaveLength(0);player.vy=0;expect(deckPassengers([part],context.actors,new Set(['walker']))).toHaveLength(0);player.x+=3;expect(deckPassengers([part],context.actors,new Set())).toHaveLength(0);});
it('blocks a deck pose that would carry someone through a wall, ceiling or another actor',()=>{for(const kind of['wall','ceiling','actor']){const {part,context}=setup(),passengers=deckPassengers([part],context.actors,new Set()),pose={...part,position:{x:30.8,y:1,z:30}};if(kind==='wall')context.solid=p=>p.x>31.4;if(kind==='ceiling')context.solid=p=>p.y>2.2;if(kind==='actor')context.actors.push({id:'other',position:{x:31.4,y:1.125,z:30}});expect(passengersClear(passengers,[pose],[part],context)).toBe(false);}});
it('authority physics carries two deck walkers without requiring seats or drifting relative to the floor',()=>{const {part,context,player}=setup();const other={x:29.5,y:1.125,z:30,vy:0,grounded:true};context.actors.push({id:'other',position:other});const powers=new SkyboundPowers({version:2,parts:[part],blueprints:[],fusions:{}}),start=player.x;for(let i=0;i<12;i++){context.tick++;powers.step(1/30,context);}expect(player.x).toBeGreaterThan(start+.2);expect(player.x-powers.state.parts[0].position.x).toBeCloseTo(.5);expect(other.x-powers.state.parts[0].position.x).toBeCloseTo(-.5);});
it('carries a walker on recalled platform poses without rewinding inventory or body state',()=>{const{part,context,player}=setup();context.actors=[];const powers=new SkyboundPowers({version:2,parts:[part],blueprints:[],fusions:{}});for(let i=0;i<12;i++){context.tick++;powers.step(1/30,context);}const root=powers.state.parts[0];Object.assign(player,{x:root.position.x,y:root.position.y+.125,z:root.position.z,vy:0,grounded:true});context.actors=[{id:'walker',position:player}];const start=player.x;context.inventory.wood=17;powers.action('operator','sky-recall','1',undefined,{x:0,y:0,z:1},context);for(let i=0;i<8;i++){context.tick++;powers.step(1/30,context);}expect(player.x).toBeLessThan(start);expect(player.x-root.position.x).toBeCloseTo(0);expect(player.y-root.position.y).toBeCloseTo(.125);expect(context.inventory.wood).toBe(17);});
it('keeps host and guest standing on the same authority deck through actual session movement and snapshots',async()=>{const{SessionAuthority}=await import('../../src/simulation/session');const room=new SessionAuthority(),sim=room.sim,guest=room.join('walker'),{part}=setup();sim.world.density=p=>p.y;sim.fluid.restore([]);sim.bodies.length=0;sim.adventure.state.resources=[];sim.adventure.state.enemies=[];sim.adventure.state.buildings=[];sim.skybound.state.parts=[part];Object.assign(sim.player,{x:30.5,y:1.125,z:30,vy:0,grounded:true});Object.assign(guest.player,{x:29.5,y:1.125,z:30,vy:0,grounded:true});for(let i=0;i<12;i++)room.step({x:0,z:0,jump:false});expect(sim.player.x).toBeGreaterThan(30.7);expect(sim.player.x-part.position.x).toBeCloseTo(.5);expect(guest.player.x-part.position.x).toBeCloseTo(-.5);expect(room.view('walker').peers.find(p=>p.id==='host')!.player).toEqual(sim.player);expect(room.view('host').peers.find(p=>p.id==='walker')!.player).toEqual(guest.player);});
