import {describe,it,expect} from 'vitest';
import {NpcLife,NAGI_HOME,NAGI_WORK,NAGI_SOCIAL,NAGI_BED,npcSchedule,validNpcLifeState,createNpcLifeState,npcBody,type NpcLifeContext} from '../../src/prototype/core/npc-life';
import {VoxelField} from '../../src/prototype/core/voxel';
const flat=(a:{x:number;z:number},b:{x:number;z:number})=>Math.hypot(a.x-b.x,a.z-b.z);
function setup(){const field=new VoxelField();field.box({x:-8,y:-1,z:0},{x:1,y:.25,z:8},2);const npc=new NpcLife(),context:NpcLifeContext={field,hour:10,rain:false,bed:false};npc.reconcile(true,context);return {npc,field,context};}
function advance(npc:NpcLife,c:NpcLifeContext,seconds:number,dt=1/30){for(let i=0;i<Math.round(seconds/dt);i++)npc.tick(dt,c);}
function bed(c:NpcLifeContext){c.bed=true;c.field.box({x:-5,y:.25,z:2},{x:-3.5,y:.68,z:3},4,'build:home:bed',.05);c.field.box({x:-5.5,y:2.8,z:1.5},{x:-3,y:3,z:3.5},4,'bed-roof');}

describe('Nagi daily life uses the actual supported world',()=>{
 it('has stable work, social and overnight schedule boundaries',()=>{for(const [h,s] of [[0,'rest'],[5.99,'rest'],[6,'social'],[8,'work'],[12,'social'],[14,'work'],[18,'social'],[22,'rest'],[24,'rest']] as const)expect(npcSchedule(h)).toBe(s);});
 it('walks between workplaces and social space, with no terrain edits or teleport',()=>{const {npc,field,context:c}=setup();advance(npc,c,2);expect(flat(npc.position,NAGI_WORK)).toBeLessThan(.09);expect(npc.state?.activity).toBe('work');const revision=field.revision;c.hour=12;let moved=0;for(let i=0;i<500;i++){const before={...npc.position};npc.tick(1/30,c);expect(flat(before,npc.position)).toBeLessThanOrEqual(.8/30+1e-8);moved+=flat(before,npc.position);expect(npc.overlapsTerrain(field)).toBe(false);}expect(flat(npc.position,NAGI_SOCIAL)).toBeLessThan(.09);expect(npc.state?.activity).toBe('social');expect(moved).toBeGreaterThan(2);expect(field.revision).toBe(revision);expect(validNpcLifeState(npc.state)).toBe(true);});
 it('uses a real sheltered mattress and stops sleeping when its bed or roof disappears',()=>{const {npc,context:c}=setup();bed(c);c.hour=23;advance(npc,c,15);expect(flat(npc.position,NAGI_BED)).toBeLessThan(.09);expect(npc.position.y).toBeGreaterThan(.6);expect(npc.state?.activity).toBe('sleep');expect(npc.pose).toBe('sleep');c.field.removeObject('bed-roof');advance(npc,c,15);expect(npc.state?.activity).toBe('rest');c.field.removeObject('build:home:bed');advance(npc,c,1);expect(npc.state?.activity).not.toBe('sleep');expect(npc.overlapsTerrain(c.field)).toBe(false);});
 it('takes cover in existing roofed space when it rains, then resumes the schedule',()=>{const {npc,context:c}=setup();bed(c);c.rain=true;advance(npc,c,15);expect(npc.state?.activity).toBe('shelter');expect(flat(npc.position,NAGI_BED)).toBeLessThan(.09);c.rain=false;advance(npc,c,15);expect(npc.state?.activity).toBe('work');});
 it('routes around player walls; cannot cross an enclosed wall or recover out of it',()=>{const {npc,field,context:c}=setup();advance(npc,c,1);field.box({x:-3.5,y:.25,z:4},{x:-3.25,y:2.6,z:5.5},4,'wall');c.hour=12;advance(npc,c,18);expect(npc.state?.activity).toBe('social');expect(npc.overlapsTerrain(field)).toBe(false);
  const q={...npc.position};for(const [id,a,b] of [['l',{x:q.x-1,y:.25,z:q.z-1},{x:q.x-.65,y:3,z:q.z+1}],['r',{x:q.x+.65,y:.25,z:q.z-1},{x:q.x+1,y:3,z:q.z+1}],['f',{x:q.x-1,y:.25,z:q.z-1},{x:q.x+1,y:3,z:q.z-.65}],['b',{x:q.x-1,y:.25,z:q.z+.65},{x:q.x+1,y:3,z:q.z+1}]] as const)field.box(a,b,3,id);const before={...npc.position};npc.restore(npc.snapshot());npc.reconcile(true,c);c.hour=15;advance(npc,c,8);expect(npc.state?.recovery).toBe('none');expect(npc.state?.activity).toBe('waiting');expect(flat(npc.position,before)).toBeLessThan(.1);
 });
 it('waits for players without displacing them, then continues after they leave',()=>{const {npc,context:c}=setup();advance(npc,c,1);c.hour=12;c.blockers=[{...NAGI_SOCIAL}];advance(npc,c,15);expect(npc.state?.activity).toBe('waiting');expect(flat(npc.position,NAGI_SOCIAL)).toBeGreaterThan(.7);c.blockers=[];advance(npc,c,8);expect(npc.state?.activity).toBe('social');});
 it('cannot walk across a pit and does not teleport for an unreachable goal',()=>{const {npc,context:c}=setup();advance(npc,c,1);c.field.box({x:-3.3,y:-2,z:0},{x:-2.1,y:1.5,z:8},0);c.hour=12;advance(npc,c,15);expect(npc.position.x).toBeLessThan(-3.3);expect(npc.state?.activity).toBe('waiting');expect(npc.state?.recovery).toBe('none');});
 it('only recovers an embedded legacy actor or an actual void fall, without changing the world',()=>{const {npc,field,context:c}=setup();field.box({x:NAGI_HOME.x-.5,y:.25,z:NAGI_HOME.z-.5},{x:NAGI_HOME.x+.5,y:2.5,z:NAGI_HOME.z+.5},4,'build:old');const revision=field.revision;npc.restore(createNpcLifeState());npc.reconcile(true,c);expect(npc.visible).toBe(true);expect(npc.overlapsTerrain(field)).toBe(false);expect(field.revision).toBe(revision);
  const empty=new VoxelField();advance(npc,{...c,field:empty},3);expect(npc.state?.recovery).toBe('void');expect(npc.visible).toBe(false);advance(npc,c,2);expect(npc.visible).toBe(true);expect(npc.overlapsTerrain(field)).toBe(false);
 });
 it('conversation and rays follow the moving body and obey distance and walls',()=>{const {npc,field,context:c}=setup();advance(npc,c,1);c.hour=12;advance(npc,c,15);const eye={x:npc.position.x,y:npc.position.y+1,z:npc.position.z+2};expect(npc.talk(eye,field).ok).toBe(true);expect(npc.state?.activity).toBe('talking');const before={...npc.position};c.hour=15;advance(npc,c,2);expect(npc.position).toEqual(before);expect(npc.talk({x:-20,y:1,z:4},field).ok).toBe(false);field.box({x:eye.x-1,y:.25,z:eye.z-1},{x:eye.x+1,y:3,z:eye.z-.75},4,'conversation-wall');expect(npc.talk(eye,field).ok).toBe(false);expect(npc.ray(eye,{x:0,y:0,z:-1},3,field)).toBeNull();});
 it('keeps saved movement detached, rejects malformed state and matches 30/60/120Hz',()=>{const states=[30,60,120].map(fps=>{const {npc,context:c}=setup();c.hour=12;advance(npc,c,2,1/fps);return npc.snapshot()!;});for(const s of states){expect(validNpcLifeState(s)).toBe(true);expect(s.position).toEqual(states[0].position);}const npc=new NpcLife();expect(npc.restore(states[0])).toBe(true);states[0].position.x=-6;expect(npc.position.x).not.toBe(-6);const saved=npc.snapshot();for(const bad of [{...saved,extra:1},{...saved,position:{x:30,y:0,z:0}},{...saved,phase:Infinity},{...saved,recovery:'void'},{...saved,accumulator:1/30},{...saved,activity:'invalid'}]){expect(npc.restore(bad)).toBe(false);expect(npc.snapshot()).toEqual(saved);}expect(npcBody('work-a')).toBe(npcBody('work-a'));expect(npcBody('sleep').surface.positions.length).toBeGreaterThan(100);});
});
