import {setDoor} from '../../src/prototype/core/world';
import {describe,it,expect} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {captureCampaign,defaultSettings,hydrateCampaign,restoreCampaignInto,isCampaignSave} from '../../src/prototype/campaign-session';
import {captureGameFrame,applyGameFrame,validGameFrame} from '../../src/prototype/network/game-frame';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {createNpcLifeState,NAGI_BED,NAGI_HOME} from '../../src/prototype/core/npc-life';
import {createNpcLifeView} from '../../src/prototype/rendering/npc-life-view';
import * as THREE from 'three';
const neutral:Controls={x:0,z:0,sprint:false,block:false,water:false};
function setup(){const sim=new CoreSimulation(true,false,true);sim.survival.inventory[4]=8;sim.survival.inventory[3]=6;expect(sim.campaign.interact('hearth',{x:-3,y:.25,z:5}).ok).toBe(true);sim.player.position={x:-2.5,y:.25,z:-1.7};sim.player.yaw=0;sim.player.pitch=-.2;return sim;}
function rescue(sim:CoreSimulation){expect(sim.target()?.hit.cell.object).toBe('artisan');sim.action('interact',neutral);expect(sim.campaign.state.artisanRescued).toBe(true);expect(sim.npc.visible).toBe(true);}
function face(sim:CoreSimulation){const p=sim.player.position,n=sim.npc.position;sim.player.yaw=Math.atan2(p.x-n.x,p.z-n.z);sim.player.pitch=Math.atan2(n.y+1.1-p.y-1.52,Math.hypot(n.x-p.x,n.z-p.z));}

describe('saved and authoritative Nagi integration',()=>{
 it('keeps original rescue conditions and finite rewards, then targets his actual home position',()=>{const s=setup(),xp=s.campaign.state.xp,inv={...s.survival.inventory};rescue(s);expect(s.survival.inventory[10]-inv[10]).toBe(12);expect(s.survival.inventory[7]-inv[7]).toBe(12);expect(s.survival.inventory[6]-inv[6]).toBe(6);expect(s.campaign.state.xp).toBeGreaterThan(xp);expect(s.target()?.hit.cell.object).not.toBe('artisan');expect([...s.arena.field.objectSamples('artisan')].some(c=>c.distance<0)).toBe(false);
  const rewards=s.campaign.snapshot(),materials={...s.survival.inventory};s.player.position={x:-3.9,y:.25,z:6.05};face(s);expect(s.target()?.npc).toBe(true);for(let i=0;i<5;i++)s.action('interact',neutral);expect(s.campaign.snapshot()).toEqual(rewards);expect(s.survival.inventory).toEqual(materials);expect(s.events.at(-1)?.text).toContain('ナギ「');
 });
 it('saves position/activity, migrates old rescued saves without new rewards, and rejects bad NPC state atomically',()=>{const s=setup();rescue(s);s.player.position={x:0,y:.25,z:6};s.worldHour=12;for(let i=0;i<45;i++)s.tick(1/30,neutral);const saved=captureCampaign(s,defaultSettings()),rewards=s.campaign.snapshot(),materials={...s.survival.inventory};expect(isCampaignSave(saved)).toBe(true);const loaded=hydrateCampaign(saved);expect(loaded).not.toBeNull();expect(loaded!.sim.npc.snapshot()).toEqual(saved.npcLife);expect(loaded!.sim.campaign.snapshot()).toEqual(rewards);expect(loaded!.sim.survival.inventory).toEqual(materials);
  s.arena.field.box({x:NAGI_HOME.x-.2,y:.25,z:NAGI_HOME.z-.2},{x:NAGI_HOME.x+.2,y:1.8,z:NAGI_HOME.z+.2},10,'artisan');const legacy=captureCampaign(s,defaultSettings());delete (legacy as {npcLife?:unknown}).npcLife;const old=hydrateCampaign(legacy);expect(old).not.toBeNull();expect(old!.sim.npc.visible).toBe(true);expect([...old!.sim.arena.field.objectSamples('artisan')].some(c=>c.distance<0)).toBe(false);expect(old!.sim.campaign.snapshot()).toEqual(rewards);expect(old!.sim.survival.inventory).toEqual(materials);
  const before=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,{...saved,npcLife:{...saved.npcLife,position:{x:100,y:0,z:0}}})).toBeNull();expect(captureCampaign(s,defaultSettings())).toEqual(before);expect(isCampaignSave({...saved,campaign:{...saved.campaign,artisanRescued:false}})).toBe(false);
 },20000);
 it('does not reveal an NPC before rescue and protects his body from tools, spells and arrows',()=>{const s=setup();expect(s.npc.visible).toBe(false);rescue(s);s.player.position={x:-3.95,y:.25,z:6};face(s);const inventory={...s.survival.inventory},field=s.arena.field.exportState(),state=s.npc.snapshot();s.action('cast',neutral);expect(s.survival.inventory).toEqual(inventory);expect(s.arena.field.exportState()).toEqual(field);expect(s.npc.snapshot()).toEqual(state);s.arrows.push({position:{x:s.npc.position.x,y:s.npc.position.y+1,z:s.npc.position.z+.8},velocity:{x:0,y:0,z:-12},life:3});for(let i=0;i<4;i++)s.tick(1/30,neutral);expect(s.arrows).toHaveLength(0);expect(s.survival.inventory).toEqual(inventory);expect(s.npc.visible).toBe(true);});
 it('retains crafting at the hearth regardless of schedule, and rejects furniture on his body before paying',()=>{const s=setup();rescue(s);s.player.position={x:-3.5,y:.25,z:5.3};s.survival.inventory[4]=50;s.survival.inventory[10]=50;const actor=createNpcLifeState();actor.position={...NAGI_BED,y:.27};s.npc.restore(actor);const materials={...s.survival.inventory};expect(executeGameCommand(s,{type:'homestead',id:'furniture:bed'}).ok).toBe(false);expect(s.home.state.furniture).not.toContain('bed');expect(s.survival.inventory).toEqual(materials);s.npc.state!.activity='sleep';expect(executeGameCommand(s,{type:'craft',id:'iron-blade'}).ok).toBe(true);});
 it('reaches the real authored camp bed, work area and social spot around the furnace',()=>{const s=setup();rescue(s);setDoor(s.arena.field,true);s.arena.objects.get('door')!.open=true;s.player.position={x:0,y:.25,z:6};s.home.state.furniture.push('bed');s.buildFurniture('bed');s.arena.field.box({x:-5.5,y:2.8,z:1.5},{x:-3,y:3,z:3.5},4,'build:test-roof');s.worldHour=23;for(let i=0;i<900;i++)s.npc.tick(1/30,{...s.npcContext,rain:false});expect(s.npc.state?.activity).toBe('sleep');expect(s.npc.overlapsTerrain(s.arena.field)).toBe(false);s.worldHour=10;for(let i=0;i<900;i++)s.npc.tick(1/30,{...s.npcContext,rain:false});expect(s.npc.state?.activity).toBe('work');s.worldHour=12;for(let i=0;i<900;i++)s.npc.tick(1/30,{...s.npcContext,rain:false});expect(s.npc.state?.activity).toBe('social');expect(s.npc.overlapsTerrain(s.arena.field)).toBe(false);},20000);
 it('refuses to swing the original crypt door through Nagi',()=>{const s=setup();rescue(s);s.player.position={x:0,y:.25,z:3.4};s.player.yaw=0;s.player.pitch=-.15;const actor=createNpcLifeState();actor.position={x:-1.3,y:.27,z:2};s.npc.restore(actor);expect(s.npc.overlapsTerrain(s.arena.field)).toBe(false);expect(s.target()?.hit.cell.object).toBe('door');s.action('interact',neutral);expect(s.arena.objects.get('door')!.open).toBe(false);expect(s.npc.overlapsTerrain(s.arena.field)).toBe(false);expect(s.events.at(-1)?.text).toContain('体に当たる');});
 it('replicates a detached host actor without running guest schedules or awarding resources',()=>{const host=setup();rescue(host);host.enableCompanion();const frame=captureGameFrame(host),guest=new CoreSimulation(true,false,true),before={...guest.survival.inventory};expect(validGameFrame(frame,host.enemies.length)).toBe(true);expect(applyGameFrame(guest,frame)).not.toBeNull();expect(guest.npc.snapshot()).toEqual(host.npc.snapshot());expect(guest.survival.inventory).toEqual(before);frame.npcLife!.position.x=-6;expect(guest.npc.position.x).not.toBe(-6);expect(validGameFrame({...frame,npcLife:{...frame.npcLife,grounded:'yes'}},host.enemies.length)).toBe(false);});
 it('builds reusable visible work/rest/social poses and disposes every GPU resource',()=>{const sim=setup();rescue(sim);const scene=new THREE.Scene(),view=createNpcLifeView(scene,sim);view.update();const first=scene.children[0] as THREE.Mesh;expect(first.position.x).toBe(sim.npc.position.x);sim.npc.state!.activity='sleep';view.update();expect(scene.children.filter(o=>o.visible).map(o=>o.name)).toEqual(['nagi-life:sleep']);sim.npc.state!.activity='work';view.update();expect(scene.children.filter(o=>o.visible).map(o=>o.name)).toEqual(['nagi-life:work-a']);const count=scene.children.length;view.update();expect(scene.children.length).toBe(count);view.dispose();view.dispose();expect(scene.children).toHaveLength(0);});
});

describe('Nagi landing and overlap recovery',()=>{
 it('does not trap a player who falls onto Nagi, and retains terrain collision',()=>{const s=setup();rescue(s);s.player.position={...s.npc.position,y:3};s.player.grounded=false;s.player.vy=0;for(let i=0;i<240;i++)s.tick(1/60,neutral);const start={...s.player.position};// Move west, away from the solid furnace immediately east of the landing.
  for(let i=0;i<240;i++)s.tick(1/60,{...neutral,x:-1});expect(Math.hypot(s.player.position.x-start.x,s.player.position.z-start.z)).toBeGreaterThan(.75);expect(s.npc.overlaps(s.player.position)).toBe(false);expect(s.arena.field.overlaps(s.player.position)).toBe(false);expect(s.npc.overlapsTerrain(s.arena.field)).toBe(false);});
 it('separates a restored actor overlap without consuming resources or passing through the actor',()=>{const s=setup();rescue(s);const saved=captureCampaign(s,defaultSettings());saved.player.position={...saved.npcLife!.position};const restored=hydrateCampaign(saved)!;expect(restored).not.toBeNull();const sim=restored.sim,inventory={...sim.survival.inventory};for(let i=0;i<180;i++)sim.tick(1/60,{...neutral,x:-1});expect(sim.npc.overlaps(sim.player.position)).toBe(false);expect(sim.arena.field.overlaps(sim.player.position)).toBe(false);expect(sim.survival.inventory).toEqual(inventory);});
 it('still rejects walking from outside into a stationary NPC',()=>{const s=setup();rescue(s);s.player.position={x:s.npc.position.x-.9,y:.27,z:s.npc.position.z};const start=s.player.position.x;const npc=s.npc.snapshot()!;npc.activity='talking';npc.talkSeconds=4;s.npc.restore(npc);for(let i=0;i<30;i++)s.tick(1/60,{...neutral,x:1});expect(s.player.position.x).toBeGreaterThanOrEqual(start);expect(s.npc.overlaps(s.player.position)).toBe(false);});
});
