import {describe,it,expect} from 'vitest';
import {ParticipantJournal} from '../../src/prototype/participant-journal';
import {isGameCommand} from '../../src/prototype/campaign-commands';
const quests=[{id:'hearth',label:'炉を灯す',detail:'素材を集めて炉を灯す',completed:true},{id:'artisan',label:'ナギを救出',completed:false}];
const away={position:{x:12,y:.25,z:8},alive:true,hearth:true,artisan:{x:-4,y:.25,z:4}};
const memory=()=>{const values=new Map<string,string>();return {getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},values};};
describe('private participant story and world progress',()=>{
 it('distinguishes pre-join context from shared milestones and never regrants rewards',()=>{const storage=memory(),j=new ParticipantJournal(()=>storage),before=structuredClone(quests);j.update('room:guest',quests,away);expect(j.rows().find(r=>r.id==='hearth')?.reason).toContain('合流前');expect(j.rows().find(r=>r.id==='personal-recap')?.completed).toBe(false);expect(j.read('hearth')).toContain('報酬を再取得しません');expect(j.read('hearth')).toContain('炉を灯す');expect(j.read('artisan')).toBeNull();expect(j.rows().find(r=>r.id==='personal-recap')?.completed).toBe(true);expect(quests).toEqual(before);expect(isGameCommand({type:'story-read',id:'hearth'})).toBe(false);j.update('room:guest',quests.map(q=>({...q,completed:true})),away);expect(j.rows().find(r=>r.id==='artisan')?.reason).toContain('参加中');});
 it('requires this actor to visit living locations and preserves records on reconnect without sharing another role',()=>{const storage=memory(),j=new ParticipantJournal(()=>storage);j.update('room:guest',quests,away);expect(j.rows()[0].completed).toBe(false);j.update('room:guest',quests,{...away,position:{x:-3,y:.25,z:4},alive:false});expect(j.rows()[0].completed).toBe(false);j.update('room:guest',quests,{...away,position:{x:-3,y:.25,z:4}});expect(j.rows()[0].completed).toBe(true);expect(j.rows()[1].completed).toBe(true);j.read('hearth');const restored=new ParticipantJournal(()=>storage);restored.update('room:guest',quests,away);expect(restored.rows()[0].completed).toBe(true);expect(restored.rows().find(r=>r.id==='hearth')?.reason).toContain('確認済み');restored.update('room:host',quests,away);expect(restored.rows()[0].completed).toBe(false);expect(restored.rows().find(r=>r.id==='hearth')?.reason).toContain('未確認');});
 it('fails safely for malformed or unavailable storage and keeps bounded room history',()=>{const storage=memory();storage.setItem('seven-lights-participant-journal-v1','{"version":1,"records":[{"scope":"room:guest"}]}');const j=new ParticipantJournal(()=>storage);for(let i=0;i<12;i++)j.update('room'+i+':guest',quests,away);const saved=JSON.parse([...storage.values.values()][0]);expect(saved.records).toHaveLength(8);const blocked=new ParticipantJournal(()=>{throw new Error('blocked');});blocked.update('room:guest',quests,away);expect(blocked.rows()[2].reason).toContain('保存ができません');expect(blocked.read('hearth')).toContain('炉を灯す');});
});
