import {afterEach,describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {createPerformancePipeline,performanceViewport,PERFORMANCE_VIEW_DISTANCE} from '../../src/prototype/rendering/performance-pipeline';
function fixture(){const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(74,1,.035,120),sky=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.ShaderMaterial({uniforms:{sunPosition:{value:new THREE.Vector3()},rayleigh:{value:3}}})),terrain=new THREE.Mesh(new THREE.IcosahedronGeometry(2,2),new THREE.MeshStandardMaterial({roughness:.87,metalness:.04}));scene.add(sky,terrain);const gl={getExtension:vi.fn(()=>({UNMASKED_RENDERER_WEBGL:123})),getParameter:vi.fn(()=> 'ANGLE SwiftShader')};let pixelRatio=1;const renderer={getContext:()=>gl,shadowMap:{enabled:true,needsUpdate:true},toneMappingExposure:1,info:{reset:vi.fn()},setPixelRatio:vi.fn((v:number)=>{pixelRatio=v;}),getPixelRatio:()=>pixelRatio,setSize:vi.fn(),setRenderTarget:vi.fn(),render:vi.fn(),compileAsync:vi.fn(async()=>scene)};const atmosphere={stats:{hour:12},prepare:vi.fn()};const pipeline=createPerformancePipeline(renderer as unknown as THREE.WebGLRenderer,scene,camera,atmosphere as unknown as Parameters<typeof createPerformancePipeline>[3]);return {scene,camera,sky,terrain,renderer,atmosphere,pipeline};}
afterEach(()=>vi.unstubAllGlobals());
describe('production performance quality budget',()=>{
 it.each([[1280,720],[1920,1080],[3840,2160],[915,412],[360,780],[4096,4096]])('bounds raster pixels at %dx%d without changing simulation geometry', (w,h)=>{const software=performanceViewport(w,h,2,true),hardware=performanceViewport(w,h,2,false);expect(Math.max(software.width,software.height)).toBeLessThanOrEqual(480);expect(software.width*software.height).toBeLessThanOrEqual(480*480);expect(Math.max(hardware.width,hardware.height)).toBeLessThanOrEqual(720);expect(software.pixelRatio).toBeLessThanOrEqual(hardware.pixelRatio);});
 it('preserves CSS aspect and does not supersample low-power screens',()=>{const v=performanceViewport(1280,720,3,true);expect(v.width).toBe(480);expect(v.height).toBe(270);expect(v.pixelRatio).toBe(.375);expect(performanceViewport(320,180,1,true).pixelRatio).toBe(1);});
 it('uses one PBR render per frame with no shadow update, sky shader, PMREM or readback preparation',async()=>{vi.stubGlobal('devicePixelRatio',2);const f=fixture(),geometry=f.terrain.geometry,material=f.terrain.material,vertices=geometry.getAttribute('position').count;f.pipeline.resize(1280,720);expect(f.pipeline.render(1/60)).toBe(false);expect(f.renderer.render).not.toHaveBeenCalled();await Promise.resolve();for(let i=0;i<30;i++)f.pipeline.render(1/60);expect(f.renderer.render).toHaveBeenCalledTimes(30);expect(f.atmosphere.prepare).not.toHaveBeenCalled();expect(f.renderer.shadowMap.enabled).toBe(false);expect(f.renderer.shadowMap.needsUpdate).toBe(false);expect(f.sky.visible).toBe(false);expect(f.terrain.geometry).toBe(geometry);expect(f.terrain.material).toBe(material);expect(f.terrain.geometry.getAttribute('position').count).toBe(vertices);expect(material).toBeInstanceOf(THREE.MeshStandardMaterial);expect(f.pipeline.stats).toMatchObject({softwareRendering:true,renderScale:.375,renderWidth:480,renderHeight:270,pixelBudget:129600,dynamicEnvironmentCapture:false});expect(f.camera.far).toBe(PERFORMANCE_VIEW_DISTANCE);f.pipeline.dispose();});
 it('restores quality-dependent state when returning to balanced or high',()=>{const f=fixture();f.pipeline.resize(1280,720);f.pipeline.render(.1);f.pipeline.dispose();expect(f.sky.visible).toBe(true);expect(f.renderer.shadowMap.enabled).toBe(true);expect(f.camera.far).toBe(120);expect(f.scene.fog).toBeNull();expect(f.scene.background).toBeNull();expect(f.scene.getObjectByName('performance-ambient')).toBeUndefined();});
 it('tracks real day/night presentation without touching game time',async()=>{const f=fixture();f.pipeline.render(.1);await Promise.resolve();f.pipeline.render(.1);const day=(f.scene.background as THREE.Color).clone();f.atmosphere.stats.hour=0;f.pipeline.render(.1);expect((f.scene.background as THREE.Color).getHex()).not.toBe(day.getHex());expect(f.atmosphere.stats.hour).toBe(0);expect(f.renderer.render).toHaveBeenCalledTimes(2);f.pipeline.dispose();});
});
