import {describe,it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {executeGameCommand} from '../../src/prototype/campaign-commands';
import {captureCampaign,defaultSettings,restoreCampaignInto} from '../../src/prototype/campaign-session';
import {DawnDuskWait,PLAYER_BED,PLAYER_BED_OBJECT,REST_NEUTRAL,playerBedIntact,validPlayerBedSave} from '../../src/prototype/core/player-rest';
function setup(){const s=new CoreSimulation(true,false,true);s.campaign.state.flameTier=1;Object.assign(s.survival.inventory,{4:30,10:12});s.player.position={x:-3.5,y:.25,z:5.3};s.player.grounded=true;return s;}
function bed(){const s=setup();const r=executeGameCommand(s,{type:'homestead',id:'furniture:player-bed'});expect(r).toEqual({ok:true,message:expect.any(String)});s.player.position={x:-1.5,y:.25,z:5.1};s.tick(.1,REST_NEUTRAL);expect(s.playerRestStatus()).toEqual({ok:true,message:expect.any(String)});return s;}
describe('owned player bed and bounded waiting',()=>{
 it('requires paid independent furniture, real shelter and intact geometry; repair pays once',()=>{const s=setup();expect(s.startPlayerRest('dawn').ok).toBe(false);s.home.state.furniture.push('bed');s.buildFurniture('bed');expect(s.startPlayerRest('dawn').ok).toBe(false);const before={...s.survival.inventory};expect(executeGameCommand(s,{type:'homestead',id:'furniture:player-bed'}).ok).toBe(true);expect(s.survival.inventory[4]).toBe(before[4]-10);expect(s.survival.inventory[10]).toBe(before[10]-3);expect(s.home.state.furniture).toEqual(['bed',PLAYER_BED]);expect(playerBedIntact(s.arena.field)).toBe(true);expect(s.npc.profile.bedFurniture).toBe('bed');expect(s.npc.profile.bedObject).not.toBe(PLAYER_BED_OBJECT);expect(executeGameCommand(s,{type:'homestead',id:'furniture:player-bed'}).ok).toBe(false);s.arena.field.removeObject(PLAYER_BED_OBJECT);expect(s.repairPlayerBed().ok).toBe(true);expect(s.survival.inventory[4]).toBe(before[4]-16);expect(s.survival.inventory[10]).toBe(before[10]-5);expect(s.repairPlayerBed().ok).toBe(false);});
 it('coexists with existing physical furniture, including the hearth-side brazier',()=>{const s=setup();for(const id of ['bed','table','brazier','rug']){s.home.state.furniture.push(id);s.buildFurniture(id);}expect(executeGameCommand(s,{type:'homestead',id:'furniture:player-bed'}).ok).toBe(true);expect(playerBedIntact(s.arena.field)).toBe(true);s.player.position={x:-1.7,y:.25,z:5.1};s.tick(.1,REST_NEUTRAL);expect(s.playerRestStatus().ok).toBe(true);});
 it('fails closed on full construction overlap without charging',()=>{const s=setup(),before={...s.survival.inventory};s.arena.field.box({x:-.75,y:.4,z:5},{x:-.25,y:1,z:5.5},3,'obstruction');expect(executeGameCommand(s,{type:'homestead',id:'furniture:player-bed'}).ok).toBe(false);expect(s.survival.inventory).toEqual(before);expect(s.home.state.furniture).toEqual([]);});
 it('gates death, action, motion, distance, roof, danger, unlit base and every companion session',()=>{const s=bed();for(const change of [()=>{s.player.hp=0;},()=>{s.player.phase='heal';},()=>{s.player.vx=1;},()=>{s.player.position.x=-4;},()=>{s.player.position.z=3.8;},()=>{s.campaign.state.flameTier=0;},()=>{s.environment.burning=1;},()=>{s.enemies[0].position={x:0,y:.25,z:4};}]){const saved=captureCampaign(s,defaultSettings());change();expect(s.startPlayerRest('dawn').ok).toBe(false);expect(restoreCampaignInto(s,saved)).not.toBeNull();s.player.grounded=true;}
  expect(s.startPlayerRest('dawn',true).ok).toBe(false);s.enableCompanion();s.setCompanionConnected(false);expect(s.startPlayerRest('dawn').ok).toBe(false);s.disableCompanion();s.arena.field.removeObject(PLAYER_BED_OBJECT);expect(s.startPlayerRest('dawn').message).toContain('破損');
 });
 it('advances actual crops, processing, buffs, weather and NPC time with safe bounded ticks',()=>{const s=bed();s.worldHour=5.25;expect(s.weather.kind).toBe('wind');s.campaign.state.artisanRescued=true;s.reconcileNpc();s.campaign.state.foodSeconds=60;s.campaign.state.restSeconds=60;s.home.state.plots[0]={id:0,planted:true,remaining:60};s.home.state.jobs=[{id:1,recipe:'weave',remaining:30}];s.home.state.nextJobId=2;const npc=JSON.stringify(s.npc.snapshot()),before=s.seconds;expect(s.startPlayerRest('dawn').ok).toBe(true);expect(s.startPlayerRest('dusk').ok).toBe(false);let chunks=0;while(s.bedWait.active&&chunks++<100){const prior=s.seconds;s.advancePlayerRest();expect(s.seconds-prior).toBeLessThanOrEqual(4.00001);}expect(s.bedWait.active).toBe(false);expect(s.seconds-before).toBeCloseTo(67.5,6);expect(s.worldHour).toBeCloseTo(6,8);expect(s.weather.kind).toBe('clear');expect(s.home.state.plots[0].remaining).toBe(0);expect(s.home.state.jobs[0].remaining).toBe(0);expect(s.campaign.state.foodSeconds).toBe(0);expect(s.campaign.state.restSeconds).toBe(240);expect(s.campaign.staminaRegenMultiplier).toBe(1.4);expect(JSON.stringify(s.npc.snapshot())).not.toBe(npc);s.player.position={x:2,y:.25,z:5};s.tick(.1,REST_NEUTRAL);expect(s.campaign.state.restSeconds).toBeCloseTo(239.9);},30000);
 it('interruption preserves elapsed systems; save and restore never enqueue further waiting',()=>{const s=bed();s.worldHour=23.99;expect(s.startPlayerRest('dawn').ok).toBe(true);const before=s.seconds;s.advancePlayerRest(false,()=>true);expect(s.seconds-before).toBeCloseTo(.1);expect(s.bedWait.snapshot().elapsed).toBeCloseTo(.1);const saved=captureCampaign(s,defaultSettings());expect('playerRest' in saved).toBe(false);const r=new CoreSimulation(true,false,true);expect(restoreCampaignInto(r,saved)).not.toBeNull();expect(r.bedWait.active).toBe(false);expect(r.seconds).toBe(s.seconds);s.advancePlayerRest(true);expect(s.bedWait.active).toBe(false);expect(s.seconds-before).toBeCloseTo(.1);expect(s.campaign.state.restSeconds).toBeCloseTo(179.9);});
 it('fully removed paid bed stays absent through reload and failed waits never refund or rebuild it',()=>{const s=bed(),materials={...s.survival.inventory};s.arena.field.removeObject(PLAYER_BED_OBJECT);const saved=captureCampaign(s,defaultSettings());expect(validPlayerBedSave(saved.home.furniture,saved.field)).toBe(true);const r=new CoreSimulation(true,false,true);expect(restoreCampaignInto(r,saved)).not.toBeNull();r.player.grounded=true;expect(r.home.state.furniture).toContain(PLAYER_BED);expect([...r.arena.field.ownedLayerSamples(PLAYER_BED_OBJECT)]).toHaveLength(0);const before=r.seconds;expect(r.startPlayerRest('dawn').ok).toBe(false);expect(r.advancePlayerRest().ended).toBe(false);expect(executeGameCommand(r,{type:'homestead',id:'furniture:player-bed'}).ok).toBe(false);expect(r.seconds).toBe(before);expect(r.survival.inventory).toEqual(materials);expect([...r.arena.field.ownedLayerSamples(PLAYER_BED_OBJECT)]).toHaveLength(0);expect(playerBedIntact(r.arena.field)).toBe(false);});
 it('rolls midnight via simulation, grants finite comfort only after completion, and rejects forged ownership',()=>{const s=bed();s.worldHour=23.99;s.worldDay=3;s.startPlayerRest('dawn');s.advancePlayerRest();expect(s.worldDay).toBe(4);expect(s.worldHour).toBeLessThan(.04);s.bedWait.cancel();const saved=captureCampaign(s,defaultSettings());expect(validPlayerBedSave(saved.home.furniture,saved.field)).toBe(true);expect(validPlayerBedSave([],saved.field)).toBe(false);saved.field.layers.find(l=>l.id===PLAYER_BED_OBJECT)!.cells.push([999,999,999,-.2,4]);expect(validPlayerBedSave(saved.home.furniture,saved.field)).toBe(false);});
});
it('controller honors cancellation, wall budgets, exact target and invalid target without clock assignment',()=>{const w=new DawnDuskWait(),safe=()=>({ok:true,message:''});expect(w.start('dawn',6).ok).toBe(false);expect(w.start('dawn',NaN).ok).toBe(false);expect(w.start('bogus' as 'dawn',10).ok).toBe(false);expect(w.start('dusk',17.99).ok).toBe(true);let elapsed=0;const result=w.advance(dt=>{elapsed+=dt;},safe);expect(result.completed).toBe(true);expect(elapsed).toBeCloseTo(.9);expect(w.active).toBe(false);w.start('dawn',18);w.advance(dt=>{elapsed+=dt;},safe,()=>true);expect(w.snapshot().elapsed).toBeCloseTo(.1);w.cancel();const at=elapsed;w.advance(dt=>{elapsed+=dt;},safe);expect(elapsed).toBe(at);});

it('refuses waiting during a held heavy charge without consuming mana or changing time',()=>{const s=bed(),hour=s.worldHour,mana=s.combat.mana;s.action('heavy-start',REST_NEUTRAL);expect(s.combat.charging).toBe(true);expect(s.startPlayerRest('dusk').ok).toBe(false);expect(s.worldHour).toBe(hour);expect(s.combat.mana).toBe(mana);s.cancelCombat();expect(s.startPlayerRest('dusk').ok).toBe(true);});
