import {it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,restoreCampaignInto,defaultSettings,isCampaignSave} from '../../src/prototype/campaign-session';
import {captureGameFrame,applyGameFrame,validGameFrame} from '../../src/prototype/network/game-frame';
import {captureSharedCampaign,applySharedCampaign} from '../../src/prototype/campaign-network-state';
import {createPlayerEnvironmentState} from '../../src/prototype/core/player-environment';
const idle={x:0,z:0,sprint:false,block:false,water:false};
const tick=(s:CoreSimulation,seconds:number)=>{for(let i=0;i<Math.ceil(seconds*30);i++)s.tick(1/30,idle);};
function aim(s:CoreSimulation,p:{x:number;y:number;z:number}){const e=s.eye(),yaw=Math.atan2(-(p.x-e.x),-(p.z-e.z)),pitch=Math.atan2(p.y-e.y,Math.hypot(p.x-e.x,p.z-e.z));s.look(-(yaw-s.player.yaw),s.player.pitch-pitch);}
function ignite(){const s=new CoreSimulation(true,false,true);s.arena.field.box({x:.5,y:.25,z:5.5},{x:.75,y:2,z:6.5},4,'test-hazard');aim(s,{x:.5,y:1,z:6});expect(s.target(7)?.hit.cell.object).toBe('test-hazard');s.action('cast',idle);tick(s,.65);return s;}
it('a real self-authored terrain fire damages its caster; water cast at the feet extinguishes it',()=>{const s=ignite();expect(s.environment.burning).toBeGreaterThan(0);expect(s.player.hp).toBeLessThan(100);tick(s,.6);s.action('element-next',idle);expect(s.selectedElement).toBe('water');aim(s,{x:0,y:.2,z:6.08});s.action('cast',idle);tick(s,.65);expect(s.environment.wet).toBeGreaterThan(0);expect(s.environment.burning).toBe(0);const hp=s.player.hp;tick(s,.5);expect(s.player.hp).toBe(hp);expect(s.events.some(e=>e.text?.includes('火が消えた'))).toBe(true);});
it('validates and preserves exposure in current saves, defaults old saves, and resets only on respawn',()=>{const s=ignite(),save=captureCampaign(s,defaultSettings()),state={...s.environment};expect(isCampaignSave(save)).toBe(true);expect(restoreCampaignInto(s,save)).not.toBeNull();expect(s.environment).toEqual(state);const corrupt=structuredClone(save);corrupt.environment!.wet=999;const before=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,corrupt)).toBeNull();expect(captureCampaign(s,defaultSettings())).toEqual(before);delete save.environment;expect(restoreCampaignInto(s,save)).not.toBeNull();expect(s.environment).toEqual(createPlayerEnvironmentState());s.environment.burning=2;s.respawn();expect(s.environment).toEqual(createPlayerEnvironmentState());});
it('keeps host and guest exposure separate and validates optional frame fields before applying',()=>{const host=ignite();const guest=host.enableCompanion({x:2,y:.25,z:6});host.withCompanion(()=>{host.environment.wet=5;});tick(host,.1);expect(host.environment.burning).toBeGreaterThan(0);expect(host.environment.wet).toBe(0);expect(host.companionSnapshot()!.aux.environment!.wet).toBeGreaterThan(4);expect(host.companionSnapshot()!.aux.environment!.burning).toBe(0);expect(guest.hp).toBe(100);
 const client=new CoreSimulation(true,false,true),frame=captureGameFrame(host);expect(validGameFrame(frame,host.enemies.length)).toBe(true);const remote=applyGameFrame(client,frame)!;expect(client.environment).toEqual(frame.guest!.aux.environment);expect(remote.environment).toEqual(host.environment);const personal={...client.environment};expect(applySharedCampaign(client,captureSharedCampaign(host,defaultSettings())).ok).toBe(true);expect(client.environment).toEqual(personal);
 const bad=structuredClone(frame);bad.guest!.aux.environment!.burning=Infinity;const hp=client.player.hp;expect(applyGameFrame(client,bad)).toBeNull();expect(client.player.hp).toBe(hp);const old=structuredClone(frame);delete old.host.environment;delete old.guest!.aux.environment;expect(validGameFrame(old,host.enemies.length)).toBe(true);expect(applyGameFrame(client,old)).not.toBeNull();expect(client.environment).toEqual(createPlayerEnvironmentState());
});
it('a dug position below regional water is not treated as swimming through the floor',()=>{const s=new CoreSimulation(true,false,true);s.player.position={x:13,y:-1,z:-49};s.tick(1/30,idle);expect(s.swimming).toBe(false);expect(s.oxygen).toBe(20);expect(s.environment.wet).toBe(0);});
it('player recovery searches past a burning landing spot without consuming or changing the hazard',()=>{const s=new CoreSimulation(true,false,true),preferred={x:0,y:.25,z:6};s.arena.field.box({x:-.4,y:.26,z:7.1},{x:.4,y:.55,z:7.9},4,'burning-landing');const hit=s.arena.field.ray({x:0,y:2,z:7.5},{x:0,y:-1,z:0},3)!;s.elements.cast('fire',hit,{x:0,y:-1,z:0});const unsafe=s.safePosition(preferred),before=JSON.stringify(s.elements.exportState()),safe=s.safePosition(preferred,true);expect(safe).not.toEqual(unsafe);expect(s.arena.field.overlaps(safe)).toBe(false);expect(JSON.stringify(s.elements.exportState())).toBe(before);expect(safe.y).toBeLessThan(8);});
