import { describe,it,expect } from 'vitest';
import { VoxelField,direction,WATER_SIZE } from '../../src/prototype/core/voxel';
import { CoreSimulation,type Controls } from '../../src/prototype/core/simulation';
import { VoxelWater } from '../../src/prototype/core/water';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false};
const advance=(s:CoreSimulation,seconds:number,c=idle)=>{for(let i=0;i<Math.ceil(seconds*60);i++)s.tick(1/60,c);};
describe('shared voxel geometry',()=>{
 it('selects the nearest occluding volume and reports the entered face',()=>{const f=new VoxelField();f.set(0,0,-4,3,'wall');f.set(0,0,-8,4,'chest');const h=f.ray({x:.1,y:.1,z:0},{x:0,y:0,z:-1},3);expect(h?.cell.object).toBe('wall');expect(h?.normal.z).toBe(1);expect(h?.distance).toBeCloseTo(.75);});
 it('checks reach, empty space, negative coordinates and vertical rays',()=>{const f=new VoxelField();f.set(-1,-2,-1,3);expect(f.ray({x:-.1,y:1,z:-.1},{x:0,y:-1,z:0},1)).toBeNull();expect(f.ray({x:-.1,y:1,z:-.1},{x:0,y:-1,z:0},2)?.distance).toBeCloseTo(1.25);expect(f.ray({x:0,y:0,z:0},{x:0,y:0,z:0},2)).toBeNull();});
 it('uses an edited solid for collision and ray queries',()=>{const f=new VoxelField();f.set(0,0,0,4);expect(f.overlaps({x:.1,y:0,z:.1})).toBe(true);f.set(0,0,0,0);expect(f.overlaps({x:.1,y:0,z:.1})).toBe(false);expect(f.cells.size).toBe(0);});
 it('supports continuous first-person yaw and near-vertical pitch',()=>{expect(direction(Math.PI/2,0).x).toBeCloseTo(-1);expect(direction(0,Math.PI/2).y).toBeCloseTo(1);});
});
describe('first-person action and contextual interaction',()=>{
 it('requires reach and aim, opens the aimed door and changes its collision',()=>{const s=new CoreSimulation();s.action('interact',idle);expect(s.arena.objects.get('door')?.open).toBe(false);s.player.position.z=3;expect(s.target()?.hit.cell.object).toBe('door');s.player.yaw=Math.PI;s.action('interact',idle);expect(s.arena.objects.get('door')?.open).toBe(false);s.player.yaw=0;s.action('interact',idle);expect(s.arena.objects.get('door')?.open).toBe(true);expect(s.arena.field.at({x:0,y:1,z:.875})).toBeUndefined();});
 it('rejects a chest hidden behind solid stone and never duplicates loot',()=>{const s=new CoreSimulation();s.player.position={x:-2.5,y:.25,z:-1.5};s.player.pitch=-.45;s.arena.field.box({x:-3,y:.25,z:-2.5},{x:-2,y:2.5,z:-2.25},3);s.action('interact',idle);expect(s.player.flasks).toBe(1);s.arena.field.box({x:-3,y:.25,z:-2.5},{x:-2,y:2.5,z:-2.25},0);expect(s.target()?.hit.cell.object).toBe('chest');s.action('interact',idle);expect(s.player.flasks).toBe(3);s.action('interact',idle);expect(s.player.flasks).toBe(3);});
 it('does not damage during windup and does not repeat an attack each tick',()=>{const s=new CoreSimulation();s.player.position={x:0,y:.25,z:-4};s.enemies[1].hp=0;s.action('attack',idle);advance(s,.15);expect(s.enemies[0].hp).toBe(100);advance(s,.13);expect(s.enemies[0].hp).toBe(68);advance(s,.15);expect(s.enemies[0].hp).toBe(68);});
 it('prevents action spam and insufficient-stamina attacks',()=>{const s=new CoreSimulation();s.action('heavy',idle);s.action('attack',idle);expect(s.player.stamina).toBe(68);advance(s,1.5);s.player.stamina=10;s.action('heavy',idle);expect(s.player.phase).toBe('idle');});
 it('light attacks cannot indefinitely cancel a committed enemy swing',()=>{const s=new CoreSimulation();s.player.position={x:0,y:.25,z:-4.5};s.enemies[1].hp=0;const e=s.enemies[0];e.phase='windup';e.time=0;e.yaw=Math.PI;s.action('attack',idle);advance(s,.75);expect(e.hp).toBe(68);expect(s.player.hp).toBe(72);});
 it('enemies fall when their supporting voxels are excavated',()=>{const s=new CoreSimulation();s.arena.field.box({x:-1,y:-1,z:-7},{x:1,y:.25,z:-5},0);advance(s,.2);expect(s.enemies[0].position.y).toBeLessThan(.25);});
 it('parries only a correctly faced fresh guard',()=>{const s=new CoreSimulation();s.player.position={x:0,y:.25,z:-4.5};s.enemies[1].hp=0;const e=s.enemies[0];e.yaw=Math.PI;e.phase='strike';e.hit=false;s.tick(1/60,{...idle,block:true});expect(s.player.hp).toBe(100);expect(e.phase).toBe('stagger');expect(s.events.some(e=>e.kind==='parry')).toBe(true);});
 it('does not allow a shield to block attacks from behind',()=>{const s=new CoreSimulation();s.player.position={x:0,y:.25,z:-4.5};s.player.yaw=Math.PI;s.enemies[1].hp=0;const e=s.enemies[0];e.yaw=Math.PI;e.phase='strike';e.hit=false;s.tick(1/60,{...idle,block:true});expect(s.player.hp).toBe(72);});
 it('has a limited dodge invulnerability interval and charges stamina',()=>{const s=new CoreSimulation();s.player.position={x:0,y:.25,z:-4.5};s.enemies[1].hp=0;s.action('dodge',idle);expect(s.player.stamina).toBe(76);s.player.time=.1;const e=s.enemies[0];e.yaw=Math.PI;e.phase='strike';e.hit=false;s.tick(1/60,idle);expect(s.player.hp).toBe(100);advance(s,.4);expect(s.player.phase).toBe('idle');});
 it('stands, jumps, hits ceilings and cannot walk through a closed door',()=>{const s=new CoreSimulation();advance(s,.1);expect(s.player.grounded).toBe(true);expect(s.player.position.y).toBe(.25);s.action('jump',idle);advance(s,.1);expect(s.player.position.y).toBeGreaterThan(.25);advance(s,1);expect(s.player.position.y).toBe(.25);advance(s,3,{...idle,z:1});expect(s.player.position.z).toBeGreaterThan(1.25);});
});
describe('fine voxel water',()=>{
 it('is one eighth the existing linear spacing and conserves water while flowing',()=>{const w=new VoxelWater(new VoxelField());expect(WATER_SIZE).toBe(.125);const initial=w.total();for(let i=0;i<50;i++)w.step();expect(w.total()).toBeCloseTo(initial,5);expect(w.surface(7,0)).toBeGreaterThan(-Infinity);});
 it('excludes solid volumes and redistributes displaced water without deleting mass',()=>{const f=new VoxelField(),w=new VoxelWater(f);const initial=w.total();f.box({x:4,y:-.5,z:-5},{x:4.25,y:0,z:-4.75},3);w.refreshSolids();expect(w.add(0,0,0,1)).toBe(0);for(let i=0;i<10;i++)w.step();expect(w.total()).toBeCloseTo(initial,5);expect(w.volume[w.index(0,0,0)]).toBe(0);});
});
