import {expect,it} from 'vitest';
import {AuthorityRoom,type RoomCheckpoint} from '../../src/networking/authority-room';
import {COOP_PROTOCOL,type CoopWireServerPacket} from '../../src/networking/coop-protocol';
import {type RoomAdminOperation,validateRoomAccess} from '../../src/networking/room-access';
import {validateCheckpoint} from '../../src/save/checkpoint';
const A='a'.repeat(64),B='b'.repeat(64),C='c'.repeat(64);
function connect(room:AuthorityRoom,socket:string){const packets:CoopWireServerPacket[]=[],closed:{code:number;reason:string}[]=[];room.connect(socket,{send:p=>packets.push(p),close:(code,reason)=>closed.push({code,reason})});return {packets,closed};}
function admit(room:AuthorityRoom,socket:string,player:string,commit=true){const wire=connect(room,socket),result=room.receive(socket,JSON.stringify({type:'hello',protocol:COOP_PROTOCOL}),player);if(commit)result.acknowledgment?.();return {...wire,result};}
function command(room:AuthorityRoom,socket:string,operation:RoomAdminOperation,targetId?:string,id:string=crypto.randomUUID()){const packet={type:'room-admin',commandId:id,expectedRevision:room.viewAccess(A).revision,operation,...targetId?{targetId}:{}};return {packet,result:room.receive(socket,JSON.stringify(packet))};}
it('claims the first authenticated participant only after persistence, scopes views and leaves legacy rooms unmanaged',()=>{
 const room=new AuthorityRoom(null,'one'),a=admit(room,'a',A,false);expect(room.viewAccess(A).canManage).toBe(false);expect(a.packets.some(p=>p.type==='welcome')).toBe(false);expect(room.checkpoint().access?.administratorId).toBe(A);a.result.acknowledgment?.();expect(a.packets.some(p=>p.type==='welcome')).toBe(true);expect(room.viewAccess(A).canManage).toBe(true);admit(room,'b',B);expect(room.viewAccess(B).members).toBeUndefined();expect(Object.keys(room.viewAccess(B)).sort()).toEqual(['canManage','locked','pending','readOnly','revision']);
 const old=room.checkpoint();delete old.access;const legacy=new AuthorityRoom(old,'old');admit(legacy,'new',C);expect(legacy.viewAccess(C).canManage).toBe(false);expect(legacy.checkpoint().access?.administratorId).toBeNull();expect(legacy.checkpoint().access?.claimable).toBe(false);
});
it('rejects public-identity spoofing, non-admin commands, self-ban, extra fields and stale revisions',()=>{
 const room=new AuthorityRoom(null,'auth'),wire=connect(room,'bad');room.receive('bad',JSON.stringify({type:'hello',protocol:COOP_PROTOCOL,playerId:A}));expect(wire.packets.some(p=>p.type==='welcome')).toBe(false);expect(room.checkpoint().access?.administratorId).toBeNull();room.disconnect('bad');const a=admit(room,'a',A),b=admit(room,'b',B);
 command(room,'b','ban',A).result.acknowledgment?.();expect(b.packets.at(-1)).toMatchObject({type:'ack',kind:'room-admin',accepted:false});command(room,'a','ban',A);expect(a.packets.at(-1)).toMatchObject({accepted:false});room.receive('a',JSON.stringify({type:'room-admin',commandId:'spoof',expectedRevision:room.viewAccess(A).revision,operation:'ban',targetId:B,owner:A}));expect(a.packets.at(-1)).toMatchObject({accepted:false});room.receive('a',JSON.stringify({type:'room-admin',commandId:'old',expectedRevision:0,operation:'lock'}));expect(a.packets.at(-1)).toMatchObject({accepted:false});expect(room.checkpoint().access?.bannedIds).toEqual([]);
});
it('locks only new identities, bans after commit, preserves inventory/buildings and allows unban to the same save',()=>{
 const room=new AuthorityRoom(null,'lifecycle'),a=admit(room,'a',A),b=admit(room,'b',B);room.authority.actors.get(B)!.adventure.state.inventory.wood=17;room.authority.sim.adventure.state.buildings.push({id:991,definition:'chest',creator:B,shared:false,x:10,y:3,z:8,rotation:0,support:3,contents:{stone:4}});
 const lock=command(room,'a','lock');expect(room.viewAccess(A)).toMatchObject({locked:false,pending:true});const tick=room.authority.sim.tick;room.step();expect(room.authority.sim.tick).toBe(tick);lock.result.acknowledgment?.();expect(room.viewAccess(A).locked).toBe(true);const c=admit(room,'c',C);expect(c.closed.at(-1)?.code).toBe(4004);room.disconnect('c');room.disconnect('b');const back=admit(room,'back',B);expect(back.packets.some(p=>p.type==='welcome')).toBe(true);expect(room.authority.actors.get(B)!.adventure.state.inventory.wood).toBe(17);
 const ban=command(room,'a','ban',B);expect(back.closed).toHaveLength(0);const staged=validateCheckpoint(room.checkpoint());expect(staged.world.members!.find(m=>m.id===B)!.adventure.inventory.wood).toBe(17);ban.result.acknowledgment?.();expect(back.closed.at(-1)?.code).toBe(4003);expect(room.authority.actors.has(B)).toBe(false);expect(room.checkpoint().world.members!.find(m=>m.id===B)!.adventure.inventory.wood).toBe(17);expect(room.checkpoint().world.adventure!.buildings.find(b=>b.id===991)!.creator).toBe(B);
 const denied=admit(room,'denied',B);expect(denied.closed.at(-1)?.code).toBe(4003);room.disconnect('denied');command(room,'a','unban',B).result.acknowledgment?.();admit(room,'return',B);expect(room.authority.actors.get(B)!.adventure.state.inventory.wood).toBe(17);expect(a.packets.some(p=>p.type==='ack'&&p.kind==='room-admin'&&p.accepted)).toBe(true);expect(b.closed).toHaveLength(0);
});
it('replays admin receipts without repeating kick and rejects reused command IDs with a different effect',()=>{
 const room=new AuthorityRoom(null,'replay'),a=admit(room,'a',A),b=admit(room,'b',B),kick=command(room,'a','kick',B,'kick-once');expect(room.receive('a',JSON.stringify(kick.packet)).changed).toBe(false);kick.result.acknowledgment?.();expect(b.closed.at(-1)?.code).toBe(4005);const back=admit(room,'back',B);room.receive('a',JSON.stringify(kick.packet)).acknowledgment?.();expect(back.closed).toHaveLength(0);expect(a.packets.at(-1)).toMatchObject({accepted:true});room.receive('a',JSON.stringify({...kick.packet,operation:'ban'}));expect(a.packets.at(-1)).toMatchObject({accepted:false});expect(room.checkpoint().access!.bannedIds).toEqual([]);
 const restored=new AuthorityRoom(validateCheckpoint(room.checkpoint()),'restart');const again=admit(restored,'a',A);restored.receive('a',JSON.stringify(kick.packet)).acknowledgment?.();expect(again.packets.at(-1)).toMatchObject({accepted:true});
});
it('fails closed without any success ACK on uncertain persistence, then resolves from either durable outcome',()=>{
 const room=new AuthorityRoom(null,'failure'),a=admit(room,'a',A),before=room.checkpoint(),lock=command(room,'a','lock','' as never,'save-uncertain'),candidate=room.checkpoint();room.failPersistence();lock.result.acknowledgment?.();expect(room.readOnly).toBe(true);expect(a.closed.at(-1)?.code).toBe(1011);expect(a.packets.some(p=>p.type==='ack'&&p.commandId==='save-uncertain'&&p.accepted)).toBe(false);expect(()=>room.checkpoint()).toThrow('再読込');
 const old=new AuthorityRoom(before,'old');admit(old,'old',A);expect(old.viewAccess(A).locked).toBe(false);const committed=new AuthorityRoom(candidate,'committed'),owner=admit(committed,'owner',A);committed.receive('owner',JSON.stringify(lock.packet)).acknowledgment?.();expect(committed.viewAccess(A).locked).toBe(true);expect(owner.packets.at(-1)).toMatchObject({accepted:true});
});
it('does not grant a failed first claimant a manager welcome, freezes actions, and rejects malformed access state',()=>{
 const room=new AuthorityRoom(null,'claim'),a=admit(room,'a',A,false);room.failPersistence();a.result.acknowledgment?.();expect(a.packets.some(p=>p.type==='welcome')).toBe(false);const fresh=new AuthorityRoom(null,'fresh');const owner=admit(fresh,'owner',A);const lock=command(fresh,'owner','lock');fresh.receive('owner',JSON.stringify({type:'action',commandId:'blocked-game',message:{type:'game-action',action:'drop',id:'berry:1',aim:{x:0,y:0,z:1}}}));expect(owner.packets.at(-1)).toMatchObject({type:'ack',accepted:false});lock.result.acknowledgment?.();const access=fresh.checkpoint().access!;expect(()=>validateRoomAccess({...access,administratorId:B})).toThrow();expect(()=>validateRoomAccess({...access,bannedIds:[A]})).toThrow();expect(()=>validateRoomAccess({...access,receipts:[{operation:'lock',expectedRevision:0,revision:1}]})).toThrow();
});
it('honors CheckpointQueue persist-before-ACK and fails closed on its rejection path',async()=>{
 const {CheckpointQueue}=await import('../../src/networking/checkpoint-queue');const room=new AuthorityRoom(null,'queue'),a=admit(room,'a',A);let finish:()=>void=()=>{},fail=false,captured:RoomCheckpoint|undefined;const queue=new CheckpointQueue(async()=>{captured=room.checkpoint();await new Promise<void>(resolve=>finish=resolve);if(fail)throw Error('quota');},1000);const lock=command(room,'a','lock',undefined,'queued-lock');const result=queue.request().then(()=>lock.result.acknowledgment?.()).catch(()=>room.failPersistence());const flushing=queue.flush();expect(captured?.access?.locked).toBe(true);expect(a.packets.some(p=>p.type==='ack'&&p.commandId==='queued-lock')).toBe(false);finish();await flushing;await result;expect(a.packets.at(-2)).toMatchObject({type:'ack',kind:'room-admin',accepted:true});
 const unlock=command(room,'a','unlock',undefined,'queued-unlock');fail=true;const rejected=queue.request().then(()=>unlock.result.acknowledgment?.()).catch(()=>room.failPersistence());const writing=queue.flush();finish();await writing;await rejected;expect(room.readOnly).toBe(true);expect(a.packets.some(p=>p.type==='ack'&&p.commandId==='queued-unlock'&&p.accepted)).toBe(false);
});
