import {describe,it,expect} from 'vitest';
import {VoxelField} from '../../src/prototype/core/voxel';
import {SurvivalSystem} from '../../src/prototype/core/survival';
import {ElementSystem} from '../../src/prototype/core/elements';
import {EntityElements} from '../../src/prototype/core/entity-elements';
import {VoxelWater} from '../../src/prototype/core/water';
import {CheckpointStore,type SaveStorage} from '../../src/save/checkpoint';
import {record,integer} from '../../src/save/validation';
const terrain=()=>{const f=new VoxelField();f.box({x:-1,y:-1,z:-1},{x:1,y:.25,z:1},3);f.box({x:-.5,y:0,z:-.5},{x:.5,y:1,z:.5},4,'wood');f.captureBaseline('save-test-v1');return f;};
class MemoryStorage implements SaveStorage {readonly data=new Map<string,string>();failKey='';getItem(key:string){return this.data.get(key)??null;}setItem(key:string,value:string){if(key===this.failKey)throw new Error('quota');this.data.set(key,value);}removeItem(key:string){this.data.delete(key);}}
const validate=(v:unknown):v is {wood:number}=>record(v)&&integer(v.wood);
describe('versioned persistent world',()=>{
 it('saves sparse changes and preserves hidden terrain ownership',()=>{const f=terrain();expect(f.exportState().base).toEqual([]);expect(f.exportState().layers.every(l=>l.cells.length===0)).toBe(true);const c=[...f.cells.values()].find(c=>c.object==='wood'&&c.distance<0)!;f.depleteSample(c);f.carve({x:.6,y:.1,z:.6},.3);const saved=f.exportState(),loaded=terrain();expect(loaded.restoreState(JSON.parse(JSON.stringify(saved)))).toBe(true);expect([...loaded.cells]).toEqual([...f.cells]);loaded.removeObject('wood');f.removeObject('wood');expect([...loaded.cells]).toEqual([...f.cells]);});
 it('preserves removed objects and newly authored building layers',()=>{const f=terrain();f.removeObject('wood');f.box({x:2,y:0,z:2},{x:3,y:1,z:3},4,'build:wall:1');const loaded=terrain();expect(loaded.restoreState(f.exportState())).toBe(true);expect([...loaded.cells.values()].some(c=>c.object==='wood')).toBe(false);expect([...loaded.cells]).toEqual([...f.cells]);});
 it('rejects incompatible or malformed terrain without partial writes',()=>{const f=terrain(),before=JSON.stringify(f.exportState());const bad=f.exportState();bad.base.push([0,0,0,NaN,3]);expect(f.restoreState(bad)).toBe(false);expect(f.restoreState({...f.exportState(),baseline:'different-world'})).toBe(false);expect(f.restoreState({...f.exportState(),layers:[...f.exportState().layers,...f.exportState().layers]})).toBe(false);expect(JSON.stringify(f.exportState())).toBe(before);});
 it('does not expose mutable internal samples in snapshots',()=>{const f=terrain();f.carve({x:.6,y:.1,z:.6},.3);const saved=f.exportState(),first=saved.base[0],before=f.sample(first[0],first[1],first[2]);first[3]=-.5;expect(f.sample(first[0],first[1],first[2])).toBe(before);});
 it('preserves pickup identities, pending resources, velocity and selection',()=>{const s=new SurvivalSystem(new VoxelField());for(let i=0;i<200;i++)s.addDrops([{id:`drop-${i}`,material:4,count:2,position:{x:i*2,y:1,z:0}}]);s.drops[0].velocity={x:1,y:2,z:3};s.selected='floor';s.inventory[6]=8;const restored=new SurvivalSystem(new VoxelField());expect(restored.restoreState(JSON.parse(JSON.stringify(s.exportState())))).toBe(true);expect(restored.exportState()).toEqual(s.exportState());expect(restored.addDrops([{id:'drop-0',material:4,count:2,position:{x:0,y:1,z:0}}])).toBe(0);expect(restored.tick(.01,{x:0,y:0,z:0})).toBe(2);const twice=new SurvivalSystem(new VoxelField());expect(twice.restoreState(restored.exportState())).toBe(true);expect(twice.tick(.01,{x:0,y:0,z:0})).toBe(0);expect(twice.inventory[4]).toBe(2);});
 it('rejects duplicated pickups and invalid quantities atomically',()=>{const s=new SurvivalSystem(new VoxelField());s.addDrops([{material:4,count:1,position:{x:0,y:1,z:0}}]);const good=s.exportState();expect(s.restoreState({...good,drops:[...good.drops,...good.drops]})).toBe(false);expect(s.restoreState({...good,inventory:{...good.inventory,4:-1}})).toBe(false);expect(s.restoreState({...good,sequence:0})).toBe(false);expect(s.exportState()).toEqual(good);});
 it('retains workbench location and build sequence without spending inventory again',()=>{const f=new VoxelField();f.box({x:-8,y:-1,z:-8},{x:8,y:.25,z:8},3);f.captureBaseline('floor');const s=new SurvivalSystem(f);s.inventory[4]=24;expect(s.place({x:0,y:.25,z:0},{x:0,y:.25,z:2.2}).ok).toBe(true);const f2=new VoxelField();f2.box({x:-8,y:-1,z:-8},{x:8,y:.25,z:8},3);f2.captureBaseline('floor');expect(f2.restoreState(f.exportState())).toBe(true);const loaded=new SurvivalSystem(f2);expect(loaded.restoreState(s.exportState())).toBe(true);expect(loaded.hasWorkbench({x:0,y:.25,z:2})).toBe(true);expect(loaded.inventory[4]).toBe(16);loaded.selected='floor';expect(loaded.place({x:1.5,y:.25,z:.5},{x:0,y:.25,z:2.2}).ok).toBe(true);expect(loaded.exportState().buildings.map(b=>b.id)).toEqual(['build:workbench:1','build:floor:2']);});
 it('preserves partial durability, damaged-object guards and undelivered drops',()=>{const f=terrain(),e=new ElementSystem(f,new VoxelWater(f));const c=[...f.cells.values()].find(c=>c.object==='wood'&&c.distance<0)!;const point={x:(c.x+.5)*f.size,y:(c.y+.5)*f.size,z:(c.z+.5)*f.size};e.damage({cell:c,point,normal:{x:0,y:1,z:0},distance:0},5,0);const loaded=new ElementSystem(f,new VoxelWater(f));expect(loaded.restoreState(e.exportState())).toBe(true);expect(loaded.durability(c)).toBe(40);expect(loaded.damagedObjects.has('wood')).toBe(true);e.damage({cell:c,point,normal:{x:0,y:1,z:0},distance:0},100,0);expect(loaded.restoreState(e.exportState())).toBe(true);expect(loaded.drainDrops()).toHaveLength(1);expect(loaded.drainDrops()).toHaveLength(0);});
 it('never regenerates enemy reward budgets on load',()=>{const e=new EntityElements(),p={x:0,y:0,z:0};expect(e.deathDrops(p)[0].count).toBe(12);const loaded=new EntityElements();expect(loaded.restoreState(e.exportState())).toBe(true);expect(loaded.deathDrops(p)).toEqual([]);const before=loaded.exportState();expect(loaded.restoreState({...before,reward:12})).toBe(false);expect(loaded.exportState()).toEqual(before);});
});
describe('verified checkpoint storage',()=>{
 it('loads round trips and recovers the previous good save after corruption',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',validate);expect(store.read()).toEqual({status:'empty'});expect(store.write({wood:1})).toEqual({ok:true});expect(store.write({wood:2})).toEqual({ok:true});storage.setItem('world','broken');expect(store.read()).toMatchObject({status:'recovered',data:{wood:1}});expect(store.write({wood:3}).ok).toBe(false);expect(storage.getItem('world')).toBe('broken');expect(store.recoverBackup().ok).toBe(true);expect(storage.getItem('world:corrupt')).toBe('broken');expect(store.read()).toMatchObject({status:'loaded',data:{wood:1}});});
 it('retains successful saves on quota failure and reports failure',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',validate);store.write({wood:1});const raw=storage.getItem('world');storage.failKey='world';expect(store.write({wood:2}).ok).toBe(false);expect(storage.getItem('world')).toBe(raw);expect(store.read()).toMatchObject({status:'loaded',data:{wood:1}});storage.failKey='world:backup';expect(store.write({wood:3}).ok).toBe(false);expect(storage.getItem('world')).toBe(raw);});
 it('refuses future schema downgrade even with a valid backup',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',validate);store.write({wood:1});store.write({wood:2});const e=JSON.parse(storage.getItem('world')!);e.version=2;storage.setItem('world',JSON.stringify(e));expect(store.read().status).toBe('unsupported');expect(store.recoverBackup().ok).toBe(false);expect(store.write({wood:3}).ok).toBe(false);});
 it('preserves the old world on explicit new-game reset',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',validate);store.write({wood:9});const old=storage.getItem('world');expect(store.reset().ok).toBe(true);expect(store.read()).toEqual({status:'empty'});expect(storage.getItem('world:backup')).toBe(old);expect(store.write({wood:0}).ok).toBe(true);expect(storage.getItem('world:backup')).toBe(old);});
 it('handles unavailable storage without throwing or pretending success',()=>{const storage:SaveStorage={getItem(){throw new Error('private');},setItem(){throw new Error('private');},removeItem(){throw new Error('private');}},store=new CheckpointStore(storage,'world',validate);expect(store.read().status).toBe('unavailable');expect(store.write({wood:1}).ok).toBe(false);expect(store.reset().ok).toBe(false);});
 it('rejects checksum damage, missing data and unknown item states',()=>{const storage=new MemoryStorage(),store=new CheckpointStore(storage,'world',validate);store.write({wood:1});const e=JSON.parse(storage.getItem('world')!);e.payload='{"wood":200}';storage.setItem('world',JSON.stringify(e));expect(store.read().status).toBe('invalid');expect(store.write({wood:-1}).ok).toBe(false);});
});
