import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {createShaderWarmup} from '../../src/prototype/rendering/shader-warmup';
function fixture(){const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(),material=new THREE.MeshStandardMaterial(),mesh=new THREE.Mesh(new THREE.BoxGeometry(),material),hidden=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.ShaderMaterial());hidden.visible=false;scene.add(mesh,hidden);let resolve!:()=>void,reject!:(reason:unknown)=>void;const renderer={compileAsync:vi.fn(()=>new Promise<THREE.Object3D>((yes,no)=>{resolve=()=>yes(scene);reject=no;}))};return {scene,camera,mesh,hidden,material,renderer,warmup:createShaderWarmup(renderer,scene,camera),resolve:()=>resolve(),reject:(reason:unknown)=>reject(reason)};}
describe('nonblocking first use of performance PBR shaders',()=>{
 it('waits for async compilation, uses the target lighting scene, and keeps live geometry/parents intact',async()=>{const f=fixture();expect(f.warmup.ready()).toBe(false);expect(f.warmup.ready()).toBe(false);expect(f.renderer.compileAsync).toHaveBeenCalledOnce();const [batch,camera,target]=f.renderer.compileAsync.mock.calls[0] as unknown as [THREE.Group,THREE.Camera,THREE.Scene];expect(camera).toBe(f.camera);expect(target).toBe(f.scene);expect(batch.children).toHaveLength(1);expect((batch.children[0] as THREE.Mesh).material).toBe(f.material);expect((batch.children[0] as THREE.Mesh).geometry).toBe(f.mesh.geometry);expect(f.mesh.parent).toBe(f.scene);expect(f.hidden.parent).toBe(f.scene);f.resolve();await Promise.resolve();expect(f.warmup.ready()).toBe(true);expect(f.warmup.stats).toMatchObject({shaderWarmup:'ready',shaderWarmupBatches:1});});
 it('warms newly visible materials and changed versions without recompiling unchanged terrain',async()=>{const f=fixture();f.warmup.ready();f.resolve();await Promise.resolve();f.hidden.visible=true;expect(f.warmup.ready()).toBe(false);f.resolve();await Promise.resolve();f.material.needsUpdate=true;expect(f.warmup.ready()).toBe(false);f.resolve();await Promise.resolve();for(let i=0;i<10;i++)expect(f.warmup.ready()).toBe(true);expect(f.renderer.compileAsync).toHaveBeenCalledTimes(3);});
 it('accepts Three transparent pass version bumps without an endless warm-up loop',async()=>{const f=fixture();f.material.transparent=true;f.material.side=THREE.DoubleSide;f.renderer.compileAsync.mockImplementation(async()=>{f.material.needsUpdate=true;f.material.needsUpdate=true;return f.scene;});expect(f.warmup.ready()).toBe(false);await Promise.resolve();expect(f.warmup.ready()).toBe(true);for(let i=0;i<20;i++){f.material.needsUpdate=true;f.material.needsUpdate=true;f.warmup.rendered();expect(f.warmup.ready()).toBe(true);}expect(f.renderer.compileAsync).toHaveBeenCalledOnce();});
 it('does not mark a material edit made during compilation ready',async()=>{const f=fixture();f.warmup.ready();f.material.needsUpdate=true;f.resolve();await Promise.resolve();expect(f.warmup.ready()).toBe(false);expect(f.renderer.compileAsync).toHaveBeenCalledTimes(2);});
 it('rewarms existing materials when the effective lighting changes',async()=>{const f=fixture();f.warmup.ready();f.resolve();await Promise.resolve();f.scene.add(new THREE.PointLight());expect(f.warmup.ready()).toBe(false);f.resolve();await Promise.resolve();expect(f.warmup.ready()).toBe(true);expect(f.renderer.compileAsync).toHaveBeenCalledTimes(2);});
 it('does not revive a disposed pipeline when a shader promise resolves',async()=>{const f=fixture();f.warmup.ready();f.warmup.dispose();f.resolve();await Promise.resolve();expect(f.warmup.ready()).toBe(false);expect(f.renderer.compileAsync).toHaveBeenCalledOnce();});
 it('surfaces shader errors instead of silently declaring readiness',async()=>{const f=fixture();f.warmup.ready();f.reject(new Error('shader failed'));await Promise.resolve();expect(()=>f.warmup.ready()).toThrow('shader failed');expect(f.warmup.stats.shaderWarmup).toBe('failed');});
});
