import {SITES} from '../../src/content/adventure-sites';
import {expect,it} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {SkyboundPowers} from '../../src/game/skybound/powers';
import {skyContext} from '../../src/game/skybound/context';
const id=850003,aim={x:0,y:0,z:1};
function setup(){const sim=new GameSimulation(),game=sim.adventure,site=SITES.find(s=>s.id===id)!,o={x:site.x,y:game.state.siteWorld!.bases[id],z:site.z},guide=game.state.resources.find(r=>r.id===SITES.find(s=>s.id===id)!.npc)!;game.state.enemies=[];sim.fluid.restore([]);Object.assign(sim.player,{x:guide.x,y:guide.y,z:guide.z,grounded:true});game.sites.action('site-accept',String(id));const parts=sim.skybound.state.parts.filter(p=>p.loan?.site===id);return {sim,game,o,parts,battery:parts.find(p=>p.kind==='battery')!,emitter:parts.find(p=>p.kind==='emitter')!,lamp:parts.find(p=>p.kind==='lamp')!,device:parts.find(p=>p.kind==='block')!};}
it('lets a player wire the supplied sky emitter instead of requiring direct graph writes',()=>{const {sim,game,o,battery,emitter}=setup();expect(emitter.anchored).toBe(false);Object.assign(sim.player,{x:o.x+1,y:o.y+.2,z:o.z,grounded:true});expect(()=>game.action('sky-grab',String(battery.id),undefined,aim)).not.toThrow();game.action('sky-move',String(battery.id),{x:emitter.position.x-.625,y:emitter.position.y,z:emitter.position.z},aim);expect(()=>game.action('sky-glue',battery.id+':'+emitter.id,undefined,aim)).not.toThrow();expect(battery.links).toContain(emitter.id);game.action('sky-release',String(battery.id));game.action('sky-toggle',String(emitter.id));sim.tick++;sim.skybound.step(1/30,skyContext(sim));expect(sim.skybound.isPowered(emitter.id)).toBe(true);});
it('does not accept passive thaw and water as proof of a real fire-then-water sequence',()=>{const {sim,game,device,lamp,battery}=setup();battery.links=[lamp.id];lamp.links=[battery.id];lamp.enabled=true;device.frozen=0;device.wet=3;game.state.siteWorld!.evidence[id]=2|8;for(let i=0;i<30;i++){sim.tick++;sim.skybound.step(1/30,skyContext(sim));game.sites.step(1/30);}expect(game.state.siteWorld!.evidence[id]&8).toBe(0);expect(game.state.siteWorld!.evidence[id]&1).toBe(0);});
it('migrates only the impossible isolated loan anchor while retaining player parts and valid fixed circuits',()=>{const {sim,emitter,battery}=setup();emitter.anchored=true;emitter.epoch=4;const saved=sim.skybound.save();const custom=structuredClone(emitter);custom.id=90;custom.loan=undefined;custom.creator='host';saved.parts.push(custom);const fixed=structuredClone(emitter);fixed.id=91;fixed.links=[battery.id];saved.parts.push(fixed);battery.links.push(91);saved.parts.find(p=>p.id===battery.id)!.links.push(91);saved.nextId=92;const migrated=new SkyboundPowers(saved).state.parts;expect(migrated.find(p=>p.id===emitter.id)).toMatchObject({anchored:false,epoch:5,position:emitter.position});expect(migrated.find(p=>p.id===90)?.anchored).toBe(true);expect(migrated.find(p=>p.id===91)?.anchored).toBe(true);});
