import {expect,it} from 'vitest';
import {SkyboundPowers} from '../../src/game/skybound/powers';
import {SkyContactCursor} from '../../src/game/skybound/contact-events';
import {createdPreview} from '../../src/game/skybound/preview';
import {ENVIRONMENT_LIMITS,type SkyContext,type SkyPart} from '../../src/game/skybound/types';
import {WORLD} from '../../src/world/types';
function fixture(parts:SkyPart[]){return{powers:new SkyboundPowers({version:2,parts,blueprints:[],fusions:{}}),ctx:{tick:15,bounds:WORLD,player:{x:20,y:2,z:20},inventory:{wood:10},actors:[],solid:(p:{y:number})=>p.y<0} as SkyContext};}
function part(id:number,kind:'block'|'battery'='block'):SkyPart{return{...createdPreview(kind,'wood',{x:id*.5,y:3,z:0}).parts[0],id,enabled:false,...(kind==='battery'?{energy:50}:{})};}
it('chains dry battery heat explosions within eight parts and never silently removes untouched parts',()=>{const{powers,ctx}=fixture(Array.from({length:12},(_,i)=>part(i+1,'battery'))),before={...ctx.inventory};const effects=powers.affect(1,'fire',8,ctx);expect(effects.length).toBeGreaterThan(1);expect(effects.length).toBeLessThanOrEqual(ENVIRONMENT_LIMITS.chainParts);expect(effects.every(e=>e.range===0&&e.radius===3&&e.damage<=24)).toBe(true);expect(powers.state.parts.filter(p=>p.energy===0)).toHaveLength(effects.length);expect(powers.state.parts).toHaveLength(12);expect(ctx.inventory).toEqual(before);expect(powers.snapshot('a').contactEvents?.filter(e=>e.kind==='explosion')).toHaveLength(effects.length);});
it('gives water and frost priority over charged-battery explosion and retains charge when suppressed',()=>{for(const condition of['wet','frost']as const){const battery=part(1,'battery');if(condition==='wet')battery.wet=5;else battery.frozen=4;const{powers,ctx}=fixture([battery]);expect(powers.affect(1,'fire',4,ctx)).toHaveLength(0);expect(powers.state.parts[0].energy).toBe(50);expect(powers.snapshot('a').contactEvents).toEqual([]);}});
it('wind spreads burning downwind within the fixed spread budget while water extinguishes before ignition',()=>{const parts=[part(1),part(2),part(3)];parts[0].burning=6;parts[2].wet=5;const{powers,ctx}=fixture(parts);ctx.wind=()=>({x:1,y:0,z:0});powers.step(1/30,ctx);expect(powers.state.parts[1].burning).toBeGreaterThan(0);expect(powers.state.parts[2].burning??0).toBe(0);});
it('keeps repeated impact presentation idempotent and resets its cursor for a restarted authority tick',()=>{const block=part(1);block.position.y=.51;block.velocity.y=-6;const{powers,ctx}=fixture([block]);powers.step(1/30,ctx);const events=powers.snapshot('a').contactEvents!;expect(events.length).toBeGreaterThan(0);const cursor=new SkyContactCursor();expect(cursor.take(events,ctx.tick)).toHaveLength(events.length);expect(cursor.take(events,ctx.tick)).toEqual([]);expect(cursor.take(events,ctx.tick+1)).toEqual([]);const restart=events.map(e=>({...e,tick:1}));expect(cursor.take(restart,1)).toHaveLength(events.length);expect(powers.save()).not.toHaveProperty('contactEvents');});
it('caps simultaneous explosions and expired event history across repeated authority actions',()=>{const{powers,ctx}=fixture(Array.from({length:32},(_,i)=>({...part(i+1,'battery'),position:{x:-20+i,y:3,z:0}})));for(const p of powers.state.parts)powers.affect(p.id,'fire',4,ctx);const events=powers.snapshot('a').contactEvents!;expect(events.length).toBeLessThanOrEqual(16);ctx.tick+=31;powers.step(1/30,ctx);expect(powers.snapshot('a').contactEvents?.every(e=>e.tick===ctx.tick)).toBe(true);});
it('blocks explosion propagation and wind ignition across a solid wall',()=>{const first=part(1,'battery'),second=part(2,'battery'),{powers,ctx}=fixture([first,second]);ctx.solid=p=>p.x>.7&&p.x<.8;powers.affect(1,'fire',4,ctx);expect(powers.state.parts[1].energy).toBe(50);expect(powers.state.parts[1].burning??0).toBe(0);ctx.wind=()=>({x:1,y:0,z:0});powers.step(1/30,ctx);expect(powers.state.parts[1].burning??0).toBe(0);});
it('uses a fresh presentation epoch after save reconstruction even if the authority tick and part ID are identical',()=>{const first=part(1);first.position.y=.51;first.velocity.y=-6;const a=fixture([first]),b=fixture([first]);a.powers.step(1/30,a.ctx);b.powers.step(1/30,b.ctx);const ae=a.powers.snapshot('a').contactEvents!,be=b.powers.snapshot('a').contactEvents!;expect(ae[0].id).not.toBe(be[0].id);const cursor=new SkyContactCursor();expect(cursor.take(ae,a.ctx.tick)).toHaveLength(1);expect(cursor.take(be,b.ctx.tick)).toHaveLength(1);expect(cursor.take(be,b.ctx.tick)).toEqual([]);});
