import {expect,it} from 'vitest';
import {SkyboundPowers} from '../../src/game/skybound/powers';
import {createdPreview} from '../../src/game/skybound/preview';
import type {SkyContext,SkyMaterial} from '../../src/game/skybound/types';
import {WORLD} from '../../src/world/types';
const aim={x:1,y:0,z:0};
function setup(material:SkyMaterial='wood'){const part={...createdPreview('block',material,{x:2,y:3,z:0}).parts[0],id:1},powers=new SkyboundPowers({version:2,parts:[part],blueprints:[],fusions:{}}),context:SkyContext={tick:1,bounds:WORLD,player:{x:0,y:2,z:0},actors:[],inventory:{wood:13},solid:p=>p.y<0};powers.action('owner','sky-grab','1',undefined,aim,context);return{powers,context,part:powers.state.parts[0]};}
it('throws the actual held authority assembly with a bounded directional impulse and releases its complete lease',()=>{const{powers,context,part}=setup();powers.action('owner','sky-throw','1',undefined,aim,context);expect(part.velocity.x).toBeCloseTo(6);expect(powers.leases.size).toBe(0);for(let i=0;i<8;i++){context.tick++;powers.step(1/30,context);}expect(part.position.x).toBeGreaterThan(3);expect(context.inventory.wood).toBe(13);expect(powers.state.parts).toHaveLength(1);});
it('uses a capped impulse so a heavier metal part travels more slowly than the same wooden part',()=>{const light=setup('wood'),heavy=setup('metal');for(const f of[light,heavy])f.powers.action('owner','sky-throw','1',undefined,aim,f.context);expect(heavy.part.velocity.x).toBe(2);expect(heavy.part.velocity.x).toBeLessThan(light.part.velocity.x);});
it('refuses unowned, expired and invalid direction throws without releasing or moving a valid held object',()=>{const{powers,context,part}=setup();expect(()=>powers.action('other','sky-throw','1',undefined,aim,context)).toThrow('別の冒険者');expect(()=>powers.action('owner','sky-throw','1',undefined,{x:NaN,y:0,z:0},context)).toThrow('方向');expect(part.velocity.x).toBe(0);expect(powers.leases.get(1)?.owner).toBe('owner');context.tick+=151;expect(()=>powers.action('owner','sky-throw','1',undefined,aim,context)).toThrow('掴んで');expect(part.velocity.x).toBe(0);});
it('runs thrown parts through the existing voxel boundary guard without tunneling through a thin wall',()=>{const{powers,context,part}=setup();context.solid=p=>p.y<0||p.x>3&&p.x<3.125;powers.action('owner','sky-throw','1',undefined,aim,context);for(let i=0;i<15;i++){context.tick++;powers.step(1/30,context);expect(part.position.x).toBeLessThanOrEqual(2.5+1e-6);}expect(powers.state.parts).toHaveLength(1);});
