import {expect,it} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
import {createdPreview} from '../../src/game/skybound/preview';
import {DROP_LIMIT} from '../../src/game/interaction/drops';
const aim={x:0,y:0,z:1};
function setup(){const sim=new GameSimulation();sim.fluid.restore([]);sim.adventure.state.enemies=[];sim.adventure.state.resources=[];sim.adventure.state.buildings=[];sim.world.density=()=>1;Object.assign(sim.player,{x:30,y:2,z:30,grounded:false,vy:0});sim.skybound.state.parts=[{...createdPreview('block','wood',{x:30,y:2,z:32}).parts[0],id:1,creator:'host'}];sim.adventure.action('sky-grab','1',undefined,aim);return sim;}
it('keeps the actual part, lease, graph and inventory intact if salvage cannot reserve a drop ID',()=>{const sim=setup(),before=sim.skybound.save(),lease=structuredClone([...sim.skybound.leases]),inventory={...sim.adventure.state.inventory};sim.reserveEntityIds=()=>{throw Error('injected allocation failure');};expect(()=>sim.adventure.action('sky-salvage','1',undefined,aim)).toThrow('allocation');expect(sim.skybound.save()).toEqual(before);expect([...sim.skybound.leases]).toEqual(lease);expect(sim.adventure.state.resources).toEqual([]);expect(sim.adventure.state.inventory).toEqual(inventory);});
it('rejects full ground-drop capacity before deleting the source part',()=>{const sim=setup();sim.adventure.state.resources=Array.from({length:DROP_LIMIT},(_,i)=>({id:i+100,kind:'berry',amount:1,ready:0,drop:true,x:200,y:2,z:200}));sim.adventure.state.resources[0]={id:100,kind:'wood',amount:99,ready:0,drop:true,x:30,y:2,z:32};expect(()=>sim.adventure.action('sky-salvage','1',undefined,aim)).toThrow('上限');expect(sim.adventure.state.resources[0].amount).toBe(99);expect(sim.skybound.state.parts).toHaveLength(1);expect(sim.skybound.leases.get(1)?.owner).toBe('host');expect(sim.adventure.state.resources).toHaveLength(DROP_LIMIT);});
it('commits salvage exactly once as a ground drop',()=>{const sim=setup(),inventory={...sim.adventure.state.inventory};sim.adventure.action('sky-salvage','1',undefined,aim);expect(sim.skybound.state.parts).toHaveLength(0);expect(sim.skybound.leases.size).toBe(0);expect(sim.adventure.state.resources.filter(r=>r.drop)).toHaveLength(1);expect(sim.adventure.state.resources[0]).toMatchObject({kind:'wood',amount:3});expect(sim.adventure.state.inventory).toEqual(inventory);expect(()=>sim.adventure.action('sky-salvage','1',undefined,aim)).toThrow('見つかりません');expect(sim.adventure.state.resources[0].amount).toBe(3);});

it('can salvage at the drop cap if an existing stack has enough capacity, without creating another entity',()=>{const sim=setup();sim.adventure.state.resources=Array.from({length:DROP_LIMIT},(_,i)=>({id:i+100,kind:'berry',amount:1,ready:0,drop:true,x:200,y:2,z:200}));sim.adventure.state.resources[0]={id:100,kind:'wood',amount:97,ready:0,drop:true,x:30,y:2,z:32};sim.adventure.action('sky-salvage','1',undefined,aim);expect(sim.adventure.state.resources).toHaveLength(DROP_LIMIT);expect(sim.adventure.state.resources[0].amount).toBe(100);expect(sim.skybound.state.parts).toHaveLength(0);});
