import {describe,it,expect,vi} from 'vitest';
import {VoxelField,type Hit} from '../../src/prototype/core/voxel';
import {SurvivalSystem} from '../../src/prototype/core/survival';
import {SoilFillSystem,decodeSoilFill,validSoilGeometry,SOIL_FILL_COST,type SoilContext} from '../../src/prototype/core/soil-fill';
import {ElementSystem} from '../../src/prototype/core/elements';
import {VoxelWater} from '../../src/prototype/core/water';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,restoreCampaignInto,defaultSettings} from '../../src/prototype/campaign-session';
import {validCompanionSnapshot} from '../../src/prototype/core/companion';
import {createBuildGhost} from '../../src/prototype/rendering/campaign-decor';
import * as THREE from 'three';
const contact={x:.125,y:.25,z:.125},player={x:.125,y:.25,z:1.8};
function fixture(){const f=new VoxelField();f.box({x:-4,y:-.5,z:-4},{x:4,y:.25,z:4},2);f.captureBaseline('soil-test');const water=new VoxelWater(f),elements=new ElementSystem(f,water),survival=new SurvivalSystem(f,water,elements.damagedObjects);survival.inventory[2]=27;const context:SoilContext={player:{...player},bodies:[],protectedObjects:elements.protectedObjects,bounds:{minX:-4,maxX:4,minZ:-4,maxZ:4}};return {f,water,elements,survival,soil:survival.soil,context};}
const neutral={x:0,z:0,sprint:false,block:false,water:false};
describe('finite paid soil layers',()=>{
 it('previews exact paid SDF bounds without spending and creates a solid walkable quarter-meter step',()=>{const {f,soil,survival,context}=fixture(),before=f.exportState(),p=soil.preview(contact,context);expect(p).toMatchObject({ok:true,cost:9,target:{x:.125,y:.5,z:.125},bounds:{min:{x:-.25,y:0,z:-.25},max:{x:.5,y:.5,z:.5}}});expect(f.exportState()).toEqual(before);expect(survival.inventory[2]).toBe(27);expect(soil.place(contact,context).ok).toBe(true);expect(survival.inventory[2]).toBe(18);expect(f.distance({x:.125,y:.375,z:.125})).toBeLessThan(0);expect(f.ray({x:.125,y:2,z:.125},{x:0,y:-1,z:0},3)?.point.y).toBeCloseTo(.5,2);expect(f.overlaps({x:.125,y:.5,z:.125})).toBe(false);expect(f.overlaps({...contact,y:.27})).toBe(true);});
 it('levels a shallow excavated patch back to its neighboring quarter-meter plane',()=>{const {f,soil,context}=fixture();f.box({x:-.25,y:0,z:-.25},{x:.5,y:.3,z:.5},0);expect(f.distance({x:.125,y:.125,z:.125})).toBeGreaterThan(0);const result=soil.place({...contact,y:0},context);expect(result.ok,result.message).toBe(true);expect(result.target.y).toBe(.25);expect(f.ray({x:.125,y:2,z:.125},{x:0,y:-1,z:0},3)?.point.y).toBeCloseTo(.25,2);expect(f.ray({x:1,y:2,z:.125},{x:0,y:-1,z:0},3)?.point.y).toBeCloseTo(.25,2);});
 it('rejects poverty, bounds, permission, bodies, air, non-soil solids and an occluded surface atomically',()=>{
  for(const scenario of ['poor','bounds','permission','body','air','stone','wall'] as const){const {f,soil,survival,context}=fixture();let target=contact;
   if(scenario==='poor')survival.inventory[2]=8;if(scenario==='bounds')context.bounds.maxX=.25;if(scenario==='permission')context.permission='host denied';if(scenario==='body')context.bodies=[{...contact}];if(scenario==='air')target={...contact,y:1};if(scenario==='stone')f.box({x:0,y:.25,z:0},{x:.25,y:.5,z:.25},3,'rock');if(scenario==='wall')f.box({x:-1,y:.25,z:.8},{x:1,y:2,z:1},4,'wall');const before=survival.exportState(),world=f.exportState();expect(soil.place(target,context).ok,scenario).toBe(false);expect(survival.exportState(),scenario).toEqual(before);expect(f.exportState(),scenario).toEqual(world);
  }
 });
 it('checks protected hidden layers, existing building support and paid layers rather than composed ownership',()=>{const {f,soil,context}=fixture();f.box({x:0,y:.1,z:0},{x:.25,y:.2,z:.25},2,'quest');context.protectedObjects=new Set(['quest']);expect(f.materialAt({x:.125,y:.125,z:.125})?.object).toBeUndefined();expect(soil.place(contact,context).message).toContain('保護');f.removeObject('quest');f.box({x:0,y:.1,z:0},{x:.25,y:.2,z:.25},4,'build:wall:1');expect(soil.place(contact,context).ok).toBe(false);});
 it('returns at most the nine paid units, once, with untouched underlying terrain',()=>{const {f,soil,survival,context}=fixture(),original=f.exportState();soil.place(contact,context);expect(soil.undo(context).ok).toBe(true);expect(survival.inventory[2]).toBe(27);expect(soil.undo(context).ok).toBe(false);expect(f.exportState()).toEqual(original);});
 it('rolls back a partial shape failure without consuming resources or leaving an unowned layer',()=>{const {f,soil,survival,context}=fixture(),before=f.exportState(),write=f.shape.bind(f);vi.spyOn(f,'shape').mockImplementation((...args)=>{write(...args);throw Error('interrupted authoring');});expect(soil.place(contact,context).ok).toBe(false);expect(survival.inventory[2]).toBe(27);expect(soil.snapshot().patches).toEqual([]);expect(f.exportState()).toEqual(before);});
 it('mining one’s overlapping fill creates no drops and permanently loses its dismantle refund, also after save/reload',()=>{const {f,soil,elements,survival,context}=fixture();soil.place(contact,context);const id=soil.snapshot().patches[0].id;const cell=[...f.ownedLayerSamples(id)].find(c=>c.distance<0&&c.y===1)!;const point={x:(cell.x+.5)*.25,y:(cell.y+.5)*.25,z:(cell.z+.5)*.25};const hit:Hit={point,cell,normal:{x:0,y:1,z:0},distance:1};expect(elements.damage(hit,1000,0).destroyed).toBe(1);expect(elements.drainDrops()).toEqual([]);const world=f.exportState(),state=survival.exportState(),e=elements.exportState(),other=fixture();expect(other.f.restoreState(world)).toBe(true);expect(other.survival.restoreState(state)).toBe(true);expect(other.elements.restoreState(e)).toBe(true);expect(validSoilGeometry(other.soil.snapshot(),world)).toBe(true);expect(other.soil.remove(id,context).ok).toBe(true);expect(other.survival.inventory[2]).toBe(18);expect(other.soil.remove(id,context).ok).toBe(false);expect(other.f.distance({x:.125,y:.125,z:.125})).toBeLessThan(0);});
 it('restores a completely mined paid patch without losing the save or reviving its refund',()=>{
  const s=new CoreSimulation(true,false,true);s.survival.inventory[2]=18;s.campaign.state.flameTier=1;s.player.position={x:0,y:.25,z:6};const target={x:0,y:.25,z:4.5};expect(s.survival.soil.place(target,s.soilContext(target)).ok).toBe(true);const id=s.survival.soil.snapshot().patches[0].id;
  for(let pass=0;pass<3;pass++)for(const owned of [...s.arena.field.ownedLayerSamples(id)].filter(c=>c.distance<0)){const cell=s.arena.field.get(owned.x,owned.y,owned.z)!;s.elements.damage({cell,point:{x:(cell.x+.5)*.25,y:(cell.y+.5)*.25,z:(cell.z+.5)*.25},normal:{x:0,y:1,z:0},distance:1},1000,0);}
  expect([...s.arena.field.ownedLayerSamples(id)].filter(c=>c.distance<0)).toEqual([]);// Only the nine pre-existing ground samples beneath the paid shape can drop soil.
  expect(s.elements.drainDrops().reduce((n,d)=>n+d.count,0)).toBeLessThanOrEqual(9);const saved=captureCampaign(s,defaultSettings());expect(restoreCampaignInto(s,saved)).not.toBeNull();expect(s.survival.soil.snapshot()).toEqual(saved.survival.soil);expect(s.survival.inventory[2]).toBe(9);expect(s.survival.soil.remove(id,s.soilContext(target)).ok).toBe(true);expect(s.survival.inventory[2]).toBe(9);
 });
 it('even an undepleted damaged sample disables the refund, including concealed original overlap',()=>{const {f,soil,elements,survival,context}=fixture();soil.place(contact,context);const id=soil.snapshot().patches[0].id,cell=[...f.ownedLayerSamples(id)].find(c=>c.distance<0&&c.y===1)!;elements.damage({cell,point:{x:(cell.x+.5)*.25,y:.375,z:(cell.z+.5)*.25},normal:{x:0,y:1,z:0},distance:1},1,0);expect(soil.remove(id,context).ok).toBe(true);expect(survival.inventory[2]).toBe(18);});
 it('cannot refund support under a body, another tile, or an existing building',()=>{const {f,soil,context}=fixture();soil.place(contact,context);const id=soil.snapshot().patches[0].id;expect(soil.remove(id,{...context,bodies:[{...contact,y:.5}]}).ok).toBe(false);f.box({x:0,y:.5,z:0},{x:.25,y:.8,z:.25},4,'build:wall:2');expect(soil.remove(id,context).ok).toBe(false);});
 it('retains pristine finite entitlement through restoration but never persists an undo operation',()=>{const a=fixture();a.soil.place(contact,a.context);const b=fixture();b.f.restoreState(a.f.exportState());b.survival.restoreState(a.survival.exportState());expect(b.soil.undo(b.context).ok).toBe(false);expect(b.soil.remove(b.soil.snapshot().patches[0].id,b.context).ok).toBe(true);expect(b.survival.inventory[2]).toBe(27);});
 it('rejects missing, added, deepened, moved and wrong-material owned geometry and invalid finite state',()=>{const {f,soil,context}=fixture();soil.place(contact,context);const state=soil.snapshot(),world=f.exportState();expect(validSoilGeometry(state,world)).toBe(true);expect(validSoilGeometry({version:1,sequence:0,patches:[]},world)).toBe(false);
  for(const change of ['missing','extra','deeper','material']){const data=structuredClone(world),layer=data.layers.find(l=>l.id===state.patches[0].id)!;if(change==='missing')data.layers=data.layers.filter(l=>l!==layer);if(change==='extra')layer.cells.push([99,99,99,-.1,2]);if(change==='deeper')layer.cells[0][3]-=.01;if(change==='material')layer.cells[0][4]=6;expect(validSoilGeometry(state,data),change).toBe(false);}
  for(const value of [{...state,sequence:-1},{...state,patches:[{...state.patches[0],cost:18}]},{...state,patches:[{...state.patches[0],position:{x:0,y:.5,z:0}}]}])expect(decodeSoilFill(value)).toBeNull();expect(decodeSoilFill(undefined)).toEqual({version:1,sequence:0,patches:[]});
 });
 it('refreshes water exclusion after accepted fill and conservatively displaces existing volume',()=>{const f=new VoxelField();f.box({x:4,y:-.5,z:-5},{x:10,y:.25,z:1},2);const water=new VoxelWater(f),inventory={2:9},soil=new SoilFillSystem(f,inventory),context:SoilContext={player:{x:5.125,y:.25,z:-1.2},bodies:[],protectedObjects:new Set(),bounds:{minX:4,maxX:10,minZ:-5,maxZ:1}},contact={x:5.125,y:.25,z:-2.875};const i=water.index(9,6,17);water.add(9,6,17,1);const before=water.total();expect(soil.place(contact,context).ok).toBe(true);water.refreshSolids();expect(water.blocked[i]).toBe(1);water.step();expect(water.volume[i]).toBe(0);expect(water.total()).toBeCloseTo(before,6);});
 it('rejects original ground duplication across stacked paid layers and repeated mining/save cycles',()=>{let a=fixture();const originalUnits=[...a.f.cells.values()].filter(c=>c.distance<0).length;let originalDrops=0;for(let round=0;round<3;round++){if(round===0)a.soil.place(contact,a.context);for(const cell of [...a.f.cells.values()].filter(c=>c.distance<0&&c.x===0&&c.z===0&&c.y>=0)){const result=a.elements.damage({cell,point:{x:.125,y:(cell.y+.5)*.25,z:.125},normal:{x:0,y:1,z:0},distance:1},1000,0);if(result.destroyed)originalDrops+=a.elements.drainDrops().reduce((n,d)=>n+d.count,0);}const state=a.survival.exportState(),world=a.f.exportState(),elements=a.elements.exportState(),b=fixture();expect(b.f.restoreState(world)).toBe(true);expect(b.survival.restoreState(state)).toBe(true);expect(b.elements.restoreState(elements)).toBe(true);a=b;}expect(originalDrops).toBeLessThanOrEqual(1);expect(originalDrops).toBeLessThan(originalUnits);expect(a.soil.remove(a.soil.snapshot().patches[0].id,a.context).ok).toBe(true);expect(a.survival.inventory[2]).toBe(18);});
 it('uses matching preview bounds, validity and feedback in the rendered ghost',()=>{const {soil,context}=fixture(),scene=new THREE.Scene(),ghost=createBuildGhost(scene,()=>soil.preview(contact,context));ghost.update(true,0);const mesh=scene.getObjectByName('building-preview')!;expect(mesh.scale.toArray()).toEqual([.75,.5,.75]);expect(mesh.userData.valid).toBe(true);context.permission='host denied';ghost.update(true,100);expect(mesh.userData.valid).toBe(false);expect(mesh.userData.message).toBe('host denied');ghost.dispose();});
});
describe('campaign soil authority and atomic restore',()=>{
 function sim(){const s=new CoreSimulation(true,false,true);s.survival.inventory[2]=18;s.survival.inventory[4]=4;s.survival.inventory[3]=2;s.campaign.craft('terrain-rake',s.player.position);s.campaign.equip('terrain-rake');s.campaign.state.flameTier=1;s.action('chisel',neutral);s.player.pitch=-.8;return s;}
 it('keeps cut as default, toggles per actor, validates host permission and preserves mode isolation',()=>{const s=sim();expect(s.soilFilling).toBe(false);s.action('element-next',neutral);expect(s.soilFilling).toBe(true);const guest=s.enableCompanion({x:3,y:.25,z:6});s.companionAction('chisel');s.companionAction('element-next');expect(s.companionSnapshot()?.aux.soilFill).toBe(true);expect(validCompanionSnapshot(s.companionSnapshot())).toBe(true);const before=s.survival.exportState(),revision=s.arena.field.revision;s.companionAction('attack');s.companionAction('special');expect(s.arena.field.revision).toBe(revision);expect(s.survival.exportState()).toEqual(before);s.companionAction('cast');expect(s.companionSnapshot()?.aux.soilFill).toBe(false);expect(s.soilFilling).toBe(true);expect(guest.tool).toBe(true);});
 it('rejects preview/action before an active hearth or with a broken rake without spending anything',()=>{const s=sim();s.action('element-next',neutral);s.campaign.state.flameTier=0;const before=s.survival.inventory[2];expect(s.soilPreview()?.message).toContain('炉');s.action('attack',neutral);expect(s.survival.inventory[2]).toBe(before);s.campaign.state.flameTier=1;s.campaign.state.gearState['terrain-rake'].durability=0;expect(s.soilPreview()?.message).toContain('破損');s.action('attack',neutral);expect(s.survival.inventory[2]).toBe(before);});
 it('atomically rejects forged soil terrain and budget; accepts missing old soil state',()=>{const s=sim(),original=captureCampaign(s,defaultSettings());const target={x:0,y:.25,z:4.5},context=s.soilContext(target);expect(s.survival.soil.place(target,context).ok).toBe(true);const data=captureCampaign(s,defaultSettings()),before=JSON.stringify(data),p=data.survival.soil!.patches[0],layer=data.field.layers.find(l=>l.id===p.id)!;layer.cells[0][4]=6;expect(restoreCampaignInto(s,data)).toBeNull();expect(JSON.stringify(captureCampaign(s,defaultSettings()))).toBe(before);delete original.survival.soil;expect(restoreCampaignInto(s,original)).not.toBeNull();expect(s.survival.soil.snapshot().patches).toEqual([]);});
});
