import {beforeAll,describe,it,expect} from 'vitest';
import {CoreSimulation,type Controls} from '../../src/prototype/core/simulation';
import {StreamedCampaignField} from '../../src/prototype/core/streamed-campaign-field';
import {createCampaignSamplePrototype,CAMPAIGN_SAMPLE_MANIFEST} from '../../src/prototype/core/campaign-sample-provider';
import {captureCampaign,hydrateCampaign,restoreCampaignInto,defaultSettings,isCampaignSave,getCampaignRestoreFailure,type CampaignSave} from '../../src/prototype/campaign-session';
import {prepareLegacyCampaignMigration} from '../../src/save/campaign-migration';
import {captureSharedCampaign,applySharedCampaign} from '../../src/prototype/campaign-network-state';
const idle:Controls={x:0,z:0,sprint:false,block:false,water:false};
let legacy:CoreSimulation,streamed:CoreSimulation;
beforeAll(()=>{legacy=new CoreSimulation(true);streamed=new CoreSimulation(true,false,true);},20000);
describe('explicit streamed Core runtime',()=>{
 it('starts immediately with the same actor/object roster, safe SDF spawn and no full sample map',()=>{expect(streamed.streamedWorld).toBe(true);expect(streamed.worldReady).toBe(true);expect(streamed.arena.field).toBeInstanceOf(StreamedCampaignField);expect(streamed.arena.field.cells.size).toBe(0);expect(streamed.enemies.map(e=>[e.id,e.hp,e.position])).toEqual(legacy.enemies.map(e=>[e.id,e.hp,e.position]));expect([...streamed.arena.objects]).toEqual([...legacy.arena.objects]);expect(streamed.arena.field.overlaps(streamed.player.position)).toBe(false);expect(streamed.arena.field.get(28,15,-28)?.object).toBe('grapple-mist');expect(captureCampaign(streamed,defaultSettings()).world).toBe('campaign-v3');expect(captureCampaign(legacy,defaultSettings()).world).toBe('campaign-v2');});
 it('mines real samples with the Core tool action and collects finite material drops',()=>{const s=streamed,p=s.player,eye=s.eye(),target={x:-2,y:.56,z:6.25},dx=target.x-eye.x,dy=target.y-eye.y,dz=target.z-eye.z;p.yaw=Math.atan2(-dx,-dz);p.pitch=Math.atan2(dy,Math.hypot(dx,dz));p.tool=true;expect(s.target(2.5)?.hit.cell.object).toBe('sample-wood');s.action('heavy',idle);for(let i=0;i<90;i++)s.tick(1/60,idle);const collected=()=>Object.values(s.survival.inventory).reduce((a,b)=>a+b,0);expect(collected()+[...s.survival.drops,...s.survival.pendingDrops].reduce((a,b)=>a+b.count,0)).toBeGreaterThan(0);if(!collected()){const first=s.survival.drops[0];p.position={x:first.position.x,y:.25,z:first.position.z};s.tick(1/60,idle);}expect(collected()).toBeGreaterThan(0);expect(s.arena.field.cells.size).toBe(0);},10000);
 it('builds, opens and reloads a door in the real v3 Core without losing resources or body state',()=>{const s=new CoreSimulation(true,false,true);s.survival.inventory[4]=40;const player={x:0,y:.25,z:7};expect(s.survival.place({x:0,y:.25,z:8},player).ok).toBe(true);s.survival.selected='door';expect(s.survival.place({x:2,y:.25,z:8.5},player).ok).toBe(true);const id=s.survival.exportState().buildings.find(b=>b.recipe==='door')!.id;expect(s.survival.toggleDoor(id,player).ok).toBe(true);s.enableCompanion({x:1,y:.25,z:6}).hp=39;const data=captureCampaign(s,defaultSettings());expect(data.world).toBe('campaign-v3');expect(data.field.baseline).toBe(CAMPAIGN_SAMPLE_MANIFEST);expect(isCampaignSave(data)).toBe(true);const restored=hydrateCampaign(JSON.parse(JSON.stringify(data)));expect(restored).not.toBeNull();if(!restored)throw new Error('Restore failed');expect(restored.sim.streamedWorld).toBe(true);expect(restored.sim.arena.field.cells.size).toBe(0);expect(restored.sim.survival.exportState()).toEqual(s.survival.exportState());expect(restored.sim.survival.toggleDoor(id,player).ok).toBe(true);expect(restored.sim.survival.inventory[4]).toBe(22);expect(restored.sim.companion?.hp).toBe(39);expect(restored.sim.companionSuspended).toBe(true);},15000);
 it('migrates a certified legacy Core into v3 with all non-geometric game state conserved',()=>{legacy.survival.inventory[4]=23;legacy.survival.inventory[3]=17;legacy.survival.addDrops([{id:'migration-resource',material:6,count:3,position:{x:2,y:1,z:7}}]);legacy.arena.field.carve({x:2,y:.1,z:6},.35);legacy.arena.field.removeObject('tree0');legacy.enableCompanion({x:1,y:.25,z:6}).hp=42;const old=captureCampaign(legacy,defaultSettings()),candidate=prepareLegacyCampaignMigration(old,createCampaignSamplePrototype());expect(candidate).not.toBeNull();if(!candidate)throw new Error('Migration failed');const restored=hydrateCampaign(candidate);expect(restored).not.toBeNull();if(!restored)throw new Error('Hydration failed');const actual=captureCampaign(restored.sim,defaultSettings());const {field:oldField,world:oldWorld,...oldGame}=old,{field:newField,world:newWorld,...newGame}=actual;expect(newGame).toEqual(oldGame);expect(newWorld).toBe('campaign-v3');expect(newField.suppressed).toContain('tree0');expect(restored.sim.arena.field.distance({x:2,y:.1,z:6})).toBe(legacy.arena.field.distance({x:2,y:.1,z:6}));expect(restored.sim.companionSuspended).toBe(true);},15000);
 it('rejects mismatched backends and malformed v3 state atomically',()=>{const data=captureCampaign(streamed,defaultSettings()),before=JSON.stringify(data);expect(restoreCampaignInto(legacy,data)).toBeNull();expect(getCampaignRestoreFailure(legacy)).toBe('envelope');const invalid={...data,field:{...data.field,suppressed:['unknown-layer']}};expect(restoreCampaignInto(streamed,invalid)).toBeNull();expect(JSON.stringify(captureCampaign(streamed,defaultSettings()))).toBe(before);expect(isCampaignSave({...data,world:'campaign-v9'})).toBe(false);expect(isCampaignSave({...data,field:{...data.field,baseline:'unknown'}})).toBe(false);});
 it('shares v3 state with manifest-aware reuse while preserving the guest actor',()=>{const host=new CoreSimulation(true,false,true),guest=new CoreSimulation(true,false,true),data=captureSharedCampaign(host,defaultSettings());guest.player.yaw=1;expect(applySharedCampaign(guest,data).ok).toBe(true);const revision=guest.arena.field.revision;expect(applySharedCampaign(guest,data).ok).toBe(true);expect(guest.arena.field.revision).toBe(revision);expect(guest.player.yaw).toBe(1);expect(applySharedCampaign(legacy,data).ok).toBe(false);},15000);
});
