import {expect,it} from 'vitest';
import {TerrainQueue,meshBytes} from '../../src/platform/terrain-queue';
import type {MeshData} from '../../src/world/types';
const mesh=(id:string,n=3):MeshData=>({id,positions:new Float32Array(n),normals:new Float32Array(n),colors:new Float32Array(n),indices:new Uint32Array(n),milliseconds:0});
it('limits a burst to two uploaded bricks per frame',()=>{const queue=new TerrainQueue(),applied:string[]=[];for(let i=0;i<100;i++)queue.enqueue(mesh(String(i)));expect(queue.flush(m=>applied.push(m.id),()=>{},()=>0)).toBe(2);expect(applied).toEqual(['0','1']);expect(queue.size).toBe(98);});
it('stops after the first indivisible upload exhausts the time budget',()=>{const queue=new TerrainQueue();let time=0;queue.enqueue(mesh('a'));queue.enqueue(mesh('b'));expect(queue.flush(()=>{time+=3;},()=>{},()=>time)).toBe(1);expect(queue.stats.maxMilliseconds).toBe(3);expect(queue.size).toBe(1);});
it('counts coarse and grass transfer sizes and bounds uploaded bytes',()=>{const queue=new TerrainQueue(),a=mesh('a',20000);a.grass=new Float32Array(100);a.coarse=mesh('a',1000);expect(meshBytes(a)).toBe(336400);queue.enqueue(a);queue.enqueue(mesh('b',20000));expect(queue.flush(()=>{},()=>{},()=>0)).toBe(1);expect(queue.stats.bytes).toBe(336400);});
it('coalesces replacement generations and acknowledges discarded work exactly once',()=>{const queue=new TerrainQueue(),a=mesh('a'),b=mesh('a',6);expect(queue.enqueue(a)).toBe(0);expect(queue.enqueue(b)).toBe(1);const received:MeshData[]=[];expect(queue.flush(m=>received.push(m),()=>{},()=>0)).toBe(1);expect(received).toEqual([b]);});
it('an unload supersedes a queued mesh and a later reload supersedes removal',()=>{const queue=new TerrainQueue();queue.enqueue(mesh('a'));expect(queue.remove(['a'])).toBe(1);expect(queue.enqueue(mesh('a',6))).toBe(0);const removed:string[]=[];expect(queue.flush(()=>{},id=>removed.push(id),()=>0)).toBe(1);expect(removed).toEqual([]);});
it('budgets removals and clears pending work on reset',()=>{const queue=new TerrainQueue(),removed:string[]=[];queue.remove(['a','b','c']);queue.enqueue(mesh('d'));queue.flush(()=>{},id=>removed.push(id),()=>0);expect(removed).toEqual(['a','b','c']);expect(queue.clear()).toBe(0);expect(queue.size).toBe(0);});

it('a160-brick boundary unload cannot starve the first incoming mesh',()=>{const queue=new TerrainQueue();queue.remove(Array.from({length:160},(_,i)=>String(i)));queue.enqueue(mesh('new'));const applied:string[]=[];queue.flush(m=>applied.push(m.id),()=>{},()=>0);expect(applied).toEqual(['new']);expect(queue.stats.removed).toBe(32);});
it('filters unrendered/empty removals while acknowledging queued stale meshes',()=>{const queue=new TerrainQueue();queue.enqueue(mesh('stale'));expect(queue.remove(['stale',...Array.from({length:160},(_,i)=>String(i))],()=>false)).toBe(1);expect(queue.size).toBe(0);queue.enqueue(mesh('new'));expect(queue.flush(()=>{},()=>{},()=>0)).toBe(1);});

it('a ready fence waits for already-published nearby meshes but not continuous distant streaming',()=>{const queue=new TerrainQueue();queue.enqueue(mesh('near'));const ready=queue.fence();queue.enqueue(mesh('far'));expect(queue.hasPending(ready)).toBe(true);queue.flush(()=>{},()=>{},()=>0,{items:1,bytes:512*1024,milliseconds:2});expect(queue.size).toBe(1);expect(queue.hasPending(ready)).toBe(false);});
it('drains bounded empty density fields without spending the two GPU uploads',()=>{const queue=new TerrainQueue();for(let i=0;i<12;i++){const m=mesh('empty'+i,0);m.field={id:m.id,origin:{x:0,y:0,z:0},size:2,step:8,density:new Float32Array(8).fill(1),surface:false};queue.enqueue(m);}for(let i=0;i<3;i++)queue.enqueue(mesh('surface'+i));const ids:string[]=[];expect(queue.flush(m=>ids.push(m.id),()=>{},()=>0)).toBe(10);expect(ids.filter(x=>x.startsWith('empty'))).toHaveLength(8);expect(ids.filter(x=>x.startsWith('surface'))).toHaveLength(2);expect(queue.size).toBe(5);});
