import {it,expect} from 'vitest';
import {SessionAuthority} from '../../src/simulation/session';
import {raceGates,validateRace} from '../../src/game/trail-race';
import {validateSave} from '../../src/save/format';
const aim={x:0,y:0,z:-1};
it('finishes the six gates using actual movement input and keeps personal records on reload',()=>{const r=new SessionAuthority(),sim=r.sim,npc=sim.adventure.state.resources.find(n=>n.id===830001)!;sim.fluid.restore([]);Object.assign(sim.player,{x:npc.x,y:sim.groundAt(npc.x,npc.z),z:npc.z,grounded:true});r.action('host',{type:'game-action',action:'race',id:'start',aim});let sequence=0;
 for(let i=0;i<2600&&sim.adventure.state.race?.run;i++){const run=sim.adventure.state.race.run,target=raceGates(sim)[run.next],dx=target.x-sim.player.x,dz=target.z-sim.player.z,n=Math.hypot(dx,dz);sim.adventure.state.enemies=[];r.input('host',{x:dx/Math.max(n,.01),z:dz/Math.max(n,.01),jump:false},++sequence);r.step();}
 expect(sim.adventure.state.race?.message).toBe('finished');expect(sim.adventure.state.race?.finishes).toBe(1);expect(sim.adventure.state.race!.best).toBeLessThan(90);const restored=new SessionAuthority(validateSave(r.save()));expect(restored.sim.adventure.state.race!.finishes).toBe(1);expect(restored.join('newcomer').adventure.state.race).toBeUndefined();});
it('invalidates teleport, checks start position and rejects malformed saved coordinates',()=>{const r=new SessionAuthority();expect(()=>r.action('host',{type:'game-action',action:'race',id:'start',aim})).toThrow('キリ');const sim=r.sim,npc=sim.adventure.state.resources.find(n=>n.id===830001)!;Object.assign(sim.player,{x:npc.x,y:npc.y,z:npc.z,grounded:true});sim.tick+=4;r.action('host',{type:'game-action',action:'race',id:'start',aim});sim.player.x+=30;sim.adventure.race.step(1/30);expect(sim.adventure.state.race!.message).toBe('cancelled');expect(()=>validateRace({finishes:0,run:{started:0,next:0,previous:{y:0,z:0}}})).toThrow();});
