import {expect,it} from 'vitest';
import {GameSimulation} from '../../src/simulation/game-simulation';
const input={x:0,z:0,jump:false};
function setup(){const sim=new GameSimulation();sim.fluid.restore([]);sim.adventure.state.enemies=[];sim.adventure.state.resources=[];sim.adventure.state.buildings=[];sim.skybound.state.parts=[];sim.adventure.state.stamina=50;Object.assign(sim.player,{x:40,y:1,z:40,heading:0,vy:0,grounded:false});return sim;}
it('warns before submerged breath runs out, damages at a bounded cadence, and recovers above water',()=>{
 const sim=setup();sim.fluid.immersion=()=>1;const game=sim.adventure,hp=game.state.health;
 for(let i=0;i<75;i++)game.traversal.beforeMove(input,.1);
 expect(game.traversal.snapshot().warning).toContain('息');expect(game.state.health).toBe(hp);
 for(let i=0;i<60;i++)game.traversal.beforeMove(input,.1);
 expect(game.state.health).toBeLessThan(hp);expect(game.traversal.snapshot().breath).toBe(0);
 sim.fluid.immersion=()=>0;game.traversal.beforeMove(input,1);expect(game.traversal.snapshot().breath).toBe(4);expect(game.traversal.snapshot().warning).toBeUndefined();
});
it('warns about swimming fatigue while the head is still above water',()=>{const sim=setup();sim.fluid.immersion=(_p,height)=>height===1.45?.7:0;sim.adventure.state.stamina=12;sim.adventure.traversal.beforeMove(input,.1);expect(sim.adventure.traversal.snapshot()).toMatchObject({swimming:true,breath:12});expect(sim.adventure.traversal.snapshot().warning).toContain('岸');});
it('mantles a swim bank on jump+direction and consumes stamina once',()=>{const sim=setup();sim.world.density=p=>p.z>40.45&&p.y<1.8?-1:1;sim.fluid.immersion=p=>p.z<40.45? .8:0;const game=sim.adventure,before=game.state.stamina;const move=game.traversal.beforeMove({x:0,z:1,jump:true},1/30);expect(move.handled).toBe(true);expect(sim.player.z).toBeCloseTo(40.8);expect(sim.player.y).toBeGreaterThan(1.8);expect(game.state.stamina).toBe(before-5);});
it('rejects bank mantling through a ceiling or another player without spending stamina',()=>{for(const obstacle of['ceiling','actor']){const sim=setup();sim.world.density=p=>p.z>40.45&&p.y<1.8||obstacle==='ceiling'&&p.y>2.6?-1:1;sim.fluid.immersion=p=>p.z<40.45?.8:0;if(obstacle==='actor')sim.targets=[{player:{...sim.player,x:40,z:40.8,y:1.8},adventure:{owner:'guest',state:sim.adventure.state} as typeof sim.adventure}];const before=sim.adventure.state.stamina;expect(sim.adventure.traversal.beforeMove({x:0,z:1,jump:true},1/30).handled).toBe(false);expect(sim.player.z).toBe(40);expect(sim.adventure.state.stamina).toBe(before);}});
it('hangs with no movement, climbs with input, and slips from wet stone only after a warning interval',()=>{const sim=setup();sim.world.density=p=>p.z>40.5?-1:1;const game=sim.adventure;game.action('climb','on',undefined,{x:0,y:0,z:1});game.traversal.beforeMove(input,.1);expect(sim.player.y).toBe(1);expect(game.traversal.snapshot().hanging).toBe(true);game.traversal.beforeMove({x:0,z:1,jump:false},.1);expect(sim.player.y).toBeGreaterThan(1);game.state.stamina=100;game.state.meadows!.wet=100;for(let i=0;i<32;i++)game.traversal.beforeMove(input,.1);expect(game.traversal.climbing).toBe(false);expect(sim.player.vy).toBeLessThan(0);});
it('reads grip from carved wooden wall and tree voxels rather than treating every fixed surface as stone',()=>{for(const kind of['wall','tree']){const sim=setup();sim.world.density=()=>1;if(kind==='wall')sim.adventure.state.buildings=[{id:1,definition:'wall',x:40,y:1,z:40.65,rotation:0,support:4,contents:{}}];else sim.adventure.state.resources=[{id:20,kind:'beech',x:40,y:1,z:40.75,amount:10,ready:0}];const game=sim.adventure;game.state.stamina=100;game.state.meadows!.wet=100;game.action('climb','on',undefined,{x:0,y:0,z:1});game.traversal.beforeMove(input,.1);expect(game.traversal.snapshot().grip).toBe('wood');for(let i=0;i<35;i++)game.traversal.beforeMove(input,.1);expect(game.traversal.climbing).toBe(true);}});

it('does not mantle a downed swimmer even when a jump command and stamina remain',()=>{const sim=setup();sim.world.density=p=>p.z>40.45&&p.y<1.8?-1:1;sim.fluid.immersion=p=>p.z<40.45?.8:0;sim.adventure.state.health=0;expect(sim.adventure.traversal.beforeMove({x:0,z:1,jump:true},1/30).handled).toBe(false);expect(sim.player.z).toBe(40);});

it('never applies drowning health damage while replaying client prediction inputs',()=>{const sim=setup(),health=sim.adventure.state.health;sim.fluid.immersion=()=>1;for(let i=0;i<500;i++)sim.adventure.traversal.beforeMove(input,1/30,false);expect(sim.adventure.state.health).toBe(health);});
