import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {voxelAppearance,voxelGeometry,configureVoxelMaterial,WorldMeshes} from '../../src/prototype/rendering/meshes';
import {extractSurface} from '../../src/prototype/core/surface';
import {VoxelField} from '../../src/prototype/core/voxel';
import {REGIONS} from '../../src/prototype/core/regions';
const center=(id:string)=>{const r=REGIONS.find(r=>r.id===id)!;return {x:(r.bounds.minX+r.bounds.maxX)/2,y:r.groundY,z:(r.bounds.minZ+r.bounds.maxZ)/2};};
const luminance=(c:THREE.Color)=>c.r*.2126+c.g*.7152+c.b*.0722;
describe('original per-material PBR rendering',()=>{
 it('makes wood warm, leaves green, and metal brighter/less rough than soil or stone',()=>{const wood=voxelAppearance(4,0,1,0,0),leaf=voxelAppearance(7,0,1,0,0),metal=voxelAppearance(6,0,1,0,0),soil=voxelAppearance(2,0,1,0,0),stone=voxelAppearance(3,0,1,0,0);expect(wood.color.r).toBeGreaterThan(wood.color.b*2);expect(leaf.color.g).toBeGreaterThan(leaf.color.r);expect(metal.metalness).toBeGreaterThan(.7);expect(metal.roughness).toBeLessThan(stone.roughness);expect(luminance(metal.color)).toBeGreaterThan(luminance(soil.color));expect(stone.metalness).toBeLessThan(.1);});
 it('tints upward soil faces with grass while retaining exposed earth on the sides',()=>{const top=voxelAppearance(2,0,.25,0,1),side=voxelAppearance(2,0,.25,0,0),bottom=voxelAppearance(2,0,.25,0,-1);expect(top.color.g/top.color.r).toBeGreaterThan(side.color.g/side.color.r);expect(side.color.toArray()).toEqual(bottom.color.toArray());expect(top.roughness).toBe(side.roughness);});
 it('uses bounded regional snow, copper and ash accents, leaving distant/high structures unchanged',()=>{const snow=center('rimepass'),copper=center('coppermesa'),ash=center('cinderkeep');const snowTop=voxelAppearance(3,snow.x,snow.y,snow.z,1),snowSide=voxelAppearance(3,snow.x,snow.y,snow.z,0);expect(luminance(snowTop.color)).toBeGreaterThan(luminance(snowSide.color)*1.4);const warm=voxelAppearance(3,copper.x,copper.y,copper.z,1);expect(warm.color.r/warm.color.b).toBeGreaterThan(1.5);const dusty=voxelAppearance(2,ash.x,ash.y,ash.z,1);expect(Math.abs(dusty.color.r-dusty.color.g)).toBeLessThan(.12);const high=voxelAppearance(3,snow.x,snow.y+5,snow.z,1),highSide=voxelAppearance(3,snow.x,snow.y+5,snow.z,0);expect(high.color.toArray()).toEqual(highSide.color.toArray());});
 it('emits light only for the flame material and reuses an appearance object when supplied',()=>{const out=voxelAppearance(9,0,1,0,1);expect(out.emission).toBe(1.8);for(const id of [1,2,3,4,5,6,7,8,10,999]){expect(voxelAppearance(id,0,1,0,1,out)).toBe(out);expect(out.emission).toBe(0);expect(out.roughness).toBeGreaterThanOrEqual(.04);expect(out.roughness).toBeLessThanOrEqual(1);}});
 it('keeps SDF surface positions, normals, triangles and authoritative material IDs unchanged',()=>{const f=new VoxelField(.25);f.box({x:-1,y:-.5,z:-1},{x:1,y:.25,z:1},2);f.box({x:-.5,y:.25,z:-.5},{x:.5,y:1.25,z:.5},6,'metal');const before=[...f.cells].map(([key,c])=>[key,{...c}]),revision=f.revision,data=extractSurface(f),g=voxelGeometry(f),flat=g.toNonIndexed();expect(flat.getAttribute('position').count).toBe(data.positions.length/3);for(const [name,source] of [['position',data.positions],['normal',data.normals]] as const){const actual=flat.getAttribute(name).array,wanted=new Float32Array(source);expect(actual.length).toBe(wanted.length);for(let i=0;i<wanted.length;i++)expect(Math.abs(actual[i]-wanted[i])).toBeLessThan(.00002);}const count=g.getAttribute('position').count;expect(g.getAttribute('color').count).toBe(count);expect(g.getAttribute('voxelSurface').count).toBe(count);expect(g.getAttribute('voxelSurface').itemSize).toBe(3);const materialCounts:Record<number,number>={};for(const id of data.materials)materialCounts[id]=(materialCounts[id]??0)+1;expect(g.userData.sourceMaterialCounts).toEqual(materialCounts);expect([...f.cells].map(([key,c])=>[key,{...c}])).toEqual(before);expect(f.revision).toBe(revision);flat.dispose();g.dispose();});
 it('patches installed Three standard chunks while retaining standard lights and torch emission',()=>{const m=configureVoxelMaterial(new THREE.MeshStandardMaterial({vertexColors:true})),shader={vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader,uniforms:{}};for(const token of ['#include <common>','#include <begin_vertex>'])expect(shader.vertexShader).toContain(token);for(const token of ['#include <roughnessmap_fragment>','#include <metalnessmap_fragment>','#include <emissivemap_fragment>'])expect(shader.fragmentShader).toContain(token);m.onBeforeCompile(shader as Parameters<typeof m.onBeforeCompile>[0],{} as THREE.WebGLRenderer);expect(shader.vertexShader).toContain('attribute vec3 voxelSurface;');expect(shader.vertexShader).toContain('vVoxelSurface = voxelSurface;');expect(shader.fragmentShader).toContain('roughnessFactor = clamp(vVoxelSurface.x');expect(shader.fragmentShader).toContain('metalnessFactor = clamp(vVoxelSurface.y');expect(shader.fragmentShader).toContain('totalEmissiveRadiance += vColor.rgb');expect(shader.fragmentShader).toContain('#include <lights_fragment_begin>');expect(THREE.ShaderChunk.roughnessmap_fragment).toContain('roughnessFactor');expect(THREE.ShaderChunk.metalnessmap_fragment).toContain('metalnessFactor');expect(m.customProgramCacheKey()).toBe('ash-voxel-pbr-v2');m.dispose();});
 it('keeps one shared material and disposes all extended geometries during eviction and shutdown',()=>{const f=new VoxelField(.25);f.box({x:-1,y:-.5,z:4},{x:1,y:.25,z:7},2);const scene=new THREE.Scene(),world=new WorldMeshes(f,scene);world.sync({x:0,y:.25,z:6},64);expect(world.chunks.size).toBeGreaterThan(0);const meshes=[...world.chunks.values()],dispose=meshes.map(mesh=>vi.spyOn(mesh.geometry,'dispose'));expect(meshes.every(mesh=>mesh.material===world.material)).toBe(true);expect(meshes.every(mesh=>mesh.geometry.hasAttribute('voxelSurface'))).toBe(true);world.sync({x:70,y:0,z:70},0);for(const spy of dispose)expect(spy).toHaveBeenCalledOnce();expect(world.chunks.size).toBe(0);const materialDispose=vi.spyOn(world.material,'dispose');world.dispose();expect(materialDispose).toHaveBeenCalledOnce();});
});
