import {it,expect,vi} from 'vitest';
import {VoxelField} from '../../src/prototype/core/voxel';
import {sampleWarmth,WarmthProbe,type WarmthSource} from '../../src/prototype/core/warmth';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,hydrateCampaign,defaultSettings} from '../../src/prototype/campaign-session';
const idle={x:0,z:0,sprint:false,block:false,water:false};
function sourceFixture(){const field=new VoxelField();field.box({x:-.5,y:0,z:-.5},{x:.5,y:.5,z:.5},3,'stove');const source:WarmthSource={position:{x:0,y:1,z:0},object:'stove',radius:4,strength:1};return {field,source,position:{x:1.5,y:0,z:0}};}
it('warms near a physically present hearth, fades with distance and cannot pass a wall',()=>{const {field,source,position}=sourceFixture();const close=sampleWarmth(position,field,[source]);expect(close.strength).toBeGreaterThan(.5);expect(sampleWarmth({x:3.5,y:0,z:0},field,[source]).strength).toBeLessThan(close.strength);expect(sampleWarmth({x:5,y:0,z:0},field,[source]).strength).toBe(0);field.box({x:.8,y:0,z:-1},{x:1,y:2,z:1},3,'wall');expect(sampleWarmth(position,field,[source]).strength).toBe(0);});
it('unlit or destroyed hearths cannot provide invisible heat',()=>{const {field,source,position}=sourceFixture();expect(sampleWarmth(position,field,[]).strength).toBe(0);field.removeObject('stove');expect(sampleWarmth(position,field,[source]).strength).toBe(0);});
it('burning material heat checks the exact visible cell, not a shared object name',()=>{const field=new VoxelField();field.box({x:.75,y:0,z:-.5},{x:1,y:1.5,z:.5},4,'fire-wall');const cell=[...field.cells.values()].find(c=>c.distance<0&&c.y===3&&c.z===0)!;const source:WarmthSource={position:{x:(cell.x+.5)*.25,y:(cell.y+.5)*.25,z:(cell.z+.5)*.25},cell,radius:2.5,strength:.7},position={x:0,y:0,z:0};expect(sampleWarmth(position,field,[source]).strength).toBeGreaterThan(0);field.box({x:.25,y:0,z:-.5},{x:.5,y:2,z:.5},3,'fire-wall');expect(sampleWarmth(position,field,[source]).strength).toBe(0);field.removeObject('fire-wall');expect(sampleWarmth(position,field,[source]).strength).toBe(0);});
it('bounds heat rays and never adds stacked heat beyond one source',()=>{const {field,source,position}=sourceFixture(),ray=vi.spyOn(field,'ray');const out=sampleWarmth(position,field,Array.from({length:400},()=>source));expect(out.rays).toBeLessThanOrEqual(16);expect(ray).toHaveBeenCalledTimes(out.rays);expect(out.strength).toBeLessThan(1);});
it('caches stationary sampling but invalidates terrain edits, movement and restored clocks',()=>{const {field,source,position}=sourceFixture(),probe=new WarmthProbe(),sources=vi.fn(()=>[source]);probe.sample(position,field,1,sources);probe.sample(position,field,1.1,sources);expect(sources).toHaveBeenCalledTimes(1);probe.sample(position,field,1.3,sources);expect(sources).toHaveBeenCalledTimes(2);field.box({x:8,y:0,z:8},{x:9,y:1,z:9},3);probe.sample(position,field,1.31,sources);probe.sample({...position,x:2},field,1.32,sources);probe.sample(position,field,0,sources);expect(sources).toHaveBeenCalledTimes(5);});
it('lit regional hearth lowers actual cold in the frozen region; unclaimed hearth does not',()=>{const sim=new CoreSimulation(true,false,true);sim.player.position={x:-11.4,y:5.25,z:-47};sim.cold=60;sim.tick(.1,idle);expect(sim.warmth).toBe(0);expect(sim.cold).toBeGreaterThan(60);sim.campaign.state.claimedPoints.push('rg-rime-hearth');for(let i=0;i<60;i++)sim.tick(1/60,idle);expect(sim.warmth).toBeGreaterThan(.4);expect(sim.cold).toBeLessThan(60);});
it('keeps warmth per actor and derives it again after save reload without new persisted state',()=>{const sim=new CoreSimulation(true,false,true);sim.campaign.state.flameTier=1;sim.player.position={x:-3,y:.25,z:5.5};sim.enableCompanion({x:6,y:.25,z:6});expect(sim.warmth).toBeGreaterThan(.4);expect(sim.withCompanion(()=>sim.warmth)).toBe(0);sim.setCompanionConnected(false);const saved=captureCampaign(sim,defaultSettings());const restored=hydrateCampaign(saved);expect(restored).not.toBeNull();expect(restored!.sim.warmth).toBeGreaterThan(.4);expect(saved).not.toHaveProperty('warmth');});

it('actual fire warms until an actual water cast extinguishes its material samples',()=>{const sim=new CoreSimulation(true,false,true);sim.player.position={x:0,y:.25,z:6};sim.arena.field.box({x:1,y:.25,z:5.7},{x:1.25,y:1.25,z:6.3},4,'warmth-test-wood');const hit=sim.arena.field.ray({x:0,y:.875,z:6.125},{x:1,y:0,z:0},2)!;expect(hit.cell.object).toBe('warmth-test-wood');sim.elements.cast('fire',hit,{x:1,y:0,z:0});expect(sim.warmth).toBeGreaterThan(0);sim.elements.cast('water',hit,{x:1,y:0,z:0});sim.seconds+=.3;expect(sim.warmth).toBe(0);});
