import {describe,it,expect,vi} from 'vitest';
import * as THREE from 'three';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {WaterVisibilityProbe} from '../../src/prototype/rendering/water-visibility';
function setup(){const camera=new THREE.PerspectiveCamera(65,16/9,.1,50);camera.position.set(5.5,2,3.5);camera.lookAt(6,0,-2);camera.updateProjectionMatrix();const water=new THREE.Object3D(),ray=vi.fn(()=>null as {distance:number}|null),surface=vi.fn(()=>0);return {camera,water,ray,surface,probe:new WaterVisibilityProbe(camera,{ray},water,surface)};}
describe('shared bounded water visibility',()=>{
 it.each(['balanced','high'] as const)('detects visible unoccluded water in %s',mode=>{const s=setup();s.probe.update(.016,mode);expect(s.water.userData.reflectionVisible).toBe(true);expect(s.ray.mock.calls.length).toBeLessThanOrEqual(12);});
 it('resets and skips all visibility work in performance, then refreshes immediately on returning to balanced',()=>{const s=setup();s.probe.update(.016,'high');expect(s.water.userData.reflectionVisible).toBe(true);s.ray.mockClear();s.surface.mockClear();s.probe.update(100,'performance');expect(s.water.userData.reflectionVisible).toBe(false);expect(s.ray).not.toHaveBeenCalled();expect(s.surface).not.toHaveBeenCalled();s.probe.update(.001,'balanced');expect(s.water.userData.reflectionVisible).toBe(true);});
 it('keeps occluded, dry, hidden or off-camera water out of visibility statistics',()=>{const s=setup();s.ray.mockReturnValue({distance:.1});s.probe.update(.2,'balanced');expect(s.water.userData.reflectionVisible).toBe(false);s.ray.mockReturnValue(null);s.surface.mockReturnValue(NaN);s.probe.update(.2,'balanced');expect(s.water.userData.reflectionVisible).toBe(false);s.surface.mockReturnValue(0);s.water.visible=false;s.probe.update(.2,'balanced');expect(s.water.userData.reflectionVisible).toBe(false);s.water.visible=true;s.camera.lookAt(5.5,2,20);s.probe.update(.2,'balanced');expect(s.water.userData.reflectionVisible).toBe(false);});
 it('throttles repeated queries and bounds each sample pass',()=>{const s=setup();s.ray.mockReturnValue({distance:.1});s.probe.update(.016,'balanced');const samples=s.surface.mock.calls.length;expect(samples).toBe(12);for(let i=0;i<10;i++)s.probe.update(.01,'balanced');expect(s.surface).toHaveBeenCalledTimes(samples);s.probe.update(.11,'balanced');expect(s.surface).toHaveBeenCalledTimes(samples*2);});
});

it('detects the actual trial basin from the recorded SDF browser camera without changing terrain',()=>{const sim=new CoreSimulation(),camera=new THREE.PerspectiveCamera(74,960/540,.035,120),water=new THREE.Object3D();camera.rotation.order='YXZ';camera.position.set(5.4396,.2225+1.52,1.8104);camera.rotation.set(0,0,0);camera.updateProjectionMatrix();const probe=new WaterVisibilityProbe(camera,sim.arena.field,water,(x,z)=>sim.water.surface(x,z));probe.update(.016,'balanced');expect(water.userData.reflectionVisible).toBe(true);probe.update(.016,'performance');expect(water.userData.reflectionVisible).toBe(false);probe.update(.016,'balanced');expect(water.userData.reflectionVisible).toBe(true);});
