import {describe,it,expect} from 'vitest';
import {CoreSimulation} from '../../src/prototype/core/simulation';
import {captureCampaign,restoreCampaignInto,hydrateCampaign,isCampaignSave,isStreamedCampaignSave,defaultSettings,getCampaignRestoreFailure,createCampaignStore,STREAMED_CAMPAIGN_STORE_KEY,WESTERN_CAMPAIGN_STORE_KEY} from '../../src/prototype/campaign-session';
import {captureSharedCampaign,applySharedCampaign} from '../../src/prototype/campaign-network-state';
import {selectCampaignStore,CAMPAIGN_FORMAT_SELECTOR} from '../../src/save/campaign-store-selection';
import {WESTERN_MIGRATION_ARCHIVE,preserveWesternMigrationBackup} from '../../src/save/western-campaign-migration';
import {checksum} from '../../src/save/validation';
import type {SaveStorage} from '../../src/save/checkpoint';
const fresh=()=>new CoreSimulation(true,false,true,true);
const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
class Storage implements SaveStorage {values=new Map<string,string>();fail='';getItem(k:string){return this.values.get(k)??null;}setItem(k:string,v:string){if(k===this.fail)throw new Error('quota');this.values.set(k,v);}removeItem(k:string){this.values.delete(k);}}
const seeded=()=>{const storage=new Storage(),source=captureCampaign(new CoreSimulation(true,false,true),defaultSettings());source.survival.inventory[4]=31;expect(createCampaignStore(true,storage).write(source).ok).toBe(true);storage.setItem(CAMPAIGN_FORMAT_SELECTOR,'campaign-v3');return storage;};
describe('western v4 atomic checkpoints',()=>{
 it('round trips edited terrain, all22 actors, inventory, companion and wide map pins',()=>{const sim=fresh();sim.survival.inventory[4]=42;sim.arena.field.carve({x:-30,y:.1,z:-6},.4);sim.arena.field.removeObject('tree0');sim.arena.field.box({x:0,y:1,z:7},{x:1,y:2,z:8},4,'build:wall:900');sim.enableCompanion({x:-110,y:30,z:-140}).hp=37;sim.enemies[18].hp=51;sim.enemies[18].position={x:-110,y:30,z:-140};const settings=defaultSettings();settings.pins=[{id:'west',x:-110,z:-140}];const saved=clone(captureCampaign(sim,settings));expect(saved.world).toBe('campaign-v4');expect(isCampaignSave(saved)).toBe(true);expect(isStreamedCampaignSave(saved)).toBe(false);const loaded=hydrateCampaign(saved);expect(loaded).not.toBeNull();expect(loaded!.sim.enemies.length).toBe(22);expect(loaded!.sim.enemies[18].hp).toBe(51);expect(loaded!.sim.enemies[18].position).toEqual(saved.enemies[18].position);expect(loaded!.sim.arena.field.exportState()).toEqual(saved.field);expect(loaded!.sim.survival.inventory[4]).toBe(42);expect(loaded!.sim.companion?.hp).toBe(37);expect(loaded!.sim.companionSuspended).toBe(true);expect(loaded!.settings.pins).toEqual(settings.pins);expect(loaded!.sim.western!.snapshot()).toEqual(saved.western);});
 it('rejects malformed appended identities, owners and manifest-specific bounds',()=>{const saved=clone(captureCampaign(fresh(),defaultSettings()));for(const change of [(v:typeof saved)=>v.enemies[18].id=201,(v:typeof saved)=>v.enemies[18].summonOwner=11,(v:typeof saved)=>v.enemies[18].position.x=-129,(v:typeof saved)=>v.player.position.z=-161,(v:typeof saved)=>v.settings.pins=[{id:'bad',x:129,z:0}]]){const bad=clone(saved);change(bad);expect(isCampaignSave(bad)).toBe(false);}const old=clone(captureCampaign(new CoreSimulation(true,false,true),defaultSettings()));old.player.position.x=-110;expect(isCampaignSave(old)).toBe(false);old.player.position.x=0;old.settings.pins=[{id:'bad',x:-110,z:0}];expect(isCampaignSave(old)).toBe(false);});
 it('rejects open-ledger/closed-gate and late malformed body without changing any live state',()=>{const sim=fresh(),saved=clone(captureCampaign(sim,defaultSettings())),before=JSON.stringify(saved),revision=sim.arena.field.revision;const bad=clone(saved);bad.western!.claimed=['west-mine-switch'];bad.western!.gateOpen=true;for(const object of bad.objects)if(['west-mine-switch','west-shortcut-gate'].includes(object.id))object.open=true;expect(isCampaignSave(bad)).toBe(true);expect(restoreCampaignInto(sim,bad)).toBeNull();expect(getCampaignRestoreFailure(sim)).toBe('western-geometry');expect(JSON.stringify(captureCampaign(sim,defaultSettings()))).toBe(before);expect(sim.arena.field.revision).toBe(revision);const body=clone(saved);body.entities[21].field.base.push([0,0,0,NaN,4]);expect(restoreCampaignInto(sim,body)).toBeNull();expect(JSON.stringify(captureCampaign(sim,defaultSettings()))).toBe(before);expect(sim.arena.field.revision).toBe(revision);});
 it('shared v4 snapshots preserve the guest actor and reuse unchanged terrain',()=>{const host=fresh(),guest=fresh();guest.player.position={x:2,y:2,z:6};const position={...guest.player.position};host.survival.inventory[4]=19;const shared=captureSharedCampaign(host,defaultSettings());expect(applySharedCampaign(guest,shared).ok).toBe(true);expect(guest.player.position).toEqual(position);expect(guest.survival.inventory[4]).toBe(19);const revision=guest.arena.field.revision;expect(applySharedCampaign(guest,shared).ok).toBe(true);expect(guest.arena.field.revision).toBe(revision);});
});
describe('western separate-key migration transaction',()=>{
 it('archives exact v3 bytes once, migrates all state and never resurrects it after New Game',()=>{const storage=seeded(),original=storage.getItem(STREAMED_CAMPAIGN_STORE_KEY),selected=selectCampaignStore(storage,true,true);expect(selected.blocked,selected.error).toBe(false);expect(selected.western).toBe(true);expect(selected.migrated).toBe(true);expect(selected.store.key).toBe(WESTERN_CAMPAIGN_STORE_KEY);expect(storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBe(original);expect(storage.getItem(WESTERN_MIGRATION_ARCHIVE)).toBe(original);expect(storage.getItem(CAMPAIGN_FORMAT_SELECTOR)).toBe('campaign-v4');if(selected.loaded.status!=='loaded')throw new Error('No v4 save');expect(selected.loaded.data.survival.inventory[4]).toBe(31);expect(hydrateCampaign(selected.loaded.data)).not.toBeNull();expect(selected.store.reset().ok).toBe(true);const next=selectCampaignStore(storage);expect(next.western).toBe(true);expect(next.loaded.status).toBe('empty');expect(next.migrated).toBe(false);expect(storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBe(original);},15000);
 it.each([WESTERN_MIGRATION_ARCHIVE,WESTERN_CAMPAIGN_STORE_KEY,CAMPAIGN_FORMAT_SELECTOR])('preserves v3 on failed write %s',key=>{const storage=seeded(),original=storage.getItem(STREAMED_CAMPAIGN_STORE_KEY);storage.fail=key;const selected=selectCampaignStore(storage,true,true);expect(selected.blocked).toBe(true);expect(storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)).toBe(original);expect(storage.getItem(CAMPAIGN_FORMAT_SELECTOR)).toBe('campaign-v3');});
 it('keeps the write-once archive immutable and rejects a changed migration source',()=>{const storage=seeded(),original=storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)!;expect(preserveWesternMigrationBackup(storage,STREAMED_CAMPAIGN_STORE_KEY,original)).toEqual({ok:true,alreadyPresent:false});expect(preserveWesternMigrationBackup(storage,STREAMED_CAMPAIGN_STORE_KEY,original)).toEqual({ok:true,alreadyPresent:true});const source=createCampaignStore(true,storage).read();if(source.status!=='loaded')throw new Error('No source');expect(createCampaignStore(true,storage).write({...source.data,seconds:2}).ok).toBe(true);const newer=storage.getItem(STREAMED_CAMPAIGN_STORE_KEY)!;expect(preserveWesternMigrationBackup(storage,STREAMED_CAMPAIGN_STORE_KEY,original)).toEqual({ok:false,reason:'source-changed'});expect(preserveWesternMigrationBackup(storage,STREAMED_CAMPAIGN_STORE_KEY,newer)).toEqual({ok:false,reason:'conflict'});expect(storage.getItem(WESTERN_MIGRATION_ARCHIVE)).toBe(original);});
 it('protects future selectors and checksummed future v4 saves rather than recovering an old backup',()=>{const storage=seeded();storage.setItem(CAMPAIGN_FORMAT_SELECTOR,'campaign-v99');const before=[...storage.values];expect(selectCampaignStore(storage,true,true).loaded.status).toBe('unsupported');expect([...storage.values]).toEqual(before);const other=seeded(),selected=selectCampaignStore(other,true,true);if(selected.loaded.status!=='loaded')throw new Error(selected.error);selected.store.write({...selected.loaded.data,seconds:1});const envelope=JSON.parse(other.getItem(WESTERN_CAMPAIGN_STORE_KEY)!);const data=JSON.parse(envelope.payload);data.world='campaign-v5';envelope.payload=JSON.stringify(data);envelope.checksum=checksum(envelope.payload);other.setItem(WESTERN_CAMPAIGN_STORE_KEY,JSON.stringify(envelope));const bytes=[...other.values];expect(selectCampaignStore(other).loaded.status).toBe('unsupported');expect([...other.values]).toEqual(bytes);});
});
