import {describe,it,expect} from 'vitest';
import {VoxelField,runVoxelWork} from '../../src/prototype/core/voxel';
import {authorCampaignWorld,authorCampaignWorldFallback,bootstrapCampaignWorld,type AuthoredWorldPacket} from '../../src/prototype/core/world-bootstrap';
const hub=()=>{const f=new VoxelField();f.box({x:-4,y:-1,z:-4},{x:4,y:.25,z:4},3);f.box({x:-1,y:.25,z:0},{x:0,y:1.5,z:1},4,'door');f.box({x:1,y:.25,z:0},{x:2,y:1.5,z:1},4,'removed');f.captureBaseline('hub');return f;};
const full=()=>{const f=hub();f.box({x:-8,y:-1,z:-8},{x:8,y:.1,z:8},2);f.box({x:4,y:.25,z:0},{x:5,y:1.5,z:1},4,'new-object');f.captureBaseline('campaign-v2');return f;};
const sorted=(f:VoxelField)=>[...f.cells].sort(([a],[b])=>a.localeCompare(b));
const noWait=()=>Promise.resolve();
describe('asynchronous authored-world expansion',()=>{
 it('keeps the exact full-world baseline and save compatibility',async()=>{const target=hub(),author=full(),packet=author.packAuthoredBaseline();await target.mergeAuthoredBaseline(packet,{yieldTask:noWait});expect(target.exportState().baseline).toBe(author.exportState().baseline);expect(target.exportState().base).toEqual([]);expect(target.exportState().layers.every(l=>l.cells.length===0&&l.removed.length===0)).toBe(true);expect(sorted(target)).toEqual(sorted(author));const fresh=full();expect(fresh.restoreState(target.exportState())).toBe(true);expect(sorted(fresh)).toEqual(sorted(target));});
 it('preserves mining, removed/replaced layers and newly built layers during loading',async()=>{const target=hub(),author=full();const cell=target.get(-8,-1,-8)!;expect(cell).toBeDefined();target.depleteSample(cell);target.removeObject('removed');target.removeObject('door');target.box({x:-1,y:.25,z:0},{x:-.7,y:1.5,z:2},4,'door');target.box({x:0,y:.25,z:2},{x:1,y:1,z:3},4,'build:wall:1');const door=[...target.cells.values()].filter(c=>c.object==='door'),built=[...target.cells.values()].filter(c=>c.object==='build:wall:1');await target.mergeAuthoredBaseline(author.packAuthoredBaseline(),{yieldTask:noWait});expect(target.sample(cell.x,cell.y,cell.z)).toBe(target.size*.5);expect([...target.cells.values()].filter(c=>c.object==='door')).toEqual(door);expect([...target.cells.values()].filter(c=>c.object==='build:wall:1')).toEqual(built);expect([...target.cells.values()].some(c=>c.object==='removed')).toBe(false);const fresh=full();expect(fresh.restoreState(target.exportState())).toBe(true);expect(sorted(fresh)).toEqual(sorted(target));});
 it('retains edits made between merge batches, not just before the worker finishes',async()=>{const target=hub(),initial=target.cells.size,author=full();let edited=false,yields=0;await target.mergeAuthoredBaseline(author.packAuthoredBaseline(),{budgetMs:.5,yieldTask:async()=>{yields++;if(!edited&&target.cells.size>initial){edited=true;target.carve({x:-1,y:.8,z:.5},.4);target.removeObject('new-object');target.box({x:0,y:.25,z:2},{x:1,y:1,z:3},4,'build:wall:2');}}});expect(yields).toBeGreaterThan(0);expect(edited).toBe(true);expect(target.distance({x:-1,y:.8,z:.5})).toBeGreaterThan(0);expect([...target.cells.values()].some(c=>c.object==='new-object')).toBe(false);expect([...target.cells.values()].some(c=>c.object==='build:wall:2')).toBe(true);const fresh=full();expect(fresh.restoreState(target.exportState())).toBe(true);expect(sorted(fresh)).toEqual(sorted(target));});
 it('cannot snapshot an in-progress merge and rejects malformed input before mutation',async()=>{const target=hub(),before=target.exportState(),packet=full().packAuthoredBaseline();packet.base[3]=NaN;await expect(target.mergeAuthoredBaseline(packet,{yieldTask:noWait})).rejects.toThrow('Invalid authored sample');expect(target.exportState()).toEqual(before);let blocked=false;await target.mergeAuthoredBaseline(full().packAuthoredBaseline(),{budgetMs:.5,yieldTask:async()=>{expect(()=>target.exportState()).toThrow('World is still loading');blocked=true;}});expect(blocked).toBe(true);});
 it('generator authoring equals synchronous primitives, including CSG removal',async()=>{const a=new VoxelField(),b=new VoxelField(),lo={x:-1,y:-1,z:-1},hi={x:1,y:1,z:1},sdf=(p:{x:number;y:number;z:number})=>Math.hypot(p.x,p.y,p.z)-1;a.shape(lo,hi,sdf,3);await runVoxelWork(b.shapeSteps(lo,hi,sdf,3),{yieldTask:noWait});a.box(lo,hi,4,'wood');b.box(lo,hi,4,'wood');a.removeObject('wood');await runVoxelWork(b.removeObjectSteps('wood'),{yieldTask:noWait});expect(sorted(b)).toEqual(sorted(a));a.captureBaseline('same');await runVoxelWork(b.captureBaselineSteps('same'),{yieldTask:noWait});expect(b.exportState().baseline).toBe(a.exportState().baseline);});
 it('adds worker metadata without overwriting live object state and terminates the worker',async()=>{const field=hub(),arena={field,objects:new Map([['door',{id:'door',kind:'door' as const,name:'Door',open:true,hp:7}]])},packet:AuthoredWorldPacket={field:full().packAuthoredBaseline(),objects:[{id:'door',kind:'door',name:'Door',open:false,hp:100},{id:'new-object',kind:'tree',name:'Tree',open:false,hp:100}]};let terminated=false;const worker={onmessage:null as ((event:MessageEvent)=>void)|null,onerror:null,onmessageerror:null,terminate(){terminated=true;},postMessage(){queueMicrotask(()=>this.onmessage?.({data:packet} as MessageEvent));}},stages:string[]=[];await bootstrapCampaignWorld(arena,{workerFactory:()=>worker as unknown as Worker,yieldTask:noWait,onProgress:stage=>stages.push(stage)});expect(terminated).toBe(true);expect(arena.objects.get('door')).toMatchObject({open:true,hp:7});expect(arena.objects.has('new-object')).toBe(true);expect(stages).toEqual(['authoring','merging','ready']);});
 it('cancellation terminates a pending worker and never announces ready',async()=>{const controller=new AbortController(),stages:string[]=[],arena={field:hub(),objects:new Map()};let terminated=false;const worker={onmessage:null,onerror:null,onmessageerror:null,terminate(){terminated=true;},postMessage(){queueMicrotask(()=>controller.abort());}};await expect(bootstrapCampaignWorld(arena,{signal:controller.signal,workerFactory:()=>worker as unknown as Worker,onProgress:stage=>stages.push(stage)})).rejects.toThrow('cancelled');expect(terminated).toBe(true);expect(stages).toEqual(['authoring']);});
 it('bounded main-thread fallback authors the identical worker baseline',async()=>{let yields=0;const fallback=await authorCampaignWorldFallback({budgetMs:3,yieldTask:async()=>{yields++;}}),sync=authorCampaignWorld();expect(yields).toBeGreaterThan(20);expect(fallback.field.baseline).toBe(sync.field.baseline);expect(Buffer.from(fallback.field.base.buffer).equals(Buffer.from(sync.field.base.buffer))).toBe(true);expect(fallback.field.layers.map(l=>l.id)).toEqual(sync.field.layers.map(l=>l.id));for(let i=0;i<fallback.field.layers.length;i++)expect(Buffer.from(fallback.field.layers[i].samples.buffer).equals(Buffer.from(sync.field.layers[i].samples.buffer))).toBe(true);expect(fallback.objects).toEqual(sync.objects);},30000);
});
