import {CAMPAIGN_PROTOCOL,HOST_LEASE_MS,MAX_PACKET_BYTES,MAX_SNAPSHOT_BYTES,byteLength,integer,record,validResumeKey,validFrame,validGuestInput,validPose,validCommand,validCommandId,validManifest,BUILD_ACTIONS,snapshotChecksum,type ServerPacket,type RoomRole,type PlayerPose,type SnapshotManifest} from './protocol';
export interface RoomWire {send(packet:ServerPacket):void;close(code:number,reason:string):void}
interface Connection {wire:RoomWire;role?:RoomRole;joined:number;lastSeen:number;window:number;messages:number;inputs:number;frames:number;chatAt:number}
interface Identity {key:string;connection:string|null;poseSequence:number;commandSequence:number;pose:PlayerPose|null}
interface Transfer {manifest:SnapshotManifest;chunks:string[];bytes:number;started:number}
export interface RelayCheckpoint {version:1;host:{key:string;poseSequence:number;commandSequence:number}|null;guest:{key:string;poseSequence:number;commandSequence:number}|null;guestBuild:boolean;snapshotSequence:number;receipts:[string,{sequence:number;accepted:boolean|null;message:string}][]}
interface Receipt {sequence:number;accepted:boolean|null;message:string;pending:boolean;started:number}
/** Two-player browser-host authority. No simulation, account access, or PR5 state. */
export class CampaignRelayRoom {
 private readonly connections=new Map<string,Connection>();
 private host:Identity|null=null;private guest:Identity|null=null;
 private readonly receipts=new Map<string,Receipt>();
 private staging:Transfer|null=null;private latest:Transfer|null=null;
 private hostFrameSequence=0;private guestInputSequence=0;private guestBuild=false;private hostPresent=false;private hostPublished=false;private lastSnapshotSequence=0;
 constructor(readonly epoch:string,private readonly now:()=>number=Date.now,saved?:RelayCheckpoint){if(!/^[a-zA-Z0-9_-]{8,96}$/.test(epoch))throw new Error('Invalid epoch');if(saved){if(!validRelayCheckpoint(saved))throw new Error('Invalid relay checkpoint');this.host=saved.host?{...saved.host,connection:null,pose:null}:null;this.guest=saved.guest?{...saved.guest,connection:null,pose:null}:null;this.guestBuild=saved.guestBuild;this.lastSnapshotSequence=saved.snapshotSequence;for(const [id,r] of saved.receipts)this.receipts.set(id,{...r,pending:false,started:0});}}
 get size(){return this.connections.size;}
 get online(){return this.hostPresent;}
 connect(id:string,wire:RoomWire){if(this.connections.has(id)||this.connections.size>=4){wire.close(1008,'Room connection limit');return;}const now=this.now();this.connections.set(id,{wire,joined:now,lastSeen:now,window:now,messages:0,inputs:0,frames:0,chatAt:-Infinity});}
 private send(id:string|null,packet:ServerPacket){if(id)this.connections.get(id)?.wire.send(packet);}
 private broadcast(packet:ServerPacket){for(const c of this.connections.values())if(c.role)c.wire.send(packet);}
 private players(){this.broadcast({type:'players',epoch:this.epoch,players:([['host',this.host],['guest',this.guest]] as const).filter(([,v])=>v).map(([id,v])=>({id,connected:!!v!.connection,pose:v!.pose}))});}
 disconnect(id:string){const c=this.connections.get(id);if(!c)return;this.connections.delete(id);const identity=c.role==='host'?this.host:c.role==='guest'?this.guest:null;if(identity?.connection===id)identity.connection=null;
  if(c.role==='host'&&this.hostPresent){this.hostPresent=false;this.hostPublished=false;this.staging=null;for(const [commandId,r] of this.receipts)if(r.pending){r.pending=false;r.accepted=null;r.message='ホストが切断され、操作の反映状況を確認できません';this.send(this.guest?.connection??null,{type:'ack',epoch:this.epoch,commandId,accepted:null,message:r.message});}this.broadcast({type:'status',epoch:this.epoch,hostOnline:false,message:'ホストが切断されたため世界を一時停止。再接続を待っています'});}
  this.players();
 }
 private close(id:string,code:number,reason:string){const c=this.connections.get(id);this.disconnect(id);c?.wire.close(code,reason);}
 receive(id:string,text:string){const c=this.connections.get(id);if(!c)return;const now=this.now();if(byteLength(text)>MAX_PACKET_BYTES){this.close(id,1009,'Packet too large');return;}if(now-c.window>=1000){c.window=now;c.messages=0;c.inputs=0;c.frames=0;}if(++c.messages>240){this.close(id,1008,'Rate limit');return;}
  try {const p:unknown=JSON.parse(text);if(!record(p)||typeof p.type!=='string')throw new Error('Invalid packet');
   if(p.type==='hello'){if(c.role)throw new Error('Handshake already complete');if(p.protocol!==CAMPAIGN_PROTOCOL||!validResumeKey(String(p.resumeKey))||!['create','join'].includes(String(p.mode)))throw new Error('Protocol or identity mismatch');const key=String(p.resumeKey);
    if(p.mode==='create'){if(this.host&&this.host.key!==key)throw new Error('Host already exists');this.host??={key,connection:null,poseSequence:0,commandSequence:0,pose:null};c.role='host';this.hostFrameSequence=0;}
    else {if(!this.host)throw new Error('Host has not created this room');if(key===this.host.key)throw new Error('Use host reconnect mode');if(this.guest&&this.guest.key!==key)throw new Error('This room is limited to two players');this.guest??={key,connection:null,poseSequence:0,commandSequence:0,pose:null};c.role='guest';this.guestInputSequence=0;}
    const identity=c.role==='host'?this.host!:this.guest!;if(identity.connection&&identity.connection!==id)this.close(identity.connection,4001,'Replaced by reconnect');identity.connection=id;c.lastSeen=now;
    if(c.role==='host'){this.hostPresent=true;this.broadcast({type:'status',epoch:this.epoch,hostOnline:false,message:'ホストが再接続。新しい共有状態を待っています'});}
    c.wire.send({type:'welcome',protocol:CAMPAIGN_PROTOCOL,role:c.role,epoch:this.epoch,lastCommandSequence:identity.commandSequence,lastPoseSequence:identity.poseSequence,snapshotSequence:this.lastSnapshotSequence,guestBuild:this.guestBuild,hostOnline:c.role==='host'?this.hostPresent:this.hostPresent&&this.hostPublished});this.players();
    if(c.role==='guest'){if(this.hostPresent&&this.hostPublished&&this.latest)this.sendSnapshot(c.wire,this.latest);this.send(this.host?.connection??null,{type:'snapshot-request',epoch:this.epoch});}else if(this.guest?.connection)c.wire.send({type:'snapshot-request',epoch:this.epoch});return;
   }
   if(!c.role)throw new Error('Handshake required');if(p.epoch!==this.epoch)throw new Error('Stale room epoch');c.lastSeen=now;
   const identity=c.role==='host'?this.host!:this.guest!;
   if(p.type==='ping'){c.wire.send({type:'pong',epoch:this.epoch});return;}
   if(p.type==='resync'){if(c.role==='guest'&&this.latest&&this.hostPresent&&this.hostPublished)this.sendSnapshot(c.wire,this.latest);this.send(this.host?.connection??null,{type:'snapshot-request',epoch:this.epoch});return;}
   if(p.type==='frame'){if(c.role!=='host'||!integer(p.sequence,1)||!validFrame(p.payload))throw new Error('Invalid host frame');if(p.sequence<=this.hostFrameSequence)return;if(p.sequence>this.hostFrameSequence+10000)throw new Error('Frame sequence gap');this.hostFrameSequence=p.sequence;if(!this.hostPublished||++c.frames>20)return;this.send(this.guest?.connection??null,{type:'frame',epoch:this.epoch,sequence:p.sequence,payload:p.payload});return;}
   if(p.type==='input'){if(c.role!=='guest'||!integer(p.sequence,1)||!validGuestInput(p.input))throw new Error('Invalid guest input');if(p.sequence<=this.guestInputSequence)return;if(p.sequence>this.guestInputSequence+10000)throw new Error('Input sequence gap');this.guestInputSequence=p.sequence;if(!this.hostPresent||!this.hostPublished||++c.inputs>40)return;const input={x:p.input.x,z:p.input.z,yaw:p.input.yaw,pitch:p.input.pitch,block:p.input.block,sprint:p.input.sprint};this.send(this.host!.connection,{type:'input',epoch:this.epoch,sequence:p.sequence,playerId:'guest',input});return;}
   if(p.type==='pose'){if(!this.hostPresent)return;if(!integer(p.sequence,1)||p.sequence<=identity.poseSequence||p.sequence>identity.poseSequence+10000||!validPose(p.pose))throw new Error('Stale or invalid pose');identity.poseSequence=p.sequence;identity.pose={...p.pose};this.players();return;}
   if(p.type==='chat'){if(typeof p.text!=='string'||p.text.length<1||p.text.length>240||now-c.chatAt<1000)throw new Error('Chat rate or length limit');c.chatAt=now;this.broadcast({type:'chat',epoch:this.epoch,playerId:c.role,text:p.text.replace(/[\u0000-\u001f\u007f]/g,'')});return;}
   if(p.type==='permission'){if(c.role!=='host'||typeof p.guestBuild!=='boolean')throw new Error('Only host changes permissions');this.guestBuild=p.guestBuild;this.broadcast({type:'permission',epoch:this.epoch,guestBuild:this.guestBuild});return;}
   if(p.type==='command'){if(c.role!=='guest'||!integer(p.sequence,1)||!validCommandId(p.commandId)||!validCommand(p.command))throw new Error('Invalid guest command');const previous=this.receipts.get(p.commandId);if(previous){if(previous.sequence!==p.sequence)throw new Error('Command id reused with another sequence');if(!previous.pending)c.wire.send({type:'ack',epoch:this.epoch,commandId:p.commandId,accepted:previous.accepted,message:previous.message});return;}
    if(p.sequence<=identity.commandSequence||p.sequence>identity.commandSequence+1000)throw new Error('Stale command sequence');if(!this.hostPresent||!this.hostPublished)throw new Error('World paused: awaiting host snapshot');if([...this.receipts.values()].filter(r=>r.pending).length>=64)throw new Error('Too many pending commands');identity.commandSequence=p.sequence;
    const denied=BUILD_ACTIONS.has(p.command.action)&&!this.guestBuild;const receipt:Receipt={sequence:p.sequence,accepted:denied?false:null,message:denied?'ホストが建築・採掘・収納の変更を許可していません':'',pending:!denied,started:now};this.receipts.set(p.commandId,receipt);this.trimReceipts();if(denied)c.wire.send({type:'ack',epoch:this.epoch,commandId:p.commandId,accepted:false,message:receipt.message});else this.send(this.host!.connection,{type:'command',epoch:this.epoch,playerId:'guest',sequence:p.sequence,commandId:p.commandId,command:p.command});return;
   }
   if(p.type==='ack'){if(c.role!=='host'||!validCommandId(p.commandId)||typeof p.accepted!=='boolean'||typeof p.message!=='string'||p.message.length>400)throw new Error('Invalid host acknowledgment');const r=this.receipts.get(p.commandId);if(!r||!r.pending)return;r.pending=false;r.accepted=p.accepted;r.message=p.message;this.send(this.guest?.connection??null,{type:'ack',epoch:this.epoch,commandId:p.commandId,accepted:p.accepted,message:p.message});return;}
   if(c.role!=='host')throw new Error('Only the host publishes world state');
   if(p.type==='snapshot-begin'){if(!validManifest(p.manifest)||p.manifest.sequence<=this.lastSnapshotSequence||p.manifest.sequence>this.lastSnapshotSequence+10000)throw new Error('Invalid snapshot manifest');this.staging={manifest:{...p.manifest},chunks:[],bytes:0,started:now};return;}
   if(p.type==='snapshot-chunk'){const t=this.staging;if(!t||p.sequence!==t.manifest.sequence||p.index!==t.chunks.length||typeof p.data!=='string'||!p.data.length||byteLength(p.data)>32768||t.chunks.length>=t.manifest.chunks)throw new Error('Invalid snapshot chunk');t.bytes+=byteLength(p.data);if(t.bytes>t.manifest.bytes||t.bytes>MAX_SNAPSHOT_BYTES){this.staging=null;throw new Error('Snapshot size mismatch');}t.chunks.push(p.data);return;}
   if(p.type==='snapshot-end'){const t=this.staging;if(!t||p.sequence!==t.manifest.sequence||t.chunks.length!==t.manifest.chunks||t.bytes!==t.manifest.bytes)throw new Error('Incomplete snapshot');if(snapshotChecksum(t.chunks.join(''))!==t.manifest.checksum){this.staging=null;throw new Error('Snapshot checksum mismatch');}this.latest=t;this.lastSnapshotSequence=t.manifest.sequence;this.staging=null;if(!this.hostPublished){this.hostPublished=true;this.broadcast({type:'status',epoch:this.epoch,hostOnline:true,message:'ホストの共有世界を受信しました'});}if(this.guest?.connection){const guest=this.connections.get(this.guest.connection);if(guest)this.sendSnapshot(guest.wire,t);}return;}
   throw new Error('Unknown packet');
  }catch(error){c.wire.send({type:'notice',message:error instanceof Error?error.message:'Invalid room message'});}
 }
 checkpoint():RelayCheckpoint {const identity=(i:Identity|null)=>i?{key:i.key,poseSequence:i.poseSequence,commandSequence:i.commandSequence}:null;return {version:1,host:identity(this.host),guest:identity(this.guest),guestBuild:this.guestBuild,snapshotSequence:this.lastSnapshotSequence,receipts:[...this.receipts].map(([id,r])=>[id,{sequence:r.sequence,accepted:r.pending?null:r.accepted,message:r.pending?'再接続前の操作。最新状態で結果を確認してください':r.message}])};}
 private trimReceipts(){while(this.receipts.size>256){const done=[...this.receipts].find(([,r])=>!r.pending);if(!done)break;this.receipts.delete(done[0]);}}
 private sendSnapshot(wire:RoomWire,t:Transfer){wire.send({type:'snapshot-begin',epoch:this.epoch,manifest:t.manifest});for(let i=0;i<t.chunks.length;i++)wire.send({type:'snapshot-chunk',epoch:this.epoch,sequence:t.manifest.sequence,index:i,data:t.chunks[i]});wire.send({type:'snapshot-end',epoch:this.epoch,sequence:t.manifest.sequence});}
 tick(){const now=this.now();for(const [id,c] of this.connections){if(!c.role&&now-c.joined>10000)this.close(id,1008,'Handshake timeout');else if(c.role&&now-c.lastSeen>HOST_LEASE_MS)this.close(id,4000,'Heartbeat lease expired');}if(this.staging&&now-this.staging.started>60000)this.staging=null;for(const [commandId,r] of this.receipts)if(r.pending&&now-r.started>15000){r.pending=false;r.accepted=null;r.message='操作の確認が時間切れ。再同期して結果を確認してください';this.send(this.guest?.connection??null,{type:'ack',epoch:this.epoch,commandId,accepted:null,message:r.message});}}
}

export function validRelayCheckpoint(v:unknown):v is RelayCheckpoint {if(!record(v)||v.version!==1||typeof v.guestBuild!=='boolean'||!integer(v.snapshotSequence))return false;for(const key of ['host','guest']){const i=v[key];if(i!==null&&(!record(i)||typeof i.key!=='string'||!validResumeKey(i.key)||!integer(i.poseSequence)||!integer(i.commandSequence)))return false;}if(v.guest&&!v.host)return false;if(!Array.isArray(v.receipts)||v.receipts.length>256)return false;const ids=new Set<string>();for(const pair of v.receipts){if(!Array.isArray(pair)||pair.length!==2||!validCommandId(pair[0])||ids.has(pair[0])||!record(pair[1])||!integer(pair[1].sequence,1)||![true,false,null].includes(pair[1].accepted as boolean|null)||typeof pair[1].message!=='string'||pair[1].message.length>400)return false;ids.add(pair[0]);}return true;}
